VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild::
    .string "I kdyz jsou na stejné úrovni,\n"
    .string "POKéMONi mohou mít velmi rozdílné\l"
    .string "staty a schopnosti.\p"
    .string "POKéMON vychovany TRENÉREM je\n"
    .string "silnejsí nez ten v divocine.$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking::
    .string "Muj POKéMON byl otráven!\n"
    .string "Omdlel, kdyz jsme sli!$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes::
    .string "Je pravda, ze POKéMON s vyssí\n"
    .string "úrovní bude silnejsí…\p"
    .string "Ale vsichni POKéMONi mají slabá\n"
    .string "místa proti urcitym typum.\p"
    .string "Takze se zdá, ze neexistuje\n"
    .string "univerzálne silny POKéMON.$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain::
    .string "Touha zase bojovat s nekym,\n"
    .string "s kym jsi se uz utkal…\p"
    .string "Mel jsi nekdy takovou touhu?\n"
    .string "Jiste ano.\p"
    .string "Také jsem chtel bojovat s\n"
    .string "urcitymi lidmi znovu a znovu.\p"
    .string "Tak jsem zacal rozdávat tyto.\n"
    .string "Prosím, vezmi si jednoho!$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches::
    .string "Pouzij to zarízení a najdes\n"
    .string "TRENÉRY chtející odvetu.\p"
    .string "Aby fungovalo, musís ho dobít\n"
    .string "v baterii.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker::
    .string "Jak pouzít VS SEEKER?\n"
    .string "Není to nic tezkého.\p"
    .string "Pouzij ho jako píp-píp-píp a\n"
    .string "TRENÉRI okolo si vsimnou.\p"
    .string "Pokud nekdo chce odvetu,\n"
    .string "ihned ti to dá vedet.\p"
    .string "Nabij ho v baterii a pouzij\n"
    .string "ho, kdyz jsi na ceste.$"
