FiveIsland_MemorialPillar_Text_MiloIntro::
    .string "Jsem nejstarsí z BRATRU\n"
    .string "PTÁKU.\p"
    .string "Nejlepsí vec na ptácích…\n"
    .string "Musí to byt zobák.$"

FiveIsland_MemorialPillar_Text_MiloDefeat::
    .string "Ach, jak ostré!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle::
    .string "Odsud muzes letet na\n"
    .string "FOUR ISLAND.$"

FiveIsland_MemorialPillar_Text_ChazIntro::
    .string "Jsem prostrední z BRATRU\n"
    .string "PTÁKU.\p"
    .string "Nejlepsí vec na ptácích…\n"
    .string "Musí to byt krídla.$"

FiveIsland_MemorialPillar_Text_ChazDefeat::
    .string "Mávat, mávat!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle::
    .string "Tamhle byl jeden hodne\n"
    .string "smutny chlapík.$"

FiveIsland_MemorialPillar_Text_HaroldIntro::
    .string "Jsem nejmladsí z BRATRU\n"
    .string "PTÁKU.\p"
    .string "Nejlepsí vec na ptácích…\n"
    .string "Musí to byt prachové perí.$"

FiveIsland_MemorialPillar_Text_HaroldDefeat::
    .string "Prachové perí je tak prijemné…\n"
    .string "Az se mi chce spát…$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle::
    .string "Naplnuje me stestím, kdyz ptací\n"
    .string "POKéMON hrave skemrají…$"

FiveIsland_MemorialPillar_Text_ScrubScrub::
    .string "Drhnu, drhnu…$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy::
    .string "Zdravím…\n"
    .string "Tví POKéMON vypadají zdrave…$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix::
    .string "Tady jsem pochoval svého ONIXe…\n"
    .string "Jmenoval se TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
    .string "“Zde lezí TECTONIX” je\n"
    .string "vyryto na balvanu.\p"
    .string "Pred hrobem je polozena\n"
    .string "LEMONADE jako obet.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering::
    .string "Chces nechat dalsí LEMONADE\n"
    .string "jako obet?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade::
    .string "{PLAYER} polozil plechovku\n"
    .string "LEMONADE pred hrob.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis::
    .string "D-dekuji ti…\p"
    .string "To byl oblíbeny nápoj mého\n"
    .string "TECTONIXe…\p"
    .string "Ani te neznám, ale tvuj\n"
    .string "laskavy cin…\p"
    .string "Trochu me to potesilo.\p"
    .string "Vezmes si tohle jako mé\n"
    .string "podekování?$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo::
    .string "Bud taky hodny na své\n"
    .string "POKéMONy.$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt::
    .string "Kdyz pro to nemás místo,\n"
    .string "podrzím ti to do prístí.$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks::
    .string "Ach, to jsi ty z té doby…\p"
    .string "Porád mám tu vec, kterou jsem\n"
    .string "ti chtel dát jako podekování.$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix::
    .string "Drhnu, drhnu…\p"
    .string "… … …\n"
    .string "TECTONIXi…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix::
    .string "Balvany a kameny jsou\n"
    .string "úhledne narovnány do mohyly.\p"
    .string "“Zde lezí TECTONIX” je\n"
    .string "vyryto na balvanu.$"

