Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Spousta POKéMONu zije jen\n"
    .string "v lesích a jeskyních.\p"
    .string "Musís byt vytrvaly a hledat\n"
    .string "vsude, abys nasel ruzné druhy.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "Vsiml sis tech tenkych stromu\n"
    .string "u kraje cesty?\p"
    .string "Slysel jsem, ze je lze porazit\n"
    .string "speciálním útokem POKéMONa.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "Znás techniku zruseni vyvoje?\p"
    .string "Kdyz se POKéMON vyvíjí, muzes\n"
    .string "ten proces zastavit.\p"
    .string "Je to technika pro chov POKéMONu\n"
    .string "tak, jak jsou.$"
