SSAnne_B1F_Room1_Text_PhillipIntro::
    .string "Kámo, prohrajes a pujdes\n"
    .string "po prkne!$"

SSAnne_B1F_Room1_Text_PhillipDefeat::
    .string "Argh!\n"
    .string "Porazen díketem!$"

SSAnne_B1F_Room1_Text_PhillipPostBattle::
    .string "Na sirém mori obcas plují\n"
    .string "kolem POKéMONi-medúzy.$"

SSAnne_B1F_Room1_Text_BarnyIntro::
    .string "Ahoj, cizince!\p"
    .string "Nepoznám, jestli jsi z morí ci\n"
    .string "z hor, ale zastav se a popovídej.\p"
    .string "Vsichni mí POKéMONi jsou z more.$"

SSAnne_B1F_Room1_Text_BarnyDefeat::
    .string "Sakra!\n"
    .string "Nechal jsem ho utéct!$"

SSAnne_B1F_Room1_Text_BarnyPostBattle::
    .string "Chtel jsem te udelat svym\n"
    .string "asistentem!$"
