SaffronCity_Text_WhatDoYouWantGetLost::
    .string "Co chces?\n"
    .string "Vypadni!$"

SaffronCity_Text_BossTakeTownForTeamRocket::
    .string "SÉF rekl, ze toto mesto zabere\n"
    .string "ve jménu TEAM ROCKET!$"

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
    .string "Nevzpouzej se!\n"
    .string "Nebo ti budu muset ublízit!$"

SaffronCity_Text_SaffronBelongsToTeamRocket::
    .string "SAFFRON patrí TEAM ROCKET!$"

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
    .string "Zivot zlocince me napluje\n"
    .string "energií!$"

SaffronCity_Text_WatchWhereYoureWalking::
    .string "Au!\n"
    .string "Dívej se, kam jdes!$"

SaffronCity_Text_WeCanExploitMonsAroundWorld::
    .string "S SILPH pod kontrolou muzeme\n"
    .string "vyuzívat POKéMONy po celém svete!\p"
    .string "Budeme nechutne bohatí, jó!$"

SaffronCity_Text_YouBeatTeamRocket::
    .string "Ty jsi porazil TEAM ROCKET sám?\n"
    .string "To je úzasné!$"

SaffronCity_Text_SafeToGoOutAgain::
    .string "Jo! TEAM ROCKET je pryc!\n"
    .string "Zase je bezpecné jít ven!$"

SaffronCity_Text_PeopleComingBackToSaffron::
    .string "Lidé odsud houfne utíkali,\n"
    .string "kdyz prisli ti ROCKETI.\p"
    .string "Ted by se meli zacít vracet\n"
    .string "zpátky do SAFFRONU.$"

SaffronCity_Text_FlewHereOnPidgeot::
    .string "Priletel jsem na svém PIDGEOTU,\n"
    .string "kdyz jsem cetl o SILPHU.\p"
    .string "Uz je po vsem?\n"
    .string "Zmeskal jsem mediální dení…$"

SaffronCity_Text_Pidgeot::
    .string "PIDGEOT: Bi bibii!$"

SaffronCity_Text_SawRocketBossEscaping::
    .string "Videl jsem, jak SÉF ROCKETU prchá\n"
    .string "z budovy SILPHU.$"

SaffronCity_Text_ImASecurityGuard::
    .string "Jsem ostraha.\p"
    .string "Podezrelé deti nepoustím dovnitr!$"

SaffronCity_Text_HesTakingASnooze::
    .string "…\n"
    .string "Chrr…\p"
    .string "Ha! On si zdrímnul!$"

SaffronCity_Text_CitySign::
    .string "SAFFRON CITY\n"
    .string "Zárící, zlatá zeme obchodu$"

SaffronCity_Text_FightingDojo::
    .string "BOJOVÉ DOJO$"

SaffronCity_Text_GymSign::
    .string "SAFFRON CITY POKéMON GYM\n"
    .string "VÚDCE: SABRINA\l"
    .string "Mistryne PSYCHIC POKéMONu!$"

SaffronCity_Text_FullHealCuresStatus::
    .string "TIPY PRO TRENÉRY\p"
    .string "FULL HEAL lécí vsechny potíze\n"
    .string "jako popáleniny, paralyzu, jed,\l"
    .string "zmrazení a spánek.\p"
    .string "Stojí o neco víc, ale je to\n"
    .string "praktictejsí nez jiné predmety.$"

SaffronCity_Text_GreatBallImprovedCatchRate::
    .string "TIPY PRO TRENÉRY\p"
    .string "Novy GREAT BALL nabízí lepsi\n"
    .string "úspesnost chytání.\p"
    .string "Vyzkousej ho na tezko chytitelné\n"
    .string "POKéMONy.$"

SaffronCity_Text_SilphCoSign::
    .string "SILPH CO. KANCELÁRSKÁ BUDOVA$"

SaffronCity_Text_MrPsychicsHouse::
    .string "DUM PANA PSYCHICA$"

SaffronCity_Text_SilphsLatestProduct::
    .string "Nejnovejsí produkt SILPHU!\n"
    .string "Datum vydání bude upresneno…$"

SaffronCity_Text_TrainerFanClubSign::
    .string "POKéMON TRENÉRSKY FAN KLUB\p"
    .string "Mnozí TRENÉRI tu zanechali\n"
    .string "svá jména.$"

SaffronCity_Text_HowCanClubNotRecognizeLance::
    .string "Tenhle FAN KLUB…\n"
    .string "Tady nikdo nemá ponetí!\p"
    .string "Jak mohou neznát zárivost,\n"
    .string "kterou je LANCE?\p"
    .string "Stojí za spravedlností!\n"
    .string "Je cool a zároven vásnivy!\l"
    .string "Je nejlepsí, LANCE!$"

