ViridianForest_Text_FriendsItchingToBattle::
    .string "Prisel jsem sem s kamarády\n"
    .string "chytat BUG POKéMONy!\p"
    .string "Vsichni se nemuzou dockat,\n"
    .string "az si zabojujou s POKéMONy!$"

ViridianForest_Text_RickIntro::
    .string "Hej! Mas POKéMONy!\n"
    .string "Pojd!\l"
    .string "Pojdme se utkat!$"

ViridianForest_Text_RickDefeat::
    .string "Ne!\nCATERPIE to nezvládne!$"

ViridianForest_Text_RickPostBattle::
    .string "Pst! Zazenes broucky pryc.\n"
    .string "Jindy, ano?$"

ViridianForest_Text_DougIntro::
    .string "Hej!\n"
    .string "Nemuzes flákat, kdyz jsi\l"
    .string "POKéMON TRENéR!$"

ViridianForest_Text_DougDefeat::
    .string "Hm?\n"
    .string "Dosli mi POKéMONi!$"

ViridianForest_Text_DougPostBattle::
    .string "To je úplne strasné! Pujdu\n"
    .string "chytit silnejsí!$"

ViridianForest_Text_SammyIntro::
    .string "Hej, pockej!\n"
    .string "Kam ten spech? Kam tak letís?$"

ViridianForest_Text_SammyDefeat::
    .string "Vzdávám to!\n"
    .string "Jsi v tom dobry!$"

ViridianForest_Text_SammyPostBattle::
    .string "Obcas najdes veci na zemi.\p"
    .string "Hledám to, co jsem upustil.\n"
    .string "Pomuzes mi?$"

ViridianForest_Text_AnthonyIntro::
    .string "Mozná jsem malicky, ale\n"
    .string "nesnásím, kdyz me setrís!$"

ViridianForest_Text_AnthonyDefeat::
    .string "Ach, bu.\n"
    .string "Nic se nepovedlo.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "Prisel jsem o cást kapesného…$"

ViridianForest_Text_CharlieIntro::
    .string "Vís, ze se POKéMON vyvíjejí?$"

ViridianForest_Text_CharlieDefeat::
    .string "Ach!\n"
    .string "Prohrál jsem!$"

ViridianForest_Text_CharliePostBattle::
    .string "BUG POKéMONi se vyvíjejí\n"
    .string "rychle. Je s nimi zábava!$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "Házel jsem POKé BALLS na\n"
    .string "chytání POKéMONu, a dosly mi.\p"
    .string "Proto nikdy nemuzes mít\n"
    .string "moc POKé BALLS.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "TIPY PRO TRENéRY\p"
    .string "Pokud jsou tví POKéMONi slabí\n"
    .string "a chces se vyhnout soubojum,\l"
    .string "vyhybej se travnatym místum!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "Na jed pouzij PROTIJED!\n"
    .string "Sezenes ho v POKéMON MART!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "TIPY PRO TRENéRY\p"
    .string "Spoj se s PROF. OAKEM pres PC\n"
    .string "a nech si ohodnotit POKéDEX!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "TIPY PRO TRENéRY\p"
    .string "Nemuzes chytit POKéMONa,\n"
    .string "ktery patrí nekomu jinému.\p"
    .string "Hazej POKé BALLS jen na divoké\n"
    .string "POKéMONy, abys je chytil!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "TIPY PRO TRENéRY\p"
    .string "Oslab POKéMONy pred pokusem\n"
    .string "o chycení!\p"
    .string "Zdraví mohou utéct!$"

ViridianForest_Text_LeavingViridianForest::
    .string "OPOUSTíS VIRIDIAN FOREST\n"
    .string "PEWTER CITY PRED TEBOU$"
