SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .string "Tahle lod, to je luxusní parník\n"
    .string "pro TRENÉRY ze sveta!\p"
    .string "V kazdém prístavu poradáme\n"
    .string "veciry pro pozvané TRENÉRY.$"

SSAnne_2F_Corridor_Text_RivalIntro::
    .string "{RIVAL}: Bonjour!\n"
    .string "{PLAYER}!\p"
    .string "Co ty tu prosím tebe delás!\n"
    .string "{PLAYER}, byl jsi opravdu pozván?\p"
    .string "Tak co tvuj POKéDEX?\p"
    .string "Já uz chytil 40 druhu, kámo.\n"
    .string "Ruzné druhy jsou vsude.\p"
    .string "Plaz se v travnatych místech\n"
    .string "a hledej je dukladne.$"

SSAnne_2F_Corridor_Text_RivalDefeat::
    .string "Hmf!\p"
    .string "Alespon trénujes své\n"
    .string "POKéMONy!$"

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
    .string "{RIVAL}: Slysel jsem, ze na palube\n"
    .string "je mistr CUT.\p"
    .string "Ale je to jen stary morsky vlk!\p"
    .string "Sám CUT je opravdu uzitecny.\n"
    .string "Jo, hodí se.\p"
    .string "Mel bys ho také navstívit.\n"
    .string "Cau!$"
