CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .string "Já?\n"
    .string "Já jsem programátor!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .string "Jsem grafik!\n"
    .string "Já jsem te nakreslil!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .string "Napsal jsem príbeh!\n"
    .string "Není ERIKA roztomilá?\p"
    .string "Mám taky moc rád MISTY!\n"
    .string "A SABRINU, tu mám taky rád!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .string "Vázne?\p"
    .string "Já jsem návrhár hry!\p"
    .string "Zaplnit POKéDEX není snadné,\n"
    .string "ale nevzdávej to!\p"
    .string "Az to dokoncís, prijd mi to ríct!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "Páni! Skvele!\n"
    .string "Dokoncils svuj POKéDEX!\l"
    .string "Gratuluji!\l"
    .string "…$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .string "Tohle je herní program! Zmena by\n"
    .string "mohla hru rozhodit!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .string "Nekdo si misto práce hraje\n"
    .string "hru!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .string "Tohle je scénár!\n"
    .string "Radsi nekoukej na konec!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "GAME FREAK vyvojárna$"
