Route4_Text_TrippedOverGeodude::
    .string "Au! Zakopl jsem o skalního\n"
    .string "POKéMONa GEODUDE!$"

Route4_Text_CrissyIntro::
    .string "Prisla jsem na MT. MOON hledat\n"
    .string "houbové POKéMONy.$"

Route4_Text_CrissyDefeat::
    .string "A to jsem se tak snazila!$"

Route4_Text_CrissyPostBattle::
    .string "Mozná tu uz zádné houby\n"
    .string "nezustaly.\p"
    .string "Myslím, ze jsem je posbírala vse.$"

Route4_Text_MtMoonEntrance::
    .string "MT. MOON\n"
    .string "Vchod do tunelu$"

Route4_Text_RouteSign::
    .string "CESTA 4\n"
    .string "MT. MOON - CERULEAN CITY$"

Text_MegaPunchTeach::
    .string "Úder rachotící zurivosti!\p"
    .string "Nabity nicivou silou!\p"
    .string "Kdyz jde do tuhého,\n"
    .string "MEGA PUNCH je dokonaly útok!\l"
    .string "Souhlasís, ze?\p"
    .string "Tak!\n"
    .string "Naucím ho tvého POKéMONa!$"

Text_MegaPunchDeclined::
    .string "Vrátís se, az pochopís\n"
    .string "cenu MEGA PUNCH.$"

Text_MegaPunchWhichMon::
    .string "Dobrá!\n"
    .string "Ktery POKéMON se to naucí?$"

Text_MegaPunchTaught::
    .string "Nyní jsme bratri ve zpusobu\n"
    .string "úderu pestí!\p"
    .string "Mel bys jít, nez te uvidí ten\n"
    .string "pomateny blázen, co tam cvicí\l"
    .string "jen své hloupé kopy.$"

Text_MegaKickTeach::
    .string "Kop brutální zurivosti!\p"
    .string "Nabity nicivou silou!\p"
    .string "Kdyz se na to podíváme prímo,\n"
    .string "MEGA KICK je dokonaly útok!\l"
    .string "Nesouhlasís?\p"
    .string "Dobre!\n"
    .string "Naucím ho tvého POKéMONa!$"

Text_MegaKickDeclined::
    .string "Priplazís se zpátky, az\n"
    .string "pochopís cenu MEGA KICK.$"

Text_MegaKickWhichMon::
    .string "Dobrá!\n"
    .string "Ktery POKéMON se to chce naucit?$"

Text_MegaKickTaught::
    .string "Nyní jsme druhové ve zpusobu\n"
    .string "kopání!\p"
    .string "Mel bys utéct, nez te uvidí ten\n"
    .string "popleteny hlupák, co tam cvicí\l"
    .string "jen prosté údery pestí.$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "Páni, to je BOULDERBADGE!\n"
    .string "Más ho od BROCKA, ze ano?\p"
    .string "BROCK je super. Není jen drsny.\n"
    .string "Lidé ho mají rádi a respektují ho.\p"
    .string "Chci se stát GYM LÍDREM\n"
    .string "jako on.$"
