PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .string "DAISY: Ahoj, {PLAYER}!\p"
    .string "Muj bratr {RIVAL} je venku\n"
    .string "u dedovy LAB.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .string "DAISY: {PLAYER}, slysela jsem,\n"
    .string "zes mel souboj s {RIVAL}.\p"
    .string "To bych chtela videt!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "Deda te poslal\n"
    .string "vyrídit pochuzku?\p"
    .string "Pche, to je od nej lenivé.\n"
    .string "Tu más, tohle ti pomuze.$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .string "{PLAYER} dostal TOWN MAP\n"
    .string "od DAISY.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "Nemás na tohle místo ve\n"
    .string "svém BAG.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .string "TOWN MAP ti pomuze zjistit,\n"
    .string "kde jsi, nebo overit\l"
    .string "názvy míst.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .string "DAISY: Stejne jako lidé jsou\n"
    .string "i POKéMON zivé bytosti.\p"
    .string "Kdyz se unaví, dej jim\n"
    .string "prosím odpocinout.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .string "Je to velká mapa regionu KANTO.\n"
    .string "To by se mi hodilo!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
    .string "Police jsou narvané\n"
    .string "knihami o POKéMONech.$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .string "DAISY: Ahoj, {PLAYER}!\n"
    .string "Skvelé nacasování.\p"
    .string "Chystám se na caj.\n"
    .string "Nedás si se mnou?\p"
    .string "Ale podívej.\n"
    .string "Tví POKéMON jsou trochu spinaví.\p"
    .string "Chces, abych jednoho ucesala?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "Nepotrebujes zádné cesání?\n"
    .string "Dobre, dáme si jen caj.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "Kterého mám ucesat?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .string "DAISY: Dobre, hned ho dám\n"
    .string "do pekného stavu.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
    .string "{COLOR DARK_GRAY}{STR_VAR_1} vypadá zasnene spokojene…\p"
    .string "{COLOR RED}DAISY: A je to! Hotovo.\n"
#else @ In the JP games, gender-based text used a different font instead of different colors.
    .string "{FONT_NORMAL}{STR_VAR_1} vypadá zasnene spokojene…\p"
    .string "{FONT_FEMALE}DAISY: A je to! Hotovo.\n"
#endif
    .string "Vidís? Nevypadá to pekne?\p"
    .string "Chichi…\n"
    .string "To je roztomily POKéMON.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "Ó, promin. Vajícko opravdu\n"
    .string "ucesat neumím.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .string "DAISY: Tví POKéMON si te\n"
    .string "zamilují, kdyz je chovás s láskou.\p"
    .string "Treba, {PLAYER}, mohu videt\n"
    .string "tvého prvního POKéMONa?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .string "Víc te uz milovat ani\n"
    .string "nemuze, nez te miluje ted.\p"
    .string "Tvuj POKéMON je sasten\n"
    .string "bez sebe.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .string "Vypadá moc sastne.\p"
    .string "Kéz by to {RIVAL} videl a\n"
    .string "neco se z toho naucil.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
    .string "Je k tobe dost prátelsky.\n"
    .string "Bud k nemu dál hodny!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .string "Zacíná si te oblibovat.\n"
    .string "Asi mezi vámi roste duvera.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .string "Jeste si na tebe úplne\n"
    .string "nezvyknul.\p"
    .string "POKéMON jsou ze zacátku\n"
    .string "dost ostrazití.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .string "{PLAYER}, nelíbí se mi,\n"
    .string "jak na tebe zírá.\p"
    .string "Mohl bys na nej byt\n"
    .string "trochu hodnejsí?$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .string "…Hm, nerada to ríkám,\n"
    .string "ale…\p"
    .string "Existuje nejaky duvod, proc te\n"
    .string "tvuj POKéMON tolik nenávidí?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string "“Rozkosná a sladká\n"
    .string "CLEFAIRY”$"
