CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .string "Vítej!\n"
    .string "Vítej v CELADON OBCHODÁKU.\p"
    .string "Tabule vpravo popisuje rozlození\n"
    .string "obchodu.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .string "1F: SERVISNÍ PULT\p"
    .string "2F: TRÉNINKOVÉ TRZISTE\p"
    .string "3F: TV HERNÍ OBCHOD\p"
    .string "4F: DÁRKY OD MUDRCE\p"
    .string "5F: LÉKÁRNA\p"
    .string "STRECHA: AUTOMATY$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .string "1F: SERVISNÍ PULT$"
