Route12_Text_MonSprawledOutInSlumber::
    .string "POKéMON se rozvaluje\n"
    .string "v hlubokém, pohodlném spánku.$"

Text_SnorlaxWokeUp::
    .string "SNORLAX se probudil!\p"
    .string "Zaútocil v mrzutém vzteku!$"

Text_SnorlaxReturnedToMountains::
    .string "SNORLAX se uklidnil.\n"
    .string "Mocne zívnul…\l"
    .string "A vrátil se do hor.$"

Text_WantToUsePokeFlute::
    .string "Chces pouzít POKé FLUTE?$"

Text_PlayedPokeFlute::
    .string "{PLAYER} zahrál na POKé FLUTE.$"

Route12_Text_NedIntro::
    .string "Jo!\n"
    .string "Neco mi zabralo!$"

Route12_Text_NedDefeat::
    .string "Tja!\n"
    .string "Jen malá rybka…$"

Route12_Text_NedPostBattle::
    .string "Pockej!\n"
    .string "Mám zaseknuty vlasec!$"

Route12_Text_ChipIntro::
    .string "Bud trpelivy.\n"
    .string "Rybarení je hra na cekání.$"

Route12_Text_ChipDefeat::
    .string "Tahle mi utekla!$"

Route12_Text_ChipPostBattle::
    .string "S lepsím ROD bych chytil\n"
    .string "lepsí POKéMONy…$"

Route12_Text_JustinIntro::
    .string "Hledám MOON STONE.\n"
    .string "Nenasel jsi nejaky?$"

Route12_Text_JustinDefeat::
    .string "Auvajs!$"

Route12_Text_JustinPostBattle::
    .string "Mohl jsem nechat svého POKéMONa\n"
    .string "vyvinout pomocí MOON STONE.\p"
    .string "Pak bych vyhrál, vsadím se.$"

Route12_Text_LucaIntro::
    .string "Elektrina je má specialita.\p"
    .string "O morskych POKéMONech ale\n"
    .string "vubec nic nevím.$"

Route12_Text_LucaDefeat::
    .string "Odpojeno!$"

Route12_Text_LucaPostBattle::
    .string "Voda vede elektrinu, tak bys\n"
    .string "mel morské POKéMONy zapnout.$"

Route12_Text_HankIntro::
    .string "RYBÁRSKY BLÁZEN proti POKéMON\n"
    .string "KLUKOVI!$"

Route12_Text_HankDefeat::
    .string "Prílis mnoho!$"

Route12_Text_HankPostBattle::
    .string "Asi je clovek dobry v tom,\n"
    .string "co má rád.\p"
    .string "No, porazils me v POKéMONech,\n"
    .string "ale v rybarení me neporazís.$"

Route12_Text_ElliotIntro::
    .string "Rybarení miluju, to mi ver.\p"
    .string "Ale bylo by fajn mít taky\n"
    .string "víc práce.$"

Route12_Text_ElliotDefeat::
    .string "Není to lehké…$"

Route12_Text_ElliotPostBattle::
    .string "To nic.\n"
    .string "Prohra me uz netrápí.$"

Route12_Text_AndrewIntro::
    .string "Co se chytá?\p"
    .string "Nikdy nevís, co bys mohl\n"
    .string "chytit!$"

Route12_Text_AndrewDefeat::
    .string "Ztratil jsem to!$"

Route12_Text_AndrewPostBattle::
    .string "Co, MAGIKARP?\p"
    .string "Chytám je porád, jasne.\n"
    .string "Ale ty jsou teda mírny.$"

Route12_Text_RouteSign::
    .string "ROUTE 12 \n"
    .string "Na sever do LAVENDER$"

Route12_Text_SportfishingArea::
    .string "SPORTOVNÍ RYBÁRSKÁ OBLAST$"

Route12_Text_JesIntro::
    .string "JES: Kdyz vyhraju, pozádám\n"
    .string "GIU o ruku.$"

Route12_Text_JesDefeat::
    .string "JES: Ó, prosím, proc jsi nás\n"
    .string "nenechal vyhrát?$"

Route12_Text_JesPostBattle::
    .string "JES: Ó, GIO, odpust mi,\n"
    .string "má lásko!$"

Route12_Text_JesNotEnoughMons::
    .string "JES: GIA a já budeme\n"
    .string "navzdy spolu.\p"
    .string "Nebojujeme, dokud nemás\n"
    .string "dva vlastní POKéMONy.$"

Route12_Text_GiaIntro::
    .string "GIA: Hej, JESi…\p"
    .string "Kdyz vyhrajeme, vezmu si te!$"

Route12_Text_GiaDefeat::
    .string "GIA: Ó, ale proc?$"

Route12_Text_GiaPostBattle::
    .string "GIA: JESi, ty hlupáku!\n"
    .string "Tohle jsi zkazil!$"

Route12_Text_GiaNotEnoughMons::
    .string "GIA: Nesnesu bojovat\n"
    .string "bez svého JESe!\p"
    .string "Nemás jeste jednoho POKéMONa?$"
