SilphCo_2F_Text_ConnorIntro::
    .string "Pomoc!\n"
    .string "Jsem zamestnanec SILPHu.$"

SilphCo_2F_Text_ConnorDefeat::
    .string "Jak jsi vedel,\n"
    .string "ze jsem ROCKET?$"

SilphCo_2F_Text_ConnorPostBattle::
    .string "Pracuji pro SILPH i pro TEAM\n"
    .string "ROCKET.$"

SilphCo_2F_Text_JerryIntro::
    .string "Sem se nesmí!\n"
    .string "Bez domu!$"

SilphCo_2F_Text_JerryDefeat::
    .string "Jsi dobry.$"

SilphCo_2F_Text_JerryPostBattle::
    .string "Zvládnes ten zdejsí bludiste?\n"
    .string "Není to lehké, fakt!$"

SilphCo_2F_Text_Grunt1Intro::
    .string "Detem sem vstup zakázán!$"

SilphCo_2F_Text_Grunt1Defeat::
    .string "Drsne!$"

SilphCo_2F_Text_Grunt1PostBattle::
    .string "Kosoctvercové dlazdice jsou\n"
    .string "teleportacní bloky.\p"
    .string "Jsou to prepravníky v téhle\n"
    .string "vyspelé budove.$"

SilphCo_2F_Text_Grunt2Intro::
    .string "Hej, decko!\n"
    .string "Proc se tu touláte?$"

SilphCo_2F_Text_Grunt2Defeat::
    .string "Pokazil jsem to!$"

SilphCo_2F_Text_Grunt2PostBattle::
    .string "SILPH CO. se spojí s\n"
    .string "TEAM ROCKET!$"

Text_ThunderWaveTeach::
    .string "Íí!\n"
    .string "Ne! Pust! Pomoc!\p"
    .string "Aha, ty nejsi z TEAM ROCKET.\n"
    .string "Promin, myslela jsem…\p"
    .string "Odpustís mi, kdyz te naucím\n"
    .string "techniku THUNDER WAVE?$"

Text_ThunderWaveDeclined::
    .string "Ach…\n"
    .string "Ale THUNDER WAVE se hodí…$"

Text_ThunderWaveWhichMon::
    .string "Kterého POKéMONa mám naucit\n"
    .string "THUNDER WAVE?$"

Text_ThunderWaveTaught::
    .string "THUNDER WAVE zpusobí\n"
    .string "paralyzu cílového POKéMONa.\p"
    .string "Paralyzovany POKéMON se nemusí\n"
    .string "v boji pohnout.\p"
    .string "Je to útok typu ELECTRIC, takze\n"
    .string "na nekteré POKéMONy nezabere.$"

SilphCo_2F_Text_FloorSign::
    .string "SILPH CO. HLAVNÍ KANCELÁR\n"
    .string "2F$"
