ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Cau!\n"
    .string "Prisels z MESTA PALLET?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "Znás PROF. OAKA, ze?\p"
    .string "Prisla jeho objednávka.\n"
    .string "Mohl bys mu ji dorucit?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} dostal OAKuv BALíK\n"
    .string "od prodavace POKéMON MARTU.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Dobre, díky! Pozdravuj\n"
    .string "PROF. OAKA i ode me.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "Tenhle obchod prodává hodne\n"
    .string "PROTIJEDU, jak jsem slysel.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "Musím si koupit LEKTVARY.\p"
    .string "Nikdy nevís, kdy tvuj POKéMON\n"
    .string "bude potrebovat rychlé osetrení.$"
