ViridianCity_House_Text_NicknamingIsFun::
    .string "Vymyslet prezdívky je zábava,\n"
    .string "ale není to lehké.\p"
    .string "Chytré názvy jsou hezké, ale\n"
    .string "jednoduché si pamatujes snáz.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "Muj tatínek POKéMONy taky miluje.$"

ViridianCity_House_Text_Speary::
    .string "SPEARY: Tetweet!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "SPEAROW\n"
    .string "Jméno: SPEARY$"
