SilphCo_4F_Text_CantYouSeeImHiding::
    .string "Pst!\n"
    .string "Nevidís, ze se schovávám?$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "He?\n"
    .string "TEAM ROCKET je pryc?$"

SilphCo_4F_Text_Grunt1Intro::
    .string "TEAM ROCKET prevzal kontrolu\n"
    .string "nad SILPH CO.!$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "Argh!$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "Hahaha!\n"
    .string "Muj BOSS po tomhle prahnul!$"

SilphCo_4F_Text_RodneyIntro::
    .string "Muj POKéMON je muj verny sluha.$"

SilphCo_4F_Text_RodneyDefeat::
    .string "Sakra!\n"
    .string "Ty slaby POKéMONe!$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "Dvere jsou elektronicky\n"
    .string "uzamcené.\p"
    .string "Otevrení vyzaduje CARD KEY.$"

SilphCo_4F_Text_Grunt2Intro::
    .string "Vetrelec spatren!$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "Kdo jsi?$"

SilphCo_4F_Text_Grunt2PostBattle::
    .string "Musím to ríct BOSSOVI v 11F!$"

SilphCo_4F_Text_FloorSign::
    .string "SILPH CO. HLAVNÍ KANCELÁR\n"
    .string "4F$"
