ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "LOSTELLE: Mnauu… Smrk…\n"
    .string "Ach! Prosím, pomoc!\p"
    .string "Strasidelny POKéMON se tu pred\n"
    .string "chvílí objevil.\p"
    .string "Strásil mne porád.\n"
    .string "Vystrasil LOSTELLE.\p"
    .string "Bojím se hnout!\n"
    .string "Ale chci jít domu…$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "Ach! Uz prichází zase!\n"
    .string "Ne! Jdi pryc! Vystrasujes me!\p"
    .string "Waaaaaaah!\n"
    .string "Chci tatínka!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "Och! To bylo tak strasidelné!\n"
    .string "Dekuji ti!\p"
    .string "LOSTELLE prisla nasbírat\n"
    .string "BOBULE.\p"
    .string "Tohle si muzes vzít!$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "Jak se jmenujes?\p"
    .string "LOSTELLE se bojí, muzu jít\n"
    .string "s tebou k tátovu domu?\p"
    .string "Dobre!\n"
    .string "Pojdme domu!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "Tvoje BERRY POUCH je plná.\n"
    .string "Asi tohle nechces.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "Vítej v BERRY FOREST\p"
    .string "Bud prátelsky a podel se o\n"
    .string "BOBULE s ostatními i POKéMONy.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "Pozor na divoké POKéMONy,\n"
    .string "kterí milují BOBULE!$"

