FuchsiaCity_House2_Text_DoYouLikeToFish::
    .string "Jsem starsí bratr GURUA\n"
    .string "RYBARENÍ.\p"
    .string "Miluuuju rybarení!\n"
    .string "Bez nej byt nedokázu.\p"
    .string "Rekni, más rád rybarení?$"

FuchsiaCity_House2_Text_LikeYourStyleTakeThis::
    .string "Skvele! Líbí se mi tvuj styl.\n"
    .string "Myslím, ze muzeme byt kamarádi.\p"
    .string "Vezmi si to a rybar, kamaráde!$"

FuchsiaCity_House2_Text_ReceivedGoodRod::
    .string "{PLAYER} dostal GOOD ROD od\n"
    .string "bratra GURUA RYBARENÍ.$"

FuchsiaCity_House2_Text_GoodRodCanCatchBetterMons::
    .string "Rybarení je zpusob zivota!\n"
    .string "Je to jako nejlepsí poezie.\p"
    .string "S mizernym OLD RODem chytís\n"
    .string "jen MAGIKARPa, ze?\p"
    .string "Ale s GOOD RODem chytís\n"
    .string "mnohem lepsí POKéMONy.$"

FuchsiaCity_House2_Text_OhThatsDisappointing::
    .string "Ach…\n"
    .string "To je tak zklamání…$"

FuchsiaCity_House2_Text_HowAreTheFishBiting::
    .string "Ahoj, {PLAYER}!\p"
    .string "Jak se ryby chytají?$"

FuchsiaCity_House2_Text_YouHaveNoRoomForGift::
    .string "Ach, ne!\p"
    .string "Mel jsem pro tebe dárek, ale\n"
    .string "nemás na nej místo!$"

