LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .string "Nedávno jsem se sem prestehoval.\p"
    .string "Slysel jsem, ze MR. FUJI také není\n"
    .string "puvodne odsud.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "Divné, MR. FUJI tu není.\n"
    .string "Kam asi odesel?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "MR. FUJI se sám modlil\n"
    .string "za matku CUBONEa.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
    .string "Tohle je opravdu dum MR. FUJIho.\p"
    .string "Je velmi laskavy.\p"
    .string "Stará se o opustené\n"
    .string "a osirelé POKéMONy.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .string "Je to tak teplé!\n"
    .string "POKéMONy je príjemné objímat.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "NIDORINO: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "PSYDUCK: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "MR. FUJI: {PLAYER}…\p"
    .string "Tvá cesta s POKéDEXEM\n"
    .string "vyzaduje silné odhodlání.\p"
    .string "Bez hluboké lásky k POKéMONum\n"
    .string "muze tvá cesta selhat.\p"
    .string "Nevím, jestli ti to pomuze,\n"
    .string "ale rád bych, abys to mel.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "{PLAYER} dostal POKé FLUTE\n"
    .string "od MR. FUJIho.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "Pri zvuku POKé FLUTE\n"
    .string "se spící POKéMON probudí.\p"
    .string "Zkus to na POKéMONy, kterí\n"
    .string "spí a brání ti v ceste.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "Musís si na to udelat místo!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "MR. FUJI: Pomohla ti má\n"
    .string "POKé FLUTE?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .string "POKéMON FAN MAGAZINE\n"
    .string "Mesícní losování o velkou cenu!\p"
    .string "Prihláska je…\p"
    .string "Pryc! Byla vystrizena.\n"
    .string "Nekdo se uz musel prihlásit.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "Na polici lezí POKéMON casopisy.\p"
    .string "POKéMON INSIDER…\p"
    .string "POKéMON FAN…$"

