Route15_Text_KindraIntro::
    .string "Práve jsem pár POKéMONu vymenila.\n"
    .string "Muzu je na tobe vyzkouset?$"

Route15_Text_KindraDefeat::
    .string "To nestací!$"

Route15_Text_KindraPostBattle::
    .string "Prezdívku POKéMONa, kterého\n"
    .string "získas vymenou, nezmenís.\p"
    .string "Jen puvodní trenér ji muze\n"
    .string "dát zmenit.$"

Route15_Text_BeckyIntro::
    .string "Vypadás mírne, asi te zvládnu\n"
    .string "porazit.\p"
    .string "Pustím se do toho!$"

Route15_Text_BeckyDefeat::
    .string "Ne, omyl!$"

Route15_Text_BeckyPostBattle::
    .string "Bojím se BIKERU. Vypadají osklive\n"
    .string "a zlomyslne!$"

Route15_Text_EdwinIntro::
    .string "Kdyz pískám, dokázu prilákat\n"
    .string "ptací POKéMONy.$"

Route15_Text_EdwinDefeat::
    .string "Au!\n"
    .string "To je tragédie!$"

Route15_Text_EdwinPostBattle::
    .string "Mozná na boje nemám.\n"
    .string "Asi nejsem ten správny typ.$"

Route15_Text_ChesterIntro::
    .string "Hmm? Mí ptáci se trasou!\n"
    .string "Jsi dobry, vid?$"

Route15_Text_ChesterDefeat::
    .string "Presne jak jsem myslel!$"

Route15_Text_ChesterPostBattle::
    .string "Tohle je jasné, mel bys to\n"
    .string "vedet, ale…\p"
    .string "Útoky jako EARTHQUAKE a FISSURE\n"
    .string "na ptací POKéMONy nepusobí.$"

Route15_Text_GraceIntro::
    .string "Ach, ty malá rozkos!\n"
    .string "Jako roztomily POKéMON!$"

Route15_Text_GraceDefeat::
    .string "Vypadals tak rozkosne!$"

Route15_Text_GracePostBattle::
    .string "Odpoustím ti.\n"
    .string "Snesu to.\l"
    .string "Uz jsem velká holka.$"

Route15_Text_OliviaIntro::
    .string "Chovám POKéMONy na ochranu,\n"
    .string "protoze zijí sama.$"

Route15_Text_OliviaDefeat::
    .string "POKéMON pro me není o vítezství\n"
    .string "ani prohre.$"

Route15_Text_OliviaPostBattle::
    .string "Mám ráda, kdyz me POKéMON\n"
    .string "vítají, kdyz prijdu domu.\p"
    .string "Je to uklidnující.$"

Route15_Text_ErnestIntro::
    .string "Hej, malej! Pojd!\n"
    .string "Tyhle jsem sebral nejakemu blbcovi!$"

Route15_Text_ErnestDefeat::
    .string "Proc ne?$"

Route15_Text_ErnestPostBattle::
    .string "Zivot je príliz krátky.\n"
    .string "Zít jako psanec je super.\l"
    .string "TEAM ROCKET VLÁDNE!$"

Route15_Text_AlexIntro::
    .string "Az se mnou prohrajes, dáj mi\n"
    .string "vsechny prachy, malej!$"

Route15_Text_AlexDefeat::
    .string "To nemuze byt pravda!$"

Route15_Text_AlexPostBattle::
    .string "S tema penezma jsem jen vtipkoval.\n"
    .string "Neber to vázne.$"

Route15_Text_CeliaIntro::
    .string "Co je teraz cool?\n"
    .string "Vymenovat POKéMONy!$"

Route15_Text_CeliaDefeat::
    .string "Ríkala jsem vymena!$"

Route15_Text_CeliaPostBattle::
    .string "S kamarády vymenuju POKéMONy\n"
    .string "porád.$"

Route15_Text_YazminIntro::
    .string "Chces si zahrát s mymi POKéMONy?$"

Route15_Text_YazminDefeat::
    .string "Byla jsem moc netrpelivá!$"

Route15_Text_YazminPostBattle::
    .string "Pujdu trénovat se slabsími lidmi.$"

Route15_Text_RouteSign::
    .string "CESTA 15\n"
    .string "Na západ do FUCHSIA CITY$"

Route15_Text_MyaIntro::
    .string "MYA: Jsi ideální.\n"
    .string "Pomuzes mi vycvicit bratra?$"

Route15_Text_MyaDefeat::
    .string "MYA: RONE, musís se soustredit!\n"
    .string "Soustred se na to, co delas!$"

Route15_Text_MyaPostBattle::
    .string "MYA: Tak dobre, prituhneme.\n"
    .string "Pridám do tréninkového plánu!$"

Route15_Text_MyaNotEnoughMons::
    .string "MYA: Chces nás vyzvat?\n"
    .string "Potrebujes dva POKéMONy.$"

Route15_Text_RonIntro::
    .string "RON: Sestra je hrozná,\n"
    .string "kdyz prohrajeme.$"

Route15_Text_RonDefeat::
    .string "RON: Ach, ne, ne…\n"
    .string "Sestricko, promin!$"

Route15_Text_RonPostBattle::
    .string "RON: Ach, fuj…\n"
    .string "Kez bych mel hodnou sestru…$"

Route15_Text_RonNotEnoughMons::
    .string "RON: Chtels bojovat\n"
    .string "se mnou a se sestrou?\p"
    .string "Pak potrebujes dva POKéMONy.$"
