Route11_Text_HugoIntro::
    .string "Vyhra, prohra, nebo remíza!$"

Route11_Text_HugoDefeat::
    .string "Acha!\n"
    .string "Nevyslo to po mém!$"

Route11_Text_HugoPostBattle::
    .string "POKéMON je zivot!\n"
    .string "A zít znamená hrát hry!$"

Route11_Text_JasperIntro::
    .string "Souteze!\n"
    .string "Nemuzu se jich nabazit!$"

Route11_Text_JasperDefeat::
    .string "Mel jsem sanci!$"

Route11_Text_JasperPostBattle::
    .string "Ve svete POKéMONu nesmís\n"
    .string "byt zbabelec!$"

Route11_Text_EddieIntro::
    .string "Jdeme na to, ale nepodvádej!$"

Route11_Text_EddieDefeat::
    .string "He?\n"
    .string "To není správné!$"

Route11_Text_EddiePostBattle::
    .string "Dal jsem do toho vse.\n"
    .string "Nic nelituji.$"

Route11_Text_BraxtonIntro::
    .string "Pozor!\n"
    .string "Pokládám tady kabely!$"

Route11_Text_BraxtonDefeat::
    .string "To byl vyboj!$"

Route11_Text_BraxtonPostBattle::
    .string "Rozhlas, at se setrí energií!$"

Route11_Text_DillonIntro::
    .string "Práve jsem se stal TRENÉREM.\n"
    .string "Ale myslím, ze mohu vyhrát.$"

Route11_Text_DillonDefeat::
    .string "Mí POKéMON nevyhráli…\n"
    .string "Coze, nevyrostli dost?$"

Route11_Text_DillonPostBattle::
    .string "Co ted?\n"
    .string "Nech me byt!$"

Route11_Text_DirkIntro::
    .string "Fuhaha!\n"
    .string "Nikdy jsem neprohrál!$"

Route11_Text_DirkDefeat::
    .string "Moje první prohra!$"

Route11_Text_DirkPostBattle::
    .string "Mels jen stestí, nic víc.$"

Route11_Text_DarianIntro::
    .string "Jeste nikdy jsem nevyhrál…$"

Route11_Text_DarianDefeat::
    .string "To jsem cekal…$"

Route11_Text_DarianPostBattle::
    .string "Mel jsem smulu, jako vzdy.$"

Route11_Text_YasuIntro::
    .string "Jsem nejlepsí ve své tríde.\n"
    .string "Trénuju kazdé ráno.$"

Route11_Text_YasuDefeat::
    .string "Sakra!\n"
    .string "Mí POKéMON musí zesílit!$"

Route11_Text_YasuPostBattle::
    .string "Z hor sem chodí jeden\n"
    .string "tlusty POKéMON.\p"
    .string "Vsadím se, ze by byl silny,\n"
    .string "kdybys ho chytil.$"

Route11_Text_BernieIntro::
    .string "Pozor na zive dráty!$"

Route11_Text_BernieDefeat::
    .string "Whoa!\n"
    .string "Ty jsi ale jiskra!$"

Route11_Text_BerniePostBattle::
    .string "No, radsi zpátky do práce.$"

Route11_Text_DaveIntro::
    .string "Své POKéMONy jsem peclive\n"
    .string "choval. Uz by meli byt hotoví!$"

Route11_Text_DaveDefeat::
    .string "Papa!\n"
    .string "Díky a na shledanou!$"

Route11_Text_DavePostBattle::
    .string "Tja…\n"
    .string "Radsi pujdu najít silnejsí!$"

Route11_Text_DiglettsCave::
    .string "DIGLETT'S CAVE$"
