Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Tak se mrkneme…\n"
	.string "Ach jo! Chytils jsi jen\l"
	.string "{STR_VAR_3} druhu POKéMONu!\p"
	.string "Potrebujes {STR_VAR_1} druhu,\n"
	.string "pokud chces {STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "…Aha. Chápu.\p"
	.string "Az budes mít {STR_VAR_1} druhu,\n"
	.string "vrat se pro {STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Ach! Vidím, ze nemás místo\n"
	.string "pro {STR_VAR_2}.$"
