@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "Jsem POMOCNÍK ze SKOLKY.\p"
	.string "Pomáhám pecovat o vzácné\n"
	.string "POKéMONy TRÉNÉRu.\p"
	.string "Pokud chces, abych choval tvého\n"
	.string "POKéMONa, promluv s mou zenou.$"

DayCare_Text_DoYouWantEgg::
	.string "Ach, to jsi ty!\p"
	.string "Chovali jsme tvé POKéMONy a\n"
	.string "jaké prekvapení!\p"
	.string "Tvuj POKéMON mel VAJÍCKO!\p"
	.string "Nevíme, jak se to stalo,\n"
	.string "ale tvuj POKéMON ho mel.\p"
	.string "Chces ho, ze?$"

DayCare_Text_YourMonIsDoingFine::
	.string "Ach, to jsi ty! Rád te vidím.\n"
	.string "Tvuj {STR_VAR_1} se má skvele.$"

DayCare_Text_IllKeepIt::
	.string "Dobre, nechám si ho.\n"
	.string "Díky!$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "Nemás pro nej místo…\n"
	.string "Vrat se, az udelás místo.$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER} dostal VAJÍCKO od\n"
	.string "POMOCNÍKA ze SKOLKY.$"

DayCare_Text_TakeGoodCareOfIt::
	.string "Dobre o nej pec.$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "ポケモンを　ひきとりたい　ときは\n"
	.string "ばさんに　いって　おくれ$"

DayCare_Text_YourMonsAreDoingFine::
	.string "Ach, to jsi ty! Tvuj {STR_VAR_1} a\n"
	.string "{STR_VAR_2} se mají skvele.$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "Vázne si ho nechám.\n"
	.string "Chces ho, ze?$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "Jsem POMOCNICE ze SKOLKY.\p"
	.string "Muzeme chovat POKéMONy.\p"
	.string "Chces, abychom nejakého chovali?$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "Kterého POKéMONa pro tebe\n"
	.string "máme chovat?$"

DayCare_Text_WellRaiseYourMon::
	.string "Fajn, budeme chovat tvého\n"
	.string "{STR_VAR_1}.\p"
	.string "Vrat se pro nej pozdeji.$"

DayCare_Text_WeCanRaiseOneMore::
	.string "Muzeme chovat dva tvé POKéMONy.\p"
	.string "Chces, abychom chovali jeste\n"
	.string "jednoho?$"

DayCare_Text_HusbandWasLookingForYou::
	.string "Muj manzel te hledal.$"

DayCare_Text_FineThenComeAgain::
	.string "Dobre, tak.\n"
	.string "Prijï zas.$"

DayCare_Text_NotEnoughMoney::
	.string "Nemás dost penez…$"

DayCare_Text_TakeOtherOneBackToo::
	.string "Vezmes si zpet i toho\n"
	.string "druhého?$"

DayCare_Text_ComeAgain::
	.string "Dobre.\n"
	.string "Prijï zas.$"

DayCare_Text_GoodToSeeYou::
	.string "Ach, to jsi ty!\n"
	.string "Rád te vidím.\p"
	.string "Tvym POKéMONum se musí\n"
	.string "darit dobre!$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "Tvuj {STR_VAR_1} vyrostl\n"
	.string "o {STR_VAR_2} úrovní.$"

DayCare_Text_YourPartyIsFull::
	.string "Tvuj POKéMON tym je plny.\n"
	.string "Udelej místo a prijï.$"

DayCare_Text_TakeBackWhichMon::
	.string "どっちの　ポケモンを　ひきとるかい？$"

DayCare_Text_ItWillCostX::
	.string "Pokud chces svého {STR_VAR_1}\n"
	.string "zpet, bude te to stát ¥{STR_VAR_2}.$"

DayCare_Text_HeresYourMon::
	.string "Skvelé!\n"
	.string "Tady je tvuj POKéMON.$"

DayCare_Text_TookBackMon::
	.string "{PLAYER} si vzal {STR_VAR_1} od\n"
	.string "POMOCNICE ze SKOLKY.$"

DayCare_Text_YouHaveJustOneMon::
	.string "Ach? Ale ty mas jen\n"
	.string "jednoho POKéMONa.\p"
	.string "Prijï jindy.$"

DayCare_Text_TakeYourMonBack::
	.string "Vezmes si POKéMONa zpet?$"

DayCare_Text_WhatWillYouBattleWith::
	.string "Kdyz mi nechás toho POKéMONa,\n"
	.string "s cím budes bojovat?\p"
	.string "Prijï jindy.$"

DayCare_Text_Huh::
	.string "Co?$"
