@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "Je narvaná POKéMON\n"
	.string "knihami.$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "MAPA MESTA.$"

Text_PokeMartShelf::
	.string "Páni!\n"
	.string "Spousta POKéMON veci!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Nádobí a talíre jsou\n"
	.string "úhledne srovnané.$"

Text_Kitchen::
	.string "Voní to skvele!\n"
	.string "Nekdo tu varil.$"

Text_Dresser::
	.string "Pekne udelaná komoda.\n"
	.string "Vejde se do ní spousta veci.$"

Text_Snacks::
	.string "Je tu hromada svacin.$"

Text_PokemartSign::
	.string "Vsechny tvé potreby pro hru!\n"
	.string "POKéMON MART$"

Text_PokecenterSign::
	.string "Vylec své POKéMONy!\n"
	.string "POKéMON CENTRUM$"

Text_Indigo_UltimateGoal::
	.string "INDIGO PLATEAU\p"
	.string "Konecny cíl TRÉNÉRu!\n"
	.string "POKéMON LIGA HQ$"

Text_Indigo_HighestAuthority::
	.string "INDIGO PLATEAU\p"
	.string "Nejvyssí POKéMON autorita!\n"
	.string "POKéMON LIGA HQ$"

Text_Food::
	.string "Mela by tu byt spousta\n"
	.string "vybornych veci k jídlu.$"

Text_Blueprints::
	.string "Je to jakysi nákres.\n"
	.string "Je plny diagramu a textu.$"

Text_Painting::
	.string "Pekny obrázek POKéMONa.\n"
	.string "Vypadá, ze se cítí dobre.$"

Text_PowerPlantMachine::
	.string "Co je to za stroj?\n"
	.string "Radsi si s ním nezahrávej!$"

Text_Telephone::
	.string "Je to telefon.\n"
	.string "Radsi ho nepouzívat.$"

Text_Computer::
	.string "Samá slozitá slova a\n"
	.string "nepochopitelná císla…$"

Text_AdvertisingPoster::
	.string "Je to reklamní plakát\n"
	.string "na ruzné produkty.$"

Text_TastyFood::
	.string "Ach, voní to dobre!\n"
	.string "Mozná ti zakrucí v zaludku!$"

Text_TrashBin::
	.string "Uvnitr…\n"
	.string "……\p"
	.string "Nic tu není!$"

Text_Cup::
	.string "Hrnek se znackou POKéMONa\n"
	.string "na sobe.$"

Text_PolishedWindow::
	.string "Okno je velmi dobre vylestené.$"

Text_BeautifulSkyWindow::
	.string "Za oknem…\p"
	.string "Obloha vypadá fantasticky\n"
	.string "krásne.$"

Text_BlinkingLights::
	.string "Svetla ruznych barev\n"
	.string "blikají a zhasínají.$"

Text_NeatlyLinedUpTools::
	.string "Vsechny nástroje jsou\n"
	.string "úhledne srovnané.$"

Text_ImpressiveMachine::
	.string "Je to jakysi stroj.\n"
	.string "Je opravdu impozantní.$"

Text_VideoGame::
	.string "Je to nejnovejsí videohra!\n"
	.string "Vypadá zábavne!$"

Text_Burglary::
	.string "Jsou tu zjevné stopy\n"
	.string "vloupání…$"

Text_PlayerFacingTVScreen::
	.string "V TV je POKéMON!\n"
	.string "Vypadá, ze se baví.$"
