Trade_Text_LookingForMonWannaTradeForMon::
	.string "Hledám POKéMONa\n"
	.string "{STR_VAR_1}!\p"
	.string "Vymenís ho za mého\n"
	.string "{STR_VAR_2}?$"

Trade_Text_AwwOhWell::
	.string "Ach!\n"
	.string "No nic…$"

Trade_Text_WhatThatsNoMon::
	.string "Co?\n"
	.string "To není {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "Hej, díky!$"

Trade_Text_IsntMyOldMonGreat::
	.string "Není muj stary {STR_VAR_2} skvely?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "Ahoj! Nemás náhodou\n"
	.string "{STR_VAR_1}?\p"
	.string "Souhlasíl bys s vymenou za\n"
	.string "mého {STR_VAR_2}?$"

Trade_Text_WellIfYouDontWantTo::
	.string "No, kdyz nechces…$"

Trade_Text_ThisIsntMon::
	.string "Hmmm?\n"
	.string "Tohle není {STR_VAR_1}.\p"
	.string "Vzpomen si na me, az ho mas.$"

Trade_Text_Thanks::
	.string "Díky!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "Ten {STR_VAR_2}, kterého jsem ti dal,\n"
	.string "zesílil?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "Ahoj!\n"
	.string "Mas {STR_VAR_1}?\p"
	.string "Chces ho vymenit za mého\n"
	.string "{STR_VAR_2}?$"

Trade_Text_ThatsTooBad::
	.string "To je smula.$"

Trade_Text_ThisIsNoMon::
	.string "…Tohle není {STR_VAR_1}.\p"
	.string "Az ho budes mít, vymen ho se mnou.$"

Trade_Text_ThanksYoureAPal::
	.string "Díky, jsi kámos!$"

Trade_Text_HowIsMyOldMon::
	.string "Jak se má muj stary {STR_VAR_2}?\n"
	.string "Muj {STR_VAR_1} se má skvele!$"
