gOtherText_NewName::
    .string "NOVÉ JMÉNO$"

gNameChoice_Green::
    .string "GREEN$"

gNameChoice_Red::
    .string "RED$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "ASH$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "Jednotlivá tlacítka budou vysvetlena\n"
    .string "v poradí jejich dulezitosti.$"

gControlsGuide_Text_DPad::
    .string "Pohybuje hlavní postavou.\n"
    .string "Také slouzí k volbe ruznych\n"
    .string "polozek.$"

gControlsGuide_Text_AButton::
    .string "Slouzí k potvrzení volby, zkoumání\n"
    .string "vecí, hovoru a posouvání textu.$"

gControlsGuide_Text_BButton::
    .string "Slouzí k odchodu, zrusení volby\n"
    .string "a zrusení rezimu.$"

gControlsGuide_Text_StartButton::
    .string "Stiskni toto tlacítko pro otevrení\n"
    .string "MENU.$"

gControlsGuide_Text_SelectButton::
    .string "Slouzí k presunu predmetu a\n"
    .string "pouzití registrovaného predmetu.$"

gControlsGuide_Text_LRButtons::
    .string "Pokud potrebujes pomoc se hrou\n"
    .string "nebo jak neco udelat,\n"
    .string "stiskni L nebo R tlacítko.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Tak mi rekni. Jsi kluk?\n"
    .string "Nebo holka?$"

gPikachuIntro_Text_Page1::
    .string "Ve svete, do kterého se chystás\n"
    .string "vstoupit, te ceká velké\n"
    .string "dobrodruzství, kde budes hrdinou.\n"
    .string "\n"
    .string "Mluv s lidmi a zkoumej veci\n"
    .string "vsude, kam jdes - ve mestech,\n"
    .string "na cestách ci v jeskyních.\n"
    .string "Sbírej informace a tipy.$"

gPikachuIntro_Text_Page2::
    .string "Nové cesty se ti otevrou, kdyz\n"
    .string "budes pomáhat lidem v nouzi,\n"
    .string "zdolávat vyzvy a resit záhady.\n"
    .string "\n"
    .string "Obcas te vyzvou jiní a\n"
    .string "napadnou divoké stvury.\n"
    .string "Bud odvázny a nepolevuj.$"

gPikachuIntro_Text_Page3::
    .string "Behem svého dobrodruzství doufáme,\n"
    .string "ze poznás vsechny druhy lidí\n"
    .string "a dosáhnes osobního rustu.\n"
    .string "To je nás hlavní cíl.\n"
    .string "\n"
    .string "Stiskni tlacítko A a\n"
    .string "zacni své dobrodruzství!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Zdravícko!\n"
    .string "Rád te poznávám!\p"
    .string "Vítej ve svete POKéMONu!\p"
    .string "Jmenuji se OAK.\p"
    .string "Lidé mi laskave ríkají\n"
    .string "POKéMON PROFESOR.\p$"

gOakSpeech_Text_ThisWorld::
    .string "Tento svet…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…je obydlen siroko daleko\n"
    .string "tvory zvanymi POKéMON.\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "Pro nekoho jsou POKéMONi mazlícci.\n"
    .string "Jiní je pouzívají k souboji.\p"
    .string "Pokud jde o me…\p"
    .string "Studuji POKéMONy jako profesi.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "Ale nejprve mi povez\n"
    .string "neco o sobe.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Zacneme tvym jménem.\n"
    .string "Jak se jmenujes?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Aha…\n"
    .string "Tvé jméno je tedy {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "Tohle je muj vnuk.\p"
    .string "Je tvuj rival, co jste oba\n"
    .string "byli mimina.\p"
    .string "…Hmm, jak se to jmenoval?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Jméno tvého rivala, jak to bylo?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "…Ehm, bylo to {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "Presne tak! Uz si vzpomínám!\n"
    .string "Jeho jméno je {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Tvá vlastní POKéMON legenda\n"
    .string "se chystá zacít!\p"
    .string "Svet snu a dobrodruzství s\n"
    .string "POKéMONy ceká! Jdeme na to!$"
