Text_ObtainedTheX::
	.string "Získal jsi {STR_VAR_2}!$"

Text_BagIsFull::
	.string "TASKA je plná…$"

Text_PutItemAway::
	.string "{PLAYER} vlozil {STR_VAR_2}\n"
	.string "do {STR_VAR_3}.$"

Text_FoundOneItem::
	.string "{PLAYER} nasel {STR_VAR_2}!$"

Text_TooBadBagFull::
	.string "Smula!\n"
	.string "TASKA je plná…$"

Text_FoundXCoins::
	.string "{PLAYER} nasel\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER} ulozil MINCE do\n"
	.string "POUZDRA NA MINCE.$"

Text_CoinCaseIsFull::
	.string "Smula!\n"
	.string "POUZDRO NA MINCE je plné…$"

Text_NothingToPutThemIn::
	.string "Smula!\n"
	.string "Není kam je dát…$"

Text_FoundXItems::
	.string "{PLAYER} nasel\n"
	.string "{STR_VAR_1} {STR_VAR_2}(ks)!$"

Text_ObtainedTheDecor::
	.string "Získal jsi {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor::
	.string "Smula! Není místo pro\n"
	.string "dalsí {STR_VAR_2}…$"

Text_DecorTransferredToPC::
	.string "{STR_VAR_2} byl prenesen\n"
	.string "do PC.$"
