Text_MonSentToBoxInSomeonesPC::
    .string "{STR_VAR_2} byl prenesen\n"
    .string "na cizí PC.\p"
    .string "Umísten v \n"
    .string "BOXU “{STR_VAR_1}.”$"

Text_MonSentToBoxInBillsPC::
    .string "{STR_VAR_2} byl prenesen\n"
    .string "na BILLovo PC.\p"
    .string "Umísten v \n"
    .string "BOXU “{STR_VAR_1}.”$"

Text_MonSentToBoxSomeonesBoxFull::
    .string "BOX “{STR_VAR_3}” na\n"
    .string "cizím PC byl plny.\p"
    .string "{STR_VAR_2} byl prenesen\n"
    .string "do BOXU “{STR_VAR_1}.”$"

Text_MonSentToBoxBillsBoxFull::
    .string "BOX “{STR_VAR_3}” na\n"
    .string "BILLove PC byl plny.\p"
    .string "{STR_VAR_2} byl prenesen\n"
    .string "do BOXU “{STR_VAR_1}.”$"

Text_PlayerObtainedTheMon::
    .string "{PLAYER} získal\n"
    .string "{STR_VAR_1}!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
    .string "ポケモンを　もちきれないので\n"
    .string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
    .string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon::
    .string "Uz není místo pro POKéMONy!\p"
    .string "POKéMON BOXY jsou plné a\n"
    .string "nemohou prijmout dalsí!$"
