Text_MayIHelpYou::
	.string "Ahoj!\n"
	.string "Mohu ti pomoci?$"

Text_FillOutQuestionnaire::
	.string "Tady je dotazník.\n"
	.string "Chces ho vyplnit?$"

Text_QuestionnaireThankYou::
	.string "Díky, ze sis udelal cas\n"
	.string "a vyplnil nás dotazník.\p"
	.string "Tvá zpetná vazba poslouzí\n"
	.string "pro budoucí pouzití.$"

Text_YouKnowThoseWords::
	.string "Ahoj!\n"
	.string "Znás tato slova?\p"
	.string "To znamená, ze víc o\n"
	.string "MYSTERY GIFTu.\p"
	.string "Od ted budes dostávat\n"
	.string "MYSTERY GIFTy!$"

Text_YouCanAccessMysteryGift::
	.string "Po ulození hry budes mít\n"
	.string "prístup k MYSTERY GIFTu.$"

Text_ThankYouForAccessingMysteryGift::
	.string "Díky za pouzití systému\n"
	.string "MYSTERY GIFT.$"
