PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Rád te vidím!\n"
	.string "Jak ti jde POKéDEX?\p"
	.string "Tak se podívám.$"

PokedexRating_Text_SeenXOwnedY::
	.string "Tvuj pokrok v POKéDEXu je:\p"
	.string "{STR_VAR_1} videnych POKéMONu a\n"
	.string "{STR_VAR_2} vlastnenych POKéMONu.\p"
	.string "{FONT_NORMAL}Hodnocení PROF. OAKA:$"

PokedexRating_Text_LessThan10::
	.string "Jeste mas hodne práce.\p"
	.string "Bez do kazdé trávy, kterou\n"
	.string "uvidís, a hledej POKéMONy!$"

PokedexRating_Text_LessThan20::
	.string "Vypadá to, ze jsi na\n"
	.string "správné ceste!\p"
	.string "Dal jsem jednomu z mych\n"
	.string "POMOCNÍKu HM FLASH. Bez si pro nej!$"

PokedexRating_Text_LessThan30::
	.string "Tvuj POKéDEX by si zaslouzil\n"
	.string "trochu více!\p"
	.string "Zkus chytit dalsí druhy\n"
	.string "POKéMONu!$"

PokedexRating_Text_LessThan40::
	.string "Dobre, je videt, ze se\n"
	.string "opravdu snazís!\p"
	.string "Dal jsem jednomu z mych\n"
	.string "POMOCNÍKu ITEMFINDER. Vezmi si ho!$"

PokedexRating_Text_LessThan50::
	.string "Tvuj POKéDEX se hezky\n"
	.string "plní!\p"
	.string "Dal jsem jednomu z mych\n"
	.string "POMOCNÍKu AMULET COIN. Bez pro ni!$"

PokedexRating_Text_LessThan60::
	.string "Ach, konecne jsi prekonal\n"
	.string "50 druhu!\p"
	.string "Dal jsem jednomu z mych\n"
	.string "POMOCNÍKu EXP. SHARE. Bez pro nej!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! Toto se mení v dost\n"
	.string "úctyhodny POKéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Velmi dobré!\p"
	.string "Myslím, ze rybarením chytís\n"
	.string "jeste více POKéMONu!$"

PokedexRating_Text_LessThan90::
	.string "Úzasné! Hádám… Mas rád\n"
	.string "sberatelství, ze?$"

PokedexRating_Text_LessThan100::
	.string "Jsem ohromen!\n"
	.string "Muselo to byt tezké!$"

PokedexRating_Text_LessThan110::
	.string "Konecne jsi dosáhl 100 druhu!\n"
	.string "Nemohu uverit, jak jsi dobry!$"

PokedexRating_Text_LessThan120::
	.string "Mas i vyvinuté formy\n"
	.string "POKéMONu! Super!$"

PokedexRating_Text_LessThan130::
	.string "Vyborne! Vyménuj s prateli,\n"
	.string "abys získal dalsí!$"

PokedexRating_Text_LessThan140::
	.string "Vynikající!\n"
	.string "Stal ses opravdovym profíkem!$"

PokedexRating_Text_LessThan150::
	.string "Uz mi nezbyvá co ríct!\n"
	.string "Jsi ted POKéMON PROFESOR!$"

PokedexRating_Text_Complete::
	.string "Tvuj POKéDEX je kompletní!\n"
	.string "Gratuluji!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "A tvuj NÁRODNÍ POKéDEX je:\p"
	.string "{STR_VAR_1} videnych POKéMONu a\n"
	.string "{STR_VAR_2} vlastnenych POKéMONu.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "Tesím se, az naplnís\n"
	.string "NÁRODNÍ POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Konecne…\p"
	.string "Konecne jsi dokoncil\n"
	.string "POKéDEX!\p"
	.string "Je to nádhera!\n"
	.string "Vskutku, fantasticky cin!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_HaHa::
	.string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Díky, {PLAYER}!\n"
	.string "Upremne, díky!\l"
	.string "Splnil jsi muj sen!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ach, vítej!\p"
	.string "Povez, jak ti jde\n"
	.string "POKéDEX?\p"
	.string "Wahaha!\p"
	.string "Vlastne to vím, ale\n"
	.string "stejne se rád dívám!\p"
	.string "Tak se podívám…$"
