Pokedude_Text_SpeedierBattlerGoesFirst::
	.string "POKé DUDE: Rychlejsí bojovník\n"
	.string "útocí jako první.$"

Pokedude_Text_MyRattataFasterThanPidgey::
	.string "Vypadá to, ze muj RATTATA byl\n"
	.string "rychlejsí nez PIDGEY.$"

Pokedude_Text_BattlersTakeTurnsAttacking::
	.string "Bojovníci se strídají v útoku\n"
	.string "a snizují si navzájem HP.$"

Pokedude_Text_MyRattataWonGetsEXP::
	.string "Muj RATTATA snízil HP nepríteli\n"
	.string "na nulu, takze vyhrává!\p"
	.string "POKéMON, kterí bojovali,\n"
	.string "získají EXP. body.\p"
	.string "Kdyz POKéMON nasbírá dost\n"
	.string "EXP. bodu, postoupí na úroven.\p"
	.string "Postup zesílí tvého POKéMONa\n"
	.string "víc nez predtím.$"

Pokedude_Text_UhOhRattataPoisoned::
	.string "POKé DUDE: Ach jo…\n"
	.string "Muj RATTATA byl otráven…\p"
	.string "Kdyz je POKéMON otráven, ztrácí\n"
	.string "HP postupne.$"

Pokedude_Text_HealStatusRightAway::
	.string "Pokud má POKéMON statusovy\n"
	.string "problém, hned ho vyléc.$"

Pokedude_Text_UsingItemTakesTurn::
	.string "Pouzití predmetu na POKéMONa\n"
	.string "spotrebuje jeden tah.\p"
	.string "Ted je rada na souperi!$"

Pokedude_Text_YayWeManagedToWin::
	.string "Hurá!\n"
	.string "Podarilo se nám vyhrát!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
	.string "POKé DUDE: Útok BUBBLE je\n"
	.string "WATER typ.\p"
	.string "ODDISH je POKéMON typu\n"
	.string "GRASS/POISON.\p"
	.string "WATER útok je pohlcen\n"
	.string "GRASS POKéMONem…\p"
	.string "Útok je málo úcinny a delá\l"
	.string "jen polovicní zranení.$"

Pokedude_Text_GrassEffectiveAgainstWater::
	.string "Ach jo, to není dobré!\p"
	.string "Útok ABSORB, co jsi videl,\n"
	.string "je GRASS typu.\p"
	.string "POLIWAG je WATER POKéMON.\p"
	.string "ABSORB je tedy super úcinny\n"
	.string "a dává dvojnásobné zranení.$"

Pokedude_Text_LetsTryShiftingMons::
	.string "Nebude lehké zvítezit\n"
	.string "v této sestave…\p"
	.string "Zkusme prepnout POKéMONa!$"

Pokedude_Text_ShiftingUsesTurn::
	.string "Prepnutí POKéMONa spotrebuje\n"
	.string "jeden tah.\p"
	.string "Ted je rada na souperi.$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
	.string "BUTTERFREE je POKéMON typu\n"
	.string "BUG/FLYING.\p"
	.string "Proti tomuto POKéMONovi\n"
	.string "útok typu GRASS…\p"
	.string "…delá jen polovicní zranení\n"
	.string "na BUG POKéMONa…\p"
	.string "…a také jen polovicní zranení\n"
	.string "na FLYING POKéMONa.\p"
	.string "BUTTERFREE jako BUG/FLYING\n"
	.string "dostane jen ctvrtinu zranení.$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
	.string "ODDISH je POKéMON typu\n"
	.string "GRASS/POISON.\p"
	.string "FLYING nebo PSYCHIC útok je\n"
	.string "proti nemu super úcinny.\p"
	.string "Jeden z techto útoku\n"
	.string "udelá dvojnásobné zranení.\p"
	.string "Dobre, jedeme!$"

Pokedude_Text_YeahWeWon::
	.string "Jo!\n"
	.string "Vyhráli jsme!$"

Pokedude_Text_WeakenMonBeforeCatching::
	.string "POKé DUDE: Kdyz chytás\n"
	.string "POKéMONa, nehází hned POKé BALL.\p"
	.string "Nejdrív ho oslab snízením\n"
	.string "jeho HP.$"

Pokedude_Text_BestIfTargetStatused::
	.string "Dobre, to by melo stacit.\p"
	.string "Ale jestli to jde, je nejlepsí,\n"
	.string "kdyz má cíl statusovy\l"
	.string "problém.\p"
	.string "Treba je lehcí ho chytit,\n"
	.string "kdyz spí nebo je ochromeny.$"

Pokedude_Text_CantDoubleUpOnStatus::
	.string "To POKéMONa udelá mnohem\n"
	.string "snadnejsího k chycení!\p"
	.string "Aha. Pokud POKéMONa ochromís,\n"
	.string "nemuzes ho navíc uspat\l"
	.string "k ochromení.\p"
	.string "Jinymi slovy, nemuzes\n"
	.string "kombinovat statusové potíze.$"

Pokedude_Text_LetMeThrowBall::
	.string "Dobre!\n"
	.string "Hodím POKé BALL!$"

Pokedude_Text_PickBestKindOfBall::
	.string "Pred hodem POKé BALLem zvaz\n"
	.string "stav a typ POKéMONa\l"
	.string "a vyber druh BALLu, ktery\l"
	.string "bude fungovat nejlépe.$"
