Text_OnlySkilledTrainersAllowedThrough::
	.string "Pouze opravdu zdatní trénéri\n"
	.string "mohou projít.\p"
	.string "Jeste nemás {STR_VAR_1}\n"
	.string "!$"

Text_CantLetYouPass::
	.string "Pravidla jsou pravidla.\n"
	.string "Nemohu te pustit.$"

Text_OhThatsBadgeGoRightAhead::
	.string "Ach! To je {STR_VAR_1}!\n"
	.string "Bez rovne dál.$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "Projít muzes jen, pokud mas\n"
	.string "{STR_VAR_1}.\p"
	.string "Jeste nemás {STR_VAR_1}\n"
	.string ".\p"
	.string "Musís ho mít, abys dosel do\n"
	.string "POKéMON LIGY.$"

Text_OnlyPassWithBadgeOhGoAhead::
	.string "Projít muzes jen, pokud mas\n"
	.string "{STR_VAR_1}.\p"
	.string "Ach! To je {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "Dobre, tak.\n"
	.string "Prosím, bez rovne dál.$"
