gText_WouldYouLikeToSaveTheGame::
	.string "Chces ulozit hru?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "Uz existuje ulozená hra.\n"
	.string "Mám ji prepsat?$"

gText_SavingDontTurnOffThePower::
	.string "UKLÁDÁNÍ…\n"
	.string "NEVYPÍNEJ NAPÁJENÍ.$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} ulozil hru.$"

gText_SaveFailed2::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "VAROVÁNÍ!\p"
	.string "Existuje jiny ulozeny soubor\n"
	.string "hry.\p"
	.string "Pokud nyní ulozís, druhy\n"
	.string "soubor vcetne predmetu a\l"
	.string "POKéMONu bude úplne ztracen.\p"
	.string "Opravdu chces ulozit a prepsat\n"
	.string "druhou ulozenou hru?$"
