@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.string "Hmm…\n"
	.string "Opravdu…$"

PalletTown_Text_OhLookLook::
	.string "Ach!\n"
	.string "Podívej, podívej!$"

PalletTown_Text_ReadItReadIt::
	.string "Prectí to, prectí!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.string "TIPY PRO TRÉNÉRA\p"
	.string "Stiskni START pro otevrení MENU!$"

PalletTown_Text_SignsAreUsefulArentThey::
	.string "Cedule jsou uzitecné, ze?$"

PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "Podívej, podívej!\p"
	.string "Opsala jsem, co bylo na\n"
	.string "jedné z cedulí TIPY PRO TRÉNÉRA!$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "TIPY PRO TRÉNÉRA!\p"
	.string "Stiskni START pro otevrení MENU!$"
