CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.string "Je to POKéMON TISKÁRNA!\p"
	.string "Muze otisknout tvého POKéMONa\n"
	.string "na zadní stranu KARTY TRÉNÉRA.\p"
	.string "Stojí to jen ¥50.\n"
	.string "Chces to zkusit?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.string "Nemás dost penez.$"

CeladonCity_GameCorner_Text_ChoosePrintType::
	.string "Vyber prosím typ tisku.$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.string "Sirsí úsmev pro foto, prosím!\n"
	.string "Tri… dva… jedna…\p"
	.string "Cvak!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.string "Tvuj POKéMON tisk je hotov!\n"
	.string "Zkontroluj KARTU TRÉNÉRA.$"

FourIsland_House2_Text_WishICouldShowOffStickers::
	.string "Hihi…\n"
	.string "Mám hromadu NÁLEPEK.\l"
	.string "Kéz bych se s nimi pochlubila…$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
	.string "Ach, vyborne!\n"
	.string "Prisel jsi na správné místo!\p"
	.string "Hele, hele! Vidís? Vidís?\n"
	.string "To jsou mé NÁLEPKY!\l"
	.string "Koukni, kolik jich mám!\p"
	.string "Vsadím se, ze nejaké chces.\n"
	.string "Vsadím se, ze ano!\p"
	.string "Dám ti NÁLEPKU, kdyz mi reknes\n"
	.string "neco úzasného o sobe.\p"
	.string "Cím se pochlubís?$"

FourIsland_House2_Text_BragAboutSomethingForMe::
	.string "Pochlub se necím.\n"
	.string "Dám ti NÁLEPKU.$"

FourIsland_House2_Text_BragAboutWhatToday::
	.string "Ach, ahoj!\n"
	.string "Tady jde chvástal.\p"
	.string "Cím se dnes pochlubís?$"

FourIsland_House2_Text_WowHoFLowest::
	.string "Páni, dostal ses do\n"
	.string "SÍNE SLÁVY.\p"
	.string "To je hezké, jojo!\n"
	.string "Dám ti jednu z techto.$"

FourIsland_House2_Text_WowHoFLow::
	.string "Páni, byl jsi v SÍNI SLÁVY\n"
	.string "uz castokrát!\p"
	.string "To je impozantní, jojo!\n"
	.string "Dám ti jednu z techto.$"

FourIsland_House2_Text_WowHoFHigh::
	.string "Wow! Byl jsi v SÍNI SLÁVY\n"
	.string "tolikrát?\l"
	.string "To je vázne úzasné, jojo!\p"
	.string "Vlastnís POKéMON LIGU!\n"
	.string "Dám ti jednu z techto.$"

FourIsland_House2_Text_WowHoFHighest::
	.string "Hrome! Sel jsi do SÍNE SLÁVY\n"
	.string "tolikrát?\p"
	.string "Jsi za hranicí úzasna, jojo!\n"
	.string "Musím ti dát tohle.$"

FourIsland_House2_Text_HoFStickerApplied::
	.string "NÁLEPKA SÍNE SLÁVY byla\n"
	.string "nalepena na KARTU TRÉNÉRA.$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
	.string "Hmm…\p"
	.string "Prijd s lepsím príbehem,\n"
	.string "platí?$"

FourIsland_House2_Text_LivingLegendHoF::
	.string "Ach ne, to nejde.\p"
	.string "Jsi prakticky zijící legenda.\n"
	.string "Uz nemám NÁLEPKY pro tebe.$"

FourIsland_House2_Text_WowEggsLowest::
	.string "Páni, existují POKéMON VAJÍCKA?\n"
	.string "To jsem nevedela!\p"
	.string "To je hezké, jojo!\n"
	.string "Dám ti jednu z techto.$"

FourIsland_House2_Text_WowEggsLow::
	.string "Vylíhl jsi tolik VAJÍCEK?\n"
	.string "Vázne je musís mít rád!\p"
	.string "To je impozantní, jojo!\n"
	.string "Dám ti jednu z techto.$"

FourIsland_House2_Text_WowEggsHigh::
	.string "Wow! Vylíhl jsi celou kupu\n"
	.string "VAJÍCEK!\p"
	.string "Jsi stroj na líhnutí VAJEC!\n"
	.string "Dám ti jednu z techto.$"

FourIsland_House2_Text_WowEggsHighest::
	.string "Co… Vylíhl jsi tolik VAJÍCEK?\p"
	.string "Co stojí za tvou láskou k VAJÍCKUM?\n"
	.string "Je to za hranicí úzasna, jojo!\p"
	.string "Jsi az prílis úzasny.\n"
	.string "Musím ti dát tohle.$"

FourIsland_House2_Text_EggStickerApplied::
	.string "NÁLEPKA VAJÍCKA byla nalepena\n"
	.string "na KARTU TRÉNÉRA.$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
	.string "Hmm…\p"
	.string "Prijd s lepsím príbehem,\n"
	.string "platí?$"

FourIsland_House2_Text_LivingLegendEggs::
	.string "Ach ne, to nejde.\p"
	.string "Jsi prakticky zijící legenda.\n"
	.string "Uz nemám NÁLEPKY pro tebe.$"

FourIsland_House2_Text_WowLinkWinsLowest::
	.string "Páni, darí se ti v\n"
	.string "link soubojích?\p"
	.string "Jsi dost silny, jojo!\n"
	.string "Dám ti jednu z techto.$"

FourIsland_House2_Text_WowLinkWinsLow::
	.string "Porazil jsi prátele v link\n"
	.string "soubojích uz castokrát?\p"
	.string "Jsi impozantne silny, jojo!\n"
	.string "Dám ti jednu z techto.$"

FourIsland_House2_Text_WowLinkWinsHigh::
	.string "Wow! Porazil jsi prátele\n"
	.string "desive mnohokrát.\p"
	.string "Prisel jsi kvuli tomu o ne?\n"
	.string "Dám ti jednu z techto.$"

FourIsland_House2_Text_WowLinkWinsHighest::
	.string "Co… Setsakra páni!\n"
	.string "Vyhrál jsi neuveritelne casto!\p"
	.string "Az me dostává, jaky jsi tvrdák.\p"
	.string "Jsi nocní mura souperu!\n"
	.string "Musím ti dát tohle.$"

FourIsland_House2_Text_VictoryStickerApplied::
	.string "NÁLEPKA VÍTEZSTVÍ byla nalepena\n"
	.string "na KARTU TRÉNÉRA.$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
	.string "Hmm…\p"
	.string "Prijd s lepsím príbehem,\n"
	.string "platí?$"

FourIsland_House2_Text_LivingLegendLinkWins::
	.string "Ach ne, to nejde.\p"
	.string "Jsi prakticky zijící legenda.\n"
	.string "Uz nemám NÁLEPKY pro tebe.$"
