VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "Baterie není dostatecne nabitá.\p"
	.string "Pocet kroku k plnému nabití\n"
	.string "baterie: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "V dosahu nejsou zádní TRÉNÉRI,\n"
	.string "kterí by mohli bojovat…\p"
	.string "VS SEEKER byl vypnut.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "Ostatní TRÉNÉRI nevypadají,\n"
	.string "ze by byli pripraveni.\p"
	.string "Pockejme na pozdeji.{PAUSE_UNTIL_PRESS}$"

Route3_Text_ColtonRematchIntro::
	.string "Hej!\n"
	.string "Videl jsem te ve VIRIDIAN LESE!$"

Route3_Text_BenRematchIntro::
	.string "Ahoj! Mám rád sortky!\n"
	.string "Jsou pohodlné a snadné!\p"
	.string "Mel bys nosit sortky taky!$"

Route3_Text_JaniceRematchIntro::
	.string "Promin!\n"
	.string "Pochád na me koukás, vid?$"

Route3_Text_GregRematchIntro::
	.string "Jsi TRÉNÉR, ze?\n"
	.string "Pojdme na to hned!$"

Route3_Text_SallyRematchIntro::
	.string "Ten pohled, co mi dávás…\n"
	.string "Tak me zaujímá!$"

Route3_Text_CalvinRematchIntro::
	.string "Hej! Co je s tebou?\n"
	.string "Porád nemás sortky!$"

Route3_Text_JamesRematchIntro::
	.string "Budu s tebou bojovat s POKéMONy,\n"
	.string "co jsem zacal trénovat.$"

Route3_Text_RobinRematchIntro::
	.string "Hej!\n"
	.string "Strcil jsi do me?$"

Route4_Text_CrissyRematchIntro::
	.string "Vzdy chytám houbové POKéMONy\n"
	.string "na MT. MOON.$"

Route6_Text_RickyRematchIntro::
	.string "Ach! Ty jsi ten zvedavy klucina,\n"
	.string "co nás odposlouchával!$"

Route6_Text_NancyRematchIntro::
	.string "Promin! Nerekla jsem ti, ze\n"
	.string "je to soukromy rozhovor?\p"
	.string "Nemel bys naslouchat,\n"
	.string "neslusná osobo!$"

Route6_Text_KeigoRematchIntro::
	.string "Snazím se najít neco dobrého,\n"
	.string "co není BUG POKéMON, ale…$"

Route6_Text_JeffRematchIntro::
	.string "Hm?\n"
	.string "Zase chces se mnou?$"

Route6_Text_IsabelleRematchIntro::
	.string "Já?\n"
	.string "Dobre. Zahraju si jednou.$"

Route6_Text_ElijahRematchIntro::
	.string "Hej, dlouho jsme se nevideli!\n"
	.string "Zlepsil ses?$"

Route8_Text_AidanRematchIntro::
	.string "Jsi dobry v POKéMONech, ale\n"
	.string "jak ti jde chemie?$"

Route8_Text_StanRematchIntro::
	.string "Vyborne!\n"
	.string "Pojdme na dalsí hru!$"

Route8_Text_GlennRematchIntro::
	.string "K vítezství v boji potrebujes\n"
	.string "strategii.\p"
	.string "Dodrzujes mou radu?$"

Route8_Text_PaigeRematchIntro::
	.string "Nasbírala jsem mnoho NIDORANu.\n"
	.string "Nechci, aby se vyvinuli, ale…$"

Route8_Text_LeslieRematchIntro::
	.string "Skola je zábava, ale POKéMONi\n"
	.string "jsou taky zábava.$"

Route8_Text_AndreaRematchIntro::
	.string "MEOWTH a PERSIAN jsou rozkosní,\n"
	.string "mnau, mnau, mnau!$"

Route8_Text_MeganRematchIntro::
	.string "Mozná tu vypadáme hloupe,\n"
	.string "ale stejne muzu bojovat.$"

Route8_Text_RichRematchIntro::
	.string "Jsem tulák a hrác!\n"
	.string "Mám vítezné tazení!$"

Route8_Text_JuliaRematchIntro::
	.string "Co je rozkosny, kulaty, chlupaty\n"
	.string "POKéMON?\p"
	.string "Uz to vís, ze?$"

Route8_Text_RicardoRematchIntro::
	.string "Mé kolo má porád problém, kámo.$"

Route8_Text_JarenRematchIntro::
	.string "Dobre, mladej!\n"
	.string "Tentokrát zádné slitování!$"

Route8_Text_EliRematchIntro::
	.string "ELI: Nase dvojcata jsme jeste\n"
	.string "vylepsili!$"

Route8_Text_AnneRematchIntro::
	.string "ANNE: Nase dvojcata jsou\n"
	.string "silnejsí!$"

Route9_Text_AliciaRematchIntro::
	.string "Zase se utkáme?\n"
	.string "Tentokrát jsi muj!$"

Route9_Text_ChrisRematchIntro::
	.string "Nezapomnel jsem, ze jsi mel\n"
	.string "ty hezké POKéMONy.$"

Route9_Text_DrewRematchIntro::
	.string "Beru ROCK TUNNEL do LAVENDERu…\p"
	.string "Ale porád me nekdo cestou\n"
	.string "zastavuje…$"

Route9_Text_CaitlinRematchIntro::
	.string "Dnes me nesnízís!\n"
	.string "Hrajeme naostro!$"

Route9_Text_JeremyRematchIntro::
	.string "Bvahaha!\n"
	.string "Skvele! Zase jsem se nudil!$"

Route9_Text_BriceRematchIntro::
	.string "Hahaha!\n"
	.string "Tvrdák jako vzdy!$"

Route9_Text_BrentRematchIntro::
	.string "Vstával jsem brzy, abych\n"
	.string "trénoval své POKéMONy z kukel!$"

Route9_Text_AlanRematchIntro::
	.string "Hahahaha!\n"
	.string "Tentokrát vyhraju!$"

Route9_Text_ConnerRematchIntro::
	.string "Vyhraj, muj super BUG POKéMONe!$"

Route10_Text_MarkRematchIntro::
	.string "Páni, zase jsi tu?\n"
	.string "Jsi taky POKéMANIAK?\l"
	.string "Chces videt mou sbírku?$"

Route10_Text_ClarkRematchIntro::
	.string "Hap-hapci-cha-cha!\n"
	.string "Nemuzu prestat kychat!$"

Route10_Text_HermanRematchIntro::
	.string "Ahoj, mladej!\n"
	.string "Ukázal jsem ti své POKéMONy?$"

Route10_Text_HeidiRematchIntro::
	.string "Zase jsem byla v POKéMON GYMu.\p"
	.string "…Ale prohrála jsem jako obvykle.$"

Route10_Text_TrentRematchIntro::
	.string "Ach!\n"
	.string "Horsky vzduch je vyborny!\l"
	.string "Je tak super, ze nemohu odejít!$"

Route10_Text_CarolRematchIntro::
	.string "Zacíná se mi tocit hlava.\n"
	.string "Chodím prílis dlouho…$"

Route11_Text_HugoRematchIntro::
	.string "Vítezství, prohra, remíza!\n"
	.string "Ted nasi odvetu!$"

Route11_Text_JasperRematchIntro::
	.string "Souteení je nejlepsí drama.\n"
	.string "Nemuzu se nasytit!$"

Route11_Text_EddieRematchIntro::
	.string "Vís to, ze?\n"
	.string "Jdeme na to, ale bez podvodu!$"

Route11_Text_BraxtonRematchIntro::
	.string "Ahoj!\p"
	.string "Pozor!\n"
	.string "Porád pokládám kabely!$"

Route11_Text_DillonRematchIntro::
	.string "Jsem TRÉNÉR uz nejaky cas.\n"
	.string "Myslím, ze muzu vyhrát.$"

Route11_Text_DirkRematchIntro::
	.string "Fvahaha!\n"
	.string "Nikdy jsem neprohrál!\p"
	.string "…A kdyz ano, vsechno\n"
	.string "jsem zapomnel!$"

Route11_Text_DarianRematchIntro::
	.string "Nikdy jsem nevyhrál…\p"
	.string "Snad mi je souzeno zustat\n"
	.string "takto…$"

Route11_Text_YasuRematchIntro::
	.string "Jsem nejlepsí ve tríde.\n"
	.string "Trénuju kazdé ráno a vecer!$"

Route11_Text_BernieRematchIntro::
	.string "Pozor na zivé dráty!$"

Route11_Text_DaveRematchIntro::
	.string "Vychoval jsem své POKéMONy peclive.\n"
	.string "Ted uz by meli byt pripraveni.\l"
	.string "Tentokrát by meli vyhrát.$"

Route12_Text_NedRematchIntro::
	.string "Jo!\n"
	.string "Mám tu zábér!\l"
	.string "T-tohle muze byt skutecné!$"

Route12_Text_ChipRematchIntro::
	.string "Konecne jsi tu.\n"
	.string "Rybarení je hra na cekanou.$"

Route12_Text_JustinRematchIntro::
	.string "Stále nemohu najít MOON STONE…\n"
	.string "Nasel jsi ho?$"

Route12_Text_LucaRematchIntro::
	.string "Elektrina byla mou specializací.\p"
	.string "O POKéMONech v mori\n"
	.string "ale nic nevím.$"

Route12_Text_HankRematchIntro::
	.string "BLÁZEN DO RYB vs. POKéMON KLUK!\n"
	.string "Dalsí kolo, bojuj!$"

Route12_Text_ElliotRematchIntro::
	.string "Miluju rybarení, vázne.\n"
	.string "Chtel bych ale víc práce…\l"
	.string "…Tezko rybarení opustit!$"

Route12_Text_AndrewRematchIntro::
	.string "Co berou?\p"
	.string "To se nedozvís, dokud me\n"
	.string "neporazís!$"

Route12_Text_JesRematchIntro::
	.string "JES: Vyhraju dnes a\n"
	.string "oblíbenou GIU pozádám o ruku.$"

Route12_Text_GiaRematchIntro::
	.string "GIA: Hej, JES…\n"
	.string "Cekala jsem dlouho.\p"
	.string "Kdyz dnes vyhrajeme, vezmu si te!$"

Route13_Text_SebastianRematchIntro::
	.string "Mí ptací POKéMONi si te pamatují!$"

Route13_Text_SusieRematchIntro::
	.string "Chci byt nejlepsí TRÉNÉR,\n"
	.string "dokud jsem mladá!$"

Route13_Text_ValerieRematchIntro::
	.string "Páni!\n"
	.string "Mas víc cool ODZNAKu!$"

Route13_Text_GwenRematchIntro::
	.string "Mí roztomilí POKéMONi se chtejí\n"
	.string "s tebou znovu seznámit.$"

Route13_Text_AlmaRematchIntro::
	.string "Vyhrabala jsem úspory\n"
	.string "a koupila víc CARBOSu.$"

Route13_Text_PerryRematchIntro::
	.string "Tentokrát neprohraju.\n"
	.string "Vítr je v zádech!$"

Route13_Text_LolaRematchIntro::
	.string "Ach, zase jsi tu?\p"
	.string "Jasne, zahraju si s tebou,\n"
	.string "zlato.$"

Route13_Text_SheilaRematchIntro::
	.string "Nemuzes zapomenout, ze jsi se\n"
	.string "mnou bojoval?$"

Route13_Text_JaredRematchIntro::
	.string "Na co cumís?$"

Route13_Text_RobertRematchIntro::
	.string "Vzdy jdu s ptácími POKéMONy.\n"
	.string "Venoval jsem se jim.$"

Route14_Text_CarterRematchIntro::
	.string "Pouzil jsem TM, abych ucil\n"
	.string "dobré útoky své POKéMONy.$"

Route14_Text_MitchRematchIntro::
	.string "Mí ptací POKéMONi by meli byt\n"
	.string "tentokrát pripraveni.$"

Route14_Text_BeckRematchIntro::
	.string "Pouzívás TM na POKéMONech?\n"
	.string "Jen je drzet je k nicemu.$"

Route14_Text_MarlonRematchIntro::
	.string "Naucil jsi svého ptáka FLY?\p"
	.string "Pak s ním muzes vzlétnout\n"
	.string "do oblak! Zkus to.$"

Route14_Text_DonaldRematchIntro::
	.string "Legenda o okrídlenych prízracích…\n"
	.string "Slysel jsi ji, vid?$"

Route14_Text_BennyRematchIntro::
	.string "Nejsem do toho, ale dobre.\n"
	.string "Jdeme!$"

Route14_Text_LukasRematchIntro::
	.string "Hej!\n"
	.string "Pamatuju si te!\p"
	.string "Pojd, pojd.\n"
	.string "Jdeme, jdeme, jdeme!$"

Route14_Text_IsaacRematchIntro::
	.string "Zase tu jsi?\n"
	.string "Drz hubu a bojuj.$"

Route14_Text_GeraldRematchIntro::
	.string "Jezdíme sem kvuli\n"
	.string "sirokym otevrenym prostorum.$"

Route14_Text_MalikRematchIntro::
	.string "POKéMON souboj, ze?\n"
	.string "Cool! Do toho!$"

Route14_Text_KiriRematchIntro::
	.string "KIRI: JAN, dnes vyhrajeme.$"

Route14_Text_JanRematchIntro::
	.string "JAN: KIRI, jdeme na to!\n"
	.string "Tentokrát urcite vyhrajeme!$"

Route15_Text_KindraRematchIntro::
	.string "Budu bojovat s POKéMONy,\n"
	.string "které jsem získala vymenou.$"

Route15_Text_BeckyRematchIntro::
	.string "Vypadás jemne, asi te\n"
	.string "porazím.\p"
	.string "Zkusím to znovu!$"

Route15_Text_EdwinRematchIntro::
	.string "Kdyz piskám, ptací POKéMONi\n"
	.string "se shromazdují.\p"
	.string "Jsou úzasne rozkosní!$"

Route15_Text_ChesterRematchIntro::
	.string "Hm? Mí ptáci se trasou!\n"
	.string "Pockej, ty nejsi ten TRÉNÉR…$"

Route15_Text_GraceRematchIntro::
	.string "Ach, jsi malé rozkosníce!\n"
	.string "Jsi jako rozkosny POKéMON!\l"
	.string "Uz si te pamatuji!$"

Route15_Text_OliviaRematchIntro::
	.string "Chovám POKéMONy pro ochranu,\n"
	.string "protoze ziju sama.\p"
	.string "To se nezmenilo.$"

Route15_Text_ErnestRematchIntro::
	.string "Hej, mladej! Pojd!\n"
	.string "Vzal jsem je od nejakého poseroutky!$"

Route15_Text_AlexRematchIntro::
	.string "Dáj mi vsechny prachy, az\n"
	.string "prohrajes, mladej!$"

Route15_Text_CeliaRematchIntro::
	.string "Co je cool a frcí?\n"
	.string "Vymena POKéMONu, samozrejme.$"

Route15_Text_YazminRematchIntro::
	.string "Chces si zase hrát s mymi\n"
	.string "POKéMONy?$"

Route15_Text_MyaRematchIntro::
	.string "MYA: Ahoj, porád se potkáváme,\n"
	.string "vid?\p"
	.string "Pomuzes mi zase trénovat\n"
	.string "mého mladsího brácu?$"

Route15_Text_RonRematchIntro::
	.string "RON: Má sestra je silnejsí…$"

Route16_Text_LaoRematchIntro::
	.string "Co chces?$"

Route16_Text_KojiRematchIntro::
	.string "Hezké KOLO!\n"
	.string "Predej ho rychle!$"

Route16_Text_LukeRematchIntro::
	.string "Vylez si hrát, mysicko.\n"
	.string "Budu k tobe hodny!$"

Route16_Text_HideoRematchIntro::
	.string "Hej, pockej!\n"
	.string "Nezavolej me a pak nesmes!$"

Route16_Text_CamronRematchIntro::
	.string "Mám hlad a jsem zly!\n"
	.string "Potrebuju pytel na rány!$"

Route16_Text_RubenRematchIntro::
	.string "Ahoj!\n"
	.string "Uzijeme si to!$"

Route16_Text_JedRematchIntro::
	.string "JED: Prisel jsi videt nasi\n"
	.string "lásku bez hranic?$"

Route16_Text_LeaRematchIntro::
	.string "LEA: Obcas intenzita nasí\n"
	.string "lásky me desí.$"

Route17_Text_RaulRematchIntro::
	.string "Rekl jsem, rychlé zbohatnutí\n"
	.string "z detí v souboji nejde.$"

Route17_Text_IsaiahRematchIntro::
	.string "Jsem pysny na svoje telo, mladej.\n"
	.string "Pojd na to!$"

Route17_Text_VirgilRematchIntro::
	.string "Jsi na procházce?$"

Route17_Text_BillyRematchIntro::
	.string "Jsme BIKERI!\n"
	.string "Vládneme cestám, kámo!$"

Route17_Text_NikolasRematchIntro::
	.string "VOLTORB te dnes vázne\n"
	.string "elektrizuje!$"

Route17_Text_ZeekRematchIntro::
	.string "Trénoval jsem POKéMONa, ale\n"
	.string "vubec se nevyvine. Proc?$"

Route17_Text_JamalRematchIntro::
	.string "Aaa! Potrebuji cvicit\n"
	.string "a shodit tuky!$"

Route17_Text_CoreyRematchIntro::
	.string "Bud rebel!$"

Route17_Text_JaxonRematchIntro::
	.string "Jo, hezké KOLO!\n"
	.string "Jak se rídí?$"

Route17_Text_WilliamRematchIntro::
	.string "Ztrat se, mladej!\n"
	.string "Jsem unaveny!$"

Route18_Text_WiltonRematchIntro::
	.string "Hledal jsem v kazdé traviste\n"
	.string "nové POKéMONy.\p"
	.string "Ale není to vzdy lehké…$"

Route18_Text_RamiroRematchIntro::
	.string "Kurukukukuu!\n"
	.string "Zlepsuji se v ptacím volání?$"

Route18_Text_JacobRematchIntro::
	.string "Varoval jsem te, to je muj\n"
	.string "rajón!\p"
	.string "Nechci, abys sem chodil.$"

Route19_Text_RichardRematchIntro::
	.string "Jsem skoro rozcvícen\n"
	.string "na plavání.$"

Route19_Text_ReeceRematchIntro::
	.string "Pockej! Zpomal!\n"
	.string "Co kdyz dostanes infarkt?$"

Route19_Text_MatthewRematchIntro::
	.string "Miluju plavání!\n"
	.string "Asi jsi spís surfar.$"

Route19_Text_DouglasRematchIntro::
	.string "Co je za obzorem?\n"
	.string "Videl jsi?$"

Route19_Text_DavidRematchIntro::
	.string "Zkousel jsem zase potápení\n"
	.string "pro POKéMONy, ale nesel.$"

Route19_Text_TonyRematchIntro::
	.string "Dívám se na more, abych\n"
	.string "zapomnel na spatné veci.\p"
	.string "…Treba poslední prohru s tebou!$"

Route19_Text_AnyaRematchIntro::
	.string "Vzdy jezdís na POKéMONovi…\p"
	.string "Vypadá to relaxacne.\n"
	.string "Muzu ho mít, kdyz vyhraju?$"

Route19_Text_AliceRematchIntro::
	.string "Plavání je úzasné!\n"
	.string "Spáleniny od slunce ne!$"

Route19_Text_AxleRematchIntro::
	.string "Tyhle vody jsou zrádné!\n"
	.string "Nemel by ses sem vracet!$"

Route19_Text_ConnieRematchIntro::
	.string "Plavala jsem s prately…\n"
	.string "Jsem unavená…\l"
	.string "Vázne musíme bojovat?$"

Route19_Text_LiaRematchIntro::
	.string "LIA: Vís, ze muj brácha\n"
	.string "se práve stal TRÉNÉREM?\p"
	.string "Chci, aby se zlepsil, takze\n"
	.string "potrebuju zase pomoc.$"

Route19_Text_LucRematchIntro::
	.string "LUC: Má sestra me naucila\n"
	.string "vse o POKéMONech.\p"
	.string "Jsem lepsí?$"

Route20_Text_BarryRematchIntro::
	.string "Voda je tu melká.\n"
	.string "Spousta lidí tu plave.$"

Route20_Text_ShirleyRematchIntro::
	.string "Závidís, ze trávím dovolenou\n"
	.string "na SEAFOAMu?$"

Route20_Text_TiffanyRematchIntro::
	.string "Miluju plout s rybami\n"
	.string "tady ve vlnách.$"

Route20_Text_IreneRematchIntro::
	.string "Mela jsi taky dovolenou?$"

Route20_Text_DeanRematchIntro::
	.string "Koukni na muj svaly!\p"
	.string "Jsou jeste vyrysovanejsí\n"
	.string "nez dríve!$"

Route20_Text_DarrinRematchIntro::
	.string "Proc jezdís na POKéMONovi?\n"
	.string "Jeste neumís plavat?$"

Route20_Text_RogerRematchIntro::
	.string "Prijel jsem na ptacím POKéMONovi.$"

Route20_Text_NoraRematchIntro::
	.string "Muj prítel mi dal velké perly.\n"
	.string "A jeste vetsí jsou ted!$"

Route20_Text_MissyRematchIntro::
	.string "Plavala jsem sem z CINNABAR ISLANDu.\n"
	.string "Nebylo to lehké, jak jsem ríkala.$"

Route20_Text_MelissaRematchIntro::
	.string "CINNABAR na západe má LABORATOR\n"
	.string "pro POKéMONy.\p"
	.string "Muj táta tam pracuje.$"

Route21_North_Text_RonaldRematchIntro::
	.string "Chces vedet, jestli ryby\n"
	.string "berou?$"

Route21_North_Text_WadeRematchIntro::
	.string "Mám zase velky úlovek!\n"
	.string "Pujdes do toho jeste jednou?$"

Route21_North_Text_SpencerRematchIntro::
	.string "More cistí mé telo a dusi!$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
	.string "きょうも　およぎに\n"
	.string "きちまったぜ$"

Route21_South_Text_JackRematchIntro::
	.string "Chytám POKéMONy v mori.\n"
	.string "A tam je taky trénuju.$"

Route21_South_Text_JeromeRematchIntro::
	.string "Práve jsem v dalsím\n"
	.string "triatlonu!$"

Route21_South_Text_RolandRematchIntro::
	.string "Áááá!\n"
	.string "Cítís slunce a vítr!$"

Route21_South_Text_ClaudeRematchIntro::
	.string "Hej, prestan uz.\n"
	.string "Vzdy vyplasís ryby!$"

Route21_South_Text_NolanRematchIntro::
	.string "Drz mi spolecnost, dokud nezaberou.$"

Route21_North_Text_LilRematchIntro::
	.string "LIL: Hm? Zase souboj?\n"
	.string "IANE, nezvládnes to sám?$"

Route21_North_Text_IanRematchIntro::
	.string "IAN: Má sestra je porád lenoska.\n"
	.string "Pomoz mi ji vyhecovat!$"

Route25_Text_JoeyRematchIntro::
	.string "Tady neprohraju!$"

Route25_Text_DanRematchIntro::
	.string "Táta me vzal na skvelou party\n"
	.string "na S.S. ANNE ve VERMILION CITY.$"

Route25_Text_FlintRematchIntro::
	.string "Jsem cool kluk.\n"
	.string "Mám holku!\p"
	.string "Tentokrát jí ukázu, jak jsem\n"
	.string "cool!$"

Route25_Text_KelseyRematchIntro::
	.string "Ahoj!\n"
	.string "Muj prítel je cool!\l"
	.string "Dnes mám dobrou formu!$"

Route25_Text_ChadRematchIntro::
	.string "Mel jsem ten pocit…\n"
	.string "Vedel jsem, ze musíme zase!$"

Route25_Text_HaleyRematchIntro::
	.string "Má kamarádka má rozkosné POKéMONy.\n"
	.string "Tak ji závidím!$"

Route25_Text_FranklinRematchIntro::
	.string "Práve jsem trénoval na MT. MOON,\n"
	.string "ale jeste mám sílu!$"

Route25_Text_NobRematchIntro::
	.string "POKéMANIAK bydlí na mysu.\n"
	.string "Videl jsi jeho sbírku?$"

Route25_Text_WayneRematchIntro::
	.string "Pujdes zase za BILLem?\n"
	.string "Nejdrív budeme bojovat!$"

Route24_Text_ShaneRematchIntro::
	.string "Videl jsem tvuj cin z trávy!$"

Route24_Text_EthanRematchIntro::
	.string "Dobre!\n"
	.string "Rozdupu te!$"

Route24_Text_ReliRematchIntro::
	.string "Vzdy vypadás zaneprázdnene…\n"
	.string "Nejsi unaveny?$"

Route24_Text_TimmyRematchIntro::
	.string "Asi vázne miluje chodit\n"
	.string "na NUGGET MOST.$"

Route24_Text_AliRematchIntro::
	.string "Kdyz jsme bojovali…\p"
	.string "I kdyz jsem byl druhy v rade,\n"
	.string "byl jsem nejlepsí, ze?$"

Route24_Text_CaleRematchIntro::
	.string "Lidé tomu ríkají NUGGET MOST!\p"
	.string "Uz jsi nás porazil, takze\n"
	.string "uz se nepostavís vyzve…\p"
	.string "…Ale klidne s námi muzes\n"
	.string "bojovat znovu.$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "Lezím a vlny me kolébají…\n"
	.string "Nevsímám si, jak cas plyne…$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "Pocasí je nádherné!\n"
	.string "Zkusím to nezkazit.$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "Mé spáleniny zacínají bolet…$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "Hora ohnivého ptáka vrhá\n"
	.string "obrovsky stín…$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "Mám silny pocit, ze\n"
	.string "tentokrát vyhraju!$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "Pockej! Sekundu!\n"
	.string "Mám velkou rybu na háku!$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "Pomuzes mi zase\n"
	.string "s tréninkem?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "Nevynechali jsme zádny\n"
	.string "den tréninku!$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "Kazdé ráno pred snídaní plavu\n"
	.string "kolem tohoto ostrova…\l"
	.string "Trikrát!$"

OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "Oblec se na souboj!\n"
	.string "Vyhod tu lehkomyslnou montu, rekl!$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "Vsechno chutná lépe, kdyz jsi\n"
	.string "v divocine.$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "Zase jsem se prejedla, takze\n"
	.string "muzes bojovat pro cvik?$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "KIA: Já a brácha jsme\n"
	.string "úzasná kombinace!\p"
	.string "Tentokrát neprohrajeme!$"

OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "MIK: S KIOU se nebojíme\n"
	.string "niceho!\p"
	.string "Tentokrát to dokázeme!$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "Zase máme bojovat?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "Odkud prichází a kam jdes?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "Chci brzy plavat bez\n"
	.string "plovacího kruhu.$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "Jé, jé!\n"
	.string "POKéMON!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "Ach ne, nerekla jsem ti uz?\n"
	.string "Prosím, drz se ode me dál!$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "JOY: Zesílili jsme!\n"
	.string "Hodne!$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "MEG: Dnes nás neporazís!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "Ach, ahoj!\p"
	.string "Vychovávás své POKéMONy\n"
	.string "v dobrém prostredí?$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "Tema rukama vytvorím\n"
	.string "dnesní vítezství.$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "Musím se opakovat?\n"
	.string "Snazím se malovat.\l"
	.string "Ztrat se mi z ocí!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "Nepokrocila jsem…\n"
	.string "Stále nemám správny úhel…$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "Dáte mi dalsí prílezitost\n"
	.string "merit s vámi sily?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "Skoro dokoncili bazén\n"
	.string "pro mé POKéMONy.\p"
	.string "Musíte prijít na návstevu.$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "Jsem dobry bezec.\n"
	.string "Jsem jeste rychlejsí!$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "Hej, kámo!\n"
	.string "Uzijeme si cas spolu!$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "Jsem nejstarsí z PTACÍCH\n"
	.string "BRATRu. Pamatujes me?\p"
	.string "Jsem ten, kdo miluje ptáky\n"
	.string "kvuli jejich zobákum!$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "Jsem prostrední dít PTACÍCH\n"
	.string "BRATRu.\p"
	.string "Já miluji krídla.\n"
	.string "Bojujme znova!$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "Jsem nejmladsí z PTACÍCH\n"
	.string "BRATRu.\p"
	.string "Miluji ptáky kvuli prachovému\n"
	.string "perí. Necekal jsem te!$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "Stále nemám zádné stestí.\n"
	.string "Souboj by byl zmena!$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "Lapám po dechu…\p"
	.string "Zase jsem plaval z prístavu\n"
	.string "SIX ISLAND jedním tahem.$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "Vzdy prijdes, kdyz plavu.$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "AVA: Pojdme na dalsí\n"
	.string "morsky souboj 2 na 2!$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "GEB: Já a má sestra jsme\n"
	.string "mnohem tvrdsí nez dríve!$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "…Hm?\p"
	.string "Predstavím si svuj dum, ale\n"
	.string "TELEPORT me sem vzdy zanese!$"

SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "Ach, ahoj.\n"
	.string "Príjemny vánek zase fouká.$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "Hehehe, zase trénuji\n"
	.string "v tajnosti.$"

SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "Co, uz te unavují PLAVCI\n"
	.string "jako já?\p"
	.string "Nebud takovy!\n"
	.string "Bojuj se mnou znova.$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "Vzdech…\n"
	.string "Muj prítel je zase zanepráznen…$"

SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "Reki, kde jsou hory\n"
	.string "v techto koncinách?$"

SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "MIU: Ahoj, POKéMONe!\n"
	.string "Cas si zase hrát!$"

SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "MIA: Ahoj, POKéMONe!\n"
	.string "Cas zase bojovat!$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "V tomto svete je porád\n"
	.string "mnoho nevyresenych záhad.$"

SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "Nepoznali jsme se uz?\n"
	.string "Co te prinutilo vrátit se?$"

SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "Ríká se, ze na tomto ostrove\n"
	.string "jsou tajemné kameny.\p"
	.string "Objevil jsi neco od\n"
	.string "naseho posledního setkání?$"

SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "Odveta s tebou tak vysoko!$"

SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "Známé zdejsí krajiny.$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "Cítil jsem tvuj príchod.$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "Nekde na tomto ostrove spí\n"
	.string "podivní POKéMONi.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "Kjahaha!\p"
	.string "Návrat nic nezmení.\n"
	.string "Odfoukni te bez námahy!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "Hej! Jsi clen mého\n"
	.string "fanklubu, ze?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "Tento ostrov je moc rozlehly…\n"
	.string "Hlídání je otrava…$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "Neodpoustím lidem, co tyrají\n"
	.string "POKéMONy!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "EVE: Spojím se s JONEM\n"
	.string "a budeme zase bojovat.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "JON: Kdyz jsem s EVE, mám pocit,\n"
	.string "ze nikdy nemuzeme prohrát.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "Pojdme na dalsí souboj.\n"
	.string "Mám vrcholnou formu!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "Nezálezí na tom, jestli máte\n"
	.string "nejsilnejsí POKéMONy…\p"
	.string "Nic to neznamená, kdyz neumís\n"
	.string "je správne pouzít!$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "Pracuji na ochrane prostredí.\n"
	.string "Príroda zase chrání me!$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "Vzdy, kdyz se setkáme, mas\n"
	.string "ty cool boty.$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "Asi jsi zesílel.\n"
	.string "Bojuj se mnou, prosím!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "Dostala jsem nejlepsí vzdelání,\n"
	.string "abych byla takhle silná.\p"
	.string "Tentokrát neprohraju.\n"
	.string "Vubec ne!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "LEX: Má drahá NYA, spolu\n"
	.string "urcite vyhrajeme!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "NYA: Nezklamu mého mentora\n"
	.string "LEXE! Vyhrajeme!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "Objevil jsi neco o\n"
	.string "této kamenné komore?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "Ríká se, ze tu spí\n"
	.string "tajemny POKéMON.$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "Muj ucitel mi ukazuje\n"
	.string "víc malovat.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "Dnes jsme se prisli mimo\n"
	.string "vyuku zase podívat na komoru.$"
