Text_FirstShouldRestoreMonsHealth::
	.string "Nejprve bys mel obnovit\n"
	.string "POKéMONum plné zdraví.$"

Text_MonsHealedShouldBuyPotions::
	.string "Tví POKéMONi byli vyléceni\n"
	.string "do plného zdraví.\p"
	.string "Pokud bude POKéMONova energie,\n"
	.string "HP, nízká, prijï k nám.\p"
	.string "Pokud plánujes jít daleko,\n"
	.string "kup si pár LEKTVARu v\l"
	.string "POKéMON MARTu.\p"
	.string "Hodne stestí!$"

Text_MonsHealed::
	.string "Tví POKéMONi byli vyléceni\n"
	.string "do plného zdraví.\p"
	.string "Hodne stestí!$"

Text_HadQuiteAnExperienceTakeRest::
	.string "MAMA: {PLAYER}!\n"
	.string "Vítej doma.\p"
	.string "Zdá se, ze sis hodne\n"
	.string "zazil.\p"
	.string "Mozná by sis mel chvíli\n"
	.string "odpocinout.$"

Text_MomExplainHPGetPotions::
	.string "MAMA: Ach, vyborne! Ty a tví\n"
	.string "POKéMONi vypadáte skvele.\p"
	.string "Práve jsem mluvila s PROF. OAKEM.\p"
	.string "Ríkal, ze POKéMONova energie\n"
	.string "se merí v HP.\p"
	.string "Pokud POKéMONi ztratí HP,\n"
	.string "muzes je obnovit v kazdém\l"
	.string "POKéMON CENTRU.\p"
	.string "Kdyz pojedes daleko, chytry\n"
	.string "trénér si nakoupí zásobu\l"
	.string "LEKTVARu v POKéMON MARTu.\p"
	.string "Udelej mi radost, zlato!\p"
	.string "Opatruj se!$"

Text_WhitedOutLostMoney::
	.string "{PLAYER}ovi dosli pouzitelní\n"
	.string "POKéMONi!\p"
	.string "{PLAYER} ztratil ¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} omdlel!$"

Text_WhitedOut::
	.string "{PLAYER}ovi dosli pouzitelní\n"
	.string "POKéMONi!\p"
	.string "{PLAYER} omdlel!$"
