PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
    .string "Jeden podivny dedek me ukecal,\n"
    .string "abych si koupil tuhle rybu!\p"
    .string "Je totálne slabá a stála ¥500!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
    .string "Pokud chovás POKéMONy peclive,\n"
    .string "mohou nastat dobré veci.\p"
    .string "I ti slabí te mohou prekvapit,\n"
    .string "kdyz to s nimi nevzdás.$"

