PokemonTower_2F_Text_RivalIntro::
    .string "{RIVAL}: Hej, {PLAYER}!\n"
    .string "Co te sem privádí?\l"
    .string "Je ti POKéMON mrtvy?\p"
    .string "Hele! Je naziv!\p"
    .string "Aspon jim muzu zpusobit mdloby!\n"
    .string "Jdeme na to!$"

PokemonTower_2F_Text_RivalDefeat::
    .string "Coze?\n"
    .string "Ty smrade!\p"
    .string "Ja se s tebou jeste setrkal!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "{RIVAL}: Ach jo!\n"
    .string "Opravdu natáhli bacv kory!\l"
    .string "Slabosi!\l"
    .string "Vychovavej je poradne, prosim$"

PokemonTower_2F_Text_RivalPostBattle::
    .string "Jak ti jde POKéDEX?\n"
    .string "Práve jsem chytil CUBONEa!\p"
    .string "Nemuzu najít vetsího MAROWAKa.\n"
    .string "Kde asi jsou?\p"
    .string "Vsadím se, ze zádny nezbyl!\p"
    .string "No, radsi uz pujdu.\n"
    .string "Mám hodne práce,\l"
    .string "narozdíl od tebe.\p"
    .string "Cau ahoj!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "Ani my jsme nemohli identifikovat\n"
    .string "ty bloudivé duchy.\p"
    .string "SILPH SCOPE by je mohl\n"
    .string "odmaskovat.$"

