Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
    .string "Jedu si v klidu na novém kole\n"
    .string "s priteljkynou.$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
    .string "Jedeme spolu na novych kolech.$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
    .string "Podíváme se, co ukazují\n"
    .string "dalekohledy…\p"
    .string "Je to CELADON DEPT. STORE!$"

Route16_NorthEntrance_2F_Text_LongPathOverWater::
    .string "Podíváme se, co ukazují\n"
    .string "dalekohledy…\p"
    .string "V dálce je dlouhá cesta\n"
    .string "pres vodu.$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40::
    .string "Ahoj! Pamatujes si me?\n"
    .string "Jsem jeden z ASISTENTU PROF. OAKa.\p"
    .string "Pokud má tvuj POKéDEX kompletní\n"
    .string "data o 40 druzích, mám ti\l"
    .string "dát odmenu.\p"
    .string "PROF. OAK mi sveril AMULET COIN\n"
    .string "pro tebe.\p"
    .string "Tak, {PLAYER}, zeptám se te.\p"
    .string "Mas data alespon o 40 druzích\n"
    .string "POKéMONu?$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
    .string "Skvele! Chytils nebo vlastnils\n"
    .string "{STR_VAR_3} druhu POKéMONu!\p"
    .string "Gratuluji!\n"
    .string "Tady mas!$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide::
    .string "{PLAYER} dostal AMULET COIN\n"
    .string "od ASISTENTA.$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin::
    .string "AMULET COIN je predmet, ktery\n"
    .string "drzí POKéMON.\p"
    .string "Pokud se POKéMON úcastní vítezného\n"
    .string "souboje, vydelas více penez.$"

