@ Unused
FiveIsland_Meadow_Text_DoorNeedsTwoPasswords::
    .string "とびらを　あけるには\n"
    .string "パスワードが　2つ　いるようだ$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded::
    .string "{PLAYER} zadal heslo.\p"
    .string "“GOLDEEN need log.”\p"
    .string "… …  … …  … …\p"
    .string "K otevrení dverí je potreba\n"
    .string "jeste dalsí heslo…$"

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened::
    .string "{PLAYER} zadal dve hesla.\p"
    .string "“GOLDEEN need log.”\n"
    .string "“Yes, nah, CHANSEY.”\p"
    .string "… …  … …  … …\p"
    .string "Dvere SKLADU se otevrely!$"

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen::
    .string "Dvere SKLADU jsou jiz\n"
    .string "otevrené.$"

FiveIsland_Meadow_Text_Rocket1Intro::
    .string "Sem nikdo nesmí!\n"
    .string "Ven, ven!$"

FiveIsland_Meadow_Text_Rocket1Defeat::
    .string "To má byt vázne?$"

FiveIsland_Meadow_Text_Rocket1PostBattle::
    .string "Tady nemás co delat!\n"
    .string "Jdi domu!$"

FiveIsland_Meadow_Text_Rocket2Intro::
    .string "Za tímhle místem uz není nic,\n"
    .string "krome naseho SKLADU.\p"
    .string "Tak co te sem vede?$"

FiveIsland_Meadow_Text_Rocket2Defeat::
    .string "To se nemelo stát…$"

FiveIsland_Meadow_Text_Rocket2PostBattle::
    .string "Chces vedet, co je uvnitr\n"
    .string "tohohle SKLADU?\p"
    .string "Bude lepsí, kdyz to nebudes\n"
    .string "vedet. Pro tvé dobro.$"

FiveIsland_Meadow_Text_Rocket3Intro::
    .string "Ztrácel bys cas, i kdyby ses\n"
    .string "kolem me dostal.$"

FiveIsland_Meadow_Text_Rocket3Defeat::
    .string "Ach, to me strasne stve!$"

FiveIsland_Meadow_Text_Rocket3PostBattle::
    .string "Bez hesel se stejne dovnitr\n"
    .string "nedostanes.$"

