ThreeIsland_BondBridge_Text_NikkiIntro::
    .string "Slaná vune more…\n"
    .string "Lechtá mé srdce.$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
    .string "…Cuc, cuc…\n"
    .string "Neco je tu cítit nepríjemne…$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
    .string "Mozná je ten pach pot tvého\n"
    .string "POKéMONa…$"

ThreeIsland_BondBridge_Text_VioletIntro::
    .string "Kam tak spechás?$"

ThreeIsland_BondBridge_Text_VioletDefeat::
    .string "Vychovávás úzasné\n"
    .string "POKéMONy.$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
    .string "Kdyz pujdes touto cestou,\n"
    .string "nakonec dosáhnes BERRY FOREST.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
    .string "Mamka rekla, ze nemuzu plavat\n"
    .string "bez plavacího kruhu.$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
    .string "Waaah!\n"
    .string "Waaah!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
    .string "Letos se konecne naucím\n"
    .string "plavat!$"

ThreeIsland_BondBridge_Text_AlexisIntro::
    .string "Hura, hura!\n"
    .string "POKéMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
    .string "Co bude ted?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
    .string "Vyhrál jsem?\n"
    .string "Nebo prohrál?$"

ThreeIsland_BondBridge_Text_TishaIntro::
    .string "Ach ne, nechod sem!\n"
    .string "Prosím, drz se ode me!$"

ThreeIsland_BondBridge_Text_TishaDefeat::
    .string "Dobre, vyhráls!\n"
    .string "Ted prosím odejdi.$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
    .string "POKéMON mi prokousl plavky.\p"
    .string "Nemuzu vylézt z vody!$"

ThreeIsland_BondBridge_Text_JoyIntro::
    .string "JOY: Ukázeme ti, kdo je nás\n"
    .string "oblíbeny POKéMON!$"

ThreeIsland_BondBridge_Text_JoyDefeat::
    .string "JOY: Och…\n"
    .string "MEG!$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
    .string "JOY: Nebylo to zábavné?\n"
    .string "Doufám, ze si zabojujeme zase!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
    .string "JOY: Opravdu chci bojovat\n"
    .string "s MEG.\p"
    .string "Jeden POKéMON nestací.$"

ThreeIsland_BondBridge_Text_MegIntro::
    .string "MEG: Ukázeme ti naseho\n"
    .string "oblíbeného POKéMONa.$"

ThreeIsland_BondBridge_Text_MegDefeat::
    .string "MEG: Och…\n"
    .string "JOY!$"

ThreeIsland_BondBridge_Text_MegPostBattle::
    .string "MEG: JOY, nebylo to zábavné?$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
    .string "MEG: Chci bojovat spolu s JOY.\p"
    .string "Jeden POKéMON nestací.$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
    .string "BERRY FOREST PRED VÁMI$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
    .string "BOND BRIDGE\n"
    .string "Pri prechodu prosím bud tise.\p"
    .string "BERRY FOREST PRED VÁMI$"

