FourIsland_Text_IslandSign::
    .string "FOUR ISLAND\n"
    .string "Teply, modry, ledovy ostrov$"

FourIsland_Text_LoreleiHasReturned::
    .string "LORELEI se vrátila.\p"
    .string "Mozná pro ni byl mestsky\n"
    .string "zivot prílis stresující?$"

FourIsland_Text_LoreleiMetLaprasAsChild::
    .string "LORELEI se vrátila domu.\p"
    .string "LAPRAS, kterou má, predstavuji\n"
    .string "si jako tu z detství.\p"
    .string "Myslím, ze ji chytila v\n"
    .string "ICEFALL CAVE.\p"
    .string "Mozná je s ní ten POKéMON\n"
    .string "uz od té doby.$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa::
    .string "{RIVAL}: Hej!\n"
    .string "{PLAYER}!\p"
    .string "Co tady delás\n"
    .string "v SEVII ISLANDS?\p"
    .string "Mel bys mne prestat napodobovat,\n"
    .string "vís?\p"
    .string "Kazdopádne uz mám své VEJCE\n"
    .string "POKéMONa, s ostrovem koncím.\p"
    .string "Heh, vsadím se, ze ani nevís\n"
    .string "o POKéMON VEJCÍCH.\p"
    .string "Takhle si nikdy nenaplnís\n"
    .string "NÁRODNÍ POKéDEX.\p"
    .string "Mimochodem, videl jsem na\n"
    .string "ostrove nekoho, koho oba známe.\p"
    .string "Mrkni se kolem, jestli te to\n"
    .string "zajímá.\p"
    .string "Já nemám cas plytvat.\p"
    .string "Tak cau!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls::
    .string "Ach, nasels me!\n"
    .string "Prosím, nerekni to LORELEI.\p"
    .string "Vís, ze LORELEI má spoustu\n"
    .string "plysovych panenek?\p"
    .string "Pokazdé, kdyz se vrátí na FOUR\n"
    .string "ISLAND, sbírka roste!$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
    .string "Brr, chladno!\p"
    .string "Udelal jsem ledovou trístenku\n"
    .string "z ledu z ICEFALL CAVE.\p"
    .string "Je studená a chutná!$"

FourIsland_Text_LoreleisHouse::
    .string "LORELEIN DUM$"

