Route5_SouthEntrance_Text_ThirstyOnGuardDuty::
    .string "Mám hlídku.\n"
    .string "Páni, ale mám zízen!\p"
    .string "Aha, pockej, cesta je zavrená.$"

Route5_SouthEntrance_Text_ThatTeaLooksTasty::
    .string "Ach, ten CAJ…\n"
    .string "Vypadá strasne lákave…$"

Route5_SouthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "He? Mohu si dát to pití?\n"
    .string "Páni, díky!\l"
    .string "… …\l"
    .string "Glo, glo…\l"
    .string "… …\l"
    .string "Hltám…\l"
    .string "Jestli chces do SAFFRON\l"
    .string "CITY…\l"
    .string "… …\l"
    .string "Muzes projít.\p"
    .string "Podelím se o CAJ s ostatními\n"
    .string "hlídaci!$"

Route5_SouthEntrance_Text_HiHowsItGoing::
    .string "Ahoj, jak se vede?$"

