CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
    .string "POKé FLUTE probudí spící\n"
    .string "POKéMONy. To prece vís.\p"
    .string "Deje se to zvukem, ktery\n"
    .string "slysí jen oni.$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
    .string "Prijel jsem sem z FUCHSIA.\p"
    .string "Po CYCLING ROAD to bylo\n"
    .string "samé do kopce, jsem vycerpany.$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
    .string "Kdybych mel BIKE, vyrazil bych\n"
    .string "na CYCLING ROAD!$"
