OneIsland_TreasureBeach_Text_AmaraIntro::
    .string "Lezet a houpat se na vlnách…\n"
    .string "Je to vyborné.$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
    .string "Prohrála jsem…\n"
    .string "Je to hrozné.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
    .string "More je v techto místech\n"
    .string "príjemne teplé.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
    .string "Morsky proud vyplavuje dobré\n"
    .string "veci na tuto plázi.\p"
    .string "Proto sem chodím casto sbírat\n"
    .string "veci na brehu.$"

