OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio::
    .string "BILL: Hej, ty tam!\n"
    .string "CELIO!$"

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut::
    .string "CELIO: BILLE!\n"
    .string "Nemuzu uverit, ze jsi prijel.$"

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing::
    .string "BILL: No, jiste!\n"
    .string "Jak ti jde tvuj vyzkum?\p"
    .string "…Ach, pockej chvilku.$"

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio::
    .string "{PLAYER}, toto je muj kámos CELIO.\n"
    .string "Je to oddany PC MANIAK!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp::
    .string "CELIO, toto je {PLAYER}, vychá-\n"
    .string "zející hvezda POKéMON SAMPIÓNU!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp::
    .string "CELIO, toto je {PLAYER},\n"
    .string "vládnoucí POKéMON SAMPIÓN!$"

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive::
    .string "CELIO: To je opravdu úzasné.\p"
    .string "Nerad to ríkám, ale nemám\n"
    .string "vlohy pro souboje.\p"
    .string "Kazdopádne me tesí.$"

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed::
    .string "BILL: Tak me uved do obrazu.\n"
    .string "Jak ti bezí stroj?$"

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours::
    .string "CELIO: Bezí dobre, ale jsme\n"
    .string "tu prílis vzdáleni.\p"
    .string "PC na tomto ostrove se zkrátka\n"
    .string "nedají spojit s tvym, BILLE.$"

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou::
    .string "BILL: Ach jo?\n"
    .string "Tak se na to mrknu.\p"
    .string "…Vydrz chvilku…\n"
    .string "Myslím, ze to muzeme zprovoznit.\l"
    .string "Dovol mi ti pomoci, ano?$"

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer::
    .string "{PLAYER}, mohu te poprosit,\n"
    .string "abys na chvilku pockal?\p"
    .string "…Vlastne, mohu te poprosit\n"
    .string "o laskavost?\p"
    .string "Vedlejsí ostrov se jmenuje\n"
    .string "TWO ISLAND.\p"
    .string "Je tam clovek, ktery provozuje\n"
    .string "GAME CORNER.\p"
    .string "Má rád vzácné kameny\n"
    .string "a drahokamy.\p"
    .string "Jsme v kontaktu, oba jsme\n"
    .string "maniaci.\p"
    .string "Mohl bys mu dorucit\n"
    .string "tento METEORIT?$"

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill::
    .string "{PLAYER} prijal METEORIT\n"
    .string "od BILLA.$"

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis::
    .string "CELIO: {PLAYER}, pokud jdes\n"
    .string "na TWO ISLAND, vezmi si toto.$"

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands::
    .string "Je to PRUKAZ na trajekt\n"
    .string "obsluhující místní ostrovy.\p"
    .string "Umozní ti cestovat mezi\n"
    .string "ostrovy ONE, TWO a THREE.\p"
    .string "A jeste toto by sis mel vzít.$"

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap::
    .string "{PLAYER} obdrzel dalsí stránku\n"
    .string "pro MAPU MESTA!$"

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap::
    .string "{PLAYER} obdrzel\n"
    .string "MAPU MESTA!$"

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater::
    .string "BILL: Uvidíme se pozdeji!\n"
    .string "Pozdravuj ho ode me!$"

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis::
    .string "Hmm…\p"
    .string "Co kdybychom to zkusili takto…$"

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore::
    .string "Ach, ahoj, {PLAYER}!\p"
    .string "Videls to?\n"
    .string "Spustili jsme PC!\p"
    .string "Mám tu pár vecí na ukázku\n"
    .string "CELIOVI.\p"
    .string "Muzes se jeste chvíli projít\n"
    .string "nebo neco?$"

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost::
    .string "Omlouvám se, ze zabírám tolik\n"
    .string "BILLOVA casu.\p"
    .string "Také me mrzí, ze jsem tak\n"
    .string "spatny hostitel pri tvé návsteve.$"

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable::
    .string "Bezné PC sluzby nejsou\n"
    .string "k dispozici…$"

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer::
    .string "BILL: Ach, ahoj!\n"
    .string "{PLAYER}!$"

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone::
    .string "BILL: Co te zdrzelo tak dlouho?\n"
    .string "Mels se dobre?\p"
    .string "Zvládli jsme to.\n"
    .string "PC bezí a fungují!$"

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick::
    .string "CELIO: Práce probehla neuveritelne\n"
    .string "rychle.\p"
    .string "BILL je úzasny chlapík…$"

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot::
    .string "BILL: Ne, ne! Skoro nezbylo\n"
    .string "nic, co bych musel udelat.\p"
    .string "CELIO, musím ti to priznat.\n"
    .string "Hodne ses naucil.$"

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe::
    .string "CELIO: Vázne?\n"
    .string "Ehehe…$"

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto::
    .string "BILL: Tak, a je to.\n"
    .string "S prací jsem hotov.\l"
    .string "Meli bychom se vrátit do KANTA.\p"
    .string "CELIO, jeste se uvidíme.$"

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime::
    .string "CELIO: {PLAYER}, opravdu me mrzí,\n"
    .string "ze jsme te dnes poslali samotného.\p"
    .string "Slibuji ti, nekdy ti tyhle\n"
    .string "ostrovy ukázu.$"

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine::
    .string "CELIO: Ahoj!\n"
    .string "Vypadás jako vzdy zaneprázdneny.\p"
    .string "Jak se mi darí?\p"
    .string "No, upravuji svuj Sítovy\n"
    .string "Stroj.\p"
    .string "Az se strojem skoncím,\n"
    .string "doufám, ze ho pouzijes první,\l"
    .string "{PLAYER}.$"

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful::
    .string "CELIO: {PLAYER}, jak se ti vede?\p"
    .string "Ach, opravdu?\n"
    .string "Chytils dalsí POKéMONy.\p"
    .string "Vís co?\n"
    .string "Mozná ti budu uzitecny.$"

OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway::
    .string "Práve upravuji Sítovy Stroj.\p"
    .string "Menim ho tak, aby zvládl\n"
    .string "vymeny na velké vzdálenosti.\p"
    .string "Az to dokoncím, budes\n"
    .string "vymenovat exotické POKéMONy\l"
    .string "s TRÉNÉRy ze vzdálenych míst.$"

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone::
    .string "Ale je tu mensí hácek.\p"
    .string "Aby spojení fungovalo, Stroj\n"
    .string "potrebuje zvlástní drahokam.\p"
    .string "Má byt na ONE ISLAND,\n"
    .string "ale jeste jsem zádny nenasel.\p"
    .string "Kdo ví, kde by mohl byt.$"

OneIsland_PokemonCenter_1F_Text_TryingToFindGem::
    .string "Snazil jsem se najít drahokam,\n"
    .string "i kdyz jsem studoval.\p"
    .string "Vysledkem je, ze jsem neudelal\n"
    .string "pokrok v hledání ani studiu…\p"
    .string "Kdybych se spolehl na BILLA,\n"
    .string "jiste by muj vyzkum pokrocil.\p"
    .string "Ale tentokrát chci zkusit\n"
    .string "delat veci sám.$"

OneIsland_PokemonCenter_1F_Text_OhThats::
    .string "Ach!\n"
    .string "T-to je…$"

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio::
    .string "{PLAYER} predal RUBÍN\n"
    .string "CELIOVI.$"

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor::
    .string "Dekuji ti!\n"
    .string "{PLAYER}, jsi prosté úzasny.\p"
    .string "… … …  … … …\p"
    .string "Hm… Mohu te poprosit o jeste\n"
    .string "jednu velikou laskavost?$"

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp::
    .string "Ne… není to nic divného.\n"
    .string "Prosím, potrebuji tvou pomoc.$"

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands::
    .string "Pri studiu drahokamu jsem\n"
    .string "objevil neco duleziteho.\p"
    .string "Existuje dalsí drahokam, ktery\n"
    .string "tvorí pár s tímto RUBÍNEM.\p"
    .string "Ten druhy drahokam má byt\n"
    .string "na ostrovech SEVII.\p"
    .string "{PLAYER}, prosím, potrebuji,\n"
    .string "abys nasel ten druhy.\p"
    .string "{PLAYER}, mohu si vzít tvuj\n"
    .string "lodní PRUKAZ a MAPU MESTA?$"

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass::
    .string "{PLAYER} vrátil TRI-PASS a\n"
    .string "obdrzel DUHOVY PRUKAZ.$"

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage::
    .string "Získal dalsí stránku\n"
    .string "MAPY MESTA!$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands::
    .string "Tohle je muj vlastní lodní PRUKAZ.\p"
    .string "Umozní ti se dostat na vsechny\n"
    .string "ostrovy SEVII.\p"
    .string "{PLAYER}, prosím, bez tvé\n"
    .string "pomoci to nezvládnu.$"

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio::
    .string "{PLAYER} predal SAFÍR\n"
    .string "CELIOVI.$"

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime::
    .string "CELIO: Tak tohle je drahokam,\n"
    .string "ktery tvorí pár s RUBÍNEM…\p"
    .string "{PLAYER}, hodne sis vytrpel,\n"
    .string "abys to získal, vid?\p"
    .string "Nemusís mi to ríkat. Vím,\n"
    .string "ze to nebylo lehké.\p"
    .string "Mockrát ti dekuji!\p"
    .string "Ted je rada na me pracovat pro\n"
    .string "tebe! Dej mi chvilku.$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood::
    .string "Dobre, je to v pohode…$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette::
    .string "Dokázal jsem to!\n"
    .string "Spojil jsem se s LANETTE!$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou::
    .string "{PLAYER}…\n"
    .string "{PLAYER}, dokázal jsem to!\p"
    .string "Podarilo se mi spojit s\n"
    .string "TRÉNÉRy z regionu HOENN!\p"
    .string "Konecne je Sítovy Stroj\n"
    .string "plne funkcní!\p"
    .string "{PLAYER}, vse vdecím tobe!\p"
    .string "Díky tobe se muj sen splnil…$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck::
    .string "Já…\n"
    .string "Já neplácu.\p"
    .string "Dost uz o me!\p"
    .string "{PLAYER}, budes dál hledat\n"
    .string "exotické POKéMONy, vid?\p"
    .string "Preji ti hodne stestí!$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou::
    .string "CELIO: Ahoj!\p"
    .string "{PLAYER}, slysím o tobe\n"
    .string "ruzné fámy.$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra::
    .string "{PLAYER}, jaky je tvuj oblíbeny\n"
    .string "druh POKéMONu?\p"
    .string "BILL je POKéMANIAK, takze\n"
    .string "miluje kazdy druh.\p"
    .string "Jeho prvním úlovkem prys\n"
    .string "byla ABRA.$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod::
    .string "Mimochodem, {PLAYER}, ty jsi\n"
    .string "z PALLET TOWNU, vid?\p"
    .string "Slysel jsem, ze je to tiché\n"
    .string "a príjemné místo.\p"
    .string "BILLOVO rodné mesto je\n"
    .string "GOLDENROD CITY, kde stále zije\l"
    .string "jeho rodina.\p"
    .string "Slysel jsem, ze je to docela\n"
    .string "veselé, rusné mesto.\p"
    .string "Rád bych tam jednou jel.$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk::
    .string "{PLAYER}, je neco, co\n"
    .string "nemuzes vystát?\p"
    .string "BILL prys vubec nesnese\n"
    .string "mléko.$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt::
    .string "Aha, ty jsi zde cizinec!\n"
    .string "Ahoj! Odkud jsi prisel?\p"
    .string "…PALLET TOWN?\n"
    .string "Neznám to!$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland::
    .string "Na tomto ostrove je obrovská\n"
    .string "sopka.\p"
    .string "Uz dávno nevybuchla, tak proc\n"
    .string "si neudelat vylet?$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend::
    .string "Prála bych si vymenovat POKéMONy\n"
    .string "s pritelem, ktery zije daleko…$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend::
    .string "Vymenila jsem si POKéMONy se\n"
    .string "svym pritelem daleko!\p"
    .string "Vsichni ríkají, ze za to\n"
    .string "vdecíme tobe a CELIOVI.\p"
    .string "Takze ti dekuji!$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
    .string "Sítovy Stroj\n"
    .string "Úroven spojení 0\p"
    .string "…Systém ukládání POKéMONu\n"
    .string "se nastavuje…$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto::
    .string "Sítovy Stroj\n"
    .string "Úroven spojení 1\p"
    .string "Spojení navázáno s regionem\n"
    .string "KANTO.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn::
    .string "Sítovy Stroj\n"
    .string "Úroven spojení 2\p"
    .string "Spojení navázáno s regiony\n"
    .string "KANTO a HOENN.$"

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass::
    .string "Získal TRI-PASS!$"

