CinnabarIsland_Text_DoorIsLocked::
    .string "Dvere jsou zamcené…$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "BLAINE z CINNABAR GYMu je dost\n"
    .string "podivínsky chlapík.\p"
    .string "Zije na ostrove uz dlouho pred tím,\n"
    .string "nez tu postavili LAB.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "Vedci provádejí pokusy\n"
    .string "ve vyhorelé budove.\p"
    .string "Víte, v té, které ríkají\n"
    .string "POKéMON SÍDLO.$"

CinnabarIsland_Text_IslandSign::
    .string "CINNABAR ISLAND\n"
    .string "Ohnivé mesto planoucích tuzeb$"

CinnabarIsland_Text_PokemonLab::
    .string "POKéMON LAB$"

CinnabarIsland_Text_GymSign::
    .string "CINNABAR ISLAND POKéMON GYM\n"
    .string "VÚDCE: BLAINE\l"
    .string "Hádankársky mistr s ohnivou hlavou!$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "He?\n"
    .string "Hej, to je prece {PLAYER}!$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .string "Podívej, to jsem já, BILL.\n"
    .string "Dlouho jsme se nevideli!\p"
    .string "Doufám, ze stále pouzívás\n"
    .string "muj PC systém.\p"
    .string "Hele, kdyz uz jsme se tu potkali,\n"
    .string "co kdybys strávil cas se mnou?\p"
    .string "Je tu jeden ostruvek na jihu,\n"
    .string "ríká se mu ONE ISLAND.\p"
    .string "Kamarád me tam pozval, takze\n"
    .string "se tam práve chystám.\p"
    .string "Co ty na to?\n"
    .string "Mas chut jet se mnou?$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "Dobre, tak jdeme!\n"
    .string "Vyrazíme!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "Co, mas moc práce?\p"
    .string "Tak dobre.\n"
    .string "Lod stejne jeste neprijela.\p"
    .string "Budu cekat v POKéMON\n"
    .string "CENTRU támhle.\p"
    .string "Prijd za mnou, az tu skoncís\n"
    .string "se svymi vecmi.$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "Vypadá to, ze i lod mého\n"
    .string "kámose dorazila.\p"
    .string "Poslal ji sem na CINNABAR\n"
    .string "speciálne pro mé.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "Hej, byla to dlouhá plavba, ze?\p"
    .string "Mému kámosovi CELIOVI se\n"
    .string "tvá spolecnost líbila.\p"
    .string "Urcite te uvítá, kdybys\n"
    .string "ho prisel zase navstívit.\p"
    .string "Pokud mas TRI-PASS, muzes\n"
    .string "vzdy plout trajektem\l"
    .string "z VERMILION PORTU.\p"
    .string "Tak diky za spolecnost!$"

