PewterCity_House1_Text_Nidoran::
    .string "NIDORAN♂: Bowbow!$"

PewterCity_House1_Text_NidoranSit::
    .string "NIDORANE, sedni!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "Nás POKéMON je cizinec, je tedy\n"
    .string "vrtosivy a tezko zvladnutelny.\p"
    .string "Cizinec je POKéMON, kterého\n"
    .string "získás vymenou.\p"
    .string "Roste rychle, ale muze v boji\n"
    .string "nezkuseného TRÉNÉRA ignorovat.\p"
    .string "Kdybychom tak meli odznaky…$"

