Text_UltimateMoveThatMon::
    .string "Zdokonalil jsem konecny útok\n"
    .string "svého typu…\p"
    .string "Ale nikdo si ho nevezme\n"
    .string "pro budoucí pouzití?\p"
    .string "…Hm? Hmmm!\p"
    .string "T-ty…\n"
    .string "T-tento {STR_VAR_1}…$"

Text_JustMistaken::
    .string "…Ne…\n"
    .string "Jen jsem se zmylil.$"

Text_AllowMeToTeachMonUltimateMove::
    .string "Ach! Tohle je on!\n"
    .string "Toto je ten POKéMON!\p"
    .string "Tento {STR_VAR_1} si zaslouzí\n"
    .string "naucit muj konecny útok!\p"
    .string "Dovolís to?\p"
    .string "Dovolís svému {STR_VAR_1}\n"
    .string "naucit se muj {STR_VAR_2}?$"

Text_YouRejectIt::
    .string "Gaah! Odmítás to?\n"
    .string "Ne, nedám se odradit!$"

Text_LetMeConferUltimateMove::
    .string "Dovolís to?\p"
    .string "Pak dovol, abych predal svuj\n"
    .string "konecny {STR_VAR_2} tvému {STR_VAR_1}.\p"
    .string "Ggggrah-awooo!$"

Text_TaughtMove::
    .string "Lapám, lapám, lapám…\p"
    .string "Nemyslel jsem, ze ten útok\n"
    .string "naucím, dokud jsem zivy…$"

Text_MakeBestUseOfMove::
    .string "Naléhám na tebe, abys vyuzil\n"
    .string "ten útok a získal sílu!$"

Text_PassedOnEverythingIKnow::
    .string "Lapám, lapám, lapám…\p"
    .string "Uz nemám lítost.\n"
    .string "Predal jsem vse, co znám.\p"
    .string "Ted muzu prozít svuj zivot\n"
    .string "s vedomím, ze má práce skoncila.$"

Text_FeelRejuvenated::
    .string "Po tom, co jsem ti predal\n"
    .string "své znalosti, cítím takovou úlevu.\p"
    .string "Cítím se omlazen,\n"
    .string "jako bych byl mladsí!$"
