PokemonTower_7F_Text_Grunt1Intro::
    .string "Co chces?\n"
    .string "Proc jsi tady?$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "Vzdávám se!$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "Tohle ti nezapomenu!$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "Ten dedek si nakrácel\n"
    .string "rovnou k nasemu HIDEOUT.\p"
    .string "A pak zacne recnit, jak\n"
    .string "TEAM ROCKET tyrá POKéMONy.\p"
    .string "Tak si to vyrikáváme jako\n"
    .string "dospelí.$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "Prosím!\n"
    .string "Uz dost!$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "POKéMON jsou dobrí jen na\n"
    .string "vydelávání. Proc je nevyuzít?\p"
    .string "Drz se dál od nasí práce!$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "Nikoho nezachránis, fakane!$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "Nezahrávej si s ROCKETS!$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "Tohle ti jen tak neprojde!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "MR. FUJI: He?\n"
    .string "Prisel jsi me zachránit?\p"
    .string "Dekuji. Ale já sem prisel\n"
    .string "z vlastní vule.\p"
    .string "Prisel jsem utisit dusi\n"
    .string "CUBONEovy matky.\p"
    .string "Myslím, ze duse MAROWAK\n"
    .string "nás konecne opustila.\p"
    .string "Musím ti podekovat za tvou\n"
    .string "laskavou starost.\p"
    .string "Pojd se mnou ke mne domu, POKéMON\n"
    .string "HOUSE, na úpatí téhle veze.$"
