SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "REDITEL: Ach, mily chlapce!\n"
    .string "Díky, ze jsi zachránil SILPH.\p"
    .string "Nikdy nezapomenu, ze jsi nás\n"
    .string "zachránil v okamziku nouze.\p"
    .string "Musím ti nejak podekovat.\p"
    .string "Jsem bohaty, mohu ti dát\n"
    .string "cokoli.\p"
    .string "Tady, snad to postací.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "REDITEL: Ach, milá dívko!\n"
    .string "Díky, ze jsi zachránila SILPH.\p"
    .string "Nikdy nezapomenu, ze jsi nás\n"
    .string "zachránila v okamziku nouze.\p"
    .string "Musím ti nejak podekovat.\p"
    .string "Jsem bohaty, mohu ti dát\n"
    .string "cokoli.\p"
    .string "Tady, snad to postací.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "{PLAYER} získal MASTER BALL\n"
    .string "od REDITELE!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "REDITEL: Tohle nikde nekoupís.\p"
    .string "Je to nás tajny prototyp\n"
    .string "MASTER BALL.\p"
    .string "Chytí kazdého POKéMONa\n"
    .string "bez selhání!\p"
    .string "Ale o jeho pouzití mlc.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "Nemás na to místo.$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "SEKRETÁRKA: Díky, ze jsi\n"
    .string "zachránil nás vsechny.\p"
    .string "My, od REDITELE níz,\n"
    .string "jsme tvymi dluzníky.$"

SilphCo_11F_Text_GiovanniIntro::
    .string "Ach, {PLAYER}!\n"
    .string "Tak se zase potkáváme!\p"
    .string "S REDITELEM probíráme\n"
    .string "dulezity obchod.\p"
    .string "Nestrkej nos do dospeláckych\n"
    .string "záduzitostí…\p"
    .string "Nebo zazijes svet bolesti!$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "Argh!!\n"
    .string "Zase jsem prohrál!?$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "K certu!\n"
    .string "Znicils nase plány se SILPHem!\p"
    .string "Ale TEAM ROCKET nikdy nepadne!\p"
    .string "{PLAYER}! Nezapomen, ze\n"
    .string "vsichni POKéMONi existují\l"
    .string "pro TEAM ROCKET!\p"
    .string "Musím jít, ale vrátím se!$"

SilphCo_11F_Text_Grunt2Intro::
    .string "Stuj!\n"
    .string "Nehni se!$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "Ne…\n"
    .string "Prosím!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "Takze chces videt mého BOSSE?$"

SilphCo_11F_Text_Grunt1Intro::
    .string "Stuj! Máte schuzku\n"
    .string "s mym BOSSEM?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "Argh!\n"
    .string "Zniceno!$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "Bacha…\n"
    .string "Muj BOSS má rád drsné POKéMONy!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "Na monitoru jsou POKéMONi!$"

SilphCo_11F_Text_FloorSign::
    .string "SILPH CO. HLAVNÍ KANCELÁR\n"
    .string "11F$"
