MtMoon_B2F_Text_MiguelIntro::
    .string "Hej, stuj!\p"
    .string "Tyhle fosilie jsem nasel já!\n"
    .string "Obe jsou moje!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "Dobre!\n"
    .string "Podelím se!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "Kazdy si vezme jednu fosilii!\n"
    .string "Zádné chamtivosti!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "Tak jo.\n"
    .string "Tahle fosilie je tedy moje!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Daleko, na CINNABAR ISLAND,\n"
    .string "je POKéMON LABORATOR.\p"
    .string "Provádejí vyzkum obnovy\n"
    .string "fosilií.$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "My, TEAM ROCKET, ty fosilie\n"
    .string "najdeme!\p"
    .string "Krísení POKéMONu z nich\n"
    .string "nám vynese obrovské bohatství!$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "Aaa!\n"
    .string "Ted jsem nastvany!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "Nastvals me!\n"
    .string "TEAM ROCKET te dá na cernou listinu!$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "My, TEAM ROCKET, jsme POKéMON\n"
    .string "gangsteri!\l"
    .string "Sireny strach svou silou!$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "Pohnojil jsem to!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "Sakra!\n"
    .string "Moji parnáci to tak nenechají!$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "Deláme tu velkou prácu!\n"
    .string "Vypadni, maly!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "Tak ty jsi dobry…$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "Kdyz najdes fosilii, dej mi ji\n"
    .string "a vypadni!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "Malí caparti by si nemeli zahrávat\n"
    .string "s dospelymi!\p"
    .string "Mohlo by to dopadnout spatne!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "Jsem nazhaveny!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "POKéMONi tu zili dávno predtím,\n"
    .string "nez prisli lidé.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "Chces DOME FOSSIL?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "Chces HELIX FOSSIL?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "Získal jsi HELIX FOSSIL!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "Získal jsi DOME FOSSIL!$"

