FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
    .string "SELPHY: Ach?\n"
    .string "Znám te odnekud?\p"
    .string "Ach, ale na tom nezálezí.\p"
    .string "Jsem nesmírne znudená.\n"
    .string "Prosím, vyslys mé prání.$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
    .string "Prejí si videt POKéMONa.\n"
    .string "Roztomilého {STR_VAR_1}.\p"
    .string "Chci ho videt hned.\n"
    .string "Prosím, splnte mi mé prání.$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
    .string "SELPHY: Ach, uz mám dost.\n"
    .string "Unavuje me cekat na tebe.\p"
    .string "Tentokrát ti odpustím, ale\n"
    .string "príste me prosím nezklam.$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
    .string "SELPHY: Ach, ahoj.\p"
    .string "Propána, to musí byt ten\n"
    .string "{STR_VAR_1}, kterého jsi mi chytil.\p"
    .string "Hihi…\n"
    .string "Vidím u nej podobnost s tebou.\p"
    .string "Mockrát ti dekuji.\p"
    .string "… …  … …  … …\n"
    .string "Stalo se neco?\p"
    .string "Muzes odejít.\p"
    .string "… …  … …  … …\n"
    .string "Ach, dobre. Uz chápu.\p"
    .string "SEBASTIANE!\n"
    .string "Potrebuji te tady okamzite!$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
    .string "Komorník: Ano, paní.$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
    .string "SELPHY: Postarej se o to, aby\n"
    .string "tato osoba dostala dárek.$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
    .string "Komorník: Ucinám, jak\n"
    .string "poroucíte, paní.$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
    .string "Komorník: Upremne vám dekuji,\n"
    .string "ze jste potesil lady SELPHY.\p"
    .string "Prijmete prosím toto jako její\n"
    .string "podekování…$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
    .string "Komorník: Vás VAK se zdá\n"
    .string "bohuzel plny.$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
    .string "Ach…\n"
    .string "Jak zklamávající.$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
    .string "SELPHY: Preji ti hodne\n"
    .string "stestí.$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
    .string "Komorník: Úsmev lady SELPHY\n"
    .string "má jas slunce.\p"
    .string "Prosím, prosím, prineste\n"
    .string "lady SELPHY radost.$"

