SixIsland_Mart_Text_AgathaOldestEverEliteFourMember::
    .string "Hraj s POKéMONy hodne a zij\n"
    .string "dlouhy zivot!\p"
    .string "Vezmi si napríklad AGATHU.\p"
    .string "Vytvorila rekord jako nejstarsí\n"
    .string "clenka ELITNÍ CTYRKY v historii.\p"
    .string "Inspiruje me k vetsím vecem.$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter::
    .string "Mel bych si koupit nejakou\n"
    .string "POSTU a napsat mu dopis…$"

