Route14_Text_CarterIntro::
    .string "Musís pouzít TM, abys POKéMONa\n"
    .string "naucil dobré útoky.$"

Route14_Text_CarterDefeat::
    .string "Zatím to nestací.$"

Route14_Text_CarterPostBattle::
    .string "Mas pár HM, ze? POKéMON na ne\n"
    .string "jen tak nezapomene.$"

Route14_Text_MitchIntro::
    .string "Mí ptací POKéMON by uz meli\n"
    .string "byt pripraveni na boj.$"

Route14_Text_MitchDefeat::
    .string "Jeste pripraveni nejsme!$"

Route14_Text_MitchPostBattle::
    .string "Mí ptací POKéMON se musí\n"
    .string "naucit lepsí útoky.$"

Route14_Text_BeckIntro::
    .string "V CELADON DEPT. STORE prodávají\n"
    .string "TM ve sleve.\p"
    .string "TM nejsou vzácné, ale HM\n"
    .string "má jen málokdo.$"

Route14_Text_BeckDefeat::
    .string "Och, smula!$"

Route14_Text_BeckPostBattle::
    .string "Zkus POKéMONa naucit útok\n"
    .string "stejného typu, jako je on sám.\p"
    .string "Pry to zvysuje sílu\n"
    .string "toho útoku.$"

Route14_Text_MarlonIntro::
    .string "Naucil jsi uz svého ptáka\n"
    .string "LÉTAT?\p"
    .string "Pak s ním muzes vzlétnout\n"
    .string "do oblak!$"

Route14_Text_MarlonDefeat::
    .string "Sestrelen v plamenech!$"

Route14_Text_MarlonPostBattle::
    .string "Ptací POKéMON jsou má láska.\n"
    .string "Jiné chovat nechci.$"

Route14_Text_DonaldIntro::
    .string "Slysels uz legendu o okrídlenych\n"
    .string "prízracích?$"

Route14_Text_DonaldDefeat::
    .string "Proc?\n"
    .string "Proc jsem prohrál?$"

Route14_Text_DonaldPostBattle::
    .string "Okrídlené prizraky jsou\n"
    .string "legendární ptací POKéMON.\p"
    .string "Jsou tri: ARTICUNO,\n"
    .string "ZAPDOS a MOLTRES.$"

Route14_Text_BennyIntro::
    .string "Moc me to nebere, ale dobre.\n"
    .string "Jdeme na to!$"

Route14_Text_BennyDefeat::
    .string "Vedel jsem to!$"

Route14_Text_BennyPostBattle::
    .string "Vyhra, prohra… Pod tímto\n"
    .string "nekonecnym nebem to nic není.$"

Route14_Text_LukasIntro::
    .string "Tak pojd, pojd.\n"
    .string "Jdeme, jdeme, jdeme!$"

Route14_Text_LukasDefeat::
    .string "Arrg!\n"
    .string "Prohra! Ztrat se!$"

Route14_Text_LukasPostBattle::
    .string "Co, co, co?\n"
    .string "Co jeste chces?$"

Route14_Text_IsaacIntro::
    .string "Musím nejak zabít cas.\n"
    .string "Drz hubu a bojuj.$"

Route14_Text_IsaacDefeat::
    .string "Coze?\n"
    .string "Ty!?$"

Route14_Text_IsaacPostBattle::
    .string "Chovat POKéMONy je otrava, kámo.$"

Route14_Text_GeraldIntro::
    .string "Jezdíme sem kvuli sirokym\n"
    .string "otevrenym plánim.$"

Route14_Text_GeraldDefeat::
    .string "Smeten!$"

Route14_Text_GeraldPostBattle::
    .string "Pekné, ze jsi své POKéMONy\n"
    .string "vychoval tak silné.\p"
    .string "Vyhrává silnejsí!\n"
    .string "A ty to vís!$"

Route14_Text_MalikIntro::
    .string "POKéMON souboj?\n"
    .string "Super! Drsne!$"

Route14_Text_MalikDefeat::
    .string "Odfouknut!$"

Route14_Text_MalikPostBattle::
    .string "Víme, kdo by vyhrál, ty a já,\n"
    .string "jeden na jednoho!$"

Route14_Text_RouteSign::
    .string "CESTA 14\n"
    .string "Na západ do FUCHSIA CITY$"

Route14_Text_KiriIntro::
    .string "KIRI: JANE, zkusme to spolu\n"
    .string "ze vsech sil.$"

Route14_Text_KiriDefeat::
    .string "KIRI: Fnuk…\n"
    .string "Prohráli jsme, vid?$"

Route14_Text_KiriPostBattle::
    .string "KIRI: Prohráli jsme kvuli mne?$"

Route14_Text_KiriNotEnoughMons::
    .string "KIRI: Bojovat muzeme, kdyz mas\n"
    .string "dva POKéMONy.$"

Route14_Text_JanIntro::
    .string "JAN: KIRI, jdeme na to!\n"
    .string "Musíme se snazit!$"

Route14_Text_JanDefeat::
    .string "JAN: Iiii!\n"
    .string "To není fér!$"

Route14_Text_JanPostBattle::
    .string "JAN: KIRI, neplac!\n"
    .string "Príste se snazme víc.$"

Route14_Text_JanNotEnoughMons::
    .string "JAN: Chces bojovat?\n"
    .string "Nemas dost POKéMONu.$"
