ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger::
    .string "Je to pravda?\p"
    .string "CELADON DEPT. STORE je nekolikrát\n"
    .string "vetsí nez tento obchod?$"

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest::
    .string "Obcas tu kupuji léky.\p"
    .string "Ale spousta lidí lécí POKéMONy\n"
    .string "BOBULEMI z BERRY FOREST.\p"
    .string "Vzdyt BOBULE jsou zdarma\n"
    .string "a nikdy nedojdou.$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart::
    .string "Ti BIKERS málem rozbili tento\n"
    .string "POKéMON MART.\p"
    .string "Jsem rád, ze se rozhodli odejít!$"

