SSAnne_1F_Corridor_Text_LeStrongSilentType::
    .string "Bonjour!\n"
    .string "Já jsem le císník na lodi!\p"
    .string "Rád ti naservíruji cokoli,\n"
    .string "co si prejes!\p"
    .string "… … …\n"
    .string "Ah! Le silny mlcenlivy typ!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
    .string "Cestující jsou neklidní z téhle\n"
    .string "dlouhé plavby.\p"
    .string "Mohou te vyzvat ti nudnejsí!$"
