CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
    .string "Vítej!\p"
    .string "Své MINCE muzes vedle vymenit\n"
    .string "za skvelé ceny.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
    .string "Vítej v ROCKET GAME CORNER!\p"
    .string "Potrebujes herní MINCE?\n"
    .string "Chces si nejaké koupit?$"

CeladonCity_GameCorner_Text_ComePlaySometime::
    .string "Ne?\n"
    .string "Prijd si nekdy zahrát!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
    .string "Ach, promin.\n"
    .string "Nemás MINCOVNÍK.$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
    .string "Jejda!\n"
    .string "Tvuj MINCOVNÍK je plny.$"

CeladonCity_GameCorner_Text_CantAffordCoins::
    .string "Na MINCE nemás.$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
    .string "Díky.\n"
    .string "Tady jsou tvé MINCE!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
    .string "Mlc o tom.\p"
    .string "Povídá se, ze tohle místo\n"
    .string "vede TEAM ROCKET.$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
    .string "Myslím, ze ty automaty mají\n"
    .string "ruzné sance.$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
    .string "Decko, chces si zahrát?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
    .string "{PLAYER} dostal 10 MINCÍ\n"
    .string "od muze.$"

CeladonCity_GameCorner_Text_DontNeedMyCoins::
    .string "Moje MINCE nepotrebujes!$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
    .string "Vyhry prijdou a odejdou.\n"
    .string "Nic není jistá vec.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
    .string "Tyhle automaty…\n"
    .string "Vyhra ci prohra je jen stestí.$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
    .string "Hej!\p"
    .string "Más lepsí veci na práci,\n"
    .string "budoucí sampióne!\p"
    .string "VUDKYNE CELADON GYMu je ERIKA.\p"
    .string "Pouzívá POKéMONy typu GRASS\n"
    .string "a je v souladu s prírodou.\p"
    .string "Muze pusobit krotce kvuli\n"
    .string "kvetinovym aranzím…\p"
    .string "Ale rozhodne ji nepodcenuj!$"

CeladonCity_GameCorner_Text_RareMonsForCoins::
    .string "Nabízí vzácné POKéMONy, které\n"
    .string "lze získat za MINCE.\p"
    .string "Ale já proste neumím vyhrát!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
    .string "Hry jsou desivé!\n"
    .string "Lehko si na ne zvyknes!$"

CeladonCity_GameCorner_Text_WantSomeCoins::
    .string "Co je?\n"
    .string "Chces MINCE?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
    .string "{PLAYER} dostal 20 MINCÍ\n"
    .string "od milého chlapíka.$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
    .string "Más spoustu MINCÍ!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
    .string "Sakra! Potrebuji víc MINCÍ\n"
    .string "na POKéMONa, co chci!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
    .string "Co? Rusis me!\n"
    .string "Tady másMINCE, ted zmiz!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
    .string "{PLAYER} dostal 20 MINCÍ\n"
    .string "od muze.$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
    .string "Más spoustu vlastních\n"
    .string "MINCÍ!$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
    .string "Trik je sledovat valce\n"
    .string "pozorne.$"

CeladonCity_GameCorner_Text_GruntIntro::
    .string "Hlídám tenhle plakát!\n"
    .string "Zmiz, nebo uvidís!$"

CeladonCity_GameCorner_Text_GruntDefeat::
    .string "Sakra!$"

CeladonCity_GameCorner_Text_GruntPostBattle::
    .string "ÚKRYT TEAM ROCKET muze\n"
    .string "byt odhalen!\p"
    .string "Radsi to reknu BOSSOVI!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
    .string "Hej!\p"
    .string "Spínac za plakátem!?\n"
    .string "Zmáckni ho!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
    .string "Je potreba MINCOVNÍK…$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
    .string "Jejda!\n"
    .string "Nemás MINCOVNÍK!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
    .string "Automat!\n"
    .string "Chces si zahrát?$"

CeladonCity_GameCorner_Text_OutOfOrder::
    .string "MIMO PROVOZ\n"
    .string "Tenhle je rozbity.$"

CeladonCity_GameCorner_Text_OutToLunch::
    .string "JSEM NA OBEDE\n"
    .string "Tenhle je rezervovany.$"

CeladonCity_GameCorner_Text_SomeonesKeys::
    .string "Cizí klíce!\n"
    .string "Vrátí se pro ne.$"
