SilphCo_3F_Text_WhatAmIToDo::
    .string "Pracuji pro SILPH CO.\n"
    .string "Co mám delat?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .string "{PLAYER}!\n"
    .string "Ty a tví POKéMONi jste nás\nzachránili!$"

SilphCo_3F_Text_GruntIntro::
    .string "Prestan nás otravovat, decko!$"

SilphCo_3F_Text_GruntDefeat::
    .string "Vzdávám to!$"

SilphCo_3F_Text_GruntPostBattle::
    .string "Tip? Dvere otevres pomocí\n"
    .string "CARD KEY!$"

SilphCo_3F_Text_JoseIntro::
    .string "Podporuji TEAM ROCKET víc\n"
    .string "nez SILPH CO.!$"

SilphCo_3F_Text_JoseDefeat::
    .string "Vsadil jsi na me!$"

SilphCo_3F_Text_JosePostBattle::
    .string "Hmf…\p"
    .string "TEAM ROCKET ríkal, ze kdyz jim\n"
    .string "pomuzu, nechají me studovat.$"

SilphCo_3F_Text_FloorSign::
    .string "SILPH CO. HLAVNÍ KANCELÁR\n"
    .string "3F$"
