CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "REPEL nejen odhání broucky,\n"
    .string "funguje i na slabé POKéMONy.\p"
    .string "Dej svého nejsilnejsího POKéMONa\n"
    .string "doleva v POKéMON LISTU.\p"
    .string "Kdyz je tvuj první POKéMON silny,\n"
    .string "úcinek REPELu je zesílen.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "Vís o RARE CANDY?\n"
    .string "V obchodech ho neprodávají.\p"
    .string "Myslím, ze POKéMONa najednou\n"
    .string "velmi rychle vyspeje.$"

