TwoIsland_Text_IslandSign::
    .string "TWO ISLAND\n"
    .string "Boon Island pro dva$"

TwoIsland_Text_JoyfulGameCornerSign::
    .string "Skok a chnap!\n"
    .string "Vesely GAME CORNER$"

TwoIsland_Text_DangerFastCurrent::
    .string "POZOR! RYCHLY PROUD!\n"
    .string "Rybolov a surfování zakázáno!$"

TwoIsland_Text_WelcomeToShopMerchandiseLimited::
    .string "Ach!\n"
    .string "Ahoj, vítej v mém obchode!\p"
    .string "Otevreli jsme teprve nedávno.\p"
    .string "Naseho zbozí je málo, ale\n"
    .string "doufám, ze ti budeme uzitecní.$"

TwoIsland_Text_AddedMerchandiseForLostelle::
    .string "Nedokázu vyjádrit, jak jsem\n"
    .string "vdecny za záchranu LOSTELLE.\p"
    .string "Díky tvému cinu zmenili lidé\n"
    .string "z THREE ISLAND svuj postoj\l"
    .string "vuci lidem z KANTA.\p"
    .string "A já jsem z KANTA.\p"
    .string "Lidé z THREE ISLAND mi pomohli\n"
    .string "rozsírit nase zbozí.$"

TwoIsland_Text_HopeYouGiveItYourBest::
    .string "Ahoj! Dávám do toho vsechno.\n"
    .string "Doufám, ze ty taky, {PLAYER}.$"

TwoIsland_Text_BringingItemsFromDistantLands::
    .string "Ach, ahoj, {PLAYER}!\n"
    .string "Vítej!\p"
    .string "Zacal jsem dovázet predmety\n"
    .string "ze vzdálenych zemí.\p"
    .string "Mám i nejaké vzácné predmety.\n"
    .string "Mrkni se!$"

TwoIsland_Text_FellowMovedFromCeladonCity::
    .string "Ten chlápek tamhle, prestehoval\n"
    .string "se sem z CELADON CITY.\p"
    .string "Otevrel obchod se svym\n"
    .string "mladsím bratrem.\p"
    .string "Musís se ptát, jestli vedel,\n"
    .string "do ceho jde.$"

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner::
    .string "Bratr obchodníka se vrhl\n"
    .string "na práci v GAME CORNERU.\p"
    .string "Snazí se vydelat peníze,\n"
    .string "aby koupili více zbozí.$"

TwoIsland_Text_BrunoCameToIslandWhileBack::
    .string "Poslouchej, poslouchej.\n"
    .string "Vís?\p"
    .string "Pred chvílí prijel na OSTROV\n"
    .string "slavny TRÉNÉR.\p"
    .string "Je clenem ELITNÍ CTYRKY.\n"
    .string "Jeho jméno je BRUNO.\p"
    .string "Odjel zklamany, kdyz zjistil,\n"
    .string "ze byly vyprodány Rage\l"
    .string "Candybars.$"

TwoIsland_Text_BuyRareItemsHere::
    .string "Chytry TRÉNÉR ví, ze vzácné\n"
    .string "predmety se kupují zde!$"

TwoIsland_Text_OldWomanLivesOutOnCape::
    .string "Na mysu zije stará paní\n"
    .string "v chaloupce.\p"
    .string "Dává POKéMONum oko.\n"
    .string "Je to trochu zneklidnující.$"

TwoIsland_Text_HaveYouTriedJumpingGame::
    .string "Boing! Boing!\n"
    .string "Zkusils skákací hru?\p"
    .string "POKéMONi, které muzes nasadit…\n"
    .string "Boing!\p"
    .string "Nekterí delají boing!\p"
    .string "A jiní delají boooooooing!\p"
    .string "Vedels to?\n"
    .string "Boing!$"

