PokemonTower_6F_Text_AngelicaIntro::
    .string "Dej…mi…\n"
    .string "krev…$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "Ach!$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "Cítím se slabá a bez krve…$"

PokemonTower_6F_Text_EmiliaIntro::
    .string "Urf…\n"
    .string "Kwáá!$"

PokemonTower_6F_Text_EmiliaDefeat::
    .string "Neco vypadlo!$"

PokemonTower_6F_Text_EmiliaPostBattle::
    .string "Vlasy mi nevypadaly!\n"
    .string "Byl to zlovolny duch!$"

PokemonTower_6F_Text_JenniferIntro::
    .string "Ke…ke…ke…\n"
    .string "ke…ke…ke!$"

PokemonTower_6F_Text_JenniferDefeat::
    .string "Kíí!$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "Co se to tady deje?$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "Zmizte…\n"
    .string "Vetrelci…$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "Ten duch byl neklidnou dusí\n"
    .string "CUBONEovy matky!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "Matcina duse se uklidnila.\p"
    .string "Odesla na onen svet…$"
