ThreeIsland_Port_Text_WereKantoRiderFederation::
    .string "Jsme KANTSKÁ JEZDECKÁ FEDERACE!\n"
    .string "Vroom! Vavavavooom! Vroom!\p"
    .string "Má motorka je slabá, tak musím\n"
    .string "delat zvuk vyfuku sám!$"

ThreeIsland_Port_Text_ForkOverMoney::
    .string "Hej, hej, dámo!\n"
    .string "Vyplázni nejaké penízky!$"

ThreeIsland_Port_Text_IllCallThePolice::
    .string "Aiyeeh!\p"
    .string "K-kdo jste?!\n"
    .string "Z… Zavolám policii!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
    .string "Ti BIKERS…\n"
    .string "Jsou pryc?\p"
    .string "Ach, díky bohu!\n"
    .string "Vázne me vystrasili!$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
    .string "Ti BIKERS odjeli a LOSTELLE\n"
    .string "se nasla v poradku.\p"
    .string "Vse dopadlo nejlépe!$"

