MtMoon_1F_Text_MarcosIntro::
    .string "JÉJDA!\n"
    .string "Lekl jsi me!\l"
    .string "…A, jsi jen mlade!$"

MtMoon_1F_Text_MarcosDefeat::
    .string "Páni!\n"
    .string "Zase me vylekal!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "Mladí jako ty by neméli bloudit\n"
    .string "tady ve tme.$"

MtMoon_1F_Text_JoshIntro::
    .string "Taky ses prisel podívat\n"
    .string "do jeskyne?$"

MtMoon_1F_Text_JoshDefeat::
    .string "Prohrávání je na hovno!\n"
    .string "Je to tak trapné.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "Prisel jsem az sem dolu, abych\n"
    .string "se predved holkám.$"

MtMoon_1F_Text_MiriamIntro::
    .string "Páni! Tady uvnitr je to mnohem\n"
    .string "vetsí, nez jsem cekala!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "Jé!\n"
    .string "Prohrála jsem!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "Jak se odsud dostanu?\n"
    .string "Je to tak velké, mozná se ztratím.$"

MtMoon_1F_Text_JovanIntro::
    .string "Co!\n"
    .string "Neplíz se na mne!$"

MtMoon_1F_Text_JovanDefeat::
    .string "Mí POKéMONi nestací!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "Musím najít silnejsí POKéMONy.\n"
    .string "Kde by mohli byt?$"

MtMoon_1F_Text_IrisIntro::
    .string "Co?\n"
    .string "Cekám, az me tu najdou\l"
    .string "kamarádi.$"

MtMoon_1F_Text_IrisDefeat::
    .string "Prohrála jsem?$"

MtMoon_1F_Text_IrisPostBattle::
    .string "Prisla jsem, protoze jsem slysela,\n"
    .string "ze jsou tu vzácné fosilie.$"

MtMoon_1F_Text_KentIntro::
    .string "V jeskyni jsou podezrelí muzi.\n"
    .string "A co ty?$"

MtMoon_1F_Text_KentDefeat::
    .string "Dostal jsi me!$"

MtMoon_1F_Text_KentPostBattle::
    .string "Videl jsem je!\n"
    .string "Urcite jsou z TEAM ROCKET!$"

MtMoon_1F_Text_RobbyIntro::
    .string "Touhle jeskyní musís projít,\n"
    .string "abys se dostal do CERULEAN CITY.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "Prohrál jsem.$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "ZUBAT je tezky souper!\n"
    .string "Ale kdyz ho chytís, budes\l"
    .string "se na nej moct spolehnout.$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "Pozor!\n"
    .string "ZUBAT je krvesaj!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "Ahoj, kopu tady pod MT. MOON\n"
    .string "fosilie.\p"
    .string "Obcas mi pomáhá BROCK z\n"
    .string "PEWTER GYM.$"
