Text_DoubleEdgeTeach::
    .string "Mel bys na sebe byt hrdy,\n"
    .string "ze ses tak odvázne probojoval\l"
    .string "skrz VICTORY ROAD.\p"
    .string "Na uznání tvého ciny te\n"
    .string "naucím DOUBLE-EDGE.\p"
    .string "Chtel bys, abych te tu\n"
    .string "techniku naucil?$"

Text_DoubleEdgeDeclined::
    .string "Tu techniku te naucím\n"
    .string "kdykoli.$"

Text_DoubleEdgeWhichMon::
    .string "Kterého POKéMONa mám naucit\n"
    .string "DOUBLE-EDGE?$"

Text_DoubleEdgeTaught::
    .string "Udrz si tu chut do POKéMON\n"
    .string "LEAGUE!\p"
    .string "Vyraz na ne a slozte je\n"
    .string "k zemi!$"

VictoryRoad_3F_Text_GeorgeIntro::
    .string "Slysel jsem zvesti o zázraku.$"

VictoryRoad_3F_Text_GeorgeDefeat::
    .string "Zvesti byly pravdivé!$"

VictoryRoad_3F_Text_GeorgePostBattle::
    .string "Tak to tys porazil GIOVANNIHO\n"
    .string "z TEAM ROCKET?$"

VictoryRoad_3F_Text_AlexaIntro::
    .string "TRENÉRI zijí pro hledání\n"
    .string "silnejsích souperu.$"

VictoryRoad_3F_Text_AlexaDefeat::
    .string "Ó!\n"
    .string "Tak silny!$"

VictoryRoad_3F_Text_AlexaPostBattle::
    .string "Bojem tezkych souboju\n"
    .string "zesílís.$"

VictoryRoad_3F_Text_CarolineIntro::
    .string "Ukázu ti, jak moc jsi\n"
    .string "dobry. Ne!$"

VictoryRoad_3F_Text_CarolineDefeat::
    .string "Zurím!$"

VictoryRoad_3F_Text_CarolinePostBattle::
    .string "Ukázals mi, jak moc\n"
    .string "jsem dobrá…$"

VictoryRoad_3F_Text_ColbyIntro::
    .string "Jen vyvolení tudy projdou!$"

VictoryRoad_3F_Text_ColbyDefeat::
    .string "Tomu neverím!$"

VictoryRoad_3F_Text_ColbyPostBattle::
    .string "Vsichni TRENÉRI tady mírí do\n"
    .string "POKéMON LEAGUE.\p"
    .string "Nepolevuj v ostrazitosti.$"

VictoryRoad_3F_Text_RayIntro::
    .string "RAY: Spolecne jsme my dva\n"
    .string "predurceni k velikosti!$"

VictoryRoad_3F_Text_RayDefeat::
    .string "RAY: Smesné!\n"
    .string "To nemuze byt!$"

VictoryRoad_3F_Text_RayPostBattle::
    .string "RAY: Porazil jsi nás.\n"
    .string "Velikost zustává nedosazitelná…$"

VictoryRoad_3F_Text_RayNotEnoughMons::
    .string "RAY: Spolecne my dva usilujeme\n"
    .string "o vrchol.\p"
    .string "Potrebujeme, abys do boje s námi\n"
    .string "prinesl dva POKéMONy.$"

VictoryRoad_3F_Text_TyraIntro::
    .string "TYRA: Snazíme se spolecne\n"
    .string "stát sampióny.$"

VictoryRoad_3F_Text_TyraDefeat::
    .string "TYRA: Ó, ale…$"

VictoryRoad_3F_Text_TyraPostBattle::
    .string "TYRA: Naucils me, ze síla muze\n"
    .string "mít nekonecne podob a forem.$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
    .string "TYRA: Nemuzes s námi bojovat,\n"
    .string "kdyz más jen jednoho POKéMONa.$"
