FiveIsland_LostCave_Room1_Text_LawsonIntro::
    .string "Aiéééé!\p"
    .string "Myslel jsem, ze to jsou staré\n"
    .string "ruiny. Ale je to plné duchu!$"

FiveIsland_LostCave_Room1_Text_LawsonDefeat::
    .string "Aiéééé!\n"
    .string "Slitování!$"

FiveIsland_LostCave_Room1_Text_LawsonPostBattle::
    .string "Snazím se odsud dostat, ale\n"
    .string "porád koncím na stejném míste.\p"
    .string "Mozná pocet balvanu je\n"
    .string "vodítko…$"

