SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
    .string "SAFARI ZONE je obrovská,\n"
    .string "nemyslís?\p"
    .string "FUCHSIA GYM LEADER, KOGA,\n"
    .string "obcas hlídkuje po okolí.\p"
    .string "Díky nemu si tu muzeme hrát\n"
    .string "s vedomím, ze jsme v bezpecí.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
    .string "Házení ROCKS po POKéMONech je\n"
    .string "muze zahnat na útek, ale pak\l"
    .string "se snáz chytí.$"

SafariZone_West_Text_BaitMakesMonStickAround::
    .string "Pouzití BAIT zvysí sanci, ze\n"
    .string "POKéMON zustane, kdyz se zabere\l"
    .string "do zrání.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
    .string "Nachodil jsem se, ale nevidel\n"
    .string "jsem zádné POKéMONy, co jsem chtel.$"
