FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .string "V kotci je zamcenych spousta\n"
    .string "POKéMONu…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .string "Dvere kotce jsou odemcené.\n"
    .string "Zdá se, ze POKéMONi utekli.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
    .string "Tys sem prisel s vedomím, ze\n"
    .string "tohle je SKLAD TEAM ROCKET?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .string "Co si myslís, ze delás?!$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
    .string "TEAM ROCKET se rozpadl?\n"
    .string "Z jaké jsi planety?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .string "Ach, tví POKéMONi vypadají silne.\n"
    .string "Chces je prodat?\p"
    .string "Ach?\n"
    .string "Tys chtel bojovat?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .string "Ach, ale…\n"
    .string "Príslis silny!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .string "Dáme ti skvelou cenu.\n"
    .string "Prodej nám své POKéMONy!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
    .string "Slysel jsem o tobe od ostatních.\p"
    .string "Ale neexistuje sance, ze by\n"
    .string "fakan jako ty znal naseho\l"
    .string "BOSE GIOVANNIHO!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .string "Ne…opovaz…se…smát…$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
    .string "Neplet se do vecí dospelych,\n"
    .string "ty drzá stveni!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
    .string "Nevím ani me to nezajímá,\n"
    .string "jestli je to, co delám, správné…\p"
    .string "Jen verím GIOVANNIMU a delám,\n"
    .string "co se mi rekne.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .string "Já…\n"
    .string "Jsem zlomeny…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .string "Delás veci podle svych\n"
    .string "presvedcení a morálky.\p"
    .string "Uz to chápu…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .string "Zarídil jsem, abys mohl prijít\n"
    .string "zpátky tudy.\p"
    .string "Co kdyby ses sel odpocinout\n"
    .string "a pripravit na to, co te ceká?\p"
    .string "ADMIN za mnou me daleko\n"
    .string "prevysuje jako TRÉNÉR.\p"
    .string "Radeji se priprav na tezkou\n"
    .string "zkousku.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
    .string "To stací, dost uz si\n"
    .string "hrát na hrdinu, fakane.\p"
    .string "Sírís lzi o tom, ze TEAM\n"
    .string "ROCKET se rozpadl…\p"
    .string "Je to ocividny pokus zpusobit\n"
    .string "zmatek v nasich radách.\p"
    .string "Nastestí nejsme tak hloupí,\n"
    .string "abychom verili detskym lzím!\p"
    .string "A ted ti ukázu, jak strasny\n"
    .string "muze byt rozzlobeny dospely!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
    .string "Uh…\n"
    .string "Bylo to nad mé síly…\p"
    .string "…\n"
    .string "T-to je ODZNAK GIOVANNIHO!\p"
    .string "Takze je to pravda?\n"
    .string "TEAM ROCKET se opravdu\l"
    .string "rozpadl?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
    .string "Opustíme tento SKLAD…\p"
    .string "Ale nemysli si, ze to skoncilo.\n"
    .string "Nedovolím, aby to byl konec.\p"
    .string "Najdu GIOVANNIHO.\n"
    .string "A vzkrísím TEAM ROCKET!\l"
    .string "Já…\p"
    .string "Do té doby, sbohem!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .string "Na monitoru PC je hlásení\n"
    .string "s grafy a textem.\p"
    .string "“Vliv magnetickych vln na\n"
    .string "vyvoj POKéMONu”…\p"
    .string "… … … … … …\p"
    .string "Je to moc slozité na\n"
    .string "pochopení…$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .string "Skoro se mi podarilo prodat\n"
    .string "SAPHIR za obrovské peníze…\p"
    .string "A pak jsi musel prijít a\n"
    .string "cely obchod rozbít!\p"
    .string "Fufu… Fufufufu…\n"
    .string "Pro tebe není odpustení!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .string "Sakra! Krucipísek!\n"
    .string "Sakra! Sakra!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .string "Kdyz to nemuzu prodat, je to\n"
    .string "k nicemu! Bez, vezmi si to!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .string "Co zase chces?\n"
    .string "Bez, ztrat se, nech me byt.$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .string "Cze, ty zase?\p"
    .string "Ty… Ty nejsi syn GIOVANNIHO,\n"
    .string "ze ne?\p"
    .string "Ne, to nemuze byt pravda!\n"
    .string "Syn GIOVANNIHO má rusavé vlasy.\p"
    .string "Nemás duvod me obtezovat.\n"
    .string "Nech me na pokoji!$"

