ViridianCity_Gym_Text_GiovanniIntro::
    .string "Fwahahaha!\n"
    .string "Vítej v mém úkrytu!\p"
    .string "Bude to tak, dokud TEAM ROCKET\n"
    .string "neobnovím v plné sláve.\p"
    .string "Ale ty jsi me zase nasel.\n"
    .string "Tak budiz.\l"
    .string "Tentokrát se neudrzuji!\p"
    .string "Jeste jednou stanes proti\n"
    .string "GIOVANNIMU, nejlepsímu TRENéROVI!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "Ha!\n"
    .string "To byl skutecne tezky boj.\l"
    .string "Zvítezils!\p"
    .string "Jako dukaz, tady mas EARTHBADGE!\n"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "Po takové porázce \n"
    .string "nemohu celit svym lidem.\l"
    .string "Zradil jsem jejich duveru.\p"
    .string "Ode dneska je TEAM ROCKET\n"
    .string "navzdy u konce!\p"
    .string "Já sám zasvetím svuj zivot\n"
    .string "trénování od zacátku.\p"
    .string "Setkejme se jednou znovu!\n"
    .string "Sbohem!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "EARTHBADGE zarídí, ze POKéMON\n"
    .string "kazdé úrovne te poslechne.\p"
    .string "Je to dukaz tvého mistrovství\n"
    .string "jako POKéMON TRENéRA.\p"
    .string "S ním muzes vyzvat\n"
    .string "POKéMON LIGU.\p"
    .string "Také si vezmi tohle TM.\p"
    .string "Ber to jako dárek pro tvou\n"
    .string "vyzvu POKéMON LIGY.$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .string "{PLAYER} dostal TM26\n"
    .string "od GIOVANNIHO.$"

ViridianCity_Gym_Text_ExplainTM26::
    .string "TM26 obsahuje EARTHQUAKE.\p"
    .string "Je to mocny útok, ktery\n"
    .string "zpusobí silné otresy.\p"
    .string "Vytvoril jsem ho, kdyz jsem\n"
    .string "tu vedl GYM, uz davno… $"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "Nemás na to místo!$"

ViridianCity_Gym_Text_YujiIntro::
    .string "Heh!\n"
    .string "Uz ti asi dochází síla!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "Doslo mi palivo!$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "Budes potrebovat sílu, abys\n"
    .string "porazil naseho VUDCE GYM.$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "Rrrroar!\n"
    .string "Dostávám se do varu!$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "Wargh!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "Porád nejsem hoden!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "POKéMON a já, spolu deláme\n"
    .string "krásnou hudbu!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "Jsi v dokonalé harmonii!$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "Znás identitu naseho\n"
    .string "VUDCE GYM?$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "Karate je nejvyssí forma\n"
    .string "bojovych umení!$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "Aiyah!$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "Kdyby muji POKéMONi umeli\n"
    .string "karate jako já…$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "Skutecne nadaní vítezí stylem.$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "Ztratil jsem grip!$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "VUDCE me vyhubuje, ze jsem\n"
    .string "prohrál takhle…$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "Já jsem KRÁL KARATE!\n"
    .string "Tvuj osud lezí na me!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "Ayah!$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "POKéMON LIGA?\n"
    .string "Ty? Nebud namyslivy!$"

ViridianCity_Gym_Text_ColeIntro::
    .string "Tví POKéMONi se schoulí pri\n"
    .string "prásknutí mého bice!$"

ViridianCity_Gym_Text_ColeDefeat::
    .string "Ouvej!\n"
    .string "Bicem do me!$"

ViridianCity_Gym_Text_ColePostBattle::
    .string "Pockej!\n"
    .string "Byl jsem jen neopatrny!$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "VIRIDIAN GYM byla dlouho\n"
    .string "zavrená.\p"
    .string "Ale ted je nás VUDCE zpátky!$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "Byl jsem porazen?$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "Do POKéMON LIGY se dostanes\n"
    .string "jedine porázkou naseho VUDCE\l"
    .string "GYM!$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "Hej!\n"
    .string "Budoucí sampione!\p"
    .string "Ani já neznám identitu\n"
    .string "VIRIDIANSKéHO VUDCE.\p"
    .string "Ale jedno je jisté.\n"
    .string "Tohle bude nejtezsí ze vsech\l"
    .string "VUDCU GYM.\p"
    .string "Také jsem slysel, ze TRENéRI\n"
    .string "tu mají rádi GROUND POKéMONy.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "Hrom me bac! GIOVANNI byl VUDCE\n"
    .string "GYM ve VIRIDIANU?$"

ViridianCity_Gym_Text_GymStatue::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "VUDCE: ?\p"
    .string "VíTEZNí TRENéRI:\n"
    .string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "VIRIDIAN POKéMON GYM\n"
    .string "VUDCE: GIOVANNI\p"
    .string "VíTEZNí TRENéRI:\n"
    .string "{RIVAL}, {PLAYER}$"
