Route16_Text_LaoIntro::
    .string "Co chces?$"

Route16_Text_LaoDefeat::
    .string "Opovaz se smát!$"

Route16_Text_LaoPostBattle::
    .string "Rádi se tu jen tak poflakujeme.\n"
    .string "Co je ti do toho?$"

Route16_Text_KojiIntro::
    .string "Pekné KOLO!\n"
    .string "Dej ho sem!$"

Route16_Text_KojiDefeat::
    .string "K. O.!$"

Route16_Text_KojiPostBattle::
    .string "Zapomen, kdo by chtel tvé KOLO!$"

Route16_Text_LukeIntro::
    .string "Pojd si hrát, malá mysko!$"

Route16_Text_LukeDefeat::
    .string "Ty malá krysa!$"

Route16_Text_LukePostBattle::
    .string "Nesnásím prohry!\n"
    .string "Zmiz mi z ocí!$"

Route16_Text_HideoIntro::
    .string "Hej, ty jsi do me strcil!$"

Route16_Text_HideoDefeat::
    .string "Bum!$"

Route16_Text_HideoPostBattle::
    .string "Pojedeme se tu poflakovat\n"
    .string "porád, at se ti to líbí nebo ne.\p"
    .string "Z FUCHSIE muzes do VERMILIONu\n"
    .string "objet pobrezím.$"

Route16_Text_CamronIntro::
    .string "Mám hlad a jsem nasranej!\n"
    .string "Potrebuju boxovacího panáka!$"

Route16_Text_CamronDefeat::
    .string "Spatne, spatne, spatne!$"

Route16_Text_CamronPostBattle::
    .string "Kdyz uz mám mít POKéMONy,\n"
    .string "at jsou krutí.\p"
    .string "S nima bych nepratele rozcupoval\n"
    .string "na cucky.$"

Route16_Text_RubenIntro::
    .string "Cau!\n"
    .string "Pojdme si poradne uzít!$"

Route16_Text_RubenDefeat::
    .string "Nestvi me!$"

Route16_Text_RubenPostBattle::
    .string "Bavím se tím, ze lidi otravuju\n"
    .string "smradlavymi POKéMONy.\p"
    .string "Skvele lidi vyleknou.\n"
    .string "A jeste koukou.$"

Route16_Text_MonSprawledOutInSlumber::
    .string "POKéMON je rozvaleny\n"
    .string "v hlubokém pohodlném spánku.$"

Route16_Text_CyclingRoadSign::
    .string "Uzij si sjezd!\n"
    .string "CYKLISTICKÁ STEZKA$"

Route16_Text_RouteSign::
    .string "CESTA 16\n"
    .string "CELADON CITY - FUCHSIA CITY$"

Route16_Text_JedIntro::
    .string "JED: Nase láska nemá hranic.\n"
    .string "Jsme zamilovaní a dáváme to najevo!$"

Route16_Text_JedDefeat::
    .string "JED: Ach ne!\n"
    .string "Má láska me videla prohrát!$"

Route16_Text_JedPostBattle::
    .string "JED: Poslouchej, LEA.\n"
    .string "Soustred se míne na me.$"

Route16_Text_JedNotEnoughMons::
    .string "JED: Mas jen jednoho POKéMONa?\n"
    .string "Nemas v srdci lásku?$"

Route16_Text_LeaIntro::
    .string "LEA: Intenzita nasí lásky\n"
    .string "me obcas desí.$"

Route16_Text_LeaDefeat::
    .string "LEA: Och! Ale JED je super\n"
    .string "i v prohre!$"

Route16_Text_LeaPostBattle::
    .string "LEA: Ehehe, promin.\n"
    .string "JED je tak super.$"

Route16_Text_LeaNotEnoughMons::
    .string "LEA: Ach, nemas dva POKéMONy\n"
    .string "u sebe?\p"
    .string "Není ti smutno?\n"
    .string "A tvym POKéMONum taky?$"
