Route19_Text_RichardIntro::
    .string "Pred plaváním se musím\n"
    .string "rozcvicit a zahrát.$"

Route19_Text_RichardDefeat::
    .string "Pekne rozehráno!$"

Route19_Text_RichardPostBattle::
    .string "Díky, kluku!\n"
    .string "Jsem hotov na plavbu.$"

Route19_Text_ReeceIntro::
    .string "Pockej! Zpomal!\n"
    .string "Dostanes infarkt!$"

Route19_Text_ReeceDefeat::
    .string "Oh!\n"
    .string "To je chladno!$"

Route19_Text_ReecePostBattle::
    .string "Pozor na TENTACOOLa.\n"
    .string "Pichá tak bolestive.$"

Route19_Text_MatthewIntro::
    .string "Miluji plavání!\n"
    .string "A ty?$"

Route19_Text_MatthewDefeat::
    .string "Plácnutí brichem!$"

Route19_Text_MatthewPostBattle::
    .string "V plavání porazím i morské\n"
    .string "POKéMONy.$"

Route19_Text_DouglasIntro::
    .string "Co je za obzorem?$"

Route19_Text_DouglasDefeat::
    .string "Bublbubl!$"

Route19_Text_DouglasPostBattle::
    .string "Vidím tamhle pár\n"
    .string "ostrovu!$"

Route19_Text_DavidIntro::
    .string "Zkusil jsem se potápet pro\n"
    .string "POKéMONy, ale nepovedlo se.$"

Route19_Text_DavidDefeat::
    .string "Pomoc!$"

Route19_Text_DavidPostBattle::
    .string "Asi se na morské POKéMONy\n"
    .string "musí udit.$"

Route19_Text_TonyIntro::
    .string "Dívám se na more, abych\n"
    .string "zapomnel na vsechno spatné.$"

Route19_Text_TonyDefeat::
    .string "Oh!\n"
    .string "Traumatické!$"

Route19_Text_TonyPostBattle::
    .string "Dívám se na more, abych\n"
    .string "zapomnel na to spatné!$"

Route19_Text_AnyaIntro::
    .string "Páni, líbí se mi tvuj jízd!\n"
    .string "Mohu si ho nechat, kdyz vyhraju?$"

Route19_Text_AnyaDefeat::
    .string "Ach! Prohrála jsem!$"

Route19_Text_AnyaPostBattle::
    .string "K SEAFOAM ISLANDS je\n"
    .string "porád daleko…\p"
    .string "Chci zpet do FUCHSIE…$"

Route19_Text_AliceIntro::
    .string "Plavání je super!\n"
    .string "Spáleniny ne!$"

Route19_Text_AliceDefeat::
    .string "Sok!$"

Route19_Text_AlicePostBattle::
    .string "Muj prítel chtel plavat\n"
    .string "k SEAFOAM ISLANDS.$"

Route19_Text_AxleIntro::
    .string "Ahoj!\n"
    .string "Tyto vody jsou zrádné!$"

Route19_Text_AxleDefeat::
    .string "Oh!\n"
    .string "Nebezpecné!$"

Route19_Text_AxlePostBattle::
    .string "M-mé nohy! Mám krece!\n"
    .string "Bubl, bubl…$"

Route19_Text_ConnieIntro::
    .string "Plavala jsem sem s prátely…\n"
    .string "Jsem unavená…$"

Route19_Text_ConnieDefeat::
    .string "Jsem vycerpaná…$"

Route19_Text_ConniePostBattle::
    .string "Kdybych mela jezdit na POKéMONu\n"
    .string "po mori, chtela bych LAPRASe.\p"
    .string "LAPRAS je tak velky, jiste\n"
    .string "by me udrzel suchou.$"

Route19_Text_RouteSign::
    .string "MORSKÁ CESTA 19\n"
    .string "FUCHSIA CITY - SEAFOAM ISLANDS$"

Route19_Text_LiaIntro::
    .string "LIA: Hlídám svého bratra.\n"
    .string "Práve se stal TRÉNÉREM.$"

Route19_Text_LiaDefeat::
    .string "LIA: Tak se nezachází\n"
    .string "s mym malym bratrem!$"

Route19_Text_LiaPostBattle::
    .string "LIA: Más mladsího\n"
    .string "bratra?\p"
    .string "Doufám, ze ho ucís\n"
    .string "vsemu mozné.$"

Route19_Text_LiaNotEnoughMons::
    .string "LIA: Chci bojovat spolecne\n"
    .string "s mym malym bratrem.\p"
    .string "Nemás dva POKéMONy?$"

Route19_Text_LucIntro::
    .string "LUC: Sestra me naucila\n"
    .string "plavat a trénovat POKéMONy.$"

Route19_Text_LucDefeat::
    .string "LUC: Páni!\n"
    .string "Nekdo silnejsí nez sestra!$"

Route19_Text_LucPostBattle::
    .string "LUC: Má sestra je silná a milá.\n"
    .string "Myslím, ze je úzasná!$"

Route19_Text_LucNotEnoughMons::
    .string "LUC: Nechci, kdyz nemohu\n"
    .string "bojovat s tebou se sestrou.\p"
    .string "Nemás dva POKéMONy?$"
