ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto::
    .string "Hej, slysels novinku?\p"
    .string "PC sít zde se ted muze spojit\n"
    .string "s PC v KANTU.\p"
    .string "Nevím, jak se to stalo,\n"
    .string "ale je to fantastické!$"

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands::
    .string "Není mozné SURFovat mezi\n"
    .string "ostrovy v techto místech.\p"
    .string "Príliv je prílis rychly\n"
    .string "a zrádny.$"

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest::
    .string "Pojdme drtit BOBULE!\n"
    .string "…To by bylo plytvání BOBULEMI?\p"
    .string "Vzdy najdes nejaké BOBULE\n"
    .string "na zemi v BERRY FOREST.$"

