CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .string "Není nic, co bych nevedel,\n"
    .string "jak jsem psal na tabuli.\p"
    .string "Vím o svete POKéMONu\n"
    .string "v tvém GAME BOY ADVANCE!\p"
    .string "Sejdi se s kamarády a uzij si\n"
    .string "vymenu POKéMONu!$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "{PLAYER} získal EEVEE!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "ポケモンが　いっぱいだ\n"
    .string "ボックスを　かえて　きなさい$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .string "POKéMON Prednáska\p"
    .string "Hraní s bezdrátovym adaptérem$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "Kterou cást chces císt?$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .string "POKéMON WIRELESS CLUB je\n"
    .string "v patre v kazdém POKéMON CENTRU.\p"
    .string "Navstiv ho a propoj se s kámosi\n"
    .string "pomocí bezdrátového adaptéru.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .string "Pro spojení jen s kámosem jdi\n"
    .string "do DIRECT CORNER.\p"
    .string "Je to pravy pult v POKéMON\n"
    .string "WIRELESS CLUBu.\p"
    .string "Bez s kámosem do TRADE CORNER\n"
    .string "nebo COLOSSEUM.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .string "Pro spojení a komunikaci\n"
    .string "s kymkoli jdi do UNION ROOM.\p"
    .string "Je to levy pult v POKéMON\n"
    .string "WIRELESS CLUBu.\p"
    .string "Jdi do UNION ROOM a uzij si\n"
    .string "setkání s dalsími TRENÉRY.$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "Je to brozura o TM.\p"
    .string "… …\p"
    .string "Celkem je padesát TM.\p"
    .string "Také je sedm HM, které lze\n"
    .string "pouzívat opakovane.\p"
    .string "SILPH CO.$"
