CeruleanCity_House1_Text_AnyInterestInBerries::
    .string "Z BERRY POWDER michám\n"
    .string "rozmanité léky.\p"
    .string "S dobrym BERRY POWDER dokázu\n"
    .string "vyrobit jakykoli lék.\p"
    .string "Tak rekni, zajímají te\n"
    .string "vubec BERRIES?$"

CeruleanCity_House1_Text_HaveJustTheThing::
    .string "Ah, dobre! Pak pro tebe\n"
    .string "mám presne to pravé.$"

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner::
    .string "Ve druhém patre POKéMON CENTER\n"
    .string "je neco nového, v\l"
    .string "DIRECT CORNER.\p"
    .string "Nainstalovali tam Wireless\n"
    .string "Adapter na drcení BERRIES.\p"
    .string "A tady prijdes na radu ty.\p"
    .string "Mám prosbu, kterou mohu\n"
    .string "sverit jen tobe.\p"
    .string "Mohl bys mi na tom stroji\n"
    .string "vyrobit BERRY POWDER?\p"
    .string "Nezapomen, ten stroj je v\n"
    .string "DIRECT CORNER v POKéMON CENTER.\p"
    .string "Pripravím ti lék, kdyz mi\n"
    .string "prineses nejaky BERRY POWDER.\p"
    .string "Nezapomen, rozdrt BERRIES na\n"
    .string "BERRY POWDER a prines mi ho.$"

CeruleanCity_House1_Text_WhyMustYouLieNoBerries::
    .string "Proc mi musís lhát?\p"
    .string "Kolik más BERRIES?\n"
    .string "Ani jednu!$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings::
    .string "Tebe BERRIES nezajímají?\p"
    .string "Mlady príteli, je dulezité\n"
    .string "zajímat se o ruzné veci.$"

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder::
    .string "Ehm! Prinesl jsi mi\n"
    .string "nejaky BERRY POWDER?$"

CeruleanCity_House5_Text_ExchangeWithWhat::
    .string "Za co bys to chtel\n"
    .string "vymenit?$"

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem::
    .string "Dobre, vymenís svuj BERRY\n"
    .string "POWDER za jeden {STR_VAR_1}?$"

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder::
    .string "Hm? Nemás dost\n"
    .string "BERRY POWDER.$"

CeruleanCity_House1_Text_TradeMoreBerryPowder::
    .string "To je vskutku skvely BERRY\n"
    .string "POWDER. Bude z nej vyborny lék.\p"
    .string "Chtel bys vymenit víc BERRY\n"
    .string "POWDER za neco jiného?$"

CeruleanCity_House1_Text_HopeToSeeYouAgain::
    .string "Tak to je v porádku.\n"
    .string "Doufám, ze se zase uvidíme.$"

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder::
    .string "Prijd za mnou, kdybys chtel\n"
    .string "vymenit svuj BERRY POWDER.$"
