SixIsland_GreenPath_Text_JaclynIntro::
    .string "…Co?\p"
    .string "Predstavovala jsem si svuj dum,\n"
    .string "ale TELEPORTUJI sem?$"

SixIsland_GreenPath_Text_JaclynDefeat::
    .string "Velky prussvih!$"

SixIsland_GreenPath_Text_JaclynPostBattle::
    .string "Jsem tak roztrzitá!\p"
    .string "Musím se soustredit, abych\n"
    .string "TELEPORTOVALA správne domu!$"

SixIsland_GreenPath_Text_LeftRouteSign::
    .string "GREEN PATH\n"
    .string "PATTERN BUSH PRED VÁMI$"

SixIsland_GreenPath_Text_RightRouteSign::
    .string "GREEN PATH\n"
    .string "Myslete zelene, prírode pomozme!$"

