VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "Posílám svého PIDGEYE odletet\n"
    .string "dopis do SAFFRONU na sever.$"

VermilionCity_House3_Text_Pidgey::
    .string "PIDGEY: Kurukkoo!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Milá PIPPI,\n"
    .string "doufám, ze te brzy uvidím.\p"
    .string "Slysela jsem, ze SAFFRON má\n"
    .string "potíze s TEAM ROCKET.\p"
    .string "VERMILION se zdá bezpecny.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "Chci si vymenovat MAIL s\n"
    .string "ruznymi lidmi.\p"
    .string "Posílám svého PIDGEYE do UNION\n"
    .string "ROOMU, aby mi MAIL vymenoval.$"

