FiveIsland_LostCave_Room10_Text_SelphyIntro::
    .string "C-co se mnou hodlás\n"
    .string "udelat?$"

FiveIsland_LostCave_Room10_Text_SelphyDefeat::
    .string "Ach… Bála jsem se, ze mi chces\n"
    .string "ublízit.$"

FiveIsland_LostCave_Room10_Text_MayIAskYouToTakeMeHome::
    .string "Jsem tak ráda, ze jsi sem\n"
    .string "prisel.\p"
    .string "Chuze me uz omrzela a\n"
    .string "cítím se unavená.\p"
    .string "Mohl bys me odsud doprovodit\n"
    .string "domu?$"

