SSAnne_Deck_Text_ShipDepartingSoon::
    .string "Veciríek skoncil.\n"
    .string "Lod brzy odplouvá.$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
    .string "Uf!\n"
    .string "Drhnutí paluby je drina!$"

SSAnne_Deck_Text_FeelSeasick::
    .string "Brr… Je mi spatne…\p"
    .string "Mám morskou nemoc, tak jsem\n"
    .string "vysel ven na vzduch…$"

SSAnne_Deck_Text_EdmondIntro::
    .string "Hej, kámo!\p"
    .string "Pojdme si zatancit!$"

SSAnne_Deck_Text_EdmondDefeat::
    .string "Jsi úzasny!$"

SSAnne_Deck_Text_EdmondPostBattle::
    .string "Kolik druhu POKéMONu myslís,\n"
    .string "ze v tomto svete je?$"

SSAnne_Deck_Text_TrevorIntro::
    .string "Ahoj!\n"
    .string "Mas morskou nemoc?$"

SSAnne_Deck_Text_TrevorDefeat::
    .string "Byl jsem neopatrny!$"

SSAnne_Deck_Text_TrevorPostBattle::
    .string "Táta ríkal, ze je 100 druhu\n"
    .string "POKéMONu. Myslím, ze víc.$"
