Route21_North_Text_RonaldIntro::
	.string "Chces vedet, jestli ryby\n"
	.string "berou?$"

Route21_North_Text_RonaldDefeat::
	.string "Sakra!$"

Route21_North_Text_RonaldPostBattle::
	.string "Nemuzu chytit nic dobrého.\n"
	.string "Ani jeden slusny POKéMON!$"

Route21_North_Text_WadeIntro::
	.string "Mám velky úlovek!\n"
	.string "Pustís se do toho?$"

Route21_North_Text_WadeDefeat::
	.string "Hehe, MAGIKARP proste\n"
	.string "neobstojí, vid?$"

Route21_North_Text_WadePostBattle::
	.string "Zdá se, ze chytám jen MAGIKARP!$"

Route21_North_Text_SpencerIntro::
	.string "More mi cistí telo i dusi!$"

Route21_North_Text_SpencerDefeat::
	.string "Ajaj!$"

Route21_North_Text_SpencerPostBattle::
	.string "More je skvelé, ale taky\n"
	.string "mám rád hory.$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
	.string "おれだって　たまには\n"
	.string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
	.string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
	.string "うきやすそう　だと？\n"
	.string "うるせー　おおきな　おせわだッ！$"
