PokemonMansion_1F_Text_TedIntro::
    .string "Kdo jsi?\n"
    .string "Tady nemá nikdo byt.$"

PokemonMansion_1F_Text_TedDefeat::
    .string "Au!$"

PokemonMansion_1F_Text_TedPostBattle::
    .string "Klíc? Nevím, o cem mluvís.$"

PokemonMansion_1F_Text_JohnsonIntro::
    .string "U-u-uaaah! Vydesils me!\n"
    .string "Myslel jsem, ze jsi duch.$"

PokemonMansion_1F_Text_JohnsonDefeat::
    .string "Pche!\n"
    .string "Nemuzu nic vyhrát.$"

PokemonMansion_1F_Text_JohnsonPostBattle::
    .string "Zkoumal jsem to tu sám,\n"
    .string "ale je to tu nahánející.\p"
    .string "Asi uz pujdu.$"
