SixIsland_OutcastIsland_Text_RocketIntro::
    .string "Tady kolem nejsou zádní vzácní\n"
    .string "POKéMONi! Ani jeden!\p"
    .string "To me strasne stve, kámo.\n"
    .string "Vylezu si to na tobe!$"

SixIsland_OutcastIsland_Text_RocketDefeat::
    .string "…Co?$"

SixIsland_OutcastIsland_Text_RocketPostBattle::
    .string "Hele, nevidel jsi nejaké vzácné\n"
    .string "POKéMONy?$"

SixIsland_OutcastIsland_Text_TylorIntro::
    .string "Vubec nemám stestí.\n"
    .string "Souboj by byl prijemná zmena!$"

SixIsland_OutcastIsland_Text_TylorDefeat::
    .string "Ne, zádné stestí…$"

SixIsland_OutcastIsland_Text_TylorPostBattle::
    .string "Nemuzu se dost dobre vrátit\n"
    .string "domu, aniz bych neco chytil.$"

SixIsland_OutcastIsland_Text_MymoIntro::
    .string "Funí… Funí…\p"
    .string "Doplaval jsem sem ze SIX ISLE\n"
    .string "PORT bez prestávky.$"

SixIsland_OutcastIsland_Text_MymoDefeat::
    .string "Funí…\n"
    .string "Funí…$"

SixIsland_OutcastIsland_Text_MymoPostBattle::
    .string "Jsem v pulce cesty…\n"
    .string "Jsem unaveny…$"

SixIsland_OutcastIsland_Text_NicoleIntro::
    .string "Není snadné posílat POKéMONy\n"
    .string "ven, kdyz plaves, vid?$"

SixIsland_OutcastIsland_Text_NicoleDefeat::
    .string "Neprohrála jsem proti tobe\n"
    .string "v plavání. Tohle me netrápí.$"

SixIsland_OutcastIsland_Text_NicolePostBattle::
    .string "Mírís na ostrov za tímhle?\p"
    .string "Nevidela jsem tam nic\n"
    .string "zajímavého.$"

SixIsland_OutcastIsland_Text_AvaIntro::
    .string "AVA: Dáme si morsky zápas\n"
    .string "dva na dva!$"

SixIsland_OutcastIsland_Text_AvaDefeat::
    .string "AVA: Ach, jsi úzasny!\n"
    .string "A jeste lepsí, jsi tu sám!$"

SixIsland_OutcastIsland_Text_AvaPostBattle::
    .string "AVA: Vís, more mám radsi\n"
    .string "nez jakykoliv bazén.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
    .string "AVA: Vyzyvás nás na souboj?\p"
    .string "Budes potrebovat alespon dva\n"
    .string "POKéMONy, jestli to chces.$"

SixIsland_OutcastIsland_Text_GebIntro::
    .string "GEB: Sestricko, pomoc!\n"
    .string "Bojuj se mnou, prosím!$"

SixIsland_OutcastIsland_Text_GebDefeat::
    .string "GEB: Wow, sestricko, ten clovek\n"
    .string "je fakt dobry!$"

SixIsland_OutcastIsland_Text_GebPostBattle::
    .string "GEB: Visím se sestry, protoze\n"
    .string "nedosáhnu na dno.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
    .string "GEB: Prosím, bojuj se mnou\n"
    .string "a mou sestrou!\p"
    .string "…Ach, ty nemás dva POKéMONy?$"
