Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "Typy POKéMONu se navzájem\n"
    .string "ruzne doplnují.\p"
    .string "Kazdy typ je silnejsí proti\n"
    .string "nekterym a slabsí proti jinym.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "NUGGET je úplne k nicemu.\n"
    .string "Tak jsem ho prodal za ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "Slysel jsem, ze v LAVENDER\n"
    .string "TOWN strasí duchové.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "Ó… {PLAYER}!\n"
    .string "Hledal jsem te!\p"
    .string "To jsem já, jeden z vecne\n"
    .string "prítomnych ASISTENTU PROF. OAKA.\p"
    .string "Pokud má tvuj POKéDEX kompletní\n"
    .string "data o dvaceti druzích, mám ti\l"
    .string "dát odmenu od PROF. OAKA.\p"
    .string "Sveril mi tenhle\n"
    .string "EVERSTONE.\p"
    .string "Tak, {PLAYER}, dovol mi otázku.\p"
    .string "Nasbíral jsi data alespon\n"
    .string "o dvaceti druzích POKéMONu?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Skvele! Chytil nebo vlastnil\n"
    .string "jsi {STR_VAR_3} druhu POKéMONu!\p"
    .string "Gratuluji!\n"
    .string "Tu más!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} dostal EVERSTONE\n"
    .string "od ASISTENTA.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "Vyvíjení POKéMONu jiste\n"
    .string "muze rozsírit POKéDEX.\p"
    .string "Nekdy ale nemusís chtít, aby\n"
    .string "se urcity POKéMON vyvinul.\p"
    .string "V tom prípade dej tomu\n"
    .string "POKéMONovi EVERSTONE.\p"
    .string "Podle PROFESORA to zabrání\n"
    .string "vyvoji.$"
