LavenderTown_House1_Text_Cubone::
    .string "CUBONE: Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .string "Ti hrozní ROCKETI!\n"
    .string "Nezaslouzí si zádné slitování!\p"
    .string "Ta ubohá matka CUBONEa…\p"
    .string "Zabili ji pri pokusu o útek\n"
    .string "pred TEAMEM ROCKET.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "Duch POKéMON TOWER je\n"
    .string "pryc!\p"
    .string "Nekdo musel utisit jeho\n"
    .string "nepokojnou dusi!$"

