@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull::
    .string "{PLAYER}{KUN}の　バッグ\n"
    .string "いっぱい　みたい　だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
    .string "Nemyslís, ze je tezké\n"
    .string "vymyslet POKéMONum dobrá jména?\p"
    .string "Hlavne kdyz jich chytís\n"
    .string "celou hromadu?\p"
    .string "V LAVENDER TOWN je muz, ktery\n"
    .string "hodnotí prezdívky POKéMONu.\p"
    .string "Dokonce ti muze pomoct\n"
    .string "POKéMONa prejmenovat.$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
    .string "Pokud mírís do LAVENDER\n"
    .string "TOWN, jdi pres ROCK TUNNEL.\p"
    .string "Do ROCK TUNNEL se dostanes\n"
    .string "z CERULEAN CITY.$"
