PokemonMansion_Text_PressSecretSwitch::
    .string "Tajny spínac!\p"
    .string "Zmácknout?$"

PokemonMansion_Text_WhoWouldnt::
    .string "Kdo by ne?$"

PokemonMansion_Text_NotQuiteYet::
    .string "Jeste ne!$"

PokemonMansion_1F_Text_ArnieIntro::
    .string "Nemuzu ven!\n"
    .string "Tahle stará bouda je hlavolam.$"

PokemonMansion_1F_Text_ArnieDefeat::
    .string "Ach ne!\n"
    .string "Muj pytel lupu!$"

PokemonMansion_1F_Text_ArniePostBattle::
    .string "Spínace tady strídave otevírají\n"
    .string "a zavírají dvojice dverí.$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
    .string "Deník: 5. cervence\n"
    .string "Guyana, Jizní Amerika\p"
    .string "Hluboko v dzungli byl objeven\n"
    .string "novy POKéMON.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .string "Deník: 10. cervence\n"
    .string "Pokrtili jsme nove objeveného\l"
    .string "POKéMONa MEW.$"
