SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire::
    .string "{PLAYER} nasel SAPHIR!$"

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou::
    .string "Fufu… Fufufufu…\n"
    .string "Tipoval jsem správne.\p"
    .string "Mel jsem pravdu, ze te\n"
    .string "sleduji!$"

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword::
    .string "Vedel jsem, ze tu je SAPHIR,\n"
    .string "takze patrí mne!\p"
    .string "Prodám ho TEAM ROCKET za\n"
    .string "vázné peníze.\p"
    .string "…N-nedívej se na me tak!\p"
    .string "Pokud ho chces zpátky, co\n"
    .string "kdyby sis pro nej sel az ho\l"
    .string "prodám?\p"
    .string "Dokonce ti reknu jedno z\n"
    .string "hesel do SKLADU TEAM ROCKET.\p"
    .string "Heslo, které znám, zní\n"
    .string "“Yes, nah, CHANSEY.”\p"
    .string "Jsem hotovy.\n"
    .string "Nemysli si o mne nic spatného!$"

