SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections::
    .string "Na tomto ostrove se dejí\n"
    .string "ruzné veci v závislosti na\l"
    .string "spojeních.\p"
    .string "Co jsou ta spojení?\p"
    .string "To uz si musís zjistit sám.$"

SevenIsland_PokemonCenter_1F_Text_DidYouRideSeagallopHere::
    .string "Prijel jsi sem SEAGALLOPem?\p"
    .string "Je tu nejméne deset techto\n"
    .string "rychlolodí.\p"
    .string "Nevím vsak, kam vsude jezdí.$"

SevenIsland_PokemonCenter_1F_Text_CheckOutTrainerTower::
    .string "Kdyz si verís, mel by ses\n"
    .string "podívat na TRAINER TOWER.$"

