Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: Hej! {PLAYER}!\p"
	.string "Ty mírís do POKéMON LEAGUE?\n"
	.string "Na to zapomen!\p"
	.string "Asi nemás zádné\n"
	.string "BADGES, vid?\p"
	.string "Stráz te bez nich\n"
	.string "nepustí dál.\p"
	.string "Mimochodem, zesílili\n"
	.string "tvoji POKéMON?$"

Route22_Text_EarlyRivalDefeat::
	.string "Och!\n"
	.string "Mels jen kliku!$"

Route22_Text_EarlyRivalPostBattle::
	.string "Slysel jsem, ze POKéMON LEAGUE\n"
	.string "se hemzí drsnymi TRENÉRY.\p"
	.string "Musím prijít na to, jak\n"
	.string "je porazit.\p"
	.string "Mel by ses prestat loudat\n"
	.string "a hnout sebou!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro::
	.string "{RIVAL}: Coze? {PLAYER}!\n"
	.string "To je prekvapení, ze te tu vidím!\p"
	.string "Tak ty mírís do POKéMON\n"
	.string "LEAGUE?\p"
	.string "Posbíral jsi vsechny BADGES?\n"
	.string "To je super!\p"
	.string "Pak te zmáknu, {PLAYER}, jako\n"
	.string "rozcvicku pred POKéMON LEAGUE!\p"
	.string "Pojd na to!$"

Route22_Text_LateRivalDefeat::
	.string "Coze!?\p"
	.string "Jen jsem byl neopatrny, ty!$"

Route22_Text_LateRivalPostBattle::
	.string "To me rozhybalo.\n"
	.string "Jsem pripraven na POKéMON LEAGUE!\p"
	.string "{PLAYER}, ty potrebujes víc cviku.\p"
	.string "Ale hej, to vís sám!\n"
	.string "Já mizím. Mej se!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign::
	.string "POKéMON LEAGUE\n"
	.string "Hlavní brána$"
