SSAnne_B1F_Room4_Text_LeonardIntro::
    .string "Vís, co se ríká o námornících\n"
    .string "a souboji!$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
    .string "Tak jo!\n"
    .string "Dobry souboj, kámo!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
    .string "Hahaha!\n"
    .string "Chces byt námorník, kámo?$"

SSAnne_B1F_Room4_Text_DuncanIntro::
    .string "Tak pojd!\n"
    .string "Má námornická pycha je v sázce!$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
    .string "Tvuj duch me potopil!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
    .string "Videls GURU RYBÁRENÍ ve\n"
    .string "VERMILION CITY?$"
