CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
    .string "Prisel jsem navstívit CINNABAR\n"
    .string "GYM, ale dvere jsou zamcené.\p"
    .string "Nekde k nim musí byt\n"
    .string "klíc.\p"
    .string "Nemohl by byt v té\n"
    .string "vyhorelé vile?\p"
    .string "Ríká se, ze tam zil kamarád\n"
    .string "VÚDCE GYMu.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
    .string "Mas hodne prátel?\p"
    .string "Spojení s obvyklymi kamarády\n"
    .string "je samozrejme zábava.\p"
    .string "Ale co kdyby ses obcas\n"
    .string "podíval do UNION ROOM?\p"
    .string "Kdo ví, mozná získás\n"
    .string "nové prátele.\p"
    .string "Myslím, ze by stálo za to\n"
    .string "prozkoumat UNION ROOM.$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
    .string "POKéMONi se mohou ucit techniky\n"
    .string "i po zrusení evoluce.\p"
    .string "Evoluce muze pockat, dokud\n"
    .string "se nenaucí nové útoky.$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland::
    .string "BILL: Hej, nechals me cekat!\n"
    .string "Pripraven plout na ONE ISLAND?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet::
    .string "Aha, jeste nejsi hotov?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo::
    .string "Dobre, tak to bychom meli.\n"
    .string "Jdeme!$"

