CeruleanCity_BikeShop_Text_WelcomeToBikeShop::
    .string "Cau!\n"
    .string "Vítej v nasem BIKE SHOPu.\p"
    .string "Máme tu KOLO presne pro\n"
    .string "tebe!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt::
    .string "Promin!\n"
    .string "Na to nemás!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo::
    .string "Ó, to je…\p"
    .string "BIKE VOUCHER!\p"
    .string "Tak jo!\n"
    .string "Tady to mas!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle::
    .string "{PLAYER} vymenil\n"
    .string "BIKE VOUCHER za BICYKL.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain::
    .string "Dekuji!\n"
    .string "Prijdte zase nekdy!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle::
    .string "Jak se ti líbí tvuj novy BICYKL?\n"
    .string "Jak se na nem jezdí?\p"
    .string "Muzes na nej vyrazit na CYKLO\n"
    .string "STEZKU i do jeskyní!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle::
    .string "Udelej si místo na svuj\n"
    .string "BICYKL!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
    .string "Mne stací obycejné mestské kolo.\p"
    .string "Konec koncu, na horské kolo\n"
    .string "kos na nákup neprídelás.$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive::
    .string "Tahle kola jsou super, ale jsou\n"
    .string "strasne drahá!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool::
    .string "Páni.\n"
    .string "Tvuj BICYKL je fakt super!$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket::
    .string "ついに　はつばい！\p"
    .string "ドイツ　せい　さいこうきゅう\n"
    .string "おりたたみ　じてんしゃ！$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle::
    .string "Zbrusu novy BICYKL!$"

