Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "Cau! Jsem POKéMON…\n"
    .string "…Ne, nejsem!\p"
    .string "Ríkej mi BILL!\n"
    .string "Jsem skalní POKéMANIAK!\p"
    .string "Hej!\n"
    .string "Co je to za skepticky pohled?\p"
    .string "Nedelám si srandu, kámo.\p"
    .string "Zkazil jsem pokus a sloucil\n"
    .string "se s POKéMONem!\p"
    .string "Tak co?\n"
    .string "Pomuzes mi!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "Cau! Jsem POKéMON…\n"
    .string "…Ne, nejsem!\p"
    .string "Ríkej mi BILL!\n"
    .string "Jsem skalní POKéMANIAK!\p"
    .string "Hej!\n"
    .string "Co je to za skepticky pohled?\p"
    .string "Nedelám si srandu, slecno.\p"
    .string "Zkazil jsem pokus a sloucil\n"
    .string "se s POKéMONem!\p"
    .string "Tak co?\n"
    .string "Pomuzes mi!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "Pockej, az budu uvnitr\n"
    .string "TELEPORTERU.\p"
    .string "Az tam budu, jdi k mému PC a\n"
    .string "spust Cell Separation System.$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "Ne!?\n"
    .string "No tak nebud takovy chladny!\p"
    .string "No tak, musís pomoct chlápkovi\n"
    .string "v pekném, pekném maléru!\p"
    .string "Co ríkás, séfe?\n"
    .string "Prosím?\l"
    .string "Dobre?\l"
    .string "Tak jo!$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "Ne!?\n"
    .string "No tak nebud takovy chladná!\p"
    .string "No tak, musís pomoct chlápkovi\n"
    .string "v pekném, pekném maléru!\p"
    .string "Co ríkás, krásko?\n"
    .string "Prosím?\l"
    .string "Dobre?\l"
    .string "Tak jo!$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "BILL: Jupí!\n"
    .string "Díky, kámo! Dluzím ti!\p"
    .string "Tak, prisel ses podívat na\n"
    .string "mou sbírku POKéMONu?\p"
    .string "Ne?\n"
    .string "To je skoda.\p"
    .string "Musím ti podekovat…\n"
    .string "Ó, tu más, mozná tohle pujde.$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "BILL: Jupí!\n"
    .string "Díky, slecno! Dluzím ti!\p"
    .string "Tak, prisla ses podívat na\n"
    .string "mou sbírku POKéMONu?\p"
    .string "Ne?\n"
    .string "To je skoda.\p"
    .string "Musím ti podekovat…\n"
    .string "Ó, tu más, mozná tohle pujde.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "{PLAYER} dostal S.S. TICKET\n"
    .string "od BILLA.$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "Más toho moc!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "Ta vyletní lod S.S. ANNE je\n"
    .string "ve VERMILION CITY.\p"
    .string "Pry je na palube taky\n"
    .string "spousta TRENÉRU.\p"
    .string "Pozvali me na svou párty, ale\n"
    .string "nóbl akce nesnásím.\p"
    .string "Proc nejdes místo me?\n"
    .string "Jdi a uzij si to.$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "BILL: Chces si prohlédnout\n"
    .string "mé vzácné POKéMONy na PC?\p"
    .string "Pojd, mrkni na mé PC.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "Na monitoru PC se zobrazuje\n"
    .string "TELEPORTER.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "{PLAYER} spustil Cell\n"
    .string "Separator TELEPORTERU.$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "BILLuv seznam oblíbenych POKéMONu!$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "Kterého POKéMONa chces videt?$"
