FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "Prezdíváme SPRÁVCI\n"
    .string "“SLOWPOKE.”\p"
    .string "Vís, má ten prázdny pohled\n"
    .string "jako SLOWPOKE.$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .string "SPRÁVCE SLOWPOKE má velké\n"
    .string "znalosti o POKéMONech.\p"
    .string "Má i fosílie vzácnych,\n"
    .string "vyhynulych POKéMONu.$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "SPRÁVCE SLOWPOKE prisel,\n"
    .string "ale nerozumel jsem mu.\p"
    .string "Asi má problém s recí!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "SPRÁVCE SLOWPOKE má ted\n"
    .string "propagacní kampan.\p"
    .string "Zkus se dostat do nejvzdálenejsího\n"
    .string "kouta SAFARI ZONE.\p"
    .string "Kdyz to dokázes, vyhrajes\n"
    .string "velmi uzitecnou cenu.$"

