CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
    .string "EEVEE se muze vyvinout v jednoho\n"
    .string "ze trí druhu POKéMONu.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .string "Je tu emailová zpráva.\p"
    .string "… … …\p"
    .string "Existují tri legendární ptací\n"
    .string "POKéMONi.\p"
    .string "Jsou to ARTICUNO, ZAPDOS\n"
    .string "a MOLTRES.\p"
    .string "Místo jejich pobytu je neznámé.\p"
    .string "Plánujeme prozkoumat jeskyni\n"
    .string "blízko CERULEANu.\p"
    .string "Od: POKéMON VYZKUMNY TYM…$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .string "Jantarová dymka!$"

