Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
    .string "Ahoj! Pamatujes si me?\n"
    .string "Jsem jeden z ASISTENTU PROF. OAKa.\p"
    .string "Pokud má tvuj POKéDEX kompletní\n"
    .string "data o {STR_VAR_1} druzích, mám ti\l"
    .string "dát odmenu.\p"
    .string "PROF. OAK mi sveril {STR_VAR_2}\n"
    .string "pro tebe.\p"
    .string "Tak, {PLAYER}, zeptám se te.\p"
    .string "Mas data alespon o {STR_VAR_1}\n"
    .string "druzích POKéMONu?$"

Route15_WestEntrance_2F_Text_GreatHereYouGo::
    .string "Skvele! Chytils nebo vlastnils\n"
    .string "{STR_VAR_3} druhu POKéMONu!\p"
    .string "Gratuluji!\n"
    .string "Tady mas!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
    .string "{PLAYER} dostal {STR_VAR_2}\n"
    .string "od ASISTENTA.$"

Route15_WestEntrance_2F_Text_ExplainExpShare::
    .string "EXP. SHARE je predmet, ktery\n"
    .string "drzí POKéMON.\p"
    .string "Ten POKéMON dostane podíl\n"
    .string "z EXP bodu, aniz by musel\l"
    .string "bojovat.$"

Route15_WestEntrance_2F_Text_LargeShiningBird::
    .string "Podíváme se, co ukazují\n"
    .string "dalekohledy…\p"
    .string "Veliky zárící pták letí\n"
    .string "smerem k mori.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
    .string "Podíváme se, co ukazují\n"
    .string "dalekohledy…\p"
    .string "Vypadá to na maly ostruvek\n"
    .string "na obzoru!$"

