Route12_FishingHouse_Text_DoYouLikeToFish::
    .string "Jsem mladsí bratr\n"
    .string "FISHING GURU.\p"
    .string "Proste miiiluju rybarení!\n"
    .string "Nesnesu byt bez nej.\p"
    .string "Rekni, más rád rybarení?$"

Route12_FishingHouse_Text_TakeThisAndFish::
    .string "Bájecné! Líbí se mi tvuj styl.\n"
    .string "Myslím, ze muzeme byt prátelé.\p"
    .string "Vezmi si tohle a rybar, kamaráde!$"

Route12_FishingHouse_Text_ReceivedSuperRod::
    .string "{PLAYER} dostal SUPER ROD od\n"
    .string "bratra FISHING GURU.$"

Route12_FishingHouse_Text_IfYouCatchBigMagikarpShowMe::
    .string "Rybarení je zpusob zivota!\n"
    .string "Je jako nejlepsí poezie.\p"
    .string "Od morí po reky, vyraz ven\n"
    .string "a ulos toho velkého, príteli.\p"
    .string "A ted mám prosbu.\p"
    .string "Kdyz tím ROD chytís velkého\n"
    .string "MAGIKARPa, chci ho videt.\p"
    .string "Stejne jako miluju rybarení,\n"
    .string "miluju i pohled na obrí MAGIKARP.$"

Route12_FishingHouse_Text_OhThatsDisappointing::
    .string "Ó…\n"
    .string "To je tak zklamání…$"

Route12_FishingHouse_Text_TryFishingBringMeMagikarp::
    .string "Ahoj, {PLAYER}!\n"
    .string "Byl jsi rybarit?\p"
    .string "Zkus rybarit se SUPER ROD\n"
    .string "v jakékoli vode.\p"
    .string "V ruznych místech najdes\n"
    .string "ruzné POKéMONy.\p"
    .string "A nezapomen mi prinést\n"
    .string "obrího MAGIKARPa.$"

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee::
    .string "Ó? {PLAYER}?\n"
    .string "Ale to je prece MAGIKARP!\p"
    .string "Dovol mi ho videt, rychle!$"

Route12_FishingHouse_Text_WhoaXInchesTakeThis::
    .string "… … …Páni!\n"
    .string "{STR_VAR_2} palcu!\p"
    .string "Más vzácny cit pro jemné,\n"
    .string "poetické stránky rybarení!\p"
    .string "Tohle si musís vzít.\n"
    .string "Trvám na tom!$"

Route12_FishingHouse_Text_LookForwardToGreaterRecords::
    .string "Tesím se na jeste vetsí\n"
    .string "rekordy od tebe!$"

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast::
    .string "He?\n"
    .string "{STR_VAR_2} palcu?\p"
    .string "Tohle je stejne velké jako ten,\n"
    .string "co jsem videl predtím.$"

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp::
    .string "Hmm…\n"
    .string "Tenhle merí {STR_VAR_2} palcu.\p"
    .string "Nesahá tomu {STR_VAR_3}palcovému,\n"
    .string "co jsi prinesl predtím.$"

Route12_FishingHouse_Text_DoesntLookLikeMagikarp::
    .string "Eh… Tohle moc nevypadá\n"
    .string "jako MAGIKARP.$"

Route12_FishingHouse_Text_NoRoomForGift::
    .string "Ó ne!\p"
    .string "Mel jsem pro tebe dárek, ale\n"
    .string "nemás na nej místo.$"

Route12_FishingHouse_Text_MostGiganticMagikarpXInches::
    .string "Nejvetsí MAGIKARP, jakého\n"
    .string "jsem kdy spatril…\p"
    .string "{STR_VAR_3} palcu!$"

Route12_FishingHouse_Text_BlankChartOfSomeSort::
    .string "Je to nejaká prázdná tabulka.\p"
    .string "Má místa pro zapisování\n"
    .string "nejakych záznamu.$"
