PewterCity_Museum_1F_Text_Its50YForChildsTicket::
    .string "Ano, ano.\n"
    .string "Detsky lístek stojí ¥50.\p"
    .string "Chces jít dál?$"

PewterCity_Museum_1F_Text_ComeAgain::
    .string "Prijd zas!$"

PewterCity_Museum_1F_Text_Right50YThankYou::
    .string "Tak, ¥50!\n"
    .string "Dekuji!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
    .string "Nemás dost penez.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
    .string "Uzij si to, prosím.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs::
    .string "Nemuzes se proplízit zadem!\n"
    .string "Pekny pokus, ale ne.\p"
    .string "No, mas to mít!\n"
    .string "Vís, co je AMBER?$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter::
    .string "AMBER obsahuje geneticky\n"
    .string "materiál starych POKéMONu.\p"
    .string "Nekde existuje LABORATOR, která\n"
    .string "se snazí z AMBERu krísit POKéMONy.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap::
    .string "AMBER je vlastne míza, ta\n"
    .string "lepivá hmota tekoucí ze stromu.\p"
    .string "Stará míza casem zkamenela\n"
    .string "v tvrdy AMBER.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround::
    .string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
    .string "Mel bych byt vdecny za svuj\n"
    .string "dlouhy zivot.\p"
    .string "Nikdy jsem necekal, ze uvidím\n"
    .string "kosti draka!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
    .string "Pst! Poslouchej, musím se\n"
    .string "s nekym podelit o tajemství.\p"
    .string "Myslím, ze tento kus AMBERu\n"
    .string "obsahuje POKéMON DNA!\p"
    .string "Byl by to ohromující vedecky\n"
    .string "objev, kdyby z nej slo POKéMONy\l"
    .string "vzkrísit.\p"
    .string "Ale mí kolegové me ignorují.\p"
    .string "Mám tedy prosbu!\p"
    .string "Chci, aby ho prozkoumali v nejaké\n"
    .string "POKéMON LABORATORI.$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan::
    .string "{PLAYER} dostal OLD AMBER\n"
    .string "od toho muze.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked::
    .string "Pst!\n"
    .string "Necht prozkoumají OLD AMBER!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
    .string "Na to nemás místo.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
    .string "Vystavujeme dve fosilie vzácnych\n"
    .string "prehistorickych POKéMONu.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
    .string "Je to krásny kus AMBERu\n"
    .string "v cisté zlaté barve.$"

PewterCity_Museum_1F_Text_AerodactylFossil::
    .string "Fosilie AERODACTYLa\n"
    .string "Praveky a vzácny POKéMON.$"

PewterCity_Museum_1F_Text_KabutopsFossil::
    .string "Fosilie KABUTOPSe\n"
    .string "Praveky a vzácny POKéMON.$"

