PokemonMansion_Text_PressSecretSwitchJP::
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt::
    .string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
    .string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro::
    .string "Tohle místo je proste obrí!$"

PokemonMansion_1F_Text_SimonDefeat::
    .string "Ajaj!$"

PokemonMansion_1F_Text_SimonPostBattle::
    .string "Kam asi sel muj parták.$"

PokemonMansion_1F_Text_BraydonIntro::
    .string "Muj mentor tu kdysi bydlel.$"

PokemonMansion_1F_Text_BraydonDefeat::
    .string "Uf!\n"
    .string "Drtive!$"

PokemonMansion_1F_Text_BraydonPostBattle::
    .string "Takze jsi v koncích?\n"
    .string "Skoc tam dolu!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
    .string "Deník: 6. února\n"
    .string "MEW porodil.\p"
    .string "Pojmenovali jsme novorozence MEWTWO.$"
