Route16_House_Text_FoundMySecretRetreat::
    .string "Ach jo.\n"
    .string "Nasels muj tajny úkryt.\p"
    .string "Prosím, nikomu nerikej, ze jsem\n"
    .string "tady. Vynahradím ti to tímto!$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "{PLAYER} dostal HM02\n"
    .string "od dívky.$"

Route16_House_Text_ExplainHM02::
    .string "HM02 je FLY.\n"
    .string "Je to úzasne uzitecny útok.\p"
    .string "Prosím, dobre ho vyuzij.$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "Nemas na to misto.$"

Route16_House_Text_Fearow::
    .string "FEAROW: Kjuín!$"

