FiveIsland_WaterLabyrinth_Text_LetMeTakeLookAtMons::
    .string "Cestujes po celém svete,\n"
    .string "vid?\p"
    .string "Nehonís své POKéMONy prílis\n"
    .string "tvrde, ze ne?\p"
    .string "Nech me se na ne podívat.\n"
    .string "… … …   … … …$"

FiveIsland_WaterLabyrinth_Text_HmmISeeIsee::
    .string "Ach, hmm…\n"
    .string "Vidím, vidím…$"

FiveIsland_WaterLabyrinth_Text_TreatMonRightHaveThis::
    .string "Ach, úctyhodné.\n"
    .string "Zachází se svymi POKéMONy dobre.\p"
    .string "Myslím, ze ti tohle muzu\n"
    .string "sveric.\p"
    .string "Chtel bych ti to dát.$"

FiveIsland_WaterLabyrinth_Text_ReceivedEggFromMan::
    .string "{PLAYER} dostal VEJCE\n"
    .string "od muze!$"

FiveIsland_WaterLabyrinth_Text_DontHaveSpaceInYourParty::
    .string "…Bohuzel, nemás místo\n"
    .string "ve svém tymu.\p"
    .string "Radeji si pro to prijdes\n"
    .string "nekdy jindy.$"

@ Unused
FiveIsland_WaterLabyrinth_Text_YouveComeBackForTheEgg::
    .string "やあ\n"
    .string "タマゴを　もらいに\l"
    .string "きて　くれたんだね$"

FiveIsland_WaterLabyrinth_Text_GladIMetSomeoneLikeYou::
    .string "To VEJCE jsem dostal, kdyz\n"
    .string "jsem cestoval.\p"
    .string "Jsem rád, ze jsem potkal\n"
    .string "nekoho jako ty.$"

FiveIsland_WaterLabyrinth_Text_CuteMonRemindsMeOfDaisy::
    .string "Ach, ahoj.\n"
    .string "To je roztomily {STR_VAR_2}.\p"
    .string "Vidím ho a pripomíná mi\n"
    .string "milou holcicku, kterou jsem\l"
    .string "potkal na cestách.\p"
    .string "Jemne hladila POKéMONy…\n"
    .string "Byla to mála andílek.\p"
    .string "Jméno té holcicky…\n"
    .string "Myslím, ze to byla DAISY.$"

FiveIsland_WaterLabyrinth_Text_AlizeIntro::
    .string "Tohle je vyborné prostredí\n"
    .string "pro chov POKéMONu.$"

FiveIsland_WaterLabyrinth_Text_AlizeDefeat::
    .string "Tví POKéMONi krásne\n"
    .string "rostou!$"

FiveIsland_WaterLabyrinth_Text_AlizePostBattle::
    .string "Vís, myslím, ze mas talent\n"
    .string "stát se dobrym CHOVATELEM.$"
