FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
    .string "Vítej v SAFARI ZONE!$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
    .string "Za pouhych ¥500 si muzes\n"
    .string "zahrát SAFARI HRU.\p"
    .string "Muzes se toulat sirou safari\n"
    .string "a chytat, co se ti líbí.\p"
    .string "Chces si zahrát?$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
    .string "To bude ¥500, prosím!\p"
    .string "Pouzíváme tu jen speciální\n"
    .string "POKé BALLs.$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
    .string "{PLAYER} dostal 30 SAFARI BALLu\n"
    .string "od obsluhy.$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
    .string "Zavoláme te pres PA, az\n"
    .string "dojdou cas nebo SAFARI BALLs.\p"
    .string "Tak, hodne stestí\n"
    .string "ti preji!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
    .string "Dobre.\n"
    .string "Prosím prijdte zas!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
    .string "Ouvej!\n"
    .string "Málo penez!$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
    .string "Chces opustit SAFARI ZONE\n"
    .string "drív?$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
    .string "Prosím vrat vsechny SAFARI\n"
    .string "BALLs, které ti zbyly.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
    .string "Hodne stestí!$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
    .string "Chytils svuj podíl?\n"
    .string "Prijd zas!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
    .string "Ahoj! Jsi tu poprvé\n"
    .string "v SAFARI ZONE?$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
    .string "SAFARI ZONE má vlastne\n"
    .string "ctyri zóny.\p"
    .string "Kazdá má jiné druhy\n"
    .string "POKéMONu, i vzácné.\p"
    .string "Pouzij dodané SAFARI BALLs\n"
    .string "k jejich chytání.\p"
    .string "Muzes hodit i NÁVNADU nebo\n"
    .string "KAMENY, ne jen SAFARI BALLs.\p"
    .string "S NÁVNADOU má POKéMON mensí\n"
    .string "sanci utéci, ale tez ho\l"
    .string "chytís.\p"
    .string "S KAMENY má POKéMON vetsí\n"
    .string "sanci utéci, ale snáz ho\l"
    .string "chytís.\p"
    .string "Kdyz dojde cas ci SAFARI\n"
    .string "BALLs, je pro tebe konec hry!$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
    .string "Promin, jsi tu stály host!$"

