CeladonCity_Text_GotMyKoffingInCinnabar::
    .string "KOFFINGa jsem získal v CINNABARu.\p"
    .string "Obvykle je hodny, ale kdyz ho\n"
    .string "naserou, dycha jed.$"

CeladonCity_Text_GymIsGreatFullOfWomen::
    .string "Heheh! Ten GYM je super!\n"
    .string "Je plnej zen!$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
    .string "CELADON se pysní snahou\n"
    .string "udrzet mesto krásné.\p"
    .string "Proto novy GAME CORNER\n"
    .string "kazí povest mesta.$"

CeladonCity_Text_BlewItAllAtSlots::
    .string "Au…\n"
    .string "Profrcal jsem vsechno na automatech!\p"
    .string "Mel jsem MINCE vymenit\n"
    .string "za ceny!$"

CeladonCity_Text_MyTrustedPalPoliwrath::
    .string "Tohle je muj kamarád POLIWRATH.\p"
    .string "Vyvinul se z POLIWHIRLa,\n"
    .string "kdyz jsem pouzil WATER STONE.$"

CeladonCity_Text_Poliwrath::
    .string "POLIWRATH: Ribi ribit!$"

CeladonCity_Text_GetLostOrIllPunchYou::
    .string "Na co civís?\n"
    .string "Zmiz, nebo ti dam pesti.$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
    .string "Nepleteme se TEAM ROCKET do cesty!$"

CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "TIPY PRO TRÉNÉRY\p"
    .string "X ACCURACY zvysuje presnost\n"
    .string "útoku.\p"
    .string "DIRE HIT zvysuje sanci\n"
    .string "na kriticky zásah.\p"
    .string "Predmety serzes v CELADON\n"
    .string "DEPT. STORE!$"

CeladonCity_Text_CitySign::
    .string "CELADON CITY\n"
    .string "Mesto duhovych snu$"

CeladonCity_Text_GymSign::
    .string "CELADON CITY POKéMON GYM\n"
    .string "VÚDCE: ERIKA\l"
    .string "Princezna milující prírodu!$"

CeladonCity_Text_MansionSign::
    .string "CELADON MANSION$"

CeladonCity_Text_DeptStoreSign::
    .string "Najdes, co potrebujes, v\n"
    .string "CELADON DEPT. STORE!$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "TIPY PRO TRÉNÉRY\p"
    .string "GUARD SPEC. chrání POKéMONa\n"
    .string "pred útoky, co snizují staty\l"
    .string "behem souboje.\p"
    .string "Predmety serzes v\n"
    .string "CELADON DEPT. STORE!$"

CeladonCity_Text_PrizeExchangeSign::
    .string "MINCE menime za ceny!\n"
    .string "VYMENA CEN$"

CeladonCity_Text_GameCornerSign::
    .string "ROCKET GAME CORNER\n"
    .string "Hriste pro dospelé!$"

CeladonCity_Text_ScaldedTongueOnTea::
    .string "Aaaá, au…\n"
    .string "Spálil jsem si jazyk!\p"
    .string "Ta milá pani v MANSIONu mi\n"
    .string "dala CAJ.\p"
    .string "Jenze byl vrelej!\n"
    .string "Musí vychladnout.$"

Text_SoftboiledTeach::
    .string "Vítej!\p"
    .string "Vidávala jsem te tu, ale nikdy\n"
    .string "jsem si nestihla pokecat.\p"
    .string "To musí byt stestí, ze nás to\n"
    .string "konecne svedlo dohromady.\p"
    .string "Ráda bych to oslavila tím,\n"
    .string "ze te naucím útok SOFTBOILED.$"

Text_SoftboiledDeclined::
    .string "Budu mít na tebe pozor.\p"
    .string "Doufám, ze si zase popovídáme.$"

Text_SoftboiledWhichMon::
    .string "Tak ktery POKéMON dostane sanci\n"
    .string "naucit se SOFTBOILED?$"

Text_SoftboiledTaught::
    .string "Preji ti hodne stestí!$"

CeladonCity_Text_SomeoneStoleSilphScope::
    .string "Ach, co mám delat…\p"
    .string "Nekdo nám ukradl SILPH SCOPE.\p"
    .string "Zlodej utíkal tímhle smerem,\n"
    .string "to vím urcite.\p"
    .string "Ale ztratila jsem ho z dohledu!\n"
    .string "Kam zmizel?$"

