SSAnne_2F_Room4_Text_LamarIntro::
    .string "Co povazujes za hodnotnejsí,\n"
    .string "silného nebo vzácného POKéMONa?$"

SSAnne_2F_Room4_Text_LamarDefeat::
    .string "Musím ti vzdát hold!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
    .string "Osobne mám rád silné a vzácné\n"
    .string "POKéMONy.$"

SSAnne_2F_Room4_Text_DawnIntro::
    .string "Snad jsem te na párty\n"
    .string "nevidela?$"

SSAnne_2F_Room4_Text_DawnDefeat::
    .string "Klid!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
    .string "Tvoji silní POKéMONi jsou\n"
    .string "skvelí! Závidím ti je!$"
