SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered::
    .string "Má dcera je tak sobecká.\n"
    .string "Má jen pár prátel.$"

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople::
    .string "Má dcera ráda napodobuje lidi.\n"
    .string "Je to pekne otravné.\p"
    .string "Díky jejímu napodobování jí tu\n"
    .string "ríkají COPYCAT.$"

SaffronCity_CopycatsHouse_1F_Text_Chansey::
    .string "CHANSEY: Chaan! Sii!$"

