RocketHideout_B1F_Text_Grunt1Intro::
    .string "Kdo jsi?\n"
    .string "Jak ses sem dostal?$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "Au!\n"
    .string "Poraz!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "K certu… Ty pomlouvás TEAM\n"
    .string "ROCKET, ze?$"

RocketHideout_B1F_Text_Grunt2Intro::
    .string "Vnikl jsi do operace TEAM\n"
    .string "ROCKET? To je drzost!$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "Bum!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "S tímhle ti to neprojde,\n"
    .string "spunte!$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "Poplach! Vetrelec!$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "Nedokázu to!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
    .string "SILPH SCOPE? Hmf!\n"
    .string "Nevím, kde je.$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "Proc jsi sem prisel?$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "Tohle se nedá!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "Dobre, povím to…\n"
    .string "Bez vytahem za mym BOSSEM.$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "Ztratil ses, mala mysko?$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "Proc…?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "Ouha, ten rozruch nejak\n"
    .string "otevrel dvere!$"
