TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "Jsem POKéMON MOVE MANIAK.\p"
    .string "Znám kazdy útok, ktery se\n"
    .string "POKéMONi naucí pri rustu.\p"
    .string "Také jsem hribkovy maniak.\p"
    .string "Prines mi dva TINYMUSHROOMy\n"
    .string "nebo jeden BIG MUSHROOM.\p"
    .string "Pokud to udelás, naucím útok\n"
    .string "jednomu POKéMONovi.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Cuc, cuc…\n"
    .string "Hm! Voní ti to HRIBY!\p"
    .string "Chces, abych naucil útok\n"
    .string "nekterého z tvych POKéMONu?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "Ktery POKéMON potrebuje tutora?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "Ktery útok mám naucit?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Promin…\p"
    .string "Vypadá to, ze nemám útok,\n"
    .string "ktery bych mohl naucit\l"
    .string "tomu POKéMONovi.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "Pak budu potrebovat HRIB nebo dva.\n"
    .string "Co mi dás?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} predal dva\n"
    .string "TINYMUSHROOMy vymenou.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} predal jeden\n"
    .string "BIG MUSHROOM vymenou.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "Pokud se tvuj POKéMON má naucit\n"
    .string "útok, potrebuji HRIB nebo dva.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "Coze? Není ani jediny útok,\n"
    .string "ktery bych mohl naucit VEJCE.$"

