Route20_Text_BarryIntro::
    .string "Voda je tu melká.\n"
    .string "Hodne lidí tu plave.$"

Route20_Text_BarryDefeat::
    .string "Slup!$"

Route20_Text_BarryPostBattle::
    .string "Kéz bych mohl jet na POKéMONu.\n"
    .string "Ty nejsi unaveny.$"

Route20_Text_ShirleyIntro::
    .string "SEAFOAM je tichy úkryt.\n"
    .string "Mám tu dovolenou.$"

Route20_Text_ShirleyDefeat::
    .string "Prestan!$"

Route20_Text_ShirleyPostBattle::
    .string "Pod tímto ostrovem je\n"
    .string "obrovská jeskyne.$"

Route20_Text_TiffanyIntro::
    .string "Miluji plavat s rybami\n"
    .string "tady mezi vlnami.$"

Route20_Text_TiffanyDefeat::
    .string "Au!$"

Route20_Text_TiffanyPostBattle::
    .string "Chces plavat se mnou?$"

Route20_Text_IreneIntro::
    .string "Taky más dovolenou?$"

Route20_Text_IreneDefeat::
    .string "Vubec zádné slitování!$"

Route20_Text_IrenePostBattle::
    .string "SEAFOAM byl kdysi jediny\n"
    .string "ostrov v dávné minulosti.$"

Route20_Text_DeanIntro::
    .string "Podívej na mé svaly!$"

Route20_Text_DeanDefeat::
    .string "Slabocho!$"

Route20_Text_DeanPostBattle::
    .string "Mel jsem trénovat POKéMONy,\n"
    .string "ne sebe!$"

Route20_Text_DarrinIntro::
    .string "Proc jezdís na POKéMONu?\n"
    .string "Neumís plavat?$"

Route20_Text_DarrinDefeat::
    .string "Au!\n"
    .string "Torpédován!$"

Route20_Text_DarrinPostBattle::
    .string "Jezdit na POKéMONu vypadá fajn!$"

Route20_Text_RogerIntro::
    .string "Letel jsem sem na svém ptákovi.$"

Route20_Text_RogerDefeat::
    .string "Ach, ne!\n"
    .string "Co mám ted delat?$"

Route20_Text_RogerPostBattle::
    .string "Mí ptáci jsou vycerpaní.\n"
    .string "Nemohou me odnést zpet!$"

Route20_Text_NoraIntro::
    .string "Muj prítel mi dal velké perly.$"

Route20_Text_NoraDefeat::
    .string "Ach, ne!\n"
    .string "Mé perly byly v nich!$"

Route20_Text_NoraPostBattle::
    .string "Porostou mé perly uvnitr\n"
    .string "CLOYSTERa vetsí?$"

Route20_Text_MissyIntro::
    .string "Plavala jsem sem z CINNABAR\n"
    .string "ISLAND. Nebylo to lehké.$"

Route20_Text_MissyDefeat::
    .string "Jsem tak zklamaná!$"

Route20_Text_MissyPostBattle::
    .string "POKéMONi obsadili\n"
    .string "opusteny pansky dum na CINNABAR.\p"
    .string "Ríkají mu POKéMON MANSION.$"

Route20_Text_MelissaIntro::
    .string "CINNABAR na západe má LAB\n"
    .string "pro POKéMONy.\p"
    .string "Tatínek tam pracuje.$"

Route20_Text_MelissaDefeat::
    .string "Pockej!\n"
    .string "Más pockat!$"

Route20_Text_MelissaPostBattle::
    .string "CINNABAR je sopecny ostrov.\p"
    .string "Slysela jsem, ze povstal z more,\n"
    .string "kdyz vybuchla sopka.$"

Route20_Text_SeafoamIslands::
    .string "SEAFOAM ISLANDS$"

Route20_Text_MistyTrainsHere::
    .string "Silní TRÉNÉRI a VODNÍ POKéMONi\n"
    .string "jsou v techto castech bezní.\p"
    .string "Ríká se, ze MISTY z\n"
    .string "CERULEAN GYMU tu trénuje.$"
