SixIsland_WaterPath_House1_Text_LoveItNeedItHeracross::
    .string "Hera, hera, HERACROSS!\n"
    .string "Velky a leskly, je to bossík!\l"
    .string "Miluju ho, potrebuju, HERACROSS!$"

SixIsland_WaterPath_House1_Text_MayIMeasureHeracross::
    .string "Jiiii!\n"
    .string "To je HERACROSS!\p"
    .string "Prosím, prosím, smím zmerit,\n"
    .string "jak je velky?$"

SixIsland_WaterPath_House1_Text_ItsXInchesDeserveReward::
    .string "Iii, je {STR_VAR_2} palcu!\n"
    .string "Nikdy jsem nic takového nevidela!\l"
    .string "Zaslouzís si odmenu!$"

SixIsland_WaterPath_House1_Text_WantToSeeBiggerOne::
    .string "Chci videt mnohem, mnohem\n"
    .string "vetsího HERACROSSe nez tohohle.\p"
    .string "Ach, jak je miluji, velké\n"
    .string "HERACROSSe!$"

SixIsland_WaterPath_House1_Text_ItsXInchesSameAsBefore::
    .string "Hm? Toto merení {STR_VAR_2} palcu…\n"
    .string "Ach! Je stejné jako predtím.$"

SixIsland_WaterPath_House1_Text_ItsXInchesYInchesWasBiggest::
    .string "Ach, jen {STR_VAR_2} palcu.\n"
    .string "HERACROSS predtím byl vetsí.\p"
    .string "Bylo to {STR_VAR_3} palcu, nejvetsí\n"
    .string "HERACROSS, kterého jsi prinesl.$"

SixIsland_WaterPath_House1_Text_ThisWontDo::
    .string "Ach, ne! Tohle nestací!\p"
    .string "HERACROSS vypadá mnohem\n"
    .string "drsneji a má krásny roh!$"

SixIsland_WaterPath_House1_Text_YourBagIsFull::
    .string "Vás VAK je plny.\n"
    .string "Má odmena se tam nevejde.$"

SixIsland_WaterPath_House1_Text_BiggestHeracrossIsXInches::
    .string "Nejvetsí HERACROSS, kterého\n"
    .string "jsem dosud videla a zmerila, mel:\p"
    .string "{STR_VAR_3} palcu!$"

SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort::
    .string "Je to prázdny graf nejakého\n"
    .string "druhu.\p"
    .string "Má místa pro zapsání záznamu\n"
    .string "nejakého druhu.$"

