OneIsland_Text_BillLetsGoSeeCelio::
    .string "BILL: A jsme tady!\n"
    .string "Toto je ONE ISLAND.\p"
    .string "V okolí je nekolik ostruvku\n"
    .string "a toto je jeden z nich.\p"
    .string "Muj prítel CELIO sem poslal\n"
    .string "lod, aby me vyzvedla.\p"
    .string "Stará se o PC sít ostrova\n"
    .string "úplne sám.\p"
    .string "…Proc ti to ríkám práve ted?\n"
    .string "Pojdme za CELIEM!$"

Text_WhereDoYouWantToSail::
    .string "Ahoj, námorníku!\n"
    .string "Kam chces plout?$"

OneIsland_Text_LuckyToHaveCelioHere::
    .string "Jsme tady na ostrove uprostred\n"
    .string "niceho.\p"
    .string "Máme stestí, ze máme tak\n"
    .string "skvelého mladíka jako CELIA.\p"
    .string "Má vnucka byla bez sebe\n"
    .string "z CELIOVA prítele.\p"
    .string "Neco o slavném\n"
    .string "POKéMANIAKOVI?\p"
    .string "Nevím, co to znamená, ale\n"
    .string "CELIO je opravdu borec!$"

OneIsland_Text_HavePCLinkageWithKanto::
    .string "Má vnucka byla bez sebe\n"
    .string "z nového objevu.\p"
    .string "Ríkala, ze ted máme PC spojení\n"
    .string "s lidmi v KANTU.\p"
    .string "Nevím, co to znamená, ale\n"
    .string "CELIO je opravdu borec!$"

OneIsland_Text_HavePCLinkageWithHoenn::
    .string "Má vnucka byla bez sebe\n"
    .string "z nového objevu.\p"
    .string "Ríkala, ze konecne máme PC\n"
    .string "spojení s lidmi v HOENNU.\p"
    .string "Nevím, co to znamená, ale\n"
    .string "CELIO je opravdu borec.\p"
    .string "Byl by skvelym manzelem\n"
    .string "pro mou vnucku!$"

OneIsland_Text_IslandSign::
    .string "ONE ISLAND\n"
    .string "Prátelé se scházejí na Knot Island$"

OneIsland_Text_PokemonNetCenterSign::
    .string "Rozsirujeme svet POKéMONu!\n"
    .string "POKéMON NET CENTRUM$"

@ Unused
OneIsland_Text_ReturnToCinnabar::
    .string "グレンタウンに　もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat::
    .string "Ahoj, prijel sis prohlédnout?\n"
    .string "Není to tu krásne teplé?$"

