Route10_Text_MarkIntro::
    .string "Páni, ty ses dostal az sem?\n"
    .string "Mozná jsi taky POKéMANIAK?\l"
    .string "Chces videt mou sbírku?$"

Route10_Text_MarkDefeat::
    .string "Hmf.\n"
    .string "Nezlobím se!$"

Route10_Text_MarkPostBattle::
    .string "Doma mám víc vzácnych POKéMONu!$"

Route10_Text_ClarkIntro::
    .string "Ha-haha-a-ha!$"

Route10_Text_ClarkDefeat::
    .string "Ha-haha!\n"
    .string "Nesmeju se!\l"
    .string "Ha-senná ryma! Hapci-hapci!$"

Route10_Text_ClarkPostBattle::
    .string "Hapci-hap-ci!\n"
    .string "Hapci!\l"
    .string "Frk! Smrk!$"

Route10_Text_HermanIntro::
    .string "Ahoj, fakane!\n"
    .string "Chces videt mé POKéMONy?$"

Route10_Text_HermanDefeat::
    .string "Ó ne!\n"
    .string "Mí POKéMON!$"

Route10_Text_HermanPostBattle::
    .string "Nemám te rád.\n"
    .string "Nemám rád nikoho lepsího nez sebe!$"

Route10_Text_HeidiIntro::
    .string "Párkrát uz jsem byla\n"
    .string "v POKéMON GYM.\p"
    .string "…Ale vzdycky prohraju.$"

Route10_Text_HeidiDefeat::
    .string "Och!\n"
    .string "Po vsem tom tréninku!$"

Route10_Text_HeidiPostBattle::
    .string "Vsimla jsem si nejakych\n"
    .string "POKéMANIAKu, jak se tu plízí.\p"
    .string "Predstavís si to? Oni?\n"
    .string "Tady nahore v horách?$"

Route10_Text_TrentIntro::
    .string "Ach!\n"
    .string "Tenhle horsky vzduch je lahodny!$"

Route10_Text_TrentDefeat::
    .string "To mi projasnilo hlavu!$"

Route10_Text_TrentPostBattle::
    .string "Mám pocit, ze prasknu z toho\n"
    .string "horského vzduchu!$"

Route10_Text_CarolIntro::
    .string "Je mi trochu mdlo.\n"
    .string "Dlouho jsem nesla na túru.$"

Route10_Text_CarolDefeat::
    .string "Jsem moc unavená.\n"
    .string "Nebyla jsem na to pripravená.$"

Route10_Text_CarolPostBattle::
    .string "POKéMON tady v horách\n"
    .string "jsou tak macatí…\p"
    .string "Kéz by tu byli ruzoví POKéMON\n"
    .string "s kvetinovym vzorem!$"

Route10_Text_RockTunnelDetourToLavender::
    .string "ROCK TUNNEL\n"
    .string "Odbocka do LAVENDER TOWN$"

Route10_Text_RockTunnel::
    .string "ROCK TUNNEL$"

Route10_Text_PowerPlant::
    .string "POWER PLANT$"
