Route5_PokemonDayCare_Text_WantMeToRaiseMon::
	.string "Vedu sluzbu DAY-CARE.\p"
	.string "Chces, abych vychoval\n"
	.string "nekterého z tvych POKéMONu?$"

Route5_PokemonDayCare_Text_ComeAgain::
	.string "Prijd zas.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
	.string "Kterého POKéMONa mám vychovat?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
	.string "Dobre.\n"
	.string "Prijd, kdy budes chtít.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
	.string "Dobre, postarám se ti chvíli\n"
	.string "o {STR_VAR_1}.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
	.string "Prijd se za chvíli podívat.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
	.string "Uz jsi zpátky?\p"
	.string "Tvuj {STR_VAR_1} potrebuje\n"
	.string "se mnou strávit jeste cas.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
	.string "Dluzís mi ¥{STR_VAR_2} za vrácení\n"
	.string "tohoto POKéMONa.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
	.string "Díky!\n"
	.string "Tady je tvuj POKéMON.$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
	.string "{PLAYER} dostal zpet {STR_VAR_1}\n"
	.string "od DAY-CARE MUZE.$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
	.string "Co? Mas u sebe jen jednoho\n"
	.string "POKéMONa.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
	.string "Kdyz mi nechás toho POKéMONa,\n"
	.string "s kym budes bojovat?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
	.string "Tvuj {STR_VAR_1} hodne vyrostl.\n"
	.string "Ano, opravdu hodne, rekl bych.\p"
	.string "Podívám se…\n"
	.string "Vyrostl o {STR_VAR_2} úrovní.\p"
	.string "Nejsem ohromny?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
	.string "Nemuzes si tohoto POKéMONa vzít\n"
	.string "zpet, kdyz pro nej nemás místo.$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
	.string "Nemás dost penez.$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
    .string "きみの\n"
    .string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
    .string "わるいけど　ひでんのわざを　もった\n"
    .string "ポケモンは　あずかれないなぁ$"
