VermilionCity_Text_GrimerMultipliesInSludge::
    .string "Tady si dáváme pozor na znecistení.\p"
    .string "Slyseli jsme, ze GRIMER se mnozí\n"
    .string "v toxickém bahne.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .string "Videl jsi S.S. ANNE zakotvenou\n"
    .string "v prístavu?$"

VermilionCity_Text_SSAnneHasDepartedForYear::
    .string "Takze S.S. ANNE odplula?\p"
    .string "Vrátí se do VERMILIONU asi\n"
    .string "v tomto case za rok.$"

VermilionCity_Text_BuildingOnThisLand::
    .string "Stavím tu budovu na tomto\n"
    .string "pozemku. Vsechno je mé.\p"
    .string "Muj POKéMON dusá pudu, aby\n"
    .string "se polozily základy.$"

VermilionCity_Text_Machop::
    .string "MACHOP: Guoh! Gogogoh!$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "MACHOP dusá pudu narovno.$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "S.S. ANNE je slavná luxusní\n"
    .string "vyletní lod.\p"
    .string "Do VERMILIONU pripluje jednou\n"
    .string "za rok.$"

VermilionCity_Text_CitySign::
    .string "VERMILION CITY\n"
    .string "Prístav nádhernych západu slunce$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "POZOR!\p"
    .string "CESTA 12 muze byt zablokovaná\n"
    .string "spícím POKéMONem.\p"
    .string "Obejdete pres ROCK TUNNEL do\n"
    .string "LAVENDER TOWN.\p"
    .string "VERMILION POLICIE$"

VermilionCity_Text_PokemonFanClubSign::
    .string "POKéMON FAN CLUB\n"
    .string "Vsichni fanousci POKéMONu vítáni!$"

VermilionCity_Text_GymSign::
    .string "VERMILION CITY POKéMON GYM\n"
    .string "VUDCE: LT. SURGE\l"
    .string "Elektricky Americán!$"

VermilionCity_Text_VermilionHarbor::
    .string "VERMILION PRÍSTAV$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "Vítej na S.S. ANNE!$"

VermilionCity_Text_DoYouHaveATicket::
    .string "Vítej na S.S. ANNE!\p"
    .string "Promin, mas lístek?$"

VermilionCity_Text_FlashedSSTicket::
    .string "{FONT_NORMAL}{PLAYER} ukázal S.S. TICKET!\p"
    .string "{FONT_MALE}Skvele!\n"
    .string "Vítej na S.S. ANNE!$"

VermilionCity_Text_DontHaveNeededSSTicket::
    .string "{FONT_NORMAL}{PLAYER} nemá potrebny\n"
    .string "S.S. TICKET.\p"
    .string "{FONT_MALE}Promin!\p"
    .string "K nástupu potrebujes lístek.$"

VermilionCity_Text_TheShipSetSail::
    .string "Lod vyplula.$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "Aha, mas TRI-PASS.\p"
    .string "Chces nastoupit na\n"
    .string "SEAGALLOP trajekt?$"

VermilionCity_Text_Seagallop7Departing::
    .string "Dobre, vse je v porádku.\p"
    .string "SEAGALLOP HI-SPEED 7 ihned\n"
    .string "vyplouvá.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "Aha, mas RAINBOW PASS.\p"
    .string "Chces nastoupit na\n"
    .string "SEAGALLOP trajekt?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "Ó! To je MYSTICTICKET!\n"
    .string "To je vzácné.\p"
    .string "Rádi te kdykoliv odvezeme na\n"
    .string "NAVEL ROCK.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "Ó! To je AURORATICKET!\n"
    .string "To je vzácné.\p"
    .string "Rádi te kdykoliv odvezeme na\n"
    .string "BIRTH ISLAND.$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "Chces nastoupit na\n"
    .string "SEAGALLOP trajekt?$"

VermilionCity_Text_Seagallop10Departing::
    .string "Vse je v porádku, muzes\n"
    .string "nastoupit na speciální trajekt.\p"
    .string "SEAGALLOP HI-SPEED 10 ihned\n"
    .string "vyplouvá.$"

VermilionCity_Text_Seagallop12Departing::
    .string "Vse je v porádku, muzes\n"
    .string "nastoupit na speciální trajekt.\p"
    .string "SEAGALLOP HI-SPEED 12 ihned\n"
    .string "vyplouvá.$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "Ó, ahoj, {PLAYER}!\n"
    .string "Jak se vede?\p"
    .string "Jsem jeden z asistentu PROF. OAKA.\p"
    .string "Potkal jsi druhého asistenta?\p"
    .string "Mel pro tebe balícek od\n"
    .string "PROF. OAKA, {PLAYER}.\p"
    .string "Rekl, ze te bude hledat okolo\n"
    .string "CESTY 2, {PLAYER}.\p"
    .string "Az budes v oblasti CESTY 2,\n"
    .string "prosím, podívej se po nem.$"

