ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
    .string "Ahoj, ty tam!\n"
    .string "Jak se vede?\p"
    .string "Co tu delám, ptás se?\n"
    .string "Inu, hledám zlato!\p"
    .string "Az zbohatnu, koupím si dum\n"
    .string "v KANTU.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
    .string "Ahoj! Jak se vede?\n"
    .string "Slysels? Nasel jsem zlato!\p"
    .string "Pamatujes, ze jsem byl\n"
    .string "hledac, vid?\p"
    .string "Nedokázes si predstavit, jak\n"
    .string "jsem stastny.\p"
    .string "Tak ti to ukázu!\n"
    .string "Toto je pro tebe!$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget::
    .string "To je NUGGET!\p"
    .string "Nemuzu ti dát nuggety moudrosti,\n"
    .string "takze to bude muset stacit!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
    .string "Hopla, tvuj BATOH je narván!\n"
    .string "Dám ti to pozdeji.$"

