LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "Hledám predmety, které zvedají\n"
    .string "staty POKéMONu.\p"
    .string "Jsou úcinné po dobu\n"
    .string "jednoho souboje.\p"
    .string "X ATTACK, X DEFEND, X SPEED \n"
    .string "a X SPECIAL - to hledám.\p"
    .string "Vís, kde se dají sehnat?$"

LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "Koupil sis nejaké REVIVE?\n"
    .string "Vzkrísí kazdého omdlelého POKéMONa!$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "Nekdy te dvojice TRENÉRu vyzve\n"
    .string "se dvema POKéMONy\l"
    .string "naráz.\p"
    .string "Pokud se to stane, musís taky\n"
    .string "poslat do boje dva POKéMONy.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "Onehdy jsem v horách\n"
    .string "nasel NUGGET!\p"
    .string "Je to neuzitecná vec, ale\n"
    .string "prodal jsem ji za 5000¥$"
