FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
    .string "SPRÁVCE: Hif fuff hefifoo!\p"
    .string "Ha lof ha feef ee hafahi ho.\n"
    .string "Heff hee fwee!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
    .string "Ah howhee ho hoo!\n"
    .string "Eef ee hafahi ho!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
    .string "Ha?\n"
    .string "He ohay heh ha hoo ee haheh!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
    .string "{PLAYER} dal ZLATÉ ZUBY\n"
    .string "SPRÁVCI.$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
    .string "SPRÁVCE si nasadil zuby!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
    .string "SPRÁVCE: Díky, synu!\n"
    .string "Jsi opravdu zachránce!\p"
    .string "Nikdo mi nerozumel jediné\n"
    .string "slovo, vubec nikdo!\p"
    .string "Stydel jsem se ukázat\n"
    .string "v KANCELÁRI.\p"
    .string "Dovol, dám ti neco za\n"
    .string "tvou námahu.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
    .string "SPRÁVCE: Díky, deveecko!\n"
    .string "Jsi opravdu zachránce!\p"
    .string "Nikdo mi nerozumel jediné\n"
    .string "slovo, vubec nikdo!\p"
    .string "Stydel jsem se ukázat\n"
    .string "v KANCELÁRI.\p"
    .string "Dovol, dám ti neco za\n"
    .string "tvou námahu.$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
    .string "{PLAYER} dostal HM04\n"
    .string "od SPRÁVCE.$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
    .string "SPRÁVCE: V HM04 najdes\n"
    .string "STRENGTH.\p"
    .string "Umozní POKéMONum hybat balvany,\n"
    .string "kdyz nejsi v souboji.\p"
    .string "Aha, nasels TAJNY DUM\n"
    .string "v SAFARI ZONE?$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
    .string "なんや　にもつ\n"
    .string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
    .string "Vystavené jsou fotky a\n"
    .string "fosílie POKéMONu.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
    .string "Vystavené je staré\n"
    .string "POKéMON zbozí.$"

