FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "LORELEI: Drz svoje spinavé ruce\n"
    .string "pryc od POKéMONu v jeskyni!\p"
    .string "Udelej, co ríkám, nebo budes\n"
    .string "odpovídat mne!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "Ach, drz hubu, dámo, a nech nás\n"
    .string "byt.\p"
    .string "Nenech si zamlzit brejle!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .string "LORELEI: {PLAYER}?!\n"
    .string "Co tady delás?\p"
    .string "Ne, dohoneme se pozdeji.\n"
    .string "Práve ted potrebuji tvou pomoc.\p"
    .string "Pomoz mi vyhnat tyhle pytláky,\n"
    .string "nez nadelají dalsí skody.\p"
    .string "Chytají tu POKéMONy, a pak\n"
    .string "je prodávají!\p"
    .string "Jsi pripraven?\n"
    .string "Vezmes si toho, prosím!$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "C-coze?!\p"
    .string "Kdo ríká, ze nemuzeme s POKéMONy,\n"
    .string "co chytíme, delat, co chceme?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "S tímhle jsme nepocítali!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "LORELEI: Hmf.\n"
    .string "Tak ubohy.\p"
    .string "Ty!\n"
    .string "Rekni mi!\p"
    .string "Kam jste odnesli zajaté\n"
    .string "POKéMONy?\p"
    .string "Rozmlátím vás vsechny jednou\n"
    .string "provzdy!$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "Ne-ne!\n"
    .string "To ti nereknu!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .string "LORELEI: Pokud se nepriznás,\n"
    .string "zmrazíme te.\p"
    .string "Má LAPRAS zurí za to, co jste\n"
    .string "udelali jejím prátelum.\p"
    .string "Jdi, LAPRAS!\n"
    .string "ICE BEAM…$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "Wawaah! Dobre!\n"
    .string "Reknu to!\p"
    .string "POKéMONi jsou v ROCKET\n"
    .string "WAREHOUSE na FIVE ISLAND.\p"
    .string "Tak! Rekl jsem to!\n"
    .string "Ted odejdeme!\p"
    .string "…Ale pochybuji, ze se kdy\n"
    .string "do ROCKET WAREHOUSE dostanes!\p"
    .string "Heheheheh!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "{PLAYER}, dekuji ti.\n"
    .string "Ale tohle je hrozné…\p"
    .string "Narodila a vyrostla jsem zde\n"
    .string "na techto ostrovech.\p"
    .string "Netusila jsem, ze tu volne\n"
    .string "operují ti zlocinci…$"

