PokemonTower_5F_Text_RestHereInPurifiedSpace::
    .string "Pojd, díte!\n"
    .string "Tento prostor jsem ocistil.\l"
    .string "Muzes si tu odpocinout.$"

PokemonTower_5F_Text_TammyIntro::
    .string "Dej…mi…\n"
    .string "vse…co más…$"

PokemonTower_5F_Text_TammyDefeat::
    .string "Lapám po dechu!$"

PokemonTower_5F_Text_TammyPostBattle::
    .string "Byla jsem posedlá.$"

PokemonTower_5F_Text_RuthIntro::
    .string "Ty…se…\n"
    .string "pridás…k nám…$"

PokemonTower_5F_Text_RuthDefeat::
    .string "Jaká nocní mura!$"

PokemonTower_5F_Text_RuthPostBattle::
    .string "Byla jsem posedlá.$"

PokemonTower_5F_Text_KarinaIntro::
    .string "Zombie!$"

PokemonTower_5F_Text_KarinaDefeat::
    .string "Co?$"

PokemonTower_5F_Text_KarinaPostBattle::
    .string "Zase jsem prisla k sobe.$"

PokemonTower_5F_Text_JanaeIntro::
    .string "Urgh…\n"
    .string "Urf…$"

PokemonTower_5F_Text_JanaeDefeat::
    .string "Uf!$"

PokemonTower_5F_Text_JanaePostBattle::
    .string "Podlehl jsem zlym duchum i pres\n"
    .string "svuj vycvik v horách…$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
    .string "Vstoupil jsi do ocistené a\n"
    .string "chránené zóny.\p"
    .string "{PLAYER}ovi POKéMON byli\n"
    .string "plne uzdraveni.$"
