SaffronCity_PokemonTrainerFanClub_Text_HuhYou::
    .string "He?\n"
    .string "Ty…$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow::
    .string "Nejsi náhodou…\n"
    .string "… …\p"
    .string "Jsi to ty!\n"
    .string "Ty jsi {PLAYER}!\p"
    .string "Práve jsme o tobe mluvili!\p"
    .string "Mluvili jsme o tom, jak se\n"
    .string "objevil neuveritelne dobry TRENÉR.\p"
    .string "A ten nekdo jsi ty!\n"
    .string "Jsi tak super!\p"
    .string "Tak jsme se rozhodli, ze budeme\n"
    .string "tvuj FAN CLUB!\p"
    .string "Vsichni doufáme, ze budes dál\n"
    .string "bojovat a ukázes, jak jsi super.\p"
    .string "Tak mozná i dalsí lidé se stanou\n"
    .string "fanousky, jako já.$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou::
    .string "Vzdycky ti budu fandit!\p"
    .string "Do toho, {PLAYER}, do toho!$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou::
    .string "Vzdycky v tebe budu verit,\n"
    .string "{PLAYER}.\p"
    .string "Prosím ukaz ostatním, jaky jsi,\n"
    .string "kdyz bojujes doopravdy.$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore::
    .string "Promin.\n"
    .string "Drív jsem byl tvuj fanousek.\p"
    .string "Ale ted se zdá, ze jsi ztratil\n"
    .string "tu chut, co jsi mel drív.\p"
    .string "Poslední dobou je {STR_VAR_1}\n"
    .string "o dost vetsí frajer.$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe::
    .string "Ó!\n"
    .string "{PLAYER}!\p"
    .string "Vsichni jsou z tebe poslední\n"
    .string "dobou nadsení.\p"
    .string "Chápu proc.\n"
    .string "Vím, ze jsi silny.\p"
    .string "Ale vís co?\p"
    .string "Jakmile jsem se stal fanouskem\n"
    .string "{STR_VAR_1}, nemuzu prestat.$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling::
    .string "Myslím, ze TRENÉRI jsou tak super,\n"
    .string "kdyz bojují.\p"
    .string "Nemyslís si to taky?$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts::
    .string "Ó! To je {PLAYER}!\n"
    .string "Prílis super!\p"
    .string "Ó!\n"
    .string "Ó, jo!\p"
    .string "Muzes se mi nekam podepsat?\n"
    .string "Co treba na mé sortky?$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou::
    .string "At bylo sebevetsí horko…\p"
    .string "A at muze byt sebevetsí zima…\p"
    .string "Vzdycky jsem veril a nosil\n"
    .string "sortky!\p"
    .string "Pocítám s tím, ze budes dál\n"
    .string "vyhrávat!\p"
    .string "Verím v tebe stejne jako\n"
    .string "verím v sortky!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero::
    .string "BROCK je muj hrdina!\n"
    .string "Je to chlap mezi chlapy!\p"
    .string "Hehe, donutil jsem mámu, aby\n"
    .string "mi neco udelala.\p"
    .string "Vysila mi “BROCK”\n"
    .string "na mé sortky!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd::
    .string "…  …\p"
    .string "…  …\n"
    .string "Jsem BROCKuv fanousek!\p"
    .string "I kdybych byl jeho jediny fanda,\n"
    .string "prísahám na svou skalní vuli\l"
    .string "a na své sortky!\p"
    .string "Budu jeho fandou az do konce!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool::
    .string "BROCK je vrchol cool,\n"
    .string "tecka!\p"
    .string "To je chlapík, jako kterého\n"
    .string "chci byt!$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle::
    .string "{PLAYER}, mel jsem tu cest\n"
    .string "sledovat te v boji.\p"
    .string "Vrací mi to sladké vzpomínky\n"
    .string "na mé dávno ztracené mládí.\p"
    .string "At se ti dál darí.\n"
    .string "Más ve mne fanouska!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence::
    .string "Procestoval jsem dlouhé a\n"
    .string "siroké kraje.\p"
    .string "Ale nikdy jsem nevidel TRENÉRA\n"
    .string "tvé velkoleposti.\p"
    .string "Cerpej odvahu ze svych schopností\n"
    .string "a bojuj dál!\p"
    .string "Slib mi to,\n"
    .string "muj mlady idole!$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre::
    .string "Hmm…\n"
    .string "A ty jsi?\p"
    .string "Chtel ses prihlásit do\n"
    .string "clenství v nasem FAN CLUB?$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo::
    .string "Ah, tak ty jsi ten\n"
    .string "prosluly {PLAYER}.\p"
    .string "Vskutku más vzhled\n"
    .string "víteze.\p"
    .string "Ale abych te prijal jako\n"
    .string "skutecne velkého POKéMON…\p"
    .string "… …\p"
    .string "Más pred sebou jeste kus cesty!$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning::
    .string "Vsichni tady jsme fanousci\n"
    .string "POKéMON TRENÉRU.\p"
    .string "Jak vypadají v boji…\n"
    .string "Jsou ztelesnením cool.\p"
    .string "Mozná se o tobe bude mluvit\n"
    .string "i tady, kdyz budes dál vyhrávat.$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay::
    .string "To je {PLAYER}!\n"
    .string "To je {PLAYER}!\p"
    .string "Chci byt jednou jako {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan::
    .string "Vsichni prestali byt\n"
    .string "{PLAYER}ovymi fanousky…\p"
    .string "Ale to znamená, ze muzu mít\n"
    .string "{PLAYER} jen pro sebe!\p"
    .string "Jupí! Do toho!\n"
    .string "Muj jediny {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina::
    .string "Vís co?\n"
    .string "Chci byt jako SABRINA!\p"
    .string "Chci byt psychická holka,\n"
    .string "presne jako ona!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan::
    .string "I kdybych byla jediná, neprestanu\n"
    .string "byt fanynkou SABRINY.\p"
    .string "Mym snem je byt jako SABRINA,\n"
    .string "roztomilá, ale cool.\p"
    .string "Chci byt psychická holka,\n"
    .string "presne jako ona!$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay::
    .string "Jestlipak se jednou stanu\n"
    .string "cool TRENÉREM?$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool::
    .string "Ó, clovece, clovece!\n"
    .string "Cool! Prílis cool!\p"
    .string "…He?\n"
    .string "Ne, ty ne.\p"
    .string "Jen to, jak bojujes.\n"
    .string "To je cool.$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans::
    .string "Hej, {PLAYER}!\p"
    .string "Vypadá to, ze jsem jediny\n"
    .string "z tvych fanousku, kdo zbyl.\p"
    .string "Ale vís, líbí se mi byt jediny\n"
    .string "fanda… Je to méne stresující.\p"
    .string "Drz se a do toho!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks::
    .string "{STR_VAR_1} je cool, vid?\n"
    .string "Zboznuju, jak mluví.\p"
    .string "Fakt bych si uzila sanci\n"
    .string "potkat ho jednou osobne.$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan::
    .string "Hej, veril bys tomu?\n"
    .string "Vsichni se stali tvymi fanousky.\p"
    .string "Tak po tom vsem, cím jsme prosli,\n"
    .string "jsem osamely {STR_VAR_1} fanda?\p"
    .string "Ále, byt ten jediny {STR_VAR_1}\n"
    .string "fanda je stejne muj styl.$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle::
    .string "Ó, propána!\n"
    .string "Jsi to opravdu ty, {PLAYER}?\p"
    .string "Musím ti ríct, ze zboznuju,\n"
    .string "jak bojujes.\p"
    .string "Doufám, ze u toho zustanes.\n"
    .string "Budu tvuj fanousek císlo jedna!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan::
    .string "Ó, propána!\n"
    .string "Není to {PLAYER}!\p"
    .string "Je to zklamání… Zjistila jsem,\n"
    .string "ze jsem tvuj jediny fanda c. 1!\p"
    .string "No, nedá se nic delat!\n"
    .string "Aspon te necht povzbudit!\p"
    .string "Hurá, hurá, {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire::
    .string "Poslední dobou je {STR_VAR_1}\n"
    .string "v rázi.\p"
    .string "Jak bojuje… Je to presne\n"
    .string "tak, jak to mám rád!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou::
    .string "Ó, ahoj!\n"
    .string "Není to {PLAYER}!\p"
    .string "Poslední dobou vsichni mluví\n"
    .string "jen o tobe.\p"
    .string "Cítím se osamele, protoze\n"
    .string "mám radsi {STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing::
    .string "Úzasné!\n"
    .string "{PLAYER}, ty jsi opravdu úzasny!\p"
    .string "Místo abych jen koukal, mozná\n"
    .string "bych se mel stát taky TRENÉREM.$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan::
    .string "Jsem tvuj jediny fanda…\n"
    .string "Povzdech… To je osamelé…\p"
    .string "Nemohl by ses víc snazit, aby si\n"
    .string "te ostatní vsimli?$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity::
    .string "Mistr {STR_VAR_1} je tak vzneseny…\n"
    .string "Je úplne muj typ.\p"
    .string "Proc ostatní nevidí tu\n"
    .string "dustojnost, kterou prímo srsí?$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart::
    .string "Verím v Mistra {STR_VAR_1}\n"
    .string "celym svym srdcem.\p"
    .string "I kdybych byla jediná, kdo\n"
    .string "v nej verí.\p"
    .string "Nikdy se ale nebudu cítit osamele.\p"
    .string "Ne, pokud budu myslet na Mistra\n"
    .string "{STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational::
    .string "Hijá!\p"
    .string "Tvuj bojovy styl je vskutku\n"
    .string "poucny.\p"
    .string "Doufám, ze budes dál\n"
    .string "smerovat k úspechu, hijá!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan::
    .string "Místo abys jen koukal na boj\n"
    .string "ostatních, bojuj sám!\p"
    .string "…Takhle me seval MISTR\n"
    .string "z mého DOJO…\p"
    .string "Ale nenechám se tím odradit\n"
    .string "od toho byt tvuj fanousek!\p"
    .string "Nemuzu prestat byt tvuj fanda!$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect::
    .string "Hijá! Je jen jeden TRENÉR,\n"
    .string "ktery má muj respekt.\p"
    .string "A to není nikdo jiny nez muj\n"
    .string "MISTR z FIGHTING DOJO.\p"
    .string "Mel by ses stát fanouskem\n"
    .string "mého MISTRA jako já! Hijá!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster::
    .string "Hijá! Respektuju svého MISTRA\n"
    .string "z FIGHTING DOJO.\p"
    .string "Nikdy se nestanu fanouskem\n"
    .string "nikoho jiného nez svého MISTRA!\p"
    .string "Klidne se vykradu z DOJO,\n"
    .string "abych síril zvest o jeho velikosti.\p"
    .string "Hijá!$"
