VermilionCity_Gym_Text_LtSurgeIntro::
    .string "Hej, fakane! Co si myslís,\n"
    .string "ze tady delás?\p"
    .string "Dlouho v boji nevydrzís!\n"
    .string "Ne s tvou ubohou silou!\p"
    .string "Ríkám ti, fakane, elektricky\n"
    .string "POKéMONi me zachránili ve válce!\p"
    .string "Sokli mé neprátele do\n"
    .string "paralyzy!\p"
    .string "Stejne tak udelám i tobe!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "Krátká rada, fakane!\p"
    .string "Elektrina je vskutku silná!\p"
    .string "Ale je neúcinná proti GROUND-\n"
    .string "POKéMONum!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "THUNDERBADGE zvysí RYCHLOST\n"
    .string "tvého POKéMONa!\p"
    .string "Také umozní tvému POKéMONovi\n"
    .string "kdykoliv FLY bleskove, fakane!\p"
    .string "Jsi vyjímecny, fakane!\n"
    .string "Vezmi si to!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "{PLAYER} dostal TM34\n"
    .string "od LT. SURGE.$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "TM34 obsahuje SHOCK WAVE!\p"
    .string "Nauc to ELECTRIC POKéMONa!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "Hej, fakane, udelej místo v BAGU!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "Tak to je sok!\p"
    .string "Jsi opravdu dobry, fakane!\p"
    .string "Fajn, tady mas THUNDERBADGE!$"

VermilionCity_Gym_Text_TuckerIntro::
    .string "Kdyz jsem byl v armáde, LT. SURGE\n"
    .string "byl muj prísny velitel.\p"
    .string "Byl to tvrdy drábce.$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "Pockej!\n"
    .string "Jsi opravdu dobry!$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "Otevrít ty dvere není snadné.\p"
    .string "LT. SURGE byl v armáde slavny\n"
    .string "svou opatrnou povahou.$"

VermilionCity_Gym_Text_BailyIntro::
    .string "Jsem lehká váha, ale jdou mi\n"
    .string "elektriny!\p"
    .string "Proto jsem se pridal k GYMU.$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "Smazeny!$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "Dobre, budu mluvit!\p"
    .string "LT. SURGE rekl, ze spínace\n"
    .string "ukryl uvnitr neceho.$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "Tohle není místo pro deti!\n"
    .string "Ani kdyz jsi dobry!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "Páni!\n"
    .string "Prekvapil jsi me!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "LT. SURGE si pasti v GYMU\n"
    .string "nainstaloval sám.\p"
    .string "Dal vsude dvojité zámky.\n"
    .string "Dám ti tip.\p"
    .string "Kdyz otevres první zámek, druhy\n"
    .string "je hned vedle nej.$"

VermilionCity_Gym_Text_GymGuyAdvice::
    .string "Hej!\n"
    .string "Sampión v zácátcích!\p"
    .string "LT. SURGE má prezdívku.\p"
    .string "Lidé mu ríkají\n"
    .string "Elektricky Americán!\p"
    .string "Je odborník na elektrické\n"
    .string "POKéMONy.\p"
    .string "BIRD/WATER-POKéMONi se proti\n"
    .string "ELECTRIC typu hodí spatne.\p"
    .string "Dej si pozor i na paralyzu.\p"
    .string "LT. SURGE je velmi opatrny.\p"
    .string "Zamkl se, takze nebude snadné\n"
    .string "se k nemu dostat.$"

VermilionCity_Gym_Text_GymGuyPostVictory::
    .string "Páni!\n"
    .string "Ten zápas byl elektricky!$"

VermilionCity_Gym_Text_GymStatue::
    .string "VERMILION POKéMON GYM\n"
    .string "VUDCE: LT. SURGE\p"
    .string "VÍTEZNÍ TRENÉRI:\n"
    .string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "VERMILION POKéMON GYM\n"
    .string "VUDCE: LT. SURGE\p"
    .string "VÍTEZNÍ TRENÉRI:\n"
    .string "{RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "Ne!\n"
    .string "Je tu jen odpad.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "Hej! Pod odpadem je spínac!\n"
    .string "Zapni ho!\p"
    .string "První elektricky zámek se otevrel!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "Druhy elektricky zámek se otevrel!\n"
    .string "Motorizované dvere se otevrely!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "Ne!\n"
    .string "Je tu jen odpad.\p"
    .string "Hej!\n"
    .string "Elektrické zámky se resetly!$"

