Route18_Text_WiltonIntro::
    .string "Vzdy zkontroluju kazdy travnatej\n"
    .string "kus na nové POKéMONy.$"

Route18_Text_WiltonDefeat::
    .string "Tch!$"

Route18_Text_WiltonPostBattle::
    .string "Kéz bych mel KOLO!$"

Route18_Text_RamiroIntro::
    .string "Kurukkú!\n"
    .string "Jak se ti líbí muj ptací hlas?$"

Route18_Text_RamiroDefeat::
    .string "Musel jsem te otravovat!$"

Route18_Text_RamiroPostBattle::
    .string "O vikendech sbírám morské POKéMONy,\n"
    .string "more je tak blízko.$"

Route18_Text_JacobIntro::
    .string "To je muj revír!\n"
    .string "Vypadni odtud!$"

Route18_Text_JacobDefeat::
    .string "Sakra!$"

Route18_Text_JacobPostBattle::
    .string "Tady to mám nejradeji\n"
    .string "na chytání POKéMONu.$"

Route18_Text_RouteSign::
    .string "CESTA 18\n"
    .string "CELADON CITY - FUCHSIA CITY$"

Route18_Text_CyclingRoadSign::
    .string "CYKLISTICKÁ STEZKA\n"
    .string "Pesí zde nesmí!$"

