Text_ExplosionTeach::
    .string "Dovedes si to predstavit?\n"
    .string "Kdyby ta sopka vybuchla?\p"
    .string "Exploze by byla nas konec.\n"
    .string "Jak desivé je to?\p"
    .string "Kdyz uz se desime, mám te\n"
    .string "naucit EXPLOSION?$"

Text_ExplosionDeclined::
    .string "Jo, mas pravdu.\n"
    .string "Je to moc desivé.$"

Text_ExplosionWhichMon::
    .string "Jsi strasne odvazny!\p"
    .string "Kterého POKéMONa mám naucit\n"
    .string "EXPLOSION?$"

Text_ExplosionTaught::
    .string "Pouzít EXPLOSION na téhle\n"
    .string "sopce…\p"
    .string "Jaké desivé vzrusení!$"

@ Below 4 are unused JP versions of the above texts
Text_ExplosionTeachJP::
    .string "こ　この　かざんが\n"
    .string "もし　だいばくはつ　したら\l"
    .string "お　おれら　ひとたまりも\l"
    .string "ないなあ　‥ブルブル！\p"
    .string "こ　こわい　ついでに\n"
    .string "だいばくはつ　でも　おぼえてみる？$"

Text_ExplosionDeclinedJP::
    .string "や　やっぱ　こわいもんな\n"
    .string "ブルブル$"

Text_ExplosionWhichMonJP::
    .string "つ　つよきだね！\n"
    .string "じゃあ　どの　ポケモンに　する？$"

Text_ExplosionTaughtJP::
    .string "かざんで　だいばくはつを‥\n"
    .string "す　すごい　スリル！$"

MtEmber_Exterior_Text_WellTryDiggingHere::
    .string "Tady.\n"
    .string "Tady zkusíme kopat.\p"
    .string "Ten poklad, o kterém ADMINI\n"
    .string "mluví, by mel byt tady.$"

MtEmber_Exterior_Text_YoureInTheWayGetLost::
    .string "Co to…?\n"
    .string "Prekázís. Ztrat se.$"

MtEmber_Exterior_Text_PunchedThroughAtLast::
    .string "Fíha, konecne jsme se prokopali.\n"
    .string "Jdeme za pokladem!$"

MtEmber_Exterior_Text_WhatsPasswordAgain::
    .string "Jakykoliv poklad, co najdeme,\n"
    .string "odvezeme do SKLADU, jasné?\p"
    .string "…Jo, a jaká jsou hesla?\n"
    .string "Do SKLADU ROCKET, myslím.$"

MtEmber_Exterior_Text_FirstPasswordGoldeen::
    .string "Co, ty jsi zapomnel heslo?\n"
    .string "Jsou ve skutecnosti dve.\p"
    .string "První je “GOLDEEN need\n"
    .string "log.”\p"
    .string "A druhé je…$"

MtEmber_Exterior_Text_SnoopsBeenListeningIn::
    .string "Hej!\n"
    .string "Tenhle slídil nás odposlouchával!$"

MtEmber_Exterior_Text_Grunt1Intro::
    .string "Odposlouchával jsi nás,\n"
    .string "ze ano?$"

MtEmber_Exterior_Text_Grunt1Defeat::
    .string "Hm, co?$"

MtEmber_Exterior_Text_Grunt1PostBattle::
    .string "Proc jsi musel vyhrát?$"

MtEmber_Exterior_Text_Grunt2Intro::
    .string "Snazís se nám vzít nas poklad?\n"
    .string "Na to nesázej!$"

MtEmber_Exterior_Text_Grunt2Defeat::
    .string "Pockej!\n"
    .string "Ale jak?$"

MtEmber_Exterior_Text_Grunt2PostBattle::
    .string "Predstírej amnézii a zapomen\n"
    .string "vsechno, co jsi slysel!$"

MtEmber_Exterior_Text_WellRegroupDontStepInsideThere::
    .string "Jaká nepríjemnost…\n"
    .string "Musíme se preskupit.\p"
    .string "Ty! Ani te nenapadne udelat\n"
    .string "krok dovnitr!\p"
    .string "Jestli vís, co je pro tebe\n"
    .string "dobré, ani na to nemysli!$"

MtEmber_Exterior_Text_LoganIntro::
    .string "Aktivní sopka je ta, která\n"
    .string "vybuchuje, nebo se chystá.$"

MtEmber_Exterior_Text_LoganDefeat::
    .string "Fíha… To bylo horké!\n"
    .string "Pot ze me chrlí jako sopka!$"

MtEmber_Exterior_Text_LoganPostBattle::
    .string "Ríká se, ze ve svete je pres\n"
    .string "1 500 aktivních sopek.\p"
    .string "Uz jen pomyslení na to me\n"
    .string "rozparí!$"

MtEmber_Exterior_Text_BethIntro::
    .string "Vís, jak vznikají jeskyne\n"
    .string "uvnitr sopek?$"

MtEmber_Exterior_Text_BethDefeat::
    .string "Acha!\n"
    .string "Jsi sokujícne dobry!$"

MtEmber_Exterior_Text_BethPostBattle::
    .string "Kdyz láva na povrchu magmatu\n"
    .string "ztvrdne a magma uvnitr odtece,\l"
    .string "zustanou dutiny.$"

MtEmber_Exterior_Text_JocelynIntro::
    .string "Trénuji, abych si mohla\n"
    .string "spravit zlomené srdce…\p"
    .string "Aspon me to fyzicky\n"
    .string "posílilo! Hi-ja!$"

MtEmber_Exterior_Text_JocelynDefeat::
    .string "Myslím, ze jsem to prehnala…$"

MtEmber_Exterior_Text_JocelynPostBattle::
    .string "Tvuj zpusob boje mi pripomíná\n"
    .string "toho kluka, co me opustil…$"

