Route13_Text_SebastianIntro::
    .string "Mí ptací POKéMON s tebou\n"
    .string "chtejí bojovat!$"

Route13_Text_SebastianDefeat::
    .string "Mé duo PIDGEY a PIDGEOTTO\n"
    .string "prohrálo?$"

Route13_Text_SebastianPostBattle::
    .string "Mí POKéMON vypadají spokojene,\n"
    .string "i kdyz prohráli.$"

Route13_Text_SusieIntro::
    .string "Ríkají, ze jsem na decko dobrá.$"

Route13_Text_SusieDefeat::
    .string "Ach!\n"
    .string "Prohrála jsem!$"

Route13_Text_SusiePostBattle::
    .string "Chci byt dobrá trénérka.\n"
    .string "Budu trénovat, jen pockej.$"

Route13_Text_ValerieIntro::
    .string "Páni!\n"
    .string "Tvé ODZNAKY jsou super!$"

Route13_Text_ValerieDefeat::
    .string "Málo!$"

Route13_Text_ValeriePostBattle::
    .string "Ty ODZNAKY mas od VÚDCU GYMU.\n"
    .string "Já vím!$"

Route13_Text_GwenIntro::
    .string "Mí roztomilí POKéMON se s tebou\n"
    .string "chtejí seznámit.$"

Route13_Text_GwenDefeat::
    .string "Dobrá práce!\n"
    .string "Naprosto jsi vyhrál!$"

Route13_Text_GwenPostBattle::
    .string "Musís nechat POKéMONy bojovat,\n"
    .string "aby zesílili.$"

Route13_Text_AlmaIntro::
    .string "Jednou jsem v jeskyni nasla\n"
    .string "CARBOS, kdyz jsem ji prozkoumávala.$"

Route13_Text_AlmaDefeat::
    .string "Ach, skoda!\n"
    .string "Práve jsem to pokazila!$"

Route13_Text_AlmaPostBattle::
    .string "CARBOS zvysil RYCHLOST mého\n"
    .string "POKéMONa.$"

Route13_Text_PerryIntro::
    .string "Neprohraju.\n"
    .string "Ne kdyz mi fouká do zad!$"

Route13_Text_PerryDefeat::
    .string "Vítr se otocil!$"

Route13_Text_PerryPostBattle::
    .string "Jsem na dne.\n"
    .string "Asi poletím domu.$"

Route13_Text_LolaIntro::
    .string "Jasne, zahraju si s tebou.$"

Route13_Text_LolaDefeat::
    .string "Ach!\n"
    .string "Ty malé monstrum!$"

Route13_Text_LolaPostBattle::
    .string "Zajímalo by me, kdo je silnejsí,\n"
    .string "samec nebo samice POKéMONa?$"

Route13_Text_SheilaIntro::
    .string "Chces se mnou zabojovat\n"
    .string "s POKéMONy?$"

Route13_Text_SheilaDefeat::
    .string "Uz je konec?$"

Route13_Text_SheilaPostBattle::
    .string "Já o POKéMONech vlastne\n"
    .string "nic nevím.\p"
    .string "Ty, které pouzívám…\n"
    .string "vybrala jsem si je podle vzhledu!$"

Route13_Text_JaredIntro::
    .string "Na co civís?$"

Route13_Text_JaredDefeat::
    .string "Hergot!\n"
    .string "Strzená prevodovka!$"

Route13_Text_JaredPostBattle::
    .string "Ztrat se!$"

Route13_Text_RobertIntro::
    .string "Vzdy sázím na ptací POKéMONy.\n"
    .string "Zasvetil jsem se jim.$"

Route13_Text_RobertDefeat::
    .string "Vybitá baterka!$"

Route13_Text_RobertPostBattle::
    .string "Kéz bych umel létat jako PIDGEY\n"
    .string "a PIDGEOTTO…$"

Route13_Text_LookToLeftOfThatPost::
    .string "TIPY PRO TRÉNÉRY\p"
    .string "Hej, hej!\n"
    .string "Podívej se nalevo od sloupu!$"

Route13_Text_SelectToSwitchItems::
    .string "TIPY PRO TRÉNÉRY\p"
    .string "Pouzij SELECT k prepnutí\n"
    .string "predmetu v okne PREDMETY.$"

Route13_Text_RouteSign::
    .string "CESTA 13\n"
    .string "Na sever k MOSTU TICHA$"

