FiveIsland_ResortGorgeous_Text_DaisyIntro::
    .string "Temahle rukama vytvorím\n"
    .string "své vítezství!$"

FiveIsland_ResortGorgeous_Text_DaisyDefeat::
    .string "Ta hanba…\n"
    .string "Jsem cervená v obliceji…$"

FiveIsland_ResortGorgeous_Text_DaisyPostBattle::
    .string "Jejda, moje tuby s barvami\n"
    .string "se rozsypaly vsude!$"

FiveIsland_ResortGorgeous_Text_CelinaIntro::
    .string "Promin!\n"
    .string "Snazím se malovat.\l"
    .string "Prosím, jdi mi z ocí!$"

FiveIsland_ResortGorgeous_Text_CelinaDefeat::
    .string "Tahle prohra…\n"
    .string "Cítím, jak se rozplyvám…$"

FiveIsland_ResortGorgeous_Text_CelinaPostBattle::
    .string "GILLIANE?\n"
    .string "Naklon prosím hlavu lehce…\l"
    .string "Tak! To je presne, co chci!$"

FiveIsland_ResortGorgeous_Text_RaynaIntro::
    .string "Hmm…\n"
    .string "Ten úhel není úplne ono…$"

FiveIsland_ResortGorgeous_Text_RaynaDefeat::
    .string "Ach…\n"
    .string "Mé pocity, ty jsou modré…$"

FiveIsland_ResortGorgeous_Text_RaynaPostBattle::
    .string "Obloha a more…\n"
    .string "Jsou tak vrtkavé.\p"
    .string "Jejich menící se vyrazy je\n"
    .string "tezké zachytit.$"

FiveIsland_ResortGorgeous_Text_JackiIntro::
    .string "Navstevuji rezidenci své\n"
    .string "prítelkyne, kdyz to musís vedet.$"

FiveIsland_ResortGorgeous_Text_JackiDefeat::
    .string "Ach, jak silny.$"

FiveIsland_ResortGorgeous_Text_JackiPostBattle::
    .string "Je mi prijemné v klidu bojovat\n"
    .string "v jemné morské bríze.$"

FiveIsland_ResortGorgeous_Text_GillianIntro::
    .string "Premyslím, ze si nechám\n"
    .string "udelat bazén pro POKéMONy.$"

FiveIsland_ResortGorgeous_Text_GillianDefeat::
    .string "Ach, propána!$"

FiveIsland_ResortGorgeous_Text_GillianPostBattle::
    .string "Bazén by byl pekny, ale musím\n"
    .string "ríct, ze slunecní pokoj by byl\l"
    .string "úzasny.$"

FiveIsland_ResortGorgeous_Text_DestinIntro::
    .string "Jsem dobry bezec.\n"
    .string "Jsem fakt rychly!$"

FiveIsland_ResortGorgeous_Text_DestinDefeat::
    .string "Jejda!\n"
    .string "Spechal jsem!$"

FiveIsland_ResortGorgeous_Text_DestinPostBattle::
    .string "Kdyz bezím s vetrem, cítím se,\n"
    .string "jako bych mohl letet!$"

FiveIsland_ResortGorgeous_Text_TobyIntro::
    .string "Tedy, ten morsky zivot tady\n"
    .string "v resortu mi sedne.$"

FiveIsland_ResortGorgeous_Text_TobyDefeat::
    .string "To je sok!\n"
    .string "Musís si delat legraci.$"

FiveIsland_ResortGorgeous_Text_TobyPostBattle::
    .string "Brát tohle tak vázne…\n"
    .string "Jaky nesmysl.$"

FiveIsland_ResortGorgeous_Text_SelphyThanksYouMayGoNow::
    .string "SELPHY: Dekuji.\p"
    .string "Muzes nyní jít.$"

FiveIsland_ResortGorgeous_Text_SelphysHouse::
    .string "DUM SELPHY$"

