SafariZone_SecretHouse_Text_CongratsYouveWon::
    .string "Ah! Konecne!\p"
    .string "Jsi první clovek, ktery\n"
    .string "dorazil k SECRET HOUSE!\p"
    .string "I kdyz jsem k nasemu velkému\n"
    .string "otevrení udelal kampan,\p"
    .string "uz jsem mel strach, ze cenu\n"
    .string "z té kampane nikdo nevyhraje.\p"
    .string "Gratuluji!\n"
    .string "Vyhrál jsi!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant::
    .string "{PLAYER} dostal HM03\n"
    .string "od obsluhy!$"

SafariZone_SecretHouse_Text_ExplainSurf::
    .string "HM03 je SURF.\p"
    .string "POKéMON s ním dokázou prevézt\n"
    .string "te pres vodu.\p"
    .string "A tohle HM se nespotrebuje, tak\n"
    .string "ho muzes pouzívat porád dokola.\p"
    .string "Más velké stestí, ze jsi vyhrál\n"
    .string "tuhle bájecnou cenu!$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize::
    .string "Nemás místo na tuhle\n"
    .string "bájecnou cenu!$"
