Text_DreamEaterTeach::
    .string "Hááá!\n"
    .string "Musel jsem usnout na slunci.\p"
    .string "Mel jsem podivny sen o tom, jak\n"
    .string "DROWZEE jí muj sen.\p"
    .string "A…\n"
    .string "Naucil jsem se, jak jíst sny…\p"
    .string "Uh, tohle je príserné!\p"
    .string "Nech me to naucit POKéMONa,\n"
    .string "at na to muzu zapomenout!$"

Text_DreamEaterDeclined::
    .string "…Chrápání…$"

Text_DreamEaterWhichMon::
    .string "Ktery POKéMON se chce naucit\n"
    .string "DREAM EATER?$"

Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "Uz…nemuzu…jíst…$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "CLEFAIRY prisel z Mesíce.\n"
    .string "Tak praví povest.\p"
    .string "Objevili se, kdyz na MT. MOON\n"
    .string "spadly MOON STONES.$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "Tady není moc serióznych POKéMON\n"
    .string "TRÉNÉRU.\p"
    .string "Jsou to vetsinou BUG CATCHERs,\n"
    .string "víte, jen hobby hráci.\p"
    .string "Ale BROCK z PEWTER GYM takovy\n"
    .string "není, ani trochu.$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "Vsiml sis MUZEA?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "Nebyly ty fosilie z MT. MOON\n"
    .string "úzasné?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "Opravdu?\n"
    .string "Tam musís rozhodne zajít!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "Tady je to, MUZEUM.\p"
    .string "Vstup je placeny, ale stojí to\n"
    .string "za to. Mej se!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Pst!\n"
    .string "Vís, co delám?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "Presne tak!\n"
    .string "Je to drina!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "Strikám REPEL, aby mi do zahrady\n"
    .string "nelezli divocí POKéMONi!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "Jsi TRÉNÉR, ze?\p"
    .string "BROCK hledá nové vyzyvatele.\n"
    .string "Pojd za mnou!$"

PewterCity_Text_GoTakeOnBrock::
    .string "Pokud na to más,\n"
    .string "jdi se postavit BROCKOVI!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "TIPY PRO TRÉNÉRY\p"
    .string "Vsichni POKéMONi, kterí se\n"
    .string "objeví v boji, získají EXP body.$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "OZNÁMENÍ!\p"
    .string "Zlodeji kradou fosilie\n"
    .string "POKéMONu z MT. MOON.\p"
    .string "Volejte PEWTER POLICII, máte-li\n"
    .string "jakékoli informace.$"

PewterCity_Text_MuseumOfScience::
    .string "PEWTER MUZEUM VED$"

PewterCity_Text_GymSign::
    .string "PEWTER CITY POKéMON GYM\n"
    .string "VÚDCE: BROCK\l"
    .string "Skálopevny POKéMON TRÉNÉR!$"

PewterCity_Text_CitySign::
    .string "PEWTER CITY\n"
    .string "Kamenne sedé mesto$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer::
    .string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "Dobre, ze jsem te dohonil.\n"
    .string "Jsem ASISTENT PROF. OAKA.\p"
    .string "Mam to tu pro tebe dorucit,\n"
    .string "tady to más.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} obdrzel\n"
    .string "BEHAVÉ BOTY od ASISTENTA.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} si vymenil boty za\n"
    .string "BEHAVÉ BOTY.$"

PewterCity_Text_ExplainRunningShoes::
    .string "Stisknutím tlacítka B pobezís.\n"
    .string "Ale jen tam, kde je dost místa!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "Tak já musím zpátky do\n"
    .string "LABORATORE.\p"
    .string "Pápá!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "Je tu pripojeny dopis…\p"
    .string "Mily {PLAYER},\p"
    .string "Tady jsou BEHAVÉ BOTY\n"
    .string "pro mého milovaného vyzyvatele.\p"
    .string "Pamatuj, vzdy ti budu fandit!\n"
    .string "Nikdy se nevzdávej!\p"
    .string "Tvoje MAMA$"

