VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "Nepokochás se rozkosnym\n"
    .string "ocáskem mé PIKACHU?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "Hmf!\p"
    .string "Moje PIKACHU je dvakrát\n"
    .string "roztomilejsí nez tahle!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "Proste zboznuju svého SEELa!\n"
    .string "Je tak rozkosny!\p"
    .string "Kdyz ho objímám, pistí\n"
    .string "“Kjúúú”!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "Ó, boze!\p"
    .string "Muj SEEL je mnohem prítaznejsí.\n"
    .string "Rekla bych, ze dvojnásobne.$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "PIKACHU: Cu! Pikacu!$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "SEEL: Kjúú!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "Predsedám POKéMON Fan Clubu!\p"
    .string "Chovám víc nez sto\n"
    .string "POKéMONu!\p"
    .string "Co se POKéMONu tyce, jsem hodne\n"
    .string "vybíravy! To teda jsem!\p"
    .string "Takze…\p"
    .string "Prisel jsi slyset o mych\n"
    .string "POKéMONech?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "Dobre!\n"
    .string "Tak poslouchej!\p"
    .string "Muj oblíbeny RAPIDASH…\p"
    .string "Je…roztomily…krásny…chytry… \n"
    .string "navíc…úzasny…nemyslís?…\l"
    .string "ó ano…je…ohromující…\l"
    .string "laskave…miluju ho!\p"
    .string "Objímat ho…kdyz spí…hreje\n"
    .string "a mazlí se…velkolepy…\l"
    .string "okouzlující…\l"
    .string "…Jejda! Koukni na hodiny!\l"
    .string "Zdrzel jsem te prílis dlouho!\p"
    .string "Díky, zes me vyslechl!\n"
    .string "Chci, abys tohle dostal!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER} dostal BIKE VOUCHER\n"
    .string "od PREDSEDY.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "Vezmi ten BIKE VOUCHER do\n"
    .string "BIKE SHOP v CERULEAN CITY.\p"
    .string "Vymen ho za BICYCLE\n"
    .string "zdarma!\p"
    .string "Neboj, muj oblíbeny FEAROW\n"
    .string "me odnese, kamkoli potrebuju.\p"
    .string "Takze já BICYCLE nepotrebuju.\p"
    .string "Doufám, ze te bavi cyklistika!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "Ó. Prijd zase, az budes chtít\n"
    .string "slyset muj príbeh!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "Ahoj, {PLAYER}!\p"
    .string "Prisel ses zase zeptat na\n"
    .string "mé POKéMONy?\p"
    .string "Ne?\n"
    .string "To je skoda!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "Udelej na tohle místo!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "Nás PREDSEDA je hodne hlasity,\n"
    .string "kdyz prijde na POKéMONy.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "Poslouchejme zdvorile\n"
    .string "ostatní TRENÉRY!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "Kdyz se nekdo chlubí, chlub se taky!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "Nás PREDSEDA opravdu zboznuje\n"
    .string "své POKéMONy.\p"
    .string "Ale clovek, kterého mají POKéMON\n"
    .string "nejradeji, je DAISY, myslím.$"
