@ All Trainer Tower text (Lobby and Roof) is interleaved here

TrainerTower_Lobby_Text_WelcomeToTrainerTower::
    .string "Ahoj!\p"
    .string "Vítej v TRAINER TOWER, kde se\n"
    .string "scházejí TRENÉRI z celého sveta!$"

TrainerTower_Lobby_Text_TrainersUpToFloorNum::
    .string "TRENÉRI z celého sveta se sem\n"
    .string "scházejí, aby bojovali.\p"
    .string "Pockej…\p"
    .string "Práve ted jsou tu TRENÉRI jen\n"
    .string "do patra {STR_VAR_1}.$"

TrainerTower_Lobby_Text_TrainersUpEighthFloor::
    .string "TRENÉRI cekají na tvou\n"
    .string "vyzvu az do osmého patra.$"

TrainerTower_Lobby_Text_LikeToChallengeTrainers::
    .string "Chtel by ses utkat s\n"
    .string "cekajícími TRENÉRY?$"

TrainerTower_Lobby_Text_StartClockGetSetGo::
    .string "Dobre, spustím hodiny,\n"
    .string "tak do toho dej vse.\p"
    .string "Pripravit…\p"
    .string "Pozor…\p"
    .string "Ted!$"

TrainerTower_Lobby_Text_PleaseVisitUsAgain::
    .string "Navstiv nás zase!$"

TrainerTower_Lobby_Text_TooBadComeBackTryAgain::
    .string "To je skoda.\p"
    .string "Myslím, ze jsi do svého boje\n"
    .string "vlozil obrovské úsilí.\p"
    .string "Prijd zase a zkus to znovu!$"

TrainerTower_Lobby_Text_GiveItYourBest::
    .string "Doufám, ze do toho dás vse.$"

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch::
    .string "Kdyz si TRENÉRI menili místa,\n"
    .string "byval pohyb dost hekticky.\p"
    .string "Abychom predesli tlacenici,\n"
    .string "presunuli jsme recepci sem.\p"
    .string "Omlouvám se za nepríjemnosti.$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly::
    .string "Ahoj…\p"
    .string "Jsem majitel téhle TOWER…\p"
    .string "Jak se obloha klene nad\n"
    .string "touhle strechou…\p"
    .string "Pohlazení vetru tady nahore…\p"
    .string "Vse je tak dokonalé…\p"
    .string "Zpusob, jak jsi bojoval…\n"
    .string "I ten byl dokonalostí…$"

TrainerTower_Roof_Text_ThisIsForYou::
    .string "Tohle je pro tebe…$"

TrainerTower_Roof_Text_DoneItInRecordTime::
    .string "Ó!\n"
    .string "Úzasné!\p"
    .string "Je úchvatné, jak rychle\n"
    .string "ses dostal az sem.\p"
    .string "Pravdou je, ze jsi to dokázal\n"
    .string "v rekordním case…\p"
    .string "Tvuj rekord nechám vyvesit\n"
    .string "na recepci.$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere::
    .string "Zdá se, ze sis dal na cas,\n"
    .string "nez ses sem dostal…$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime::
    .string "Co bych rád videl, je\n"
    .string "lepsí cas z tvé strany…\p"
    .string "Spoléhám na tebe.\p"
    .string "Do té doby sbohem…$"

TrainerTower_Text_XMinYZSec::
    .string "{STR_VAR_1} min. {STR_VAR_2}.{STR_VAR_3} sek.$"

TrainerTower_Lobby_Text_HereAreTheResults::
    .string "せいせきひょうです$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble::
    .string "Tohle je souboj dva na dva.\p"
    .string "Nemuzes bojovat, dokud nemás\n"
    .string "alespon dva POKéMONy.$"

TrainerTower_Lobby_Text_ExplainTrainerTower::
    .string "Tady v TRAINER TOWER je\n"
    .string "událost zvaná TIME ATTACK.\p"
    .string "Bude se merit, jak rychle\n"
    .string "se dostanes od recepce\l"
    .string "k MAJITELI na strese.\p"
    .string "Nejlepsí casy se zapísí na\n"
    .string "Time Board.\p"
    .string "Zkus soutezit s kamarády,\n"
    .string "kdo to zvládne nejrychleji.\p"
    .string "Za porázení TRENÉRU tady\n"
    .string "nezískás zádné EXP body ani peníze.$"

TrainerTower_Lobby_Text_ThanksForCompeting::
    .string "Díky za úcast v souteze!$"

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers::
    .string "Jsem tu, abych zjistil, jak\n"
    .string "jsem dobry.\p"
    .string "Jakí TRENÉRI na me asi\n"
    .string "cekají?\p"
    .string "Je to nervy drásající!$"

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle::
    .string "Lapám, lapám…\n"
    .string "Lapám…\p"
    .string "Co boj! Tyhle schody…\n"
    .string "Jsou tezsí nez jakykoli souboj…$"
