SixIsland_PatternBush_Text_BethanyIntro::
    .string "Zajímá me, jak chovás své\n"
    .string "POKéMONy?$"

SixIsland_PatternBush_Text_BethanyDefeat::
    .string "Chovás své POKéMONy s\n"
    .string "obrovskou láskou!$"

SixIsland_PatternBush_Text_BethanyPostBattle::
    .string "Stejne jako te tvá máma\n"
    .string "vychovávala plná lásky, bys\l"
    .string "mel chovat své POKéMONy.$"

SixIsland_PatternBush_Text_AllisonIntro::
    .string "Pracuji na zachování prírodní\n"
    .string "ekologie POKéMONu zde.$"

SixIsland_PatternBush_Text_AllisonDefeat::
    .string "Ach, na nekoho tak mladého\n"
    .string "jsi neuveritelny!$"

SixIsland_PatternBush_Text_AllisonPostBattle::
    .string "Neríkám, ze by ses nemel\n"
    .string "chytat POKéMONy.\p"
    .string "Jen chci, aby lidé chovali\n"
    .string "POKéMONy zodpovedne.$"

SixIsland_PatternBush_Text_GarretIntro::
    .string "Chytil jsem BUG POKéMONa,\n"
    .string "ktery zije jen tady!$"

SixIsland_PatternBush_Text_GarretDefeat::
    .string "Hehe…\n"
    .string "Není muj POKéMON úzasny?$"

SixIsland_PatternBush_Text_GarretPostBattle::
    .string "U BUSHe je holcicka, co\n"
    .string "merí HERACROSSe TRÉNÉRum.$"

SixIsland_PatternBush_Text_JonahIntro::
    .string "Vís, prijde mi divné, kdyz\n"
    .string "nepouzívám BUG POKéMONy.$"

SixIsland_PatternBush_Text_JonahDefeat::
    .string "To nic, prohrávání je zábavná\n"
    .string "soucást POKéMON kouzla.$"

SixIsland_PatternBush_Text_JonahPostBattle::
    .string "Mimochodem, “kouzlo” je divné\n"
    .string "slovo, kdyz se nad ním zamyslís.$"

SixIsland_PatternBush_Text_VanceIntro::
    .string "Jo, jo, jo!\n"
    .string "Podívej na vsechny BUG POKéMONy!$"

SixIsland_PatternBush_Text_VanceDefeat::
    .string "Dostal jsem to, kdyz jsem se\n"
    .string "porád radoval!$"

SixIsland_PatternBush_Text_VancePostBattle::
    .string "Príste sem privedu mladsího\n"
    .string "bratra.$"

SixIsland_PatternBush_Text_NashIntro::
    .string "Podívej, podívej! Na zemi jsou\n"
    .string "smesné vzory.$"

SixIsland_PatternBush_Text_NashDefeat::
    .string "Super úzasné!$"

SixIsland_PatternBush_Text_NashPostBattle::
    .string "Ty smesné vzory na zemi…\p"
    .string "Vypadají jako vzory na satech\n"
    .string "mého dedy.$"

SixIsland_PatternBush_Text_CordellIntro::
    .string "Vsadím se, ze si myslís, ze\n"
    .string "jsem jen obycejny chlapík, hm?$"

SixIsland_PatternBush_Text_CordellDefeat::
    .string "Vsadím se, ze si myslís, ze\n"
    .string "jsem slaby, hm?$"

SixIsland_PatternBush_Text_CordellPostBattle::
    .string "Jasné, vy mestská cháska sem\n"
    .string "chodíte vsichni nóbl s parádním\l"
    .string "kloboukem…\p"
    .string "Co kdybys mi ho dal?$"

SixIsland_PatternBush_Text_DaliaIntro::
    .string "Zhluboka se nadechni.\n"
    .string "Není vzduch lahodny?$"

SixIsland_PatternBush_Text_DaliaDefeat::
    .string "Kdyz chces, naucím te správne\n"
    .string "dychat.$"

SixIsland_PatternBush_Text_DaliaPostBattle::
    .string "Nejdrív vydechni.\n"
    .string "Vyfoukni vsechno ven.\p"
    .string "Az uz nemuzes vydechovat,\n"
    .string "nadechni cisty vzduch!\p"
    .string "Není to osvezující?$"

SixIsland_PatternBush_Text_JoanaIntro::
    .string "Miluji BUG POKéMONy.\n"
    .string "Proto jsem tu porád.\p"
    .string "Jsem jediná holka taková?$"

SixIsland_PatternBush_Text_JoanaDefeat::
    .string "Prohrála jsem, ale porád se\n"
    .string "smeji. Jsem jediná taková?$"

SixIsland_PatternBush_Text_JoanaPostBattle::
    .string "Budu dál sbírat BUG POKéMONy.\p"
    .string "Jsem jediná holka taková?$"

SixIsland_PatternBush_Text_RileyIntro::
    .string "Tohle je dobré místo.\n"
    .string "Tady si postavím stan.$"

SixIsland_PatternBush_Text_RileyDefeat::
    .string "Vykasal jsem se na to…$"

SixIsland_PatternBush_Text_RileyPostBattle::
    .string "Budu tu pozorovat nocní\n"
    .string "oblohu.$"

SixIsland_PatternBush_Text_MarcyIntro::
    .string "Fuj!\n"
    .string "Myslím, ze me stípl brouk!$"

SixIsland_PatternBush_Text_MarcyDefeat::
    .string "Nebyl to brouk.\n"
    .string "Porezala jsem si holen o trávu.$"

SixIsland_PatternBush_Text_MarcyPostBattle::
    .string "Takovy maly porez…\n"
    .string "Trochu sliny stací k uzdravení!$"

SixIsland_PatternBush_Text_LaytonIntro::
    .string "Vsiml sis neceho zvlástního\n"
    .string "v techto místech?$"

SixIsland_PatternBush_Text_LaytonDefeat::
    .string "Podíval ses dobre kolem\n"
    .string "svych nohou?$"

SixIsland_PatternBush_Text_LaytonPostBattle::
    .string "V PATTERN BUSH jsou místa,\n"
    .string "kde tráva neroste.\p"
    .string "Co by mohlo zpusobit\n"
    .string "takovy jev?$"

