SSAnne_1F_Room6_Text_TakeAShortRest::
    .string "Vypadás unavene. Chces si\n"
    .string "krátce odpocinout?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
    .string "Tesí me, ze vsichni vypadají\n"
    .string "svezí a v pohode.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
    .string "Promin, ze se o tebe starám.\n"
    .string "Vypadás jako muj bratrícek…$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
    .string "Promin, ze se o tebe starám.\n"
    .string "Vypadás jako má sestricka…$"
