SixIsland_Text_IslandSign::
    .string "SIX ISLAND\n"
    .string "Fortune Island of Aged Wisdom$"

SixIsland_Text_ThatWayToWaterPathRuinValley::
    .string "Jdi porád tudy a dostanes\n"
    .string "se na WATER PATH.\p"
    .string "Zustan na ní a dostanes\n"
    .string "se do RUIN VALLEY.$"

SixIsland_Text_SkyAtNightIsFantastic::
    .string "Kdyz jsi tak daleko od mesta,\n"
    .string "nocní obloha je fantastická.$"

