LavenderTown_House2_Text_WantMeToRateNicknames::
    .string "Zdravím, zdravím!\n"
    .string "Jsem oficiální HODNOTITEL JMEN!\p"
    .string "Chces, abych ohodnotil prezdívky\n"
    .string "tvych POKéMONu?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
    .string "Kterého POKéMONa prezdívku\n"
    .string "mám zhodnotit?$"

LavenderTown_House2_Text_GiveItANicerName::
    .string "{STR_VAR_1}, ano?\n"
    .string "To je slusná prezdívka!\p"
    .string "Ale chtel bys, abych mu dal\n"
    .string "hezcí jméno?\p"
    .string "Co ty na to?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe::
    .string "Ach, dobre. A jaké bude\n"
    .string "to nové jméno?$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
    .string "Hotovo! Od ted bude tento POKéMON\n"
    .string "znám jako {STR_VAR_1}!\p"
    .string "Je to lepsí jméno nez predtím!\n"
    .string "Mas stestí!$"

LavenderTown_House2_Text_ISeeComeVisitAgain::
    .string "Aha.\n"
    .string "Prijd zas nekdy.$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
    .string "Hotovo! Od ted bude tento POKéMON\n"
    .string "znám jako {STR_VAR_1}!\p"
    .string "Vypadá to stejne jako predtím,\n"
    .string "presto je to nesrovnatelne lepsí!\p"
    .string "Mas stestí!$"

LavenderTown_House2_Text_TrulyImpeccableName::
    .string "{STR_VAR_1}, ano?\n"
    .string "To je opravdu bezchybné jméno!\p"
    .string "Dobre se o {STR_VAR_1} starej!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg::
    .string "No no.\n"
    .string "To je jen VAJÍCKO!$"

