Text_MetronomeTeach::
    .string "Cik-cak-cik!\n"
    .string "Naucím te jeden sikovny útok.\p"
    .string "Nauc ho POKéMONa a sleduj\n"
    .string "tu zábavu!\p"
    .string "Je to útok jménem METRONOME.\n"
    .string "Zaujal te?$"

Text_MetronomeDeclined::
    .string "Ríkám ti, je to velká zábava!$"

Text_MetronomeWhichMon::
    .string "Dobre!\n"
    .string "Kterého POKéMONa mám naucit?$"

Text_MetronomeTaught::
    .string "Cik-cak-cik!\n"
    .string "To je zvuk METRONOMu.\p"
    .string "Naladí mozek tvého POKéMONa\n"
    .string "na útoky, které ani nezná.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
    .string "Cau!\p"
    .string "Já dulezity doktor.\n"
    .string "Ano, velmi, opravdu.\p"
    .string "Tady studuji vzácné fosílie\n"
    .string "POKéMONu. Stále studuji.\p"
    .string "Ty!\n"
    .string "Mas pro me fosílii?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .string "Ne!\n"
    .string "To velká skoda!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
    .string "ちょっと　じかん　かかるよ！\p"
    .string "そこらへんを　すこし\n"
    .string "ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .string "Ty pozde.\n"
    .string "Kde jsi byl?\p"
    .string "Tvá fosílie je zpet zive!\n"
    .string "Byla {STR_VAR_1} jak já myslel!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .string "{PLAYER} dostal {STR_VAR_1}\n"
    .string "od doktora.$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
    .string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .string "Och!\n"
    .string "To je {STR_VAR_2}, to ano!\p"
    .string "To je fosílie {STR_VAR_1},\n"
    .string "POKéMON, ktery je jiz vyhynuly!\p"
    .string "Muj Vzkrísovací stroj toho\n"
    .string "POKéMONa privede zase k zivotu!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .string "Tak!\n"
    .string "Honem mi to dej!\p"
    .string "{FONT_NORMAL}{PLAYER} predal\n"
    .string "{STR_VAR_2} podivnému doktorovi.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .string "Já beru malou chvíli!\n"
    .string "Ty jdi se chvíli projít!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .string "Ajaj!\n"
    .string "Ty prijdes zase!$"

