SilphCo_6F_Text_RocketsTookOverBuilding::
    .string "ROCKETI prisli a zabrali\n"
    .string "budovu!$"

SilphCo_6F_Text_BetterGetBackToWork::
    .string "No, radsi zpátky do práce.$"

SilphCo_6F_Text_HelpMePlease::
    .string "Ach jo, ach jo.\n"
    .string "Pomoz mi, prosím!$"

SilphCo_6F_Text_WeGotEngaged::
    .string "Zasnoubili jsme se.\n"
    .string "Hehe!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
    .string "Ten muz vedle me…\n"
    .string "Je takovy zbabelec!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
    .string "Je tak bezmocny, potreboval\n"
    .string "me, abych se o nej starala.$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
    .string "TEAM ROCKET se snazí dobyt\n"
    .string "svet s POKéMONy.$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
    .string "TEAM ROCKET utekl, a je to\n"
    .string "vsechno díky tobe!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
    .string "Asi si vybrali SILPH kvuli\n"
    .string "nasim POKéMON produktum.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
    .string "Az budes starsí, prijd\n"
    .string "pracovat pro SILPH.$"

SilphCo_6F_Text_Grunt1Intro::
    .string "Já jsem jeden ze ctyr\n"
    .string "BRATRU ROCKETU!$"

SilphCo_6F_Text_Grunt1Defeat::
    .string "Vyhasl jsem!$"

SilphCo_6F_Text_Grunt1PostBattle::
    .string "Nevadí!\n"
    .string "Mí bratri me pomstí!$"

SilphCo_6F_Text_TaylorIntro::
    .string "Ten zatraceny REDITEL!\p"
    .string "Spravne mu patrí, ze me poslal\n"
    .string "do pobocky TIKSI!\p"
    .string "Proto si nás TEAM ROCKET dosel,\n"
    .string "jsem si tím jisty!$"

SilphCo_6F_Text_TaylorDefeat::
    .string "Sakra!$"

SilphCo_6F_Text_TaylorPostBattle::
    .string "Pobocka TIKSI?\n"
    .string "To je v ruské pustine!$"

SilphCo_6F_Text_Grunt2Intro::
    .string "Opovazujes se zradit TEAM ROCKET?$"

SilphCo_6F_Text_Grunt2Defeat::
    .string "Zrádce!$"

SilphCo_6F_Text_Grunt2PostBattle::
    .string "Kdyz stojís za právem, zradís\n"
    .string "nás, zlocince!$"

SilphCo_6F_Text_FloorSign::
    .string "SILPH CO. HLAVNÍ KANCELÁR\n"
    .string "6F$"
