VictoryRoad_2F_Text_DawsonIntro::
    .string "Jestli se sem dostanes,\n"
    .string "muzes potkat ELITE FOUR.$"

VictoryRoad_2F_Text_DawsonDefeat::
    .string "Ne!\n"
    .string "Neuveritelné!$"

VictoryRoad_2F_Text_DawsonPostBattle::
    .string "Co se znalostí o POKéMONech\n"
    .string "tyce, tam te porazím!$"

VictoryRoad_2F_Text_DaisukeIntro::
    .string "Tohle je VICTORY ROAD.\n"
    .string "Poslední test pro TRENÉRY!$"

VictoryRoad_2F_Text_DaisukeDefeat::
    .string "Acho!$"

VictoryRoad_2F_Text_DaisukePostBattle::
    .string "Kdyz se zaseknes, zkus\n"
    .string "posunout nejaké balvany.$"

VictoryRoad_2F_Text_NelsonIntro::
    .string "Ah, tak ty chces vyzvat\n"
    .string "ELITE FOUR?$"

VictoryRoad_2F_Text_NelsonDefeat::
    .string "Dostal jsi me!$"

VictoryRoad_2F_Text_NelsonPostBattle::
    .string "{RIVAL} tudy taky prosel.$"

VictoryRoad_2F_Text_VincentIntro::
    .string "Pojd na to!\n"
    .string "Zmáknu te!$"

VictoryRoad_2F_Text_VincentDefeat::
    .string "Dostal jsem na frak!$"

VictoryRoad_2F_Text_VincentPostBattle::
    .string "Vyslouzil sis právo byt na\n"
    .string "VICTORY ROAD…$"

VictoryRoad_2F_Text_GregoryIntro::
    .string "Je VICTORY ROAD moc tezká?$"

VictoryRoad_2F_Text_GregoryDefeat::
    .string "Dobrá práce!$"

VictoryRoad_2F_Text_GregoryPostBattle::
    .string "Spousta TRENÉRU tady vzdá svou\n"
    .string "vyzvu a jde domu.$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo::
    .string "ギヤーオ！$"
