Text_RockSlideTeach::
    .string "Kdyz jsi nahore na skalnaté\n"
    .string "hore jako tady, hrozí sesuvy.\p"
    .string "Predstavís si to?\n"
    .string "Balvany se na tebe valí?\p"
    .string "To by bylo jako, ááááááá!\n"
    .string "Naprostá hruza!\p"
    .string "Nezdá se, ze bys mel strach.\n"
    .string "Chces zkusit pouzít ROCK SLIDE?$"

Text_RockSlideDeclined::
    .string "Ó, tak ty se prece jen bojís.$"

Text_RockSlideWhichMon::
    .string "Kterého POKéMONa mám naucit\n"
    .string "ROCK SLIDE?$"

Text_RockSlideTaught::
    .string "V tomhle tunelu by mohlo byt\n"
    .string "strasidelné to pouzít…$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string "Tip: Balvany mohou zmenit\n"
    .string "proud vody.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "NEBEZPECÍ\n"
    .string "Rychly proud!$"
