ThreeIsland_House2_Text_CantMakeThisSpoonBend::
    .string "Urrrrrrrrgggghhhh…\n"
    .string "Kwaaaaah!\p"
    .string "…Je to k nicemu! Nemuzu ohnout\n"
    .string "tu lzíci silou své mysli.\p"
    .string "Mozná opravdu nemám zádné\n"
    .string "psychické schopnosti.$"

ThreeIsland_House2_Text_IAdmireSabrina::
    .string "Vís o dívce, GYM LEADERCE\n"
    .string "v SAFFRON CITY?\p"
    .string "Pouzívá PSYCHIC POKéMONy,\n"
    .string "vid?\p"
    .string "Obdivuji ji, opravdu.\p"
    .string "Slysela jsem, ze je jedna\n"
    .string "úzasná osoba a navíc krásná.$"

