Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .string "Ahoj! Pamatujes si me?\n"
    .string "Jsem jeden z ASISTENTU PROF. OAKA.\p"
    .string "Pokud má tvuj POKéDEX kompletní\n"
    .string "data o {STR_VAR_1} druzích, mám ti\l"
    .string "dát odmenu.\p"
    .string "PROF. OAK mi pro tebe\n"
    .string "sveril {STR_VAR_2}.\p"
    .string "Tak, {PLAYER}, dovol mi otázku.\p"
    .string "Nasbíral jsi data alespon\n"
    .string "o {STR_VAR_1} druzích POKéMONu?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .string "Skvele! Chytil nebo vlastnil\n"
    .string "jsi {STR_VAR_3} druhu POKéMONu!\p"
    .string "Gratuluji!\n"
    .string "Tu más!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .string "{PLAYER} dostal {STR_VAR_2}\n"
    .string "od ASISTENTA.$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .string "Na zemi jsou predmety, které\n"
    .string "mohou byt skryté pohledu.\p"
    .string "Pomocí ITEMFINDER odhalís\n"
    .string "skryté predmety blízko tebe.\p"
    .string "Ten stroj je trochu omezeny.\n"
    .string "Nedokáze urcit presné místo.\p"
    .string "Umí jen ukázat smer,\n"
    .string "kde predmet je.\p"
    .string "Pouzij ho k orientaci a pak\n"
    .string "podezrelou oblast prohledej rukou.$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .string "Mrkneme se, co ukázou\n"
    .string "dalekohledy…\p"
    .string "Na ceste spí velky POKéMON!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .string "Mrkneme se, co ukázou\n"
    .string "dalekohledy…\p"
    .string "To je dech beroucí vyhled!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .string "Mrkneme se, co ukázou\n"
    .string "dalekohledy…\p"
    .string "Cesta do LAVENDER TOWN\n"
    .string "z CERULEAN CITY…\p"
    .string "ROCK TUNNEL se zdá byt\n"
    .string "dobrou trasou.$"
