CeruleanCity_Gym_Text_MistyIntro::
    .string "Ahoj, novácku!\p"
    .string "Profesionálem se mohou stát jen\n"
    .string "TRÉNÉRI s jasnou filozofií.\p"
    .string "Jakym zpusobem ty chytás a\n"
    .string "trénujes svoje POKéMONy?\p"
    .string "Moje filozofie je totální útok\n"
    .string "s POKéMONy typu VODA!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "TM03 ucí WATER PULSE.\p"
    .string "Pouzij ji na vodního POKéMONa!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "CASCADEBADGE zarídí, ze te\n"
    .string "poslechnou POKéMONi do Lv. 30.\p"
    .string "I cizí, které jsi získal\n"
    .string "ve vymene.\p"
    .string "A jeste víc. Ted muzes pouzít CUT\n"
    .string "kdykoliv, i mimo souboj.\p"
    .string "Muzes ostrihnout malé stromky\n"
    .string "a otevrít si nové cesty.\p"
    .string "Také ti dám muj oblíbeny TM.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER} dostal TM03\n"
    .string "od MISTY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "Udelej si na to místo!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Páni!\n"
    .string "Ty jsi neco!\p"
    .string "Dobre!\p"
    .string "Mas CASCADEBADGE jako dukaz,\n"
    .string "ze jsi me porazil.$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "Co? Ty?\n"
    .string "Já ti stacím a víc!\p"
    .string "MISTY se s tebou nemusí trápit.$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "Smetl jsi me!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "Musís se postavit dalsím\n"
    .string "TRÉNÉRum, aby ses zlepsil.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "Splas!\p"
    .string "Jsem první!\n"
    .string "Jdeme na to!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "To není mozné!$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "MISTY je TRÉNÉR, ktery se\n"
    .string "porád zlepsuje.\p"
    .string "Nikomu jako tobe neprohraje!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "Hej!\n"
    .string "Sampión v rodu!\p"
    .string "Dám ti pár rad!\p"
    .string "VÚDKYNE MISTY je profík, ktery\n"
    .string "pouzívá POKéMONy typu VODA.\p"
    .string "Veskerou vodu z nich vysajes\n"
    .string "POKéMONy typu TRÁVA.\p"
    .string "Nebo muzes pouzít POKéMONy\n"
    .string "typu ELEKTRO a sezehnout je!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "Porazil jsi MISTY!\n"
    .string "Vidís, ríkal jsem ti to?\p"
    .string "Ty a já, kámo, jsme docela\n"
    .string "slusny tym!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "CERULEAN POKéMON GYM\n"
    .string "VÚDCE: MISTY\p"
    .string "VÍTEZNÍ TRÉNÉRI:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "CERULEAN POKéMON GYM\n"
    .string "VÚDCE: MISTY\p"
    .string "VÍTEZNÍ TRÉNÉRI:\n"
    .string "{RIVAL}, {PLAYER}$"

