PokemonTower_4F_Text_PaulaIntro::
    .string "Duch! Ne!\n"
    .string "Kwaaah!$"

PokemonTower_4F_Text_PaulaDefeat::
    .string "Kde je ten duch?$"

PokemonTower_4F_Text_PaulaPostBattle::
    .string "Asi se mi to jen zdálo…$"

PokemonTower_4F_Text_LaurelIntro::
    .string "Bud proklet se mnou!\n"
    .string "Kwaaah!$"

PokemonTower_4F_Text_LaurelDefeat::
    .string "Coze!$"

PokemonTower_4F_Text_LaurelPostBattle::
    .string "Nemuzeme urcit identitu\n"
    .string "techto duchu…$"

PokemonTower_4F_Text_JodyIntro::
    .string "Huhuhu…\n"
    .string "Neporaz me!$"

PokemonTower_4F_Text_JodyDefeat::
    .string "Coze?\n"
    .string "Kdo? Co?$"

PokemonTower_4F_Text_JodyPostBattle::
    .string "Necht zesnulí POKéMONi odpocívají\n"
    .string "v pokoji…$"

