@ The 5 texts below are supposed to be in FourIsland_House1
Text_BodySlamTeach::
    .string "Pripraven?\n"
    .string "Boing!\p"
    .string "Máme BODY SLAM zápas,\n"
    .string "kdo první vzdá.\p"
    .string "Kdyby ses k nám pripojil,\n"
    .string "byl bys rozplácnut jako brouk…\p"
    .string "Co kdybych naucil BODY SLAM\n"
    .string "nekterému z tvych POKéMONu?$"

Text_BodySlamDeclined::
    .string "Prijd zase!\n"
    .string "Boing!$"

Text_BodySlamWhichMon::
    .string "Ktery POKéMON se chce naucit\n"
    .string "BODY SLAM?$"

Text_BodySlamTaught::
    .string "Boioing!$"

FourIsland_House1_Text_FatMan::
    .string "それ　ぼよーん！\n"
    .string "おまえ　おもいなあー！$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave::
    .string "V jeskyni zije vzácny\n"
    .string "ICE POKéMON.\p"
    .string "Máme tu hodne návstevníku,\n"
    .string "kterí ho chtejí videt.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore::
    .string "Coze? POKéMON VEJCE?\n"
    .string "…Netusím.\p"
    .string "…Pockej. DAY-CARE lidé ve\n"
    .string "meste neco ríkali.\p"
    .string "Ríkali, ze nasli VEJCE\n"
    .string "na svém pozemku.$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived::
    .string "Co je tohle?\p"
    .string "Novy POKéMON JOURNAL nedorazil\n"
    .string "na tento ostrov?$"

