Route9_Text_AliciaIntro::
    .string "Mas u sebe POKéMONy!\n"
    .string "Jsi muj!$"

Route9_Text_AliciaDefeat::
    .string "Oklamal jsi me…$"

Route9_Text_AliciaPostBattle::
    .string "Tunel pred námi je uvnitr\n"
    .string "úplne cerny.\p"
    .string "Budes potrebovat FLASH, abys\n"
    .string "ho prosel.$"

Route9_Text_ChrisIntro::
    .string "Kdo to tu chodí s tak\n"
    .string "krásnymi POKéMONy?$"

Route9_Text_ChrisDefeat::
    .string "Vypl jsem se!$"

Route9_Text_ChrisPostBattle::
    .string "Bezme dál!$"

Route9_Text_DrewIntro::
    .string "Jdu pres ROCK TUNNEL do\n"
    .string "LAVENDERU…$"

Route9_Text_DrewDefeat::
    .string "Nevyrovnám se ti…$"

Route9_Text_DrewPostBattle::
    .string "Mírís taky do ROCK TUNNELU?$"

Route9_Text_CaitlinIntro::
    .string "Neopovaz se na me povysovat!$"

Route9_Text_CaitlinDefeat::
    .string "Ne!\n"
    .string "Jsi az moc dobry.$"

Route9_Text_CaitlinPostBattle::
    .string "Jsi zrejme talentovany.\n"
    .string "Hodne stestí!$"

Route9_Text_JeremyIntro::
    .string "Bvahaha!\n"
    .string "Skvele! Nudil jsem se, hm!$"

Route9_Text_JeremyDefeat::
    .string "Pokracuj, hm!\p"
    .string "Ach pockej.\n"
    .string "Doslo mi POKéMONu!$"

Route9_Text_JeremyPostBattle::
    .string "Mel jsi pred mnou koule, hm?$"

Route9_Text_BriceIntro::
    .string "Hahaha!\n"
    .string "Ty jsi taková tvrdá!$"

Route9_Text_BriceDefeat::
    .string "Co to bylo?$"

Route9_Text_BricePostBattle::
    .string "Hahaha!\n"
    .string "Deti mají byt tvrdé!$"

Route9_Text_BrentIntro::
    .string "Vstával jsem brzo kazdy den, abych\n"
    .string "POKéMONy choval od kukel!$"

Route9_Text_BrentDefeat::
    .string "CO?\p"
    .string "To je úplná ztráta casu!$"

Route9_Text_BrentPostBattle::
    .string "Musím sbírat víc nez jen brouky,\n"
    .string "abych byl silnejsí…$"

Route9_Text_AlanIntro::
    .string "Hahahaha!\n"
    .string "Tak do toho!$"

Route9_Text_AlanDefeat::
    .string "Hahahaha!\n"
    .string "Porazil jsi me férove!$"

Route9_Text_AlanPostBattle::
    .string "Hahahaha!\n"
    .string "My silácí se vzdy smejeme!$"

Route9_Text_ConnerIntro::
    .string "Jdi, muj super BUG POKéMONe!$"

Route9_Text_ConnerDefeat::
    .string "Mí brouci…$"

Route9_Text_ConnerPostBattle::
    .string "Kdyz nemás rád BUG POKéMONy,\n"
    .string "stezujes mi to!$"

Route9_Text_RouteSign::
    .string "CESTA 9\n"
    .string "CERULEAN CITY - ROCK TUNNEL$"

