SevenIsland_TrainerTower_Text_DarioIntro::
    .string "Cítil jsem tvuj príchod.$"

SevenIsland_TrainerTower_Text_DarioDefeat::
    .string "Vzdávám se…$"

SevenIsland_TrainerTower_Text_DarioPostBattle::
    .string "Ve tvé budoucnosti cítím, ze\n"
    .string "potkás mnoho dalsích.\p"
    .string "Myslím, ze budete spojeni\n"
    .string "podivnou silou.$"

SevenIsland_TrainerTower_Text_RodetteIntro::
    .string "Nekde na tomto ostrove spí\n"
    .string "zvlástní POKéMONi.$"

SevenIsland_TrainerTower_Text_RodetteDefeat::
    .string "Jaky úzasny TRÉNÉR!$"

SevenIsland_TrainerTower_Text_RodettePostBattle::
    .string "Nekde na tomto ostrove spí\n"
    .string "zvlástní POKéMONi.\p"
    .string "Nemohou na tebe cekat?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign::
    .string "VCHOD DO TRAINER TOWER\n"
    .string "Prijmete vyzvu, TRÉNÉRI!$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead::
    .string "TRAINER TOWER PRED VÁMI$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed::
    .string "トレーナータワーには\n"
    .string "いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn::
    .string "トレーナータワーが　あいてる！\n"
    .string "さっそく　はいってみよう！$"

