PokemonMansion_B1F_Text_LewisIntro::
    .string "Ouha…\n"
    .string "Kde to ted jsem?$"

PokemonMansion_B1F_Text_LewisDefeat::
    .string "Auvajs!$"

PokemonMansion_B1F_Text_LewisPostBattle::
    .string "Najdes tu veci povalující se.\n"
    .string "Nájemníci je museli nechat.$"

PokemonMansion_B1F_Text_IvanIntro::
    .string "Tohle je ideální místo pro lab.\n"
    .string "Koukni na ten prostor.$"

PokemonMansion_B1F_Text_IvanDefeat::
    .string "Za co to bylo?$"

PokemonMansion_B1F_Text_IvanPostBattle::
    .string "Tady se mi líbí.\n"
    .string "Vede ke studiu.$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
    .string "Deník: 1. zárí\n"
    .string "MEWTWO je prílis silny.\p"
    .string "Nepodarilo se nám zkrotit jeho\n"
    .string "krutost…$"
