CinnabarIsland_Gym_Text_BlaineIntro::
    .string "Ha!\p"
    .string "Já jsem BLAINE, rozzhaveny VÚDCE\n"
    .string "CINNABAR GYMu!\p"
    .string "Mí ohniví POKéMONi jsou\n"
    .string "drsní s palcivym zárem!\p"
    .string "Spálí vsechny vyzyvatele!\p"
    .string "Ha!\n"
    .string "Mas BURN HEAL?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "Shorel jsem na popel!\n"
    .string "Ani popel nezbyl!\p"
    .string "Získal jsi VOLCANOBADGE.$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .string "FIRE BLAST je nejvyssí\n"
    .string "ohnivá technika.\p"
    .string "Nemarni ho na VODNÍ POKéMONy.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "Ha!\p"
    .string "VOLCANOBADGE zvysuje SPECIÁLNÍ\n"
    .string "staty tvych POKéMONu.\p"
    .string "Vezmi si také tohle!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .string "{PLAYER} dostal TM38\n"
    .string "od BLAINEa.$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "TM38 obsahuje FIRE BLAST.\n"
    .string "Naucte ho ohnivym POKéMONum.\p"
    .string "VULPIX nebo CHARMELEON\n"
    .string "jsou pro nej ideální.$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "Udelej si na tohle místo, dítko!$"

CinnabarIsland_Gym_Text_ErikIntro::
    .string "Vís, jak horky muze byt ohnivy\n"
    .string "dech POKéMONa?$"

CinnabarIsland_Gym_Text_ErikDefeat::
    .string "Au!\n"
    .string "Horké, horké, horké!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
    .string "Ohen, nebo presneji\n"
    .string "spalování…\p"
    .string "…Kyslík ve vzduchu…\n"
    .string "Bla, bla, bla, bla…$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "Byval jsem zlodej, ale\n"
    .string "stal se ze me TRÉNÉR.$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "Vzdávám se!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "Mám nezvladatelnou chut\n"
    .string "krást cizí POKéMONy.$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "Prostudoval jsem POKéMONy.\n"
    .string "Nemuzes vyhrát!$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "Aaah!\n"
    .string "Mé studium nestacilo!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "Mé teorie jsou príli\n"
    .string "slozité, abys je pochopil.$"

CinnabarIsland_Gym_Text_RamonIntro::
    .string "Mám rád OHNIVÉ POKéMONy.\n"
    .string "Prosté mám.$"

CinnabarIsland_Gym_Text_RamonDefeat::
    .string "Príli horké!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
    .string "Kdyby existoval zlodejsky\n"
    .string "POKéMON, vzal bych si ho!$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "Vím, proc se BLAINE stal\n"
    .string "TRÉNÉREM.$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "Au!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "Nás VÚDCE BLAINE jednou\n"
    .string "zabloudil v horách.\p"
    .string "Padla noc a objevil se\n"
    .string "ohnivy ptací POKéMON.\p"
    .string "Jeho svetlo umoznilo\n"
    .string "BLAINEovi najít cestu dolu.$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "Byl jsem v mnoha GYMech, ale\n"
    .string "tenhle mi vyhovuje nejvíc.$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "Jauvajs!\n"
    .string "Príli horké!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "PONYTA, NINETALES…\n"
    .string "To jsou oblíbení OHNIVÍ POKéMONi.$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "Ohen je slaby proti H2O.$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "Och!\n"
    .string "Uhasen!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "Voda samozrejme poráí ohen.\p"
    .string "Ale ohen taví led, takze OHNIVY\n"
    .string "typ poráí LEDOVÉ POKéMONy.$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "Jo!\n"
    .string "Budoucí sampione!\p"
    .string "Horkokrevny BLAINE je profík\n"
    .string "na OHNIVÉ POKéMONy.\p"
    .string "Uhas jeho nadsení vodou!\p"
    .string "Mel by sis vzít taky\n"
    .string "nejaké BURN HEALY.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "{PLAYER}!\n"
    .string "Porazil jsi toho ohnivce!$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "CINNABAR POKéMON GYM\n"
    .string "VÚDCE: BLAINE\p"
    .string "VÍTEZNÍ TRÉNÉRI:\n"
    .string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "CINNABAR POKéMON GYM\n"
    .string "VÚDCE: BLAINE\p"
    .string "VÍTEZNÍ TRÉNÉRI:\n"
    .string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "POKéMON Kvíz!\p"
    .string "Odpovez správne a otevrou se\n"
    .string "dvere do dalsí místnosti.\p"
    .string "Odpovez spatne a celís TRÉNÉROVI!\p"
    .string "Pokud chces setrit POKéMONy\n"
    .string "pro VÚDCE GYMu…\p"
    .string "Pak odpovídej správne!\n"
    .string "Tak jdeme na to!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "CATERPIE se vyvine v METAPODA?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "Existuje devet oficiálních\n"
    .string "ODZNAKU POKéMON LIGY?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "POLIWAG se vyvíjí trikrát?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "Jsou elektrické útoky úcinné\n"
    .string "proti ZEMNÍM POKéMONum?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "POKéMONi stejného druhu a úrovne\n"
    .string "nejsou identictí?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "TM28 obsahuje TOMBSTONY?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "Naprosto správne!\p"
    .string "Projdi dál!$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "Bohuzel!\n"
    .string "Spatne!$"

