ThreeIsland_Text_IslandSign::
    .string "THREE ISLAND\n"
    .string "Kin Island rodinného pouta$"

ThreeIsland_Text_IslandBelongsToUs::
    .string "Hyahoo!\p"
    .string "Od dnesního dne tento ostrov\n"
    .string "patrí nám!$"

ThreeIsland_Text_GoBackToKanto::
    .string "Nepotrebujeme tu lidi, kterí\n"
    .string "delají hluk a potíze!\p"
    .string "Zádáme vás, abyste se vrátili\n"
    .string "do KANTA!$"

ThreeIsland_Text_BossIsOnHisWay::
    .string "Hej, jdi recnit jinam.\n"
    .string "Nás séf je na ceste.\p"
    .string "Az dorazí, ukázeme vám\n"
    .string "skvelou motorkárskou show, na\l"
    .string "kterou nezapomenete!$"

ThreeIsland_Text_GetOffIslandNow::
    .string "C-coze!? Ani náhodou!\n"
    .string "Vypadnete z ostrova!$"

ThreeIsland_Text_WhosGonnaMakeMe::
    .string "Kdo me k tomu donutí?$"

ThreeIsland_Text_AreYouBossGoBackToKanto::
    .string "Ty jsi ten sefík?\n"
    .string "Vrat se do KANTA hned ted!$"

ThreeIsland_Text_JustGotHerePal::
    .string "Hah?\p"
    .string "Práve jsem dorazil, kámo.\p"
    .string "Co je s tím neprátelskym postojem?\n"
    .string "Je to od tebe chladné!$"

ThreeIsland_Text_FollowersRaisingHavoc::
    .string "Tvá banda následovníku decimuje\n"
    .string "ostrov svymi motorkami.\p"
    .string "Más predstavu, kolik problému\n"
    .string "nám na ostrove zpusobili?$"

ThreeIsland_Text_OughtToBeThankingUs::
    .string "Ne, kámo, vubec to nechápu.\p"
    .string "Podívej se na tohle místo.\n"
    .string "Co tu deláte pro zábavu?\p"
    .string "Meli byste nám podekovat za\n"
    .string "ozivení této ospalé vesnice.\p"
    .string "Ale hej, jestli trvás, muzes\n"
    .string "zkusit nás vyhnat.$"

ThreeIsland_Text_YouCowardsToughInPack::
    .string "Grr… Vy zbabelci…\n"
    .string "Ve smecce tak tvrdí…$"

ThreeIsland_Text_WannaMakeSomethingOfYourStaring::
    .string "Ty, na co civís?\n"
    .string "Vís, ze to není slusné?\p"
    .string "Chces s tím neco delat,\n"
    .string "nebo co?$"

ThreeIsland_Text_ThatsSmart::
    .string "Tohle je chytré.\n"
    .string "Nestrkej do toho nos.$"

ThreeIsland_Text_Biker1Intro::
    .string "He, líbí se mi tvá kuráz.\n"
    .string "Prijdes o peníze, ale…$"

ThreeIsland_Text_Biker1Defeat::
    .string "Co…\n"
    .string "Co je to za fakana?!$"

ThreeIsland_Text_Biker1PostBattle::
    .string "Áááá, kámo…\n"
    .string "Neopovaz se smát!$"

ThreeIsland_Text_Biker2Intro::
    .string "Ty nejsi z KANTA?\n"
    .string "Mel bys byt na nasí strane!$"

ThreeIsland_Text_Biker2Defeat::
    .string "Prestan blbnout!$"

ThreeIsland_Text_Biker2PostBattle::
    .string "Co je s tebou, ze se tak\n"
    .string "rozcilujes?\p"
    .string "Naprosto necool, kámo!$"

ThreeIsland_Text_Biker3Intro::
    .string "Pozvali jsme sem séfa,\n"
    .string "a tys to musel zkazit!\p"
    .string "Ztrapnils nás, kámo!$"

ThreeIsland_Text_Biker3Defeat::
    .string "… … …   … … …$"

ThreeIsland_Text_Biker3PostBattle::
    .string "Séfe, ríkám ti, musís s tím\n"
    .string "fakanem neco udelat!$"

ThreeIsland_Text_PaxtonIntro::
    .string "Sleduji te a rekl bych,\n"
    .string "ze jsi udelal dost.\p"
    .string "Co jsi ty, jejich kámos\n"
    .string "nebo co?\p"
    .string "Tak budes bojovat se mnou\n"
    .string "místo nich.$"

ThreeIsland_Text_PaxtonDefeat::
    .string "Dobre, stací!\n"
    .string "Odejdeme, jak jste chteli!\p"
    .string "Budeme rádi, ze zmizíme\n"
    .string "z tohohle nudného ostrova!$"

ThreeIsland_Text_PaxtonPostBattle::
    .string "Hmf! Jasne, povaluj se klidne\n"
    .string "s temihle vidláky!$"

ThreeIsland_Text_ThankYouOhYourMonGotHurt::
    .string "Dekuji ti! Ti grázlové delali\n"
    .string "jen problémy.\p"
    .string "Ach, podívej, tvuj POKéMON\n"
    .string "se kvuli mne zranil.$"

ThreeIsland_Text_GivenFullRestore::
    .string "{PLAYER} dostal\n"
    .string "FULL RESTORE.$"

ThreeIsland_Text_OhYourBagIsFull::
    .string "Ach?\n"
    .string "Tvuj BATOH je plny.$"

ThreeIsland_Text_YouveGotImpressiveMons::
    .string "Más vskutku úzasné\n"
    .string "POKéMONy.$"

ThreeIsland_Text_LostelleWentOffTowardsBondBridge::
    .string "Bylo by skvelé, kdyby tu zil\n"
    .string "nekdo tak silny jako ty.\p"
    .string "Doufám, ze tu aspon chvíli\n"
    .string "zustanes.\p"
    .string "…Prominte?\n"
    .string "Hledáte LOSTELLE?\p"
    .string "LOSTELLE odesla smerem k BOND\n"
    .string "BRIDGE pred chvílí.$"

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain::
    .string "THREE ISLAND je vlastne\n"
    .string "nejlidnatejsí z ostrovu.\p"
    .string "Presto by mohl byt mín ospaly.\p"
    .string "Ale nechtela bych uz nikdy videt\n"
    .string "zase ty grázly z BIKERS.$"

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame::
    .string "Budu trénovat své DODUO\n"
    .string "v BERRY FOREST.\p"
    .string "Az se vyvine, pujdu si zahrát\n"
    .string "hru na TWO ISLAND.$"

ThreeIsland_Text_Doduo::
    .string "DODUO: Gigiih!$"

