Route8_Text_AidanIntro::
    .string "S POKéMONy ti to jde, ale jak\n"
    .string "mas známky z chemie?$"

Route8_Text_AidanDefeat::
    .string "Au!\n"
    .string "Tavení!$"

Route8_Text_AidanPostBattle::
    .string "Ve skole jsem lepsí nez v tomhle!$"

Route8_Text_StanIntro::
    .string "Tak jo!\n"
    .string "Pojdme si zahrát!$"

Route8_Text_StanDefeat::
    .string "Sakra!\n"
    .string "Chybelo to!$"

Route8_Text_StanPostBattle::
    .string "Dnes mi to neslo.$"

Route8_Text_GlennIntro::
    .string "Mel bys vedet.\n"
    .string "K vítezství je treba strategie!$"

Route8_Text_GlennDefeat::
    .string "To je nelogické!$"

Route8_Text_GlennPostBattle::
    .string "Jdi nejdrív s GRIMEREM…a…\n"
    .string "…a…pak…$"

Route8_Text_PaigeIntro::
    .string "Mám NIDORANY ráda, sbírám je!$"

Route8_Text_PaigeDefeat::
    .string "Proc?\n"
    .string "Proc??$"

Route8_Text_PaigePostBattle::
    .string "Kdyz POKéMON vyroste, zoskliví!\n"
    .string "Nemeli by se vyvíjet.$"

Route8_Text_LeslieIntro::
    .string "Skola je zábavná, ale i POKéMONi.$"

Route8_Text_LeslieDefeat::
    .string "Ukázal jsi mi, ze bych se\n"
    .string "mela drzet skoly.$"

Route8_Text_LesliePostBattle::
    .string "Plánovala jsem si vyjít na\n"
    .string "cerstvy vzduch, ale…\p"
    .string "Trcíme tu kvuli branám\n"
    .string "v SAFFRONU.$"

Route8_Text_AndreaIntro::
    .string "MEOWTH je tak roztomily, mnau,\n"
    .string "mnau, mnau!$"

Route8_Text_AndreaDefeat::
    .string "Mnaaaaau!$"

Route8_Text_AndreaPostBattle::
    .string "Myslím, ze PIDGEY a RATTATA jsou\n"
    .string "taky roztomilí!$"

Route8_Text_MeganIntro::
    .string "Asi vypadáme hloupe, jak tu\n"
    .string "takhle stojíme.$"

Route8_Text_MeganDefeat::
    .string "Podívej, co jsi udelal mym\n"
    .string "chudákum POKéMONum!$"

Route8_Text_MeganPostBattle::
    .string "Hlídac v SAFFRONU nás nepustí\n"
    .string "dál.\p"
    .string "Vím, ze delá svou práci, ale\n"
    .string "myslím, ze je zly.$"

Route8_Text_RichIntro::
    .string "Jsem toulavy hrácsky frajer!$"

Route8_Text_RichDefeat::
    .string "Promeskal jsem velkou sanci!$"

Route8_Text_RichPostBattle::
    .string "Hraní her a POKéMONi jsou jako\n"
    .string "buráky! Nemuzu prestat!$"

Route8_Text_JuliaIntro::
    .string "Co je roztomilé, kulaté a\n"
    .string "chlupaté POKéMON?$"

Route8_Text_JuliaDefeat::
    .string "Prestan!\p"
    .string "Nebud na mou CLEFAIRY zly!$"

Route8_Text_JuliaPostBattle::
    .string "Cetla jsem, ze CLEFAIRY se vyvine\n"
    .string "pri vystavení MOON STONE.\p"
    .string "Bylo to v POKéMON JOURNAL.\n"
    .string "Je to vubec pravda?$"

Route8_Text_UndergroundPathSign::
    .string "PODZEMNÍ CESTA\n"
    .string "CELADON CITY - LAVENDER TOWN$"

Route8_Text_EliIntro::
    .string "ELI: Síla dvojcat je úzasná.\n"
    .string "Vedels to?$"

Route8_Text_EliDefeat::
    .string "ELI: Ale…\n"
    .string "Pouzili jsme sílu dvojcat…$"

Route8_Text_EliPostBattle::
    .string "ELI: Své POKéMONy jsem chytil\n"
    .string "s ANNE!$"

Route8_Text_EliNotEnoughMons::
    .string "ELI: Nemuzeme bojovat, kdyz nemás\n"
    .string "dva POKéMONy.$"

Route8_Text_AnneIntro::
    .string "ANNE: Sokujeme te silou\n"
    .string "dvojcat!$"

Route8_Text_AnneDefeat::
    .string "ANNE: Nase síla dvojcat…$"

Route8_Text_AnnePostBattle::
    .string "ANNE: Chovám POKéMONy s\n"
    .string "ELIM.$"

Route8_Text_AnneNotEnoughMons::
    .string "ANNE: Cau, cau! Bojujme!\n"
    .string "Ale vezmi si dva POKéMONy.$"

Route8_Text_RicardoIntro::
    .string "Mé kolo zlobí, vole.$"

Route8_Text_RicardoDefeat::
    .string "Hele, vole.\n"
    .string "Nebavím se tím.$"

Route8_Text_RicardoPostBattle::
    .string "Mám trávu v drátech, vole.$"

Route8_Text_JarenIntro::
    .string "Uvolni cestu, nebo te\n"
    .string "prejedu!$"

Route8_Text_JarenDefeat::
    .string "Vázne, fakane?$"

Route8_Text_JarenPostBattle::
    .string "Nemysli si, ze jsi neco extra\n"
    .string "jen kvuli tomuhle.$"
