VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "Jsou zlí lidé, kterí pouzívají\n"
    .string "POKéMONy ke zlocinum.\p"
    .string "TEAM ROCKET obchoduje se vzácnymi\n"
    .string "POKéMONy, naprílad.\p"
    .string "Take opoustejí POKéMONy, které\n"
    .string "povazují za neoblíbené ci zbytecné.\p"
    .string "Takoví otresní lidé to jsou,\n"
    .string "TEAM ROCKET.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "Myslím, ze POKéMON muze byt dobry\n"
    .string "i zly. Závisí to na TRENÉROVI.$"

