SixIsland_WaterPath_Text_RoseIntro::
    .string "Nechala jsem se vést prijemnym\n"
    .string "vetríkem az sem.$"

SixIsland_WaterPath_Text_RoseDefeat::
    .string "Hihi… Jsi tak roztomily, kdyz\n"
    .string "jsi odhodlany.$"

SixIsland_WaterPath_Text_RosePostBattle::
    .string "Chci jít do lesa támhle, ale…\p"
    .string "Je tam spousta BUG POKéMONu.\n"
    .string "Trochu me desí.$"

SixIsland_WaterPath_Text_EdwardIntro::
    .string "Trénuji potají, aby me\n"
    .string "nikdo nevidel.$"

SixIsland_WaterPath_Text_EdwardDefeat::
    .string "Nikdo nevidel, jak prohrávám,\n"
    .string "ze ne?$"

SixIsland_WaterPath_Text_EdwardPostBattle::
    .string "Jako umelec nechci, aby lidé\n"
    .string "vedeli o úsilí, které vkládám.$"

SixIsland_WaterPath_Text_SamirIntro::
    .string "Co, naznacujes, ze más\n"
    .string "dost PLAVCU jako jsem já?\p"
    .string "Au, nezlob se na mne!$"

SixIsland_WaterPath_Text_SamirDefeat::
    .string "Ach, ne, ne, ne.$"

SixIsland_WaterPath_Text_SamirPostBattle::
    .string "Nemohl jsem zbavit stigmatu\n"
    .string "byt PLAVCEM…$"

SixIsland_WaterPath_Text_DeniseIntro::
    .string "Muj klucina je porád zaneprázdneny,\n"
    .string "tak chodím plavat sama.$"

SixIsland_WaterPath_Text_DeniseDefeat::
    .string "Aha, vedela jsem, ze se to\n"
    .string "stane!$"

SixIsland_WaterPath_Text_DenisePostBattle::
    .string "Kdyz nemuzu byt s mym klucem,\n"
    .string "trávím cas s POKéMONy, které\l"
    .string "mi dal.$"

SixIsland_WaterPath_Text_EarlIntro::
    .string "Rekni mi, kde jsou hory\n"
    .string "kolem techto míst?$"

SixIsland_WaterPath_Text_EarlDefeat::
    .string "Ztratil jsem cestu, kdyz\n"
    .string "jsem byl zabrany do boje!$"

SixIsland_WaterPath_Text_EarlPostBattle::
    .string "Nejsou tu kolem zádné hory?$"

SixIsland_WaterPath_Text_MiuIntro::
    .string "MIU: Ahoj, POKéMONe!\n"
    .string "Je cas si hrát!$"

SixIsland_WaterPath_Text_MiuDefeat::
    .string "MIU: Ach, ne!\n"
    .string "Mamí!$"

SixIsland_WaterPath_Text_MiuPostBattle::
    .string "MIU: Cítím se vsechna smutná,\n"
    .string "kdyz prohráváme…$"

SixIsland_WaterPath_Text_MiuNotEnoughMons::
    .string "MIU: MIA a já jsme DVOJCATA.\n"
    .string "Chceme bojovat spolu.$"

SixIsland_WaterPath_Text_MiaIntro::
    .string "MIA: Ahoj, POKéMONe!\n"
    .string "Je cas bojovat!$"

SixIsland_WaterPath_Text_MiaDefeat::
    .string "MIA: Jsi sprosty!\n"
    .string "Jsi zly, ze vyhrávás!$"

SixIsland_WaterPath_Text_MiaPostBattle::
    .string "MIA: Ach…\n"
    .string "Promin, muj POKéMONe…$"

SixIsland_WaterPath_Text_MiaNotEnoughMons::
    .string "MIA: Ach, mas jen jednoho\n"
    .string "POKéMONa?\p"
    .string "Necítís se osamele?$"

SixIsland_WaterPath_Text_WantedUltimateHorn::
    .string "Hledá se!\n"
    .string "Nejlepsí Roh!$"

SixIsland_WaterPath_Text_RouteSign::
    .string "WATER PATH\n"
    .string "Vede do RUIN VALLEY$"

