SaffronCity_House_Text_DontLookAtMyLetter::
    .string "…Díky za to, ze pises.\n"
    .string "Doufám, ze se brzy uvidíme!\p"
    .string "…Hej!\n"
    .string "Nedívej se mi do dopisu!$"

SaffronCity_House_Text_Pidgey::
    .string "PIDGEY: Kurukkoo!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
    .string "COPYCAT je rozkosná!\n"
    .string "Koupím jí POKé PANENKU.$"

SaffronCity_House_Text_ExplainPPUp::
    .string "Dostal jsem PP UP jako dárek.\p"
    .string "Pouzívá se ke zvysení PP\n"
    .string "u útoku POKéMONa.\p"
    .string "Mel bych ho pouzít na silny útok\n"
    .string "s nízkym poctem PP.$"

