CeruleanCity_Text_RivalIntro::
    .string "{RIVAL}: Cau! {PLAYER}!\p"
    .string "Porád se tu loudás vzadu?\p"
    .string "Mne se darí bájecne! Nachytal jsem\n"
    .string "spoustu silnych a chytrych POKéMONu!\p"
    .string "Tak ukaz, koho jsi nachytal ty,\n"
    .string "{PLAYER}!$"

CeruleanCity_Text_RivalDefeat::
    .string "Hej!\n"
    .string "V klidu!\l"
    .string "Uz jsi vyhrál!$"

CeruleanCity_Text_RivalPostBattle::
    .string "{RIVAL}: Hele, hádej co?\p"
    .string "Byl jsem u BILLa a donutil ho\n"
    .string "ukázat mi jeho vzácné POKéMONy.\p"
    .string "To mi pridalo spoustu stránek\n"
    .string "do POKéDEXu!\p"
    .string "BILL je preci celosvetove známy\n"
    .string "jako POKéMANIAK.\p"
    .string "Vymyslel taky POKéMON Storage\n"
    .string "System na PC.\p"
    .string "Kdyz jeho systém pouzívás,\n"
    .string "mel bys mu jít podekovat.\p"
    .string "No, já uz musím mazat!\n"
    .string "Tak zase nekdy!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "Aha, no jo.\p"
    .string "Je mi te líto. Vázne.\n"
    .string "Porád se za mnou plouzís.\p"
    .string "Tak na, dám ti maly dárek\n"
    .string "z laskavosti.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "Pro takového drbnu jako ty…\n"
    .string "Tahle vec je perfektní.\p"
    .string "Já ji nepotrebuju, protoze me\n"
    .string "ostatní nezajímají.\p"
    .string "Tak fajn, ted uz fakt mizím.\n"
    .string "Mej se!$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro::
    .string "Hej! Drz se dál!\n"
    .string "Tohle není tvuj dvur!\p"
    .string "…He?\n"
    .string "Já?\p"
    .string "Já jsem nevinny kolemjdoucí!\n"
    .string "Neverís mi?{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_GruntDefeat::
    .string "GRUNT: Stuj! Vzdávám se!\n"
    .string "Odejdu v tichosti!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "…Dobre.\n"
    .string "Vrátím TM, kterou jsem ukradl.$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .string "{PLAYER} získal zpet TM28\n"
    .string "od TEAM ROCKET GRUNTa.$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "Radsi uz vypadnu!\n"
    .string "Pa!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "Udelej místo!\n"
    .string "Nemuzu utéct, dokud ti to nedám!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "Ty jsi taky TRÉNÉR?\p"
    .string "Chytání, souboje…\n"
    .string "Je to tezky zivot, ze jo?$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "Vís, ze mohou ostrihnout\n"
    .string "i malé stromky?\p"
    .string "I ten stromek pred obchodem\n"
    .string "jde ostrihnout.\p"
    .string "Ale asi je tu i jiná cesta\n"
    .string "kolem.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "Kdyby tu SLOWBRO nebyl,\n"
    .string "mohl bys strom ostrihnout.\p"
    .string "Tudy by ses dostal na\n"
    .string "druhou stranu.\p"
    .string "Ale asi je tu i jiná cesta\n"
    .string "kolem.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "Ty delás encyklopedii o\n"
    .string "POKéMONech? To zní zábavne.$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "Místní lidé byli okradeni.\p"
    .string "Je jasné, ze za tímto hnusnym\n"
    .string "zlocinem stojí TEAM ROCKET!\p"
    .string "I nase POLICIE má s ROCKETy\n"
    .string "potíze!$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "Tak jo! SLOWBRO!\n"
    .string "Pouzij SONICBOOM!$"

CeruleanCity_Text_SlowbroPayAttention::
    .string "No tak, SLOWBRO, dávej pozor!$"

CeruleanCity_Text_SlowbroPunch::
    .string "SLOWBRO, pesti!$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "Ne!\n"
    .string "Zase jsi to pokazil!$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "SLOWBRO, WITHDRAW!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "Ne! Spatne!\n"
    .string "POKéMONy je tezké ovládat!\p"
    .string "Poslusnost POKéMONa závisí na\n"
    .string "tvych schopnostech TRÉNÉRA.$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "SLOWBRO si zdrímnul…$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "SLOWBRO se fláká…$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "SLOWBRO se odvrátil…$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "SLOWBRO ignoroval rozkazy…$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "Chci jasne cervené kolo.\p"
    .string "Nechám si ho doma, aby se\n"
    .string "nezasahalo.$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "Tohle je CERULEAN CAVE.\p"
    .string "Uvnitr zijí strasne silní\n"
    .string "POKéMONi.\p"
    .string "Jen vyjímecní TRÉNÉRI smí\n"
    .string "dovnitr vejít.\p"
    .string "Musel bys byt dost silny, abys\n"
    .string "se stal SAMPIÓNEM POKéMON\l"
    .string "LIGY, to pro zacátek.\p"
    .string "A musel bys mít na konte\n"
    .string "velky úspech.$"

CeruleanCity_Text_CitySign::
    .string "CERULEAN CITY\n"
    .string "Mesto, jez obklopuje záhadná\l"
    .string "modrá aura$"

CeruleanCity_Text_TrainerTipsHeldItems::
    .string "TIPY PRO TRÉNÉRY\p"
    .string "POKéMON muze drzet predmet.\n"
    .string "\p"
    .string "Nekteré predmety muze drzící\n"
    .string "POKéMON pouzít i v boji.$"

CeruleanCity_Text_BikeShopSign::
    .string "Tráva i jeskyne s prehledem!\n"
    .string "BIKE SHOP$"

CeruleanCity_Text_GymSign::
    .string "CERULEAN CITY POKéMON GYM\n"
    .string "VÚDCE: MISTY\l"
    .string "Klukovská morská víla!$"

