PokemonLeague_BrunosRoom_Text_Intro::
    .string "Já jsem BRUNO z ELITNÍ CTYRKY!\p"
    .string "Tvrdym tréninkem mohou lidé i\n"
    .string "POKéMONi sílit bez omezení.\p"
    .string "Zil jsem a trénoval se svymi\n"
    .string "bojovymi POKéMONy!\l"
    .string "A to se nikdy nezmení!\p"
    .string "{PLAYER}!\p"
    .string "Rozdrtíme te svou\n"
    .string "nadrazenou silou!\p"
    .string "Hoo ha!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_RematchIntro::
    .string "Já jsem BRUNO z ELITNÍ CTYRKY!\p"
    .string "Tvrdym tréninkem mohou lidé i\n"
    .string "POKéMONi sílit bez omezení.\p"
    .string "Zil jsem a trénoval se svymi\n"
    .string "bojovymi POKéMONy!\l"
    .string "A to se nikdy nezmení!\p"
    .string "{PLAYER}!\p"
    .string "Rozdrtíme te svou\n"
    .string "nadrazenou silou!\p"
    .string "Hoo ha!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_Defeat::
    .string "Proc?\n"
    .string "Jak jsem mohl prohrát?$"

PokemonLeague_BrunosRoom_Text_PostBattle::
    .string "Má práce je u konce.\n"
    .string "Jdi vstríc dalsí vyzve.$"

