FuchsiaCity_Text_DidYouTrySafariGame::
    .string "Zkusils uz SAFARI HRU?\p"
    .string "Jsou tam vzácní POKéMON,\n"
    .string "které jinde nechytís.$"

FuchsiaCity_Text_SafariZoneZooInFront::
    .string "Pred vchodem do SAFARI ZONE\n"
    .string "je ZOO.\p"
    .string "Vzadu je SAFARI HRA na\n"
    .string "chytání POKéMONu.$"

FuchsiaCity_Text_WheresSara::
    .string "ERIK: Kde je SARA?\n"
    .string "Mela tu na me cekat.$"

FuchsiaCity_Text_ItemBallInThere::
    .string "Ten item ball tamhle…\n"
    .string "Chtels ho taky?\p"
    .string "Já taky!\n"
    .string "…Co? To je POKéMON?$"

FuchsiaCity_Text_CitySign::
    .string "FUCHSIA CITY\n"
    .string "Hle! Vásnivá Ruzová!$"

FuchsiaCity_Text_SafariZoneSign::
    .string "POKéMON RÁJ\n"
    .string "SAFARI ZONE$"

FuchsiaCity_Text_SafariGameSign::
    .string "SAFARI HRA\n"
    .string "CHYT-SI-POKéMONa!$"

FuchsiaCity_Text_WardensHomeSign::
    .string "SAFARI ZONE\n"
    .string "DUM SPRÁVCE$"

FuchsiaCity_Text_SafariZoneOfficeSign::
    .string "POKéMON RÁJ!\n"
    .string "Vítej v SAFARI ZONE!\l"
    .string "KANCELÁR SAFARI ZONE$"

FuchsiaCity_Text_GymSign::
    .string "FUCHSIA CITY POKéMON GYM\n"
    .string "VUDCE: KOGA\l"
    .string "Mistr jedovatych ninju$"

FuchsiaCity_Text_ChanseySign::
    .string "Jméno: CHANSEY\n"
    .string "Chytit ji je vec stestí.$"

FuchsiaCity_Text_VoltorbSign::
    .string "Jméno: VOLTORB\n"
    .string "Obraz POKé BALLu.$"

FuchsiaCity_Text_KangaskhanSign::
    .string "Jméno: KANGASKHAN\p"
    .string "Matersky POKéMON, ktery\n"
    .string "nosí mláde v kapse na brise.$"

FuchsiaCity_Text_SlowpokeSign::
    .string "Jméno: SLOWPOKE\n"
    .string "Prátelsky a velmi pomaly.$"

FuchsiaCity_Text_LaprasSign::
    .string "Jméno: LAPRAS\n"
    .string "Také známy jako král morí.$"

FuchsiaCity_Text_OmanyteSign::
    .string "Jméno: OMANYTE\n"
    .string "Velmi vzácny POKéMON,\l"
    .string "obnoveny z fosílie.$"

FuchsiaCity_Text_KabutoSign::
    .string "Jméno: KABUTO\n"
    .string "Velmi vzácny POKéMON,\l"
    .string "obnoveny z fosílie.$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FuchsiaCity_Text_Ellipsis::
    .string "……$"

Text_SubstituteTeach::
    .string "Au, chtela bych byt mlade\n"
    .string "KANGASKHANa.\p"
    .string "Ráda bych byla na míste\n"
    .string "toho mládete…\p"
    .string "A schoulila se v kapse\n"
    .string "mámy KANGASKHANa.\p"
    .string "Ale jen POKéMON umí\n"
    .string "techniku SUBSTITUTE…\p"
    .string "Chces, abych SUBSTITUTE\n"
    .string "naucila jednoho z tvych?$"

Text_SubstituteDeclined::
    .string "Aha, opravdu?\n"
    .string "SUBSTITUTE vypadá tak srandovne…$"

Text_SubstituteWhichMon::
    .string "Ktery POKéMON se chce naucit\n"
    .string "SUBSTITUTE?$"

Text_SubstituteTaught::
    .string "Co bych dala za to vlézt do\n"
    .string "kapsy KANGASKHANa…$"

FuchsiaCity_Text_MyFatherIsGymLeader::
    .string "Muj otec je VUDCE GYMU\n"
    .string "tohoto mesta.\p"
    .string "Trénuji s JEDOVATYMI POKéMONy\n"
    .string "stejne jako on.$"

