FiveIsland_House1_JPText_HusbandWentOffFishing::
    .string "こんばんの　おかずは\n"
    .string "ようい　しなくて　いいぞ！\p"
    .string "って　だんなが\n"
    .string "つりに　いったん　だけど‥\l"
    .string "しんじて　いいのかねえ$"

FiveIsland_House1_Text_HusbandWentOffFishing::
    .string "Nestarej se o nákup veceri\n"
    .string "na dnesní vecer!\p"
    .string "…To mi rekl muj manzel, kdyz\n"
    .string "dnes vyrazil na ryby.\p"
    .string "Nevím, jestli mu mám verit,\n"
    .string "ze ten slib dodrzí.$"

