Text_SeismicTossTeach::
    .string "Tajemství vesmíru…\n"
    .string "Záhady Zeme…\p"
    .string "Je tolik vecí, o kterych\n"
    .string "víme tak málo.\p"
    .string "Ale to nás má hnát ke studiu,\n"
    .string "ne k tomu, abychom to vzdali.\p"
    .string "Jediné, co bys mel hodit…\p"
    .string "Co treba SEISMIC TOSS?\n"
    .string "Mám ho POKéMONa naucit?$"

Text_SeismicTossDeclined::
    .string "Jeste si pro nej prijdes,\n"
    .string "to vím jiste.$"

Text_SeismicTossWhichMon::
    .string "Ktery POKéMON se chce naucit\n"
    .string "SEISMIC TOSS?$"

Text_SeismicTossTaught::
    .string "Doufám, ze se nevzdás.\n"
    .string "Pokracuj v tom!$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .string "MOON STONE, jo?\p"
    .string "Co je na nem tak speciálního?\n"
    .string "Mne pripadá jako obycejny kámen.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "20. cervence 1969!\p"
    .string "Toho dne clovek poprvé\n"
    .string "stoupl na Mesíc.\p"
    .string "Koupil jsem si barevnou TV,\n"
    .string "abych mohl tu zprávu sledovat.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "Tento mesíc bezí u nás\n"
    .string "vesmírná vystava.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .string "Chci PIKACHU!\n"
    .string "Je tak roztomily!\p"
    .string "Poprosila jsem tátu, at\n"
    .string "mi nejakého chytí!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .string "Jo, PIKACHU brzy, slibuji!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "Raketoplán$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .string "Meteorit, ktery spadl na MT. MOON.\n"
    .string "Predpokládá se, ze je to MOON STONE.$"

