Route25_Text_JoeyIntro::
    .string "Místní TRENÉRI sem chodí\n"
    .string "trénovat.$"

Route25_Text_JoeyDefeat::
    .string "Jsi slusny.$"

Route25_Text_JoeyPostBattle::
    .string "Vsichni POKéMON mají slabiny.\n"
    .string "I ti nejsilnejsí.\p"
    .string "Proto je nejlepsí chovat\n"
    .string "POKéMONy ruznych typu.$"

Route25_Text_DanIntro::
    .string "Táta me vzal na skvelou párty\n"
    .string "na S.S. ANNE ve VERMILION CITY.$"

Route25_Text_DanDefeat::
    .string "Nezlobím se!$"

Route25_Text_DanPostBattle::
    .string "Na S.S. ANNE jsem videl TRENÉRY\n"
    .string "z celého sveta.$"

Route25_Text_FlintIntro::
    .string "Jsem frajer.\n"
    .string "Mám pritelkyni!$"

Route25_Text_FlintDefeat::
    .string "Och, sakra…$"

Route25_Text_FlintPostBattle::
    .string "No co.\n"
    .string "Pritelkyne me utesí.$"

Route25_Text_KelseyIntro::
    .string "Ahoj!\n"
    .string "Muj prítel je frajer!$"

Route25_Text_KelseyDefeat::
    .string "Nemám nejlepsí kondici…$"

Route25_Text_KelseyPostBattle::
    .string "Kéz by byl muj prítel\n"
    .string "tak dobry jako ty.$"

Route25_Text_ChadIntro::
    .string "Mel jsem ten pocit…\n"
    .string "Vedel jsem, ze musím bojovat!$"

Route25_Text_ChadDefeat::
    .string "Vedel jsem, ze i prohraju!$"

Route25_Text_ChadPostBattle::
    .string "Kdyz se tvuj POKéMON zmate,\n"
    .string "vymen ho.\p"
    .string "To je dobrá taktika.$"

Route25_Text_HaleyIntro::
    .string "Kámoska má spoustu roztomilych\n"
    .string "POKéMONu. Tak jí závidím!$"

Route25_Text_HaleyDefeat::
    .string "Uz tak nezávidím!$"

Route25_Text_HaleyPostBattle::
    .string "Ty jsi prisel z MT. MOON?\n"
    .string "Muzu dostat CLEFAIRY?$"

Route25_Text_FranklinIntro::
    .string "Práve jsem sesel z MT. MOON,\n"
    .string "ale jeste mám sílu v nádrzi!$"

Route25_Text_FranklinDefeat::
    .string "Drel jsi se!$"

Route25_Text_FranklinPostBattle::
    .string "Sakra!\n"
    .string "V té jeskyni me kousnul ZUBAT.$"

Route25_Text_NobIntro::
    .string "Jdu si prohlédnout sbírku jednoho\n"
    .string "POKéMANIAKa na mysu.$"

Route25_Text_NobDefeat::
    .string "Tys me dostal, a pekne\n"
    .string "porádne!$"

Route25_Text_NobPostBattle::
    .string "Ten POKéMANIAK to svym jménem\n"
    .string "nepreháni.\p"
    .string "V jeho sbírce je mnoho vzácnych\n"
    .string "druhu POKéMONu.$"

Route25_Text_WayneIntro::
    .string "Ty jdes za BILLEM?\n"
    .string "Nejdrív souboj!$"

Route25_Text_WayneDefeat::
    .string "Ty jsi neco.$"

Route25_Text_WaynePostBattle::
    .string "Stezka dole je zkratka do\n"
    .string "CERULEAN CITY.$"

Route25_Text_SeaCottageSign::
    .string "SEA COTTAGE\n"
    .string "Tady bydlí BILL!$"

Route25_Text_MistyHighHopesAboutThisPlace::
    .string "Tenhle mys je slavné místo\n"
    .string "na rande.\p"
    .string "MISTY, GYM LEADER, do tohohle\n"
    .string "místa vkládá velké nadeje.$"

Route25_Text_AreYouHereAlone::
    .string "Ahoj, jsi tu sám?\p"
    .string "Kdyz uz jsi na CERULEAN mysu…\n"
    .string "No, melo by to byt v páru.$"
