PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Vítej v POKéMON LIZE.\p"
    .string "Já jsem LORELEI z ELITNÍ CTYRKY.\p"
    .string "Nikdo me neporazí, kdyz prijde\n"
    .string "rec na ledové POKéMONy.\p"
    .string "Zmrazující útoky jsou mocné.\p"
    .string "Tví POKéMONi budou v mé moci,\n"
    .string "az ztuhnou ledem.\p"
    .string "Hahaha!\n"
    .string "Jsi pripraven?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "Vítej v POKéMON LIZE.\p"
    .string "Já, LORELEI z ELITNÍ CTYRKY,\n"
    .string "jsem se vrátila!\p"
    .string "Vís, jak to chodí.\n"
    .string "Nikdo me neporazí, kdyz prijde\l"
    .string "rec na ledové POKéMONy.\p"
    .string "Zmrazující útoky jsou mocné.\p"
    .string "Tví POKéMONi budou v mé moci,\n"
    .string "az ztuhnou ledem.\p"
    .string "Hahaha!\n"
    .string "Jsi pripraven?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Takhle to nemelo dopadnout!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "Jsi lepsí, nez jsem myslela.\n"
    .string "Pokracuj dál.\p"
    .string "Ochutnal jsi jen kousek\n"
    .string "síly POKéMON LIGY.$"

