CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "Ten BILL!\p"
    .string "Slysel jsem, ze udelá cokoliv\n"
    .string "pro vzácné POKéMONy.\p"
    .string "Není mu cizí udelat ruzné\n"
    .string "ulety, povídá se.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "Slysel jsi uz o BILLovi?\p"
    .string "Vsichni mu ríkají POKéMANIAK!\p"
    .string "Myslím, ze lidé BILLovi prosté\n"
    .string "závidí.\p"
    .string "Kdo by se nechtel chlubit svymi\n"
    .string "POKéMONy?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "BILL má spoustu POKéMONu!\n"
    .string "Sbírá i ty vzácné!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .string "Co kdyby ses sel nahoru\n"
    .string "vymenit POKéMONy s kamarády?\p"
    .string "Vymenou získás vetsí pestrost.\n"
    .string "\p"
    .string "POKéMONi získaní vymenou navíc\n"
    .string "rostou rychleji.$"

