CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "SUPER REPEL drzí slabé POKéMONy\n"
    .string "stranou…\p"
    .string "Hmm, je to silnejsí REPEL.$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "Na delsí vypravy si kup\n"
    .string "REVIVE.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "Spickové predmety pro TRENÉRY!\p"
    .string "2F: TRÉNINKOVÉ TRZISTE$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .string "Máme zákazníka LANCE, ktery sem\n"
    .string "obcas chodí.\p"
    .string "Vzdy si kupuje plást.\p"
    .string "Zajímalo by me… Má doma\n"
    .string "spoustu stejnych plástu?$"
