Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
    .string "Pesí na CYKLISTICKOU STEZKU\n"
    .string "nesmí!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
    .string "CYKLISTICKÁ STEZKA je sjezdovka\n"
    .string "u more. Krásná jízda.$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
    .string "S dovolením!\n"
    .string "Prosím, pockejte!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
    .string "Jak ses sem dostal?\n"
    .string "Pekná snaha!$"

