CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "Jen zrucní TRÉNÉRI mohou sbírat\n"
    .string "POKéMON ODZNAKY.\p"
    .string "Vidím, ze uz mas alespon jeden.\p"
    .string "Ty ODZNAKY mají úzasná tajemství,\n"
    .string "vís o tom?$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "Tedy…\p"
    .string "O kterém z osmi ODZNAKu mám\n"
    .string "vyprávet?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "Prijd me navstívit, kdy budes chtít.$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "ÚTOK vsech tvych POKéMONu se\n"
    .string "trosicku zvysí.\p"
    .string "Také ti dovolí pouzívat útok\n"
    .string "FLASH mimo souboj.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "POKéMONi do Lv. 30 te\n"
    .string "poslechnou.\p"
    .string "Vcetne tech, které jsi získal\n"
    .string "ve vymene.\p"
    .string "POKéMONi vyssích úrovní vsak\n"
    .string "v boji nebudou poslouchat.\p"
    .string "Také ti dovolí pouzívat útok\n"
    .string "CUT mimo souboj.$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "RYCHLOST vsech tvych POKéMONu\n"
    .string "se trosicku zvysí.\p"
    .string "Také ti dovolí pouzívat útok\n"
    .string "FLY mimo souboj.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "POKéMONi do Lv. 50 te\n"
    .string "poslechnou.\p"
    .string "Vcetne tech, které jsi získal\n"
    .string "ve vymene.\p"
    .string "POKéMONi vyssích úrovní vsak\n"
    .string "v boji nebudou poslouchat.\p"
    .string "Také ti dovolí pouzívat útok\n"
    .string "STRENGTH mimo souboj.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "OBRANA vsech tvych POKéMONu se\n"
    .string "trosicku zvysí.\p"
    .string "Také ti dovolí pouzívat útok\n"
    .string "SURF mimo souboj.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "POKéMONi do Lv. 70 te\n"
    .string "poslechnou.\p"
    .string "Vcetne tech, které jsi získal\n"
    .string "ve vymene.\p"
    .string "POKéMONi vyssích úrovní vsak\n"
    .string "v boji nebudou poslouchat.\p"
    .string "Také ti dovolí pouzívat útok\n"
    .string "ROCK SMASH mimo souboj.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "SP. ATK a SP. DEF vsech tvych\n"
    .string "POKéMONu se trosicku zvysí.\p"
    .string "Také ti dovolí pouzívat útok\n"
    .string "WATERFALL mimo souboj.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "Vsichni POKéMONi te poslechnou!$"

