SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "KAPITÁN: Auch…\n"
    .string "Je mi hrozne…\l"
    .string "Urp! Morská nemoc…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "{PLAYER} promasíroval KAPITÁNOVI\n"
    .string "záda!\p"
    .string "Tri-tri…\n"
    .string "Tri-tri…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "KAPITÁN: Uf! Díky!\n"
    .string "Cítím se uz mnohem lépe.\p"
    .string "Chces videt mou tajnou techniku\n"
    .string "CUT?\p"
    .string "Ukázal bych ti svou cennou CUT\n"
    .string "techniku, kdybych nebyl nemocny…\p"
    .string "Uz vím! Tohle si vezmi!\n"
    .string "Tenhle SKRYTY STROJ!\p"
    .string "Nauc CUT své POKéMONy a budes\n"
    .string "ho videt kdykoli!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "{PLAYER} získal HM01\n"
    .string "od KAPITÁNA!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "Pomocí CUT muzes kácet\n"
    .string "malé stromy.\p"
    .string "Co kdybys to zkusil na stromech\n"
    .string "kolem VERMILION CITY?$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "KAPITÁN: …Uf!\p"
    .string "Kdyz uz nejsem nemocny,\n"
    .string "asi prisel ten cas.\p"
    .string "S.S. ANNE brzy vypluje!\p"
    .string "Sbohem, do shledání ve\n"
    .string "VERMILION CITY!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "Ach ne!\n"
    .string "Nemás na to místo!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "Fuj!\n"
    .string "Nemel jsem se dívat!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "Jak prekonat morskou nemoc…\n"
    .string "Tohle KAPITÁN cte!$"
