OneIsland_KindleRoad_Text_MariaIntro::
    .string "Pocasí je nádherné!\n"
    .string "Perfektní na souboj!$"

OneIsland_KindleRoad_Text_MariaDefeat::
    .string "Aiyeeeeh!$"

OneIsland_KindleRoad_Text_MariaPostBattle::
    .string "Prosím necákej mi do obliceje!\n"
    .string "Znicís mi make-up.$"

OneIsland_KindleRoad_Text_AbigailIntro::
    .string "Zacínám se spálit od slunce…$"

OneIsland_KindleRoad_Text_AbigailDefeat::
    .string "Ach, jsi tak hrozny.$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
    .string "Líbí se mi tvá cepice.\n"
    .string "Mozná bych si taky mela poridit…$"

OneIsland_KindleRoad_Text_FinnIntro::
    .string "Odtud se MT. EMBER tycí\n"
    .string "vysoko k nebi.$"

OneIsland_KindleRoad_Text_FinnDefeat::
    .string "No, ty jsi ale tvrdy?$"

OneIsland_KindleRoad_Text_FinnPostBattle::
    .string "Obloha je v techto místech\n"
    .string "obrovská.$"

OneIsland_KindleRoad_Text_GarrettIntro::
    .string "Dal jsem si pauzu od plavání\n"
    .string "a hned me vyzyvás?$"

OneIsland_KindleRoad_Text_GarrettDefeat::
    .string "Hej, co to…\n"
    .string "Ty jsi dobry, ty!$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
    .string "Místo neustálého pouzívání SURFu\n"
    .string "by sis mel zaplavat.$"

OneIsland_KindleRoad_Text_TommyIntro::
    .string "Pockej! Pockej chvilku!\n"
    .string "Myslím, ze jsem chytil velkou!$"

OneIsland_KindleRoad_Text_TommyDefeat::
    .string "Zase jsem o vse prisel…$"

OneIsland_KindleRoad_Text_TommyPostBattle::
    .string "Nejen ze jsem prohrál, ale taky\n"
    .string "mi ta velká utekla!$"

OneIsland_KindleRoad_Text_SharonIntro::
    .string "Mohl bys mi pomoci\n"
    .string "s tréninkem?$"

OneIsland_KindleRoad_Text_SharonDefeat::
    .string "Byl jsi o trídu lepsí.$"

OneIsland_KindleRoad_Text_SharonPostBattle::
    .string "Je jasné, ze jsi sikovny.\n"
    .string "Líbís se mi!$"

OneIsland_KindleRoad_Text_TanyaIntro::
    .string "Není den, ve kterém bychom\n"
    .string "netrénovali!$"

OneIsland_KindleRoad_Text_TanyaDefeat::
    .string "Jsem takovy hlupák!$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
    .string "Od ted budu trénovat jeste víc!$"

OneIsland_KindleRoad_Text_SheaIntro::
    .string "Kazdé ráno pred snídaní\n"
    .string "plavu kolem tohoto ostrova.$"

OneIsland_KindleRoad_Text_SheaDefeat::
    .string "Lapám…\n"
    .string "Lapám po dechu…$"

OneIsland_KindleRoad_Text_SheaPostBattle::
    .string "Prohrál jsem, protoze jsem vycerpany\n"
    .string "ze vseho behání…$"

OneIsland_KindleRoad_Text_HughIntro::
    .string "Obléc se vhodne na souboj!\n"
    .string "Sundej ten lehkovázny oblecek!$"

OneIsland_KindleRoad_Text_HughDefeat::
    .string "Proc zrovna já?!$"

OneIsland_KindleRoad_Text_HughPostBattle::
    .string "I bojoví umelci se v dnesní dobe\n"
    .string "stávají módními…$"

OneIsland_KindleRoad_Text_BryceIntro::
    .string "Vís, vse chutná skvele,\n"
    .string "kdyz jsi v prírode.$"

OneIsland_KindleRoad_Text_BryceDefeat::
    .string "Áááh, smetlo me to!$"

OneIsland_KindleRoad_Text_BrycePostBattle::
    .string "Voda ve vulkanickych oblastech\n"
    .string "je vyborná.$"

OneIsland_KindleRoad_Text_ClaireIntro::
    .string "Po obede jsme plné, takze pojd\n"
    .string "do souboje na rozhybání?$"

OneIsland_KindleRoad_Text_ClaireDefeat::
    .string "To me celé zpotilo.$"

OneIsland_KindleRoad_Text_ClairePostBattle::
    .string "Co mám delat?\n"
    .string "Zase mám hlad.$"

OneIsland_KindleRoad_Text_KiaIntro::
    .string "KIA: Já a muj velky brácha\n"
    .string "tvoríme úzasnou kombinaci!$"

OneIsland_KindleRoad_Text_KiaDefeat::
    .string "KIA: Coze?!\n"
    .string "Nemuzu tomu uverit!$"

OneIsland_KindleRoad_Text_KiaPostBattle::
    .string "KIA: Jak muze existovat nekdo\n"
    .string "lepsí nez muj velky brácha?$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
    .string "KIA: Pokud chces bojovat\n"
    .string "s námi, musís mít aspon dva\l"
    .string "POKéMONy s sebou.$"

OneIsland_KindleRoad_Text_MikIntro::
    .string "MIK: Spolu s KIOU se nebojím\n"
    .string "niceho!$"

OneIsland_KindleRoad_Text_MikDefeat::
    .string "MIK: Páni!\n"
    .string "To je prílis!$"

OneIsland_KindleRoad_Text_MikPostBattle::
    .string "MIK: Jak by má kombinace\n"
    .string "s KIOU mohla selhat?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
    .string "MIK: Hej, chces s námi dvema\n"
    .string "bojovat?\p"
    .string "Vezmi si dva nebo více POKéMONu,\n"
    .string "pak ano.$"

OneIsland_KindleRoad_Text_RouteSign::
    .string "Toto je KINDLE ROAD.\p"
    .string "Jdi rovne k MT. EMBER.$"

OneIsland_KindleRoad_Text_EmberSpaSign::
    .string "Zapal ohen ve svém srdci!\n"
    .string "EMBER SPA$"

