IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "Jo!\n"
    .string "Budoucí sampione!\p"
    .string "V POKéMON LIZE budes celit\n"
    .string "ELITNÍ CTYRCE jednomu po druhém.\p"
    .string "Kdyz prohrajes, musís zacít\n"
    .string "úplne od zacátku!\p"
    .string "Tohle je ono!\n"
    .string "Do toho!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "Odsud dál celís\n"
    .string "ELITNÍ CTYRCE jeden po druhém.\p"
    .string "Kdyz vyhrajes, otevrou se\n"
    .string "dvere k dalsímu TRÉNÉROVI.\l"
    .string "Hodne stestí!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "Velmi se omlouvám, ale\n"
    .string "marnís zde svuj cas.\p"
    .string "LORELEI z ELITNÍ CTYRKY\n"
    .string "je nyní nepritomna.\p"
    .string "Proto je POKéMON LIGA\n"
    .string "docasne zavrená.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "AGATHINI DUCHOVÍ POKéMONi\n"
    .string "jsou desive houzevnatí.\p"
    .string "Vzal jsem si BOJOVÉ POKéMONy\n"
    .string "a vytrénoval je na maximum.\p"
    .string "Sel jsem na AGATHU sebevedome,\n"
    .string "ale naprala nám to.\p"
    .string "Ta starsí dáma má taky\n"
    .string "vybusnou povahu.\p"
    .string "Stací málo, aby ta desivá\n"
    .string "paní zacala krát.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "Mozná je v krvi byt clenem\n"
    .string "ELITNÍ CTYRKY.\p"
    .string "Z toho, co jsem slysel, má LANCE\n"
    .string "bratrance, ktery je VÚDCE GYMu\l"
    .string "nekde daleko.$"

