CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "Vylepsovace statu POKéMONu\n"
    .string "koupís jen tady.\p"
    .string "HP UP zvysí základní HP\n"
    .string "POKéMONa.\p"
    .string "CALCIUM zvysí základní SP. ATK\n"
    .string "jednoho POKéMONa.\p"
    .string "ZINC zvedne základní SP. DEF\n"
    .string "jednoho POKéMONa.\p"
    .string "CARBOS posílí základní\n"
    .string "RYCHLOST.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "Jsem tu pro vylepsovace statu\n"
    .string "POKéMONu.\p"
    .string "PROTEIN zvysí základní sílu\n"
    .string "ÚTOKU.\p"
    .string "IRON zvedne základní\n"
    .string "OBRANU.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "5F: LÉKÁRNA$"
