PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "POKéMONi se ucí nové techniky,\n"
    .string "jak rostou.\p"
    .string "Ale nektery útoky je musí\n"
    .string "naucit lidé.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "POKéMON se chytá snadneji,\n"
    .string "kdyz má status problém.\p"
    .string "Spánek, jed, popáleniny nebo\n"
    .string "paralyza… To vse úcinkuje.\p"
    .string "Ale chytání POKéMONu nikdy\n"
    .string "není zarucené!$"

