SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
    .string "Tancuj, tancuj!\n"
    .string "CHANSEY Tanec!\p"
    .string "Pridej se taky!\n"
    .string "Tancuj, tancuj!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
    .string "Chces si zatancit?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
    .string "Tak pojd, tancuj!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
    .string "{PLAYER} zatancil CHANSEY Tanec!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
    .string "Ahahaha!\p"
    .string "Tak, ted jsi cely povzbuzeny!\n"
    .string "Stastlivec!$"

SevenIsland_SevaultCanyon_House_Text_Chansey::
    .string "CHANSEY: Chansi! Chansi!$"
