LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
    .string "TEAM ROCKET udelá cokoli\n"
    .string "pro peníze!\p"
    .string "Není zádná práce moc spinavá,\n"
    .string "zádny cin moc ohavny, zádny\l"
    .string "zlocin moc temny!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
    .string "Videl jsem matku CUBONEa, jak\n"
    .string "utíká pred TEAMEM ROCKET.\p"
    .string "Zabili ji pri úteku…$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
    .string "Vís, ze druh CUBONE nosí\n"
    .string "lebky, ze?\p"
    .string "Lidé za jednu zaplatí hodne.$"

