VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
    .string "Jsem RYBÁRSKY GURU!\p"
    .string "Strasne miluji rybarení!\n"
    .string "Bez nej nemohu byt.\p"
    .string "Rekni, mas rád rybarení?$"

VermilionCity_House1_Text_TakeThisAndFish::
    .string "Bezva! Mám rád tvuj styl.\n"
    .string "Asi muzeme byt kamarádi.\p"
    .string "Vezmi si to a rybar, mlady prítel!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
    .string "{PLAYER} dostal OLD ROD od\n"
    .string "RYBÁRSKÉHO GURU.$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
    .string "Rybarení je zpusob zivota!\n"
    .string "Je to jako nejjemnejsí poezie.\p"
    .string "Od morí k rekám, vyraz a chyt\n"
    .string "toho velkého, prítel.$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
    .string "Ach…\n"
    .string "To je takové zklamání…$"

VermilionCity_House1_Text_HowAreTheFishBiting::
    .string "Ahoj, {PLAYER}!\p"
    .string "Jak rybky berou?$"

VermilionCity_House1_Text_NoRoomForNiceGift::
    .string "Ó ne!\p"
    .string "Mel jsem pro tebe pekny dárek,\n"
    .string "ale nemás pro nej místo!$"

