PalletTown_Text_OakDontGoOut::
    .string "OAK: Hej! Pockej!\n"
    .string "Nechod ven!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "OAK: To je nebezpecné!\n"
    .string "Divocí POKéMON zijí ve vysoké tráve!\p"
    .string "Pro svou ochranu potrebujes\n"
    .string "svého vlastního POKéMONa.\p"
    .string "Uz vím!\n"
    .string "Pojd se mnou, ukázu ti to!$"

PalletTown_Text_RaisingMonsToo::
    .string "Taky chovám POKéMONy.\p"
    .string "Az budou silní, budou mé\n"
    .string "umet ochránit.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Technologie je neuveritelná!\p"
    .string "Predmety i POKéMONy se dají\n"
    .string "ukládat a vyvolávat pres PC.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "OAKOVA POKéMON LABORATOR$"

PalletTown_Text_PlayersHouse::
    .string "Dum: {PLAYER}$"

PalletTown_Text_RivalsHouse::
    .string "Dum: {RIVAL}$"

PalletTown_Text_TownSign::
    .string "MESTO PALLET\n"
    .string "Stíny tvé cesty te ocekávají!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "Tak jsi zase tady?\p"
    .string "Kolik uz jsi naplnil svuj\n"
    .string "POKéDEX?\p"
    .string "Mohu ho videt?\p"
    .string "Tak se mrkneme…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "Chytils {STR_VAR_2}…\p"
    .string "Hmm, vypadá to, ze se\n"
    .string "snazís opravdu poctive.\p"
    .string "Az ho zaplnís víc,\n"
    .string "prijd mi to ukázat, prosím.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "Chytils… {STR_VAR_2}!?\n"
    .string "To je vskutku úzasné!\p"
    .string "Mám pro tebe jednu otázku,\n"
    .string "{PLAYER}.\p"
    .string "Pojd.\n"
    .string "Následuj me.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "Zdá se, ze si uzívás cestování.\p"
    .string "Kdyz te znám, {PLAYER}, dovedu si\n"
    .string "tebe predstavit, jak se vydávás\l"
    .string "do jeste exotictejsích míst.\p"
    .string "Vyborne, jen tak dál.\n"
    .string "Hohoho.$"
