FiveIsland_Text_IslandSign::
    .string "FIVE ISLAND\n"
    .string "Chrono Island: Kde plyne cas$"

FiveIsland_Text_WeirdBuildingInMeadow::
    .string "Ach, to je smula. Chtel jsem si\n"
    .string "hrát na LOUCE.\p"
    .string "Ale postavili tam divnou budovu,\n"
    .string "takze si tam hrát nemuzu.$"

FiveIsland_Text_BeenGettingBusierAroundHere::
    .string "V poslední dobe je tady cím dál\n"
    .string "rusneji.\p"
    .string "A taky uz moc nelovím dobré\n"
    .string "ryby.$"

