SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles::
    .string "Mozná tak ted nevypadám,\n"
    .string "ale kdyz jsem byl mladsí…\p"
    .string "Létal jsem vsude, vyzyval\n"
    .string "TRÉNÉRY, kde jsem je nasel.\p"
    .string "Ted je mou jedinou zábavou\n"
    .string "vzpomínat na minulost pri\l"
    .string "sledování souboju.$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
    .string "Kolem bedny fouká\n"
    .string "lehky vánek.$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer::
    .string "Ach!\n"
    .string "Vítej, príteli!\p"
    .string "Necho ti neco rekl. V suterénu\n"
    .string "je skrytá místnost.\p"
    .string "TRÉNÉR jménem {STR_VAR_1} tam\n"
    .string "ted ceká.\p"
    .string "Prisel jsi vyzvat {STR_VAR_1},\n"
    .string "ze ano?$"

SevenIsland_House_Room1_Text_OhYouWontBattle::
    .string "Ach…\n"
    .string "Nebudes bojovat…\p"
    .string "Aha, aha.\n"
    .string "… …\p"
    .string "No, mozná kdyz si to rozmyslís,\n"
    .string "vrat se.$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide::
    .string "Ach!\n"
    .string "Budes za me bojovat?\p"
    .string "Stálo to za to presunout tu\n"
    .string "bednu stranou.\p"
    .string "… …\n"
    .string "Ale je tu jeden problém.\p"
    .string "Tato skrytá místnost není\n"
    .string "stavena moc pevne.\p"
    .string "Muzu te poprosit o omezení\n"
    .string "na tri POKéMONy na stranu?$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle::
    .string "Fajn! Pred bitvou si chces\n"
    .string "ulozit hru?$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack::
    .string "Tak dobre.\n"
    .string "Nedrz se zpátky!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw::
    .string "Zápas skoncil remízou.$"

SevenIsland_House_Room1_Text_DrawWasIt::
    .string "Remíza, hm?\p"
    .string "Nicméne, byla to úctyhodná\n"
    .string "podívaná.\p"
    .string "Rekl bych, ze to byla\n"
    .string "krásná bitva s opravdovou\l"
    .string "hloubkou!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle::
    .string "Bravo!\p"
    .string "Bravo, opravdu!\n"
    .string "Jaká úzasná bitva!\p"
    .string "Bylo to tak úzasné, ze mi\n"
    .string "to porád dohání slzy do ocí!\p"
    .string "Vypady a parádování zkusene\n"
    .string "pouzitymi technikami!\p"
    .string "Strety síly se silou!\p"
    .string "Ano!\n"
    .string "Byla to cistá nádhera!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment::
    .string "Skoda!\n"
    .string "Cítím tvoje zklamání.\p"
    .string "Nicméne, to zklamání je to,\n"
    .string "co te ucinilo lepsím.\p"
    .string "Pouzij ho, uc se z nej a\n"
    .string "nech ho te motivovat k velikosti.\p"
    .string "Nezapomen na toto zklamání\n"
    .string "a zdvojnásob svuj trénink!$"

