RockTunnel_B1F_Text_SofiaIntro::
    .string "Vís, jak se neztratit\n"
    .string "v horách?\p"
    .string "Muzes ohybat vetvicky jako\n"
    .string "znacky cesty.$"

RockTunnel_B1F_Text_SofiaDefeat::
    .string "Ouvej!\n"
    .string "Dala jsem do toho vse!$"

RockTunnel_B1F_Text_SofiaPostBattle::
    .string "Chci jít domu!$"

RockTunnel_B1F_Text_DudleyIntro::
    .string "Hahaha!\n"
    .string "Zvládnes mou sílu?$"

RockTunnel_B1F_Text_DudleyDefeat::
    .string "Jejda!\n"
    .string "Preválcován!$"

RockTunnel_B1F_Text_DudleyPostBattle::
    .string "Jdu na sílu, protoze nesnásím\n"
    .string "premyslení.$"

RockTunnel_B1F_Text_CooperIntro::
    .string "Más POKéDEX?\n"
    .string "Taky bych ho chtel.$"

RockTunnel_B1F_Text_CooperDefeat::
    .string "Sakra!\n"
    .string "Tak moc zárlím!$"

RockTunnel_B1F_Text_CooperPostBattle::
    .string "Az dokoncís svuj POKéDEX,\n"
    .string "muzu ho mít já?$"

RockTunnel_B1F_Text_SteveIntro::
    .string "Hm… Vís neco o POKéMON\n"
    .string "cosplayi?$"

RockTunnel_B1F_Text_SteveDefeat::
    .string "Tak to bychom meli.$"

RockTunnel_B1F_Text_StevePostBattle::
    .string "POKéMON cosplay je oblékání se\n"
    .string "za POKéMONy pro zábavu.\p"
    .string "CLEFAIRY je oblíbená.$"

RockTunnel_B1F_Text_AllenIntro::
    .string "Mé POKéMON techniky te nechají\n"
    .string "brecet!$"

RockTunnel_B1F_Text_AllenDefeat::
    .string "Vzdávám!\n"
    .string "Jsi lepsí technik!$"

RockTunnel_B1F_Text_AllenPostBattle::
    .string "V horách casto najdes\n"
    .string "POKéMONy typu ROCK.$"

RockTunnel_B1F_Text_MarthaIntro::
    .string "Sem moc nechodím, ale s tebou\n"
    .string "se utkám.$"

RockTunnel_B1F_Text_MarthaDefeat::
    .string "Ach!\n"
    .string "Prohrála jsem!$"

RockTunnel_B1F_Text_MarthaPostBattle::
    .string "Mám ráda malé POKéMONy.\n"
    .string "Velké jsou moc strasidelné!$"

RockTunnel_B1F_Text_EricIntro::
    .string "Dej do toho vse, co más!$"

RockTunnel_B1F_Text_EricDefeat::
    .string "Odpáleno!$"

RockTunnel_B1F_Text_EricPostBattle::
    .string "Vychovám své POKéMONy, aby\n"
    .string "porazili tvé, mlady.$"

RockTunnel_B1F_Text_WinstonIntro::
    .string "Doma kreslím ilustrace\n"
    .string "POKéMONu.$"

RockTunnel_B1F_Text_WinstonDefeat::
    .string "Uf…\n"
    .string "Jsem vycerpany…$"

RockTunnel_B1F_Text_WinstonPostBattle::
    .string "Jsem umelec, ne bojovník.\n"
    .string "Pujdu domu kreslit.$"

