Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou::
    .string "Dobre, dáme sest POKé BALLU\n"
    .string "do opasku…\p"
    .string "Jo, to staci. Nanejvys muzes\n"
    .string "mít s sebou sest POKéMONu.$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean::
    .string "TEAM ROCKET napadá obcany\n"
    .string "CERULEAN…\p"
    .string "Neprojde den, aby o TEAM ROCKET\n"
    .string "nepsali ve zprávách.$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500::
    .string "MUZ: Ahoj, mlady muzi!\n"
    .string "Mám pro tebe nabídku!\p"
    .string "Prodám ti tajného POKéMONa\n"
    .string "- MAGIKARPa - jen za ¥500!\p"
    .string "Tak ho koupís, ze?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500::
    .string "MUZ: Ahoj, slecinko!\n"
    .string "Mám pro tebe nabídku!\p"
    .string "Prodám ti tajného POKéMONa\n"
    .string "- MAGIKARPa - jen za ¥500!\p"
    .string "Tak ho koupís, ze?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
    .string "{PLAYER} zaplatil neslychanych\n"
    .string "¥500 a koupil MAGIKARPa…$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
    .string "Ne? Ríkás ne? Delám to jen\n"
    .string "pro tebe, jako laskavost!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
    .string "Vypadá to, ze uz nemás místo\n"
    .string "pro dalsí POKéMONy.$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
    .string "Na to budes potrebovat víc penez!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds::
    .string "MUZ: Nevracím peníze.\n"
    .string "Vedels, co kupujes!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
    .string "Nekdy mas s sebou tolik POKéMONu,\n"
    .string "ze uz nepriberes zádné dalsí.\p"
    .string "V tom prípade si nekteré\n"
    .string "ulozís na PC.$"

Route4_PokemonCenter_1F_Text_ItsANewspaper::
    .string "Jsou to noviny.$"

