RocketHideout_B4F_Text_GiovanniIntro::
    .string "Tak! Musím ríct, ze jsem zaujat,\n"
    .string "ze ses sem dostal.\p"
    .string "TEAM ROCKET chytá POKéMONy\n"
    .string "z celého sveta.\p"
    .string "Jsou to dulezité nástroje pro\n"
    .string "nás zlocinecky podnik.\p"
    .string "Jsem vudce, GIOVANNI!\p"
    .string "Za svou drzost zazijes\n"
    .string "svet bolesti!$"

RocketHideout_B4F_Text_GiovanniDefeat::
    .string "COZE!\n"
    .string "To není mozné!$"

RocketHideout_B4F_Text_GiovanniPostBattle::
    .string "Vidím, ze POKéMONy chovás\n"
    .string "s plnou péci.\p"
    .string "Dítko jako ty by nikdy\n"
    .string "nepochopilo, co chci dosáhnout.\p"
    .string "Tentokrát ustoupím!\p"
    .string "Doufám, ze se zase setkáme…$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "Znám te!\n"
    .string "Znicils nase plány na MT. MOON!$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "Spáleno!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
    .string "Mas neco proti TEAM\n"
    .string "ROCKET?$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "Jak nevidís krásu naseho\n"
    .string "zla?$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "Ajajaj!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
    .string "BOSSI!\n"
    .string "Promin, ze jsem te zklamal!$"

RocketHideout_B4F_Text_Grunt1Intro::
    .string "Vytah nefunguje?\n"
    .string "Kdo má LIFT KEY?$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "Ne!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
    .string "Ach ne!\n"
    .string "Upustil jsem LIFT KEY!$"
