TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
    .string "Kde se LOSTELLE dnes\n"
    .string "potuluje?\p"
    .string "Vzdy mi nosí obed kazdy den\n"
    .string "presne v tuto dobu…$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
    .string "Hm? Ty tam!\n"
    .string "Jsi prítel LOSTELLE?\p"
    .string "Videls LOSTELLE nekde?\n"
    .string "Nevím, kde by mohla byt.\l"
    .string "Mela tu byt uz dávno.\p"
    .string "LOSTELLE je krasavice - má muj\n"
    .string "vzhled - co kdyby nekdo…\p"
    .string "Co kdyby se neco stalo\n"
    .string "mé LOSTELLE?!\p"
    .string "Prosím, pomoz mi ji najít!\n"
    .string "Prosím, projdi THREE ISLAND!$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
    .string "Ha? Co je to za GAME CORNER?\n"
    .string "Jak smutnejsí to muze byt?\p"
    .string "Ti hlupáci…\p"
    .string "Ríkali, ze cekají na ostrove,\n"
    .string "tak kde jsou?\p"
    .string "Hej, ty! Je tohle jediny THREE\n"
    .string "ISLAND v okolí?$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
    .string "Zkus se probudit, nez vylezes\n"
    .string "z postele, ty grázle.\p"
    .string "Tohle je TWO ISLAND!\p"
    .string "Hni se! Sundej tu spinavou\n"
    .string "motorku z mého místa!$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
    .string "Hm…\n"
    .string "Ach, jasne.\p"
    .string "Tch…\n"
    .string "Tyhle ostrovy matou…$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
    .string "Podívej se na to!\n"
    .string "Ten grázl mi poskrábal podlahu.$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
    .string "Hej, ale poslouchej! Prosím te,\n"
    .string "musís jít na THREE ISLAND.\p"
    .string "Kdyby se mé LOSTELLE neco\n"
    .string "stalo…\p"
    .string "Muj dum je ten s cervenou\n"
    .string "strechou na THREE ISLAND.\p"
    .string "Mozná se tu jen objeví pozde,\n"
    .string "takze nemuzu nikam odejít.\p"
    .string "Proto te musím poprosit\n"
    .string "o tuhle velkou laskavost.$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
    .string "Omlouvám se.\n"
    .string "Dnes hry neprovozujeme.$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
    .string "Brzy hry pro tebe\n"
    .string "spustíme!$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
    .string "Tak jsi zachránil LOSTELLE?\n"
    .string "Jak ti mám podekovat?\p"
    .string "LOSTELLE, miláci, odpust mi!\p"
    .string "Tatínek nevedel, ze se bojís\n"
    .string "a más potíze!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
    .string "LOSTELLE: To je v pohode, tati.\n"
    .string "Skamarádila jsem se s {PLAYER}!$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
    .string "Ach, co je to?\n"
    .string "Ríkás, ze tohle je pro me?\p"
    .string "Jak jsi vedel, ze mám rád\n"
    .string "vzácné kameny a drahokamy?\p"
    .string "Vís, jak udelat chlapa\n"
    .string "stastnym.$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
    .string "{PLAYER} predal METEORIT\n"
    .string "tatínkovi LOSTELLE.$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
    .string "Aha, vidím, je to od BILLA!\n"
    .string "Musís mu za to podekovat!\p"
    .string "Vís, byl jsi fantasticky.\n"
    .string "Chci, abys mel tohle.$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
    .string "{PLAYER} obdrzel MOON STONE\n"
    .string "od tatínka LOSTELLE.$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
    .string "Do tvého BATOHU se uz nic\n"
    .string "nevejde…$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
    .string "Dobre, hned uvedu GAME CORNER\n"
    .string "do provozu.\p"
    .string "Musís prijít s kámosem na návstevu.$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
    .string "Poslouchej, poslouchej!\p"
    .string "Prosím, ukaz mi zase,\n"
    .string "jak jsi cool!$"

