FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland::
    .string "Na tomto ostrove vyrostla\n"
    .string "skvelá a mocná TRÉNÉRKA.\p"
    .string "Vsadím se, ze ji znás.\n"
    .string "Je to LORELEI z ELITNÍ CTYRKY!\p"
    .string "Kdyz byla LORELEI mensí,\n"
    .string "ucila jsem ji o POKéMONech.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid::
    .string "Ostrovy SEVII jsou v celku\n"
    .string "v teplé oblasti.\p"
    .string "Ale je tu jedna vyjimka, kterou\n"
    .string "bys mel znát.\p"
    .string "ICEFALL CAVE je ledová kvuli\n"
    .string "POKéMONum, kterí v ní zijí.$"

