SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "…Pockej! Nic neríkej!\p"
    .string "Chtel jsi tohle!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "{PLAYER} dostal TM29\n"
    .string "od MR. PSYCHIC.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "Uz to vís, vid?\n"
    .string "TM29 je PSYCHIC.\p"
    .string "Je to útok, ktery muze taky\n"
    .string "snízit speciální staty cíle.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "Kam to chces dát?\n"
    .string "Nemás místo.$"
