FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland::
    .string "LORELEI: Nesto mi tezce\n"
    .string "lezí na mysli.\p"
    .string "Kdyby se neco stalo\n"
    .string "na ostrove, kde jsem se narodila…\p"
    .string "Nedozvedela bych se to,\n"
    .string "kdybych byla v POKéMON LIZE.\p"
    .string "Premyslím, jestli bych tak\n"
    .string "neopustila svuj domov…$"

FourIsland_LoreleisHouse_Text_IllReturnToLeagueInShortWhile::
    .string "LORELEI: Takze jsi vyresil\n"
    .string "vsechny problémy zde?\p"
    .string "To je nádherné.\p"
    .string "Takze uz není duvod, abych\n"
    .string "tu byla porád.\p"
    .string "Dekuji ti…\p"
    .string "Brzy se vrátím do\n"
    .string "POKéMON LIGY.$"

FourIsland_LoreleisHouse_Text_WillDoWhatICanHereAndNow::
    .string "Nevím, co se stane\n"
    .string "v budoucnu, ale…\p"
    .string "Udelám, co mohu, ted a tady.\n"
    .string "Víc neumím.$"

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore::
    .string "Spousta plysovych POKéMONu!$"

