CeruleanCity_House4_Text_NothingEntertaining::
    .string "Povzdech…\n"
    .string "Moc casu, málo zábavy…\p"
    .string "To se nikde nedeje nic\n"
    .string "zajímavého?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
    .string "Ah!\n"
    .string "Nová zpráva!\p"
    .string "Hmm…\p"
    .string "Aha!\n"
    .string "To bylo dost poucné!\p"
    .string "Chválím te, ze se v tak mladém\n"
    .string "veku zajímás o zprávy.\p"
    .string "Za to, ze ses se mnou o zprávu\n"
    .string "podelil, chci, abys to dostal.$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
    .string "Ó, ó!\n"
    .string "Ta-tahle zpráva!\p"
    .string "Hmm…\p"
    .string "Úzasné!\n"
    .string "To je neuveritelná zpráva!\p"
    .string "Tak úzasnou zprávu jsem uz\n"
    .string "hodne dlouho neslysel!\p"
    .string "Díky za sdílení té skvelé\n"
    .string "zprávy. Tu más plno BERRIES!$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
    .string "Je skoda nepodelit se o tuhle\n"
    .string "zprávu s ostatními lidmi…\p"
    .string "Kéz bych mohl nekomu ríct…\n"
    .string "Dát ostatním vedet o zprávách…$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
    .string "Ah, ty jsi tu zprávu rozsíril?\p"
    .string "Dobrá zpráva má cenu, kdyz\n"
    .string "ji sdílí spousta lidí.\p"
    .string "Za to, ze jsi tu zprávu\n"
    .string "rozsíril, si tohle vezmi!$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
    .string "Rozsíril jsi zprávu jeste víc?\n"
    .string "Skvelé!\p"
    .string "Ta zpráva musí byt nadsená,\n"
    .string "ze se takhle predává dál.\p"
    .string "Ano, vskutku!\p"
    .string "Ber to jako projev vdeku\n"
    .string "ode me a od té zprávy.\p"
    .string "Dám ti víc BERRIES, nez\n"
    .string "obvykle dávám.$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
    .string "Uzívám si rozmanité\n"
    .string "zprávy.\p"
    .string "Ano, jsem spokojeny!\n"
    .string "Chvíli se nudit nebudu.$"

CeruleanCity_House4_Text_YourBerryPouchIsFull::
    .string "Hm? Tvuj BERRY POUCH je plny.\n"
    .string "Tak dárek zustane nepredany.$"
