FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth::
    .string "SPRÁVCE SAFARI ZONE je stary,\n"
    .string "ale porád velmi aktivní.\p"
    .string "Vsechny zuby má ale umelé.$"

FuchsiaCity_House1_Text_BillIsMyGrandson::
    .string "Hmm?\n"
    .string "Potkals BILLA?\p"
    .string "To je muj vnuk!\p"
    .string "Vzdy rád sbíral veci,\n"
    .string "uz jako díte!$"

FuchsiaCity_House1_Text_BillFilesHisOwnMonData::
    .string "BILL si vede vlastní data\n"
    .string "POKéMONu na svém PC.\p"
    .string "Ukázal ti to?$"

