CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
    .string "Je to fotka BLAINE a\n"
    .string "PANA FUJIHO.\p"
    .string "Stojí rameno na rameni\n"
    .string "s velkymi úsmevy.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "Studujeme POKéMONy do hloubky\n"
    .string "kazdy den.\p"
    .string "Lidé nám casto nosí vzácné\n"
    .string "POKéMONy k vysetrení.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "Fotka zakladatele LABu…\n"
    .string "DR. FUJI?!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "POKéMON LAB\n"
    .string "Zasedací místnost$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "POKéMON LAB\n"
    .string "Vyzkumná místnost$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "POKéMON LAB\n"
    .string "Testovací místnost$"

