FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "Uh…\n"
    .string "Ano, jsem MAZAC ÚTOKU.\p"
    .string "Mohu POKéMONy nechat\n"
    .string "zapomenout jejich útoky.\p"
    .string "Chces, abych to udelal?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "Ktery POKéMON má zapomenout\n"
    .string "útok?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "Ktery útok má byt zapomenut?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "{STR_VAR_1} zná jen jeden\n"
    .string "útok…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "Hm! {STR_VAR_2} POKéMONa\n"
    .string "{STR_VAR_1}? Má byt zapomenut?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "Vyslo to dokonale!\p"
    .string "{STR_VAR_1} úplne\n"
    .string "zapomnel {STR_VAR_2}.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "Vrat se, kdyz budou jiné\n"
    .string "útoky k zapomenutí.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "Co?\n"
    .string "Zádné VEJCE nezná útoky.$"

