VictoryRoad_1F_Text_NaomiIntro::
    .string "Jestlipak jsi dost dobry\n"
    .string "na me?$"

VictoryRoad_1F_Text_NaomiDefeat::
    .string "Prohrála jsem…$"

VictoryRoad_1F_Text_NaomiPostBattle::
    .string "Nikdy jsem nechtela nikomu\n"
    .string "prohrát, hlavne mladsímu klukovi…$"

VictoryRoad_1F_Text_RolandoIntro::
    .string "Vidím, ze jsi dobry.\n"
    .string "Ukaz mi presne, jak moc!$"

VictoryRoad_1F_Text_RolandoDefeat::
    .string "Mel jsem sanci…$"

VictoryRoad_1F_Text_RolandoPostBattle::
    .string "Tja!\n"
    .string "Uznávám, jsi lepsí nez já!$"
