SafariZone_East_Text_KeepAnyItemFoundOnSafari::
    .string "Jakykoli predmet, co najdes v\n"
    .string "SAFARI ZONE, si muzes nechat.\p"
    .string "Ale dojde ti cas, kdyz se o ne\n"
    .string "budes pokouset vsechny najednou.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
    .string "Jdi do nejhlubsí cásti SAFARI\n"
    .string "ZONE. Vyhrajes cenu!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
    .string "Moje EEVEE se vyvinulo na FLAREON.\p"
    .string "Ale EEVEE kamaráda se zmenilo na\n"
    .string "VAPOREON. Coze, proc?$"
