PokemonTower_3F_Text_HopeIntro::
    .string "Urrg… Awaa…\n"
    .string "Huhu… Graa…$"

PokemonTower_3F_Text_HopeDefeat::
    .string "Hwa!\n"
    .string "Jsem zachránená!$"

PokemonTower_3F_Text_HopePostBattle::
    .string "Duchové se dají identifikovat\n"
    .string "pomocí SILPH SCOPE.$"

PokemonTower_3F_Text_CarlyIntro::
    .string "Kekeke…\n"
    .string "Kwaaah!$"

PokemonTower_3F_Text_CarlyDefeat::
    .string "Hmm?\n"
    .string "Co to delám?$"

PokemonTower_3F_Text_CarlyPostBattle::
    .string "Promin!\n"
    .string "Byla jsem posedlá!$"

PokemonTower_3F_Text_PatriciaIntro::
    .string "Zmiz!\n"
    .string "Zlovestny duchu!$"

PokemonTower_3F_Text_PatriciaDefeat::
    .string "Uf!\n"
    .string "Duch odesel!$"

PokemonTower_3F_Text_PatriciaPostBattle::
    .string "Ti ostatní nahore…\n"
    .string "Museli byt posedlí.$"

