PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: Co, jen {PLAYER}?\n"
    .string "Dedek tu není.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: Dedku!\n"
    .string "Uz me unavuje cekání!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: Hej! Dedku! To není fér!\n"
    .string "Co bude se mnou?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: Pche, nemusím byt tak\n"
    .string "lacomy jako ty. Já jsem dospely!\p"
    .string "Tak si vyber, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: Tak já si vezmu tohohle!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} dostal {STR_VAR_1}\n"
    .string "od PROF. OAKA!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: Muj POKéMON vypadá mnohem\n"
    .string "drsneji nez ten tvuj.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: Pockej, {PLAYER}!\n"
    .string "Vyzkousíme nase POKéMONy!\p"
    .string "Pojd, postavím se ti!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "CO?\n"
    .string "Neuveritelné!\l"
    .string "Vybral jsem si spatného POKéMONa!$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: Jo!\n"
    .string "Jsem skvely, ze?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: Dobre! Nechám\n"
    .string "POKéMONa bojovat, at zesílí!\p"
    .string "{PLAYER}! Dedku!\n"
    .string "Mejte se!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: Dedku!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: Skoro jsem zapomnel!\n"
    .string "Proc jsi me volal?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: Spolehni se, dedku!\n"
    .string "Vsechno nech na me!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}, neradi to ríkám, ale ty\n"
    .string "nebudes potreba.\p"
    .string "Uz vím! Pujcím si MAPU MESTA\n"
    .string "od sestry!\p"
    .string "Reknu jí, at ti zádnou nepujcí,\n"
    .string "{PLAYER}! Hahaha!\p"
    .string "Ani se neobtezuj k nám\n"
    .string "potom chodit!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "OAK: {RIVAL}?\n"
    .string "Pockej, premyslím…\p"
    .string "Aha, jiste, ríkal jsem ti, at\n"
    .string "prijdes! Pockej chvíli!\p"
    .string "Tady, {PLAYER}.\p"
    .string "Tady jsou tri POKéMONi.\p"
    .string "Haha!\p"
    .string "POKéMONi jsou uvnitr techto\n"
    .string "POKé BALLU.\p"
    .string "Kdyz jsem byl mlady, byl jsem\n"
    .string "vázny POKéMON TRÉNÉR.\p"
    .string "Ale ted, ve svém stárí, mi zbyli\n"
    .string "uz jen tihle tri.\p"
    .string "Jeden je tvuj.\n"
    .string "Tak si vyber!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "OAK: Bud trpelivy, {RIVAL}.\n"
    .string "Ty taky jednoho dostanes!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "OAK: A ted, {PLAYER}.\p"
    .string "V techto trech POKé BALLECH\n"
    .string "jsou POKéMONi.\p"
    .string "Kterého si vyberes\n"
    .string "pro sebe?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "OAK: Hej!\n"
    .string "Jeste neodcházej!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "Ah! Vybral sis CHARMANDERA.\n"
    .string "Musís ho trpelive vychovávat.\p"
    .string "Tedy, {PLAYER}, beres si\n"
    .string "OHNIVÉHO POKéMONA CHARMANDERA?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "Hm! Vybral sis SQUIRTLA.\n"
    .string "Stojí za to ho vychovat.\p"
    .string "Tedy, {PLAYER}, rozhodl ses pro\n"
    .string "VODNÍHO POKéMONA SQUIRTLA?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "Aha! Vybral sis BULBASAURA.\n"
    .string "Toho se snadno vychovává.\p"
    .string "Tedy, {PLAYER}, chces si vzít\n"
    .string "TRAVNÍHO POKéMONA BULBASAURA?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "Tento POKéMON je opravdu\n"
    .string "plny energie!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER} dostal {STR_VAR_1}\n"
    .string "od PROF. OAKA!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "OAK: Pokud se objeví divoky POKéMON,\n"
    .string "tvuj POKéMON s ním muze bojovat.\p"
    .string "S ním po boku bys mel zvládnout\n"
    .string "dostat se do dalsího mesta.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "OAK: {PLAYER}, vychovávej svého\n"
    .string "mladého POKéMONA v souboji.\p"
    .string "Musí bojovat, aby vyrostl.$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "Jak se má muj stary POKéMON?\p"
    .string "Inu, zdá se, ze si te víc a víc\n"
    .string "oblíbil.\p"
    .string "Musís byt nadany jako POKéMON\n"
    .string "TRÉNÉR.\p"
    .string "Coze?\n"
    .string "Más pro me neco?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} dorucil OAKUV BALÍCEK.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "Ah! \n"
    .string "To je ten POKé BALL na míru!\p"
    .string "Objednal jsem si ho.\n"
    .string "Dekuji!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "OAK: Aha, jeste neco!\n"
    .string "Mám pro vás prosbu.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "Na stole je muj vynález,\n"
    .string "POKéDEX!\p"
    .string "Automaticky zaznamenává data\n"
    .string "o POKéMONech, které jsi videl\l"
    .string "nebo chytil.\p"
    .string "Je to vyspelá encyklopedie!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "OAK: {PLAYER} a {RIVAL}.\n"
    .string "Vezmete si tohle s sebou.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} dostal POKéDEX\n"
    .string "od PROF. OAKA.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "OAK: Nemuzes získat údaje\n"
    .string "o POKéMONech jen tím, ze je vidís.\p"
    .string "Musís je chytit, abys získal\n"
    .string "kompletní data.\p"
    .string "Tak, tady jsou nástroje na\n"
    .string "chytání divokych POKéMONu.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} dostal pet POKé BALLU.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "Kdyz se objeví divoky POKéMON,\n"
    .string "je hrou na chycení.\p"
    .string "Stací po nem hodit POKé BALL\n"
    .string "a zkus ho chytit!\p"
    .string "Ne vzdy to ale vyjde.\p"
    .string "Zdravy POKéMON muze utéct.\n"
    .string "Musís mít stestí!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "Vytvorit kompletní pruvodce vsemi\n"
    .string "POKéMONy na svete…\p"
    .string "To byl muj sen!\p"
    .string "Ale jsem uz prílis stary.\n"
    .string "Nezvládnu to.\p"
    .string "Tak chci, abyste vy dva splnili\n"
    .string "muj sen za me.\p"
    .string "Hned se do toho pustte.\p"
    .string "Je to velkolepy pocin v\n"
    .string "historii POKéMONu!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "POKéMONi po celém svete cekají\n"
    .string "na tebe, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Ah, {PLAYER}!\n"
    .string "Jak se ti darí POKéDEX?\p"
    .string "{RIVAL} uz nekolik POKéMONu\n"
    .string "chytil a pridal je do dat.\p"
    .string "Tak, {PLAYER}, podíváme se na\n"
    .string "tvuj POKéDEX.\p"
    .string "…Co se deje?\n"
    .string "Nepridal jsi vubec nic.\p"
    .string "Dám ti tohle, tak se snaz\n"
    .string "víc.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "OAK: Stav se za mnou nekdy.\p"
    .string "Konec koncu, chci vedet, jak\n"
    .string "se ti POKéDEX darí.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "Je to jako encyklopedie, ale\n"
    .string "stránky jsou prázdné.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "To jsou POKé BALLY.\n"
    .string "Obsahují POKéMONy!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "To je poslední POKéMON PROF. OAKA.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "Stiskni START a otevri MENU!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "Moznost SAVE je v MENU.\n"
    .string "Pouzívej ji pravidelne.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "Vsechny typy POKéMONu mají silné\n"
    .string "i slabé stránky proti ostatním.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "Je tu e-mailová zpráva.\p"
    .string "…\p"
    .string "Konecne!\n"
    .string "Nejlepsí TRÉNÉRI POKéMON LIGY\l"
    .string "jsou pripraveni postavit se\l"
    .string "vsem prícházejícím!\p"
    .string "Prines svoje nejlepsí POKéMONy\n"
    .string "a uvidís, jaky jsi TRÉNÉR!\p"
    .string "VELITELSTVÍ POKéMON LIGY\n"
    .string "INDIGO PLATEAU\p"
    .string "PROF. OAK, prosím navstivte nás!\n"
    .string "…$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "Studuji POKéMONy jako asistent\n"
    .string "PROF. OAKA.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Ahoj, {PLAYER}. Vsadím se, zes\n"
    .string "se spratelil se svymi POKéMONy.\p"
    .string "Mimochodem, znás DAISY?\p"
    .string "Kdyz jí ukázes svého POKéMONa,\n"
    .string "rekne ti, jak moc te má rád.\p"
    .string "Obcas ho dokonce i ucese.\p"
    .string "Je to tajemství, tak to\n"
    .string "nikomu nerikej.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "PROF. OAK bude mít brzy vlastní\n"
    .string "rozhlasovy porad.\p"
    .string "Bude se jmenovat POKéMON\n"
    .string "SEMINÁR PROF. OAKA.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "PROF. OAK sice nevypadá moc,\n"
    .string "ale je odborník na POKéMONy.\p"
    .string "Mnoho POKéMON TRÉNÉRU si ho\n"
    .string "velmi vází.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Ah, to je vyborné!\p"
    .string "{PLAYER}, mám pro tebe dalsí\n"
    .string "duleziou prosbu.\p"
    .string "Pozorne me poslouchej.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "V poslední dobe se objevilo\n"
    .string "mnoho vzácnych POKéMONu.\p"
    .string "Mluvím o POKéMONech, kterí\n"
    .string "v KANTU nikdy nebyli videni.\p"
    .string "Rád bych se tam vydal, ale\n"
    .string "jsem uz prílis stary.\p"
    .string "Jelikoz to nemohu udelat já,\n"
    .string "{PLAYER}, chci, abys jel ty.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Hej, to jsem slysel!\p"
    .string "Dedku, proc {PLAYER} porád\n"
    .string "uprednostnujes pred mnou?\p"
    .string "Já chytil víc POKéMONu a\n"
    .string "navíc rychleji.\p"
    .string "Mel bys to nechat na me, at\n"
    .string "se postarám o vsechno.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "OAK: Já vím, já vím.\n"
    .string "Samozrejme potrebuji i tvou pomoc.\p"
    .string "Ted potrebuji videt oba\n"
    .string "vase POKéDEXY.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "PROF. OAK si vzal oba\n"
    .string "POKéDEXY.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…A je to hotové!\p"
    .string "Ted muzou zaznamenávat data\n"
    .string "o mnohem více POKéMONech.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{PLAYER}uv POKéDEX byl vylepsen!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "A ted, {PLAYER} a {RIVAL}!\p"
    .string "Tentokrát se opravdu musíte\n"
    .string "snazit naplnit POKéDEXY.\p"
    .string "Vyzyvám vás, udelejte z nich\n"
    .string "ty nejlepsí a nejúplnejsí!\p"
    .string "Skutecne je to velky pocin\n"
    .string "v historii POKéMONu!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Dedku, klid.\n"
    .string "Tolik se nerozciluj.\p"
    .string "Já POKéDEX dokoncím,\n"
    .string "o to se neboj.\p"
    .string "Asi se zacnu rozhlízet\n"
    .string "kolem ONE ISLAND…\p"
    .string "Tak jako tak, padám!$"
