SSAnne_2F_Room2_Text_BrooksIntro::
    .string "Soutezit s mladymi me drzí\n"
    .string "mladym.$"

SSAnne_2F_Room2_Text_BrooksDefeat::
    .string "Dobry zápas!\n"
    .string "Ach, cítím se zase mlady!$"

SSAnne_2F_Room2_Text_BrooksPostBattle::
    .string "Pred patnácti lety bych\n"
    .string "byl vyhrál!$"

SSAnne_2F_Room2_Text_DaleIntro::
    .string "Koukni, co jsem vylovil!$"

SSAnne_2F_Room2_Text_DaleDefeat::
    .string "Je se mnou konec!$"

SSAnne_2F_Room2_Text_DalePostBattle::
    .string "Party?\p"
    .string "Veciry na vyletní lodi by uz\n"
    .string "mela skoncit.$"
