SaffronCity_Dojo_Text_MasterKoichiIntro::
    .string "Hrr!\p"
    .string "Jsem KARATE MISTR!\n"
    .string "Jsem VÚDCE tohoto místa!\p"
    .string "Chces nás vyzvat?\n"
    .string "Necekej zádné slitování!\p"
    .string "Fwaaa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .string "Hwa!\n"
    .string "Argh! Porazen!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
    .string "Vskutku, prohrál jsem!\p"
    .string "Ale prosím te, neber si nás\n"
    .string "emblém jako trofej!\p"
    .string "Místo toho ti dám cenného\n"
    .string "FIGHTING POKéMONa!\p"
    .string "Vyber si toho, kterého chces!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
    .string "Hrr!\n"
    .string "Zustan a trénuj s námi karate!$"

SaffronCity_Dojo_Text_MikeIntro::
    .string "Hoargh!\n"
    .string "Sundej si boty!$"

SaffronCity_Dojo_Text_MikeDefeat::
    .string "Vzdávám se!$"

SaffronCity_Dojo_Text_MikePostBattle::
    .string "Pockej, az uvidís naseho MISTRA!\n"
    .string "Já jsem proti nemu malá ryba!$"

SaffronCity_Dojo_Text_HidekiIntro::
    .string "Slysel jsem, ze jsi dobry!\n"
    .string "Ukaz mi to!$"

SaffronCity_Dojo_Text_HidekiDefeat::
    .string "Rozhodcí!\n"
    .string "Jeden bod!$"

SaffronCity_Dojo_Text_HidekiPostBattle::
    .string "Nás MISTR je profesionální bojovník.\n"
    .string "Bud pripraven prohrát!$"

SaffronCity_Dojo_Text_AaronIntro::
    .string "Hijá!\n"
    .string "Niceho tvrdého se nebojím!\p"
    .string "Kazdy den rozbíjím balvany\n"
    .string "v rámci tréninku!$"

SaffronCity_Dojo_Text_AaronDefeat::
    .string "Au!\n"
    .string "Zlomil jsem si prsty!$"

SaffronCity_Dojo_Text_AaronPostBattle::
    .string "Jediné, ceho se bojíme,\n"
    .string "je psychická síla!$"

SaffronCity_Dojo_Text_HitoshiIntro::
    .string "Hwaah!\p"
    .string "Vnikás na nase území,\n"
    .string "FIGHTING DOJO!$"

SaffronCity_Dojo_Text_HitoshiDefeat::
    .string "Uf!\n"
    .string "Vzdávám se!$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
    .string "Trénují tu nejlepsí bojovníci\n"
    .string "ze vsech kraju.$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
    .string "Chces silne kopajícího\n"
    .string "HITMONLEE?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
    .string "{PLAYER} obdrzel {STR_VAR_1}\n"
    .string "od KARATE MISTRA.$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
    .string "Chces pístove pestícího\n"
    .string "HITMONCHAN?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
    .string "{PLAYER}は　カラテ　だいおう　から\n"
    .string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
    .string "Lépe nebyt chamtivy…$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
    .string "Neprátelé na vsech stranách!$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
    .string "Co se vrací, to se vrací.$"

SaffronCity_Dojo_Text_FightingDojo::
    .string "FIGHTING DOJO$"

