PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "Coze!?\p"
    .string "TEAM ROCKET je na MT. MOON?\n"
    .string "Co?\p"
    .string "Telefonuju!\n"
    .string "Zmiz!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "JIGGLYPUFF: Puu pupuu!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "Hááá!\p"
    .string "Kdyz JIGGLYPUFF zpívá,\n"
    .string "POKéMONi usínají…\p"
    .string "…I já…\n"
    .string "Chrr…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "Hrozne chci PIKACHU, takze\n"
    .string "mením svého CLEFAIRYho.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .string "Menil jsem POKéMONa s tím\n"
    .string "klukem támhle.\p"
    .string "Mel jsem dva PIKACHU, tak jsem\n"
    .string "si rekl, ze jednoho vymením.$"

