SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "Vypadás unavene.\n"
    .string "Mel bys si rychle zdrímnout.$"

SilphCo_9F_Text_DontGiveUp::
    .string "Nevzdávej to!$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "Mnohokrát díky.$"

SilphCo_9F_Text_Grunt1Intro::
    .string "Tví POKéMONi te zbozují,\n"
    .string "decko!$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "Aááá!$"

SilphCo_9F_Text_Grunt1PostBattle::
    .string "Kdybych zacal jako TRENÉR\n"
    .string "v tvém veku…$"

SilphCo_9F_Text_EdIntro::
    .string "Tví POKéMONi mají slabiny!\n"
    .string "Já je trefím!$"

SilphCo_9F_Text_EdDefeat::
    .string "Pretrefil jsi me!$"

SilphCo_9F_Text_EdPostBattle::
    .string "Vyuzívání slabin funguje.\n"
    .string "Mysli na typové vyhody.$"

SilphCo_9F_Text_Grunt2Intro::
    .string "Já jsem jeden ze ctyr\n"
    .string "BRATRU ROCKETU!$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "Warg!\n"
    .string "Bratri, prohrál jsem!$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "Mí bratri me pomstí!$"

SilphCo_9F_Text_FloorSign::
    .string "SILPH CO. HLAVNÍ KANCELÁR\n"
    .string "9F$"
