CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .string "Ahoj!\p"
    .string "Promin, ale ted máme prestávku.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .string "Mí POKéMONi jsou slabí, takze\n"
    .string "casto chodím do LÉKÁRNY.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .string "Pst! Slysel jsem, ze pod\n"
    .string "GAME CORNEREM je sklep.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .string "Mnam…\p"
    .string "Ten muz u stolu prohrál vsechno\n"
    .string "ve slotech.$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .string "Jen do toho! Smej se!\n"
    .string "Jsem úplne na dne!\p"
    .string "Zádné sloty uz!\n"
    .string "Jdu cestou poctivosti!\p"
    .string "Tady!\n"
    .string "Tohle uz nebudu potrebovat!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .string "{PLAYER} dostal MINCOVNÍK\n"
    .string "od muze.$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .string "Udelej na to místo!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .string "Vzdy jsem si myslel, ze to\n"
    .string "zase vyhraji zpátky…$"
