Text_SwordsDanceTeach::
    .string "Sem nechodí moc lidí.\p"
    .string "Kdyz tady trénuji, jsem\n"
    .string "presvedcen, ze budu silnejsí.\p"
    .string "Jo, silnejsí a silnejsí…\p"
    .string "Co kdyby ses naucil ten\n"
    .string "útok? Je to SWORDS DANCE.$"

Text_SwordsDanceDeclined::
    .string "No, to je taky v poradku.$"

Text_SwordsDanceWhichMon::
    .string "Tak fajn, vyber, kterého\n"
    .string "POKéMONa ho mám naucit.$"

Text_SwordsDanceTaught::
    .string "Kdybychom mohli porád\n"
    .string "sílit a sílit, vid?$"

SevenIsland_Text_IslandSign::
    .string "SEVEN ISLAND\n"
    .string "Quest Island of Infinity$"

SevenIsland_Text_IslandsMadeInSevenDays::
    .string "Tyto ostrovy se jmenují SEVII\n"
    .string "ISLANDS, protoze jich je sedm.\p"
    .string "…Nebo si to alespon\n"
    .string "myslí mladí lidé.\p"
    .string "Pravda je, ze tyto ostrovy se\n"
    .string "tak jmenují, protoze pry byly\l"
    .string "stvoreny za sedm dní.$"

SevenIsland_Text_IslandVirtuallyUntouched::
    .string "Tento ostrov zustal témer\n"
    .string "nedotcen ve svém prírodním\l"
    .string "stavu.\p"
    .string "Proto se po nem muze hure\n"
    .string "putovat.$"

