SaffronCity_Gym_Text_SabrinaIntro::
    .string "Mela jsem vizi tvého príchodu.\p"
    .string "Psychické schopnosti mám\n"
    .string "uz od detství.\p"
    .string "Zacalo to, kdyz se mi lzícka,\n"
    .string "kterou jsem hodila, ohnula.\p"
    .string "Nerada bojuji, ale chces-li,\n"
    .string "ukázu ti svou moc!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "Tato prohra me sokuje!\n"
    .string "Ale prohra je prohra.\p"
    .string "Priznávám, ze jsem se nesnazila\n"
    .string "dostatecne, abych vyhrála.\p"
    .string "Tvé vítezství ti vyneslo\n"
    .string "MARSHBADGE.$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "Psychickou moc nemá jen pár\n"
    .string "vyvolenych.\p"
    .string "Má ji kazdy.\n"
    .string "Lidé si to jen neuvedomují.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "MARSHBADGE prinutí POKéMONy\n"
    .string "az do Lv. 70 te poslouchat.\p"
    .string "Silnejsí POKéMONi zdivocí\n"
    .string "a v boji budou ignorovat povely.\p"
    .string "Jen je prílis nevychovávej,\n"
    .string "aby k tomu nedoslo.\p"
    .string "Pockej, vezmi si tohle TM.$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER} obdrzel TM04 od\n"
    .string "SABRINY.$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "TM04 je CALM MIND.\p"
    .string "Pomáhá POKéMONovi soustredit se\n"
    .string "a zvedá mu SP. ATK i SP. DEF.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "Tvá TASKA je plná jinych veci.$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "SABRINA je mnohem mladsí nez já,\n"
    .string "ale získala si muj respekt.$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "To nestací!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "V souboji rovnych vyhrává ten,\n"
    .string "kdo má silnejsí vuli.\p"
    .string "Chces-li porazit SABRINU,\n"
    .string "soustred se a chtej vítezit.$"

SaffronCity_Gym_Text_JohanIntro::
    .string "Desí te nase neviditelná moc?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "To jsem nevidel!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "PSYCHIC POKéMON se bojí jen\n"
    .string "duchu a hmyzu!$"

SaffronCity_Gym_Text_StacyIntro::
    .string "POKéMONi prebírají vzhled\n"
    .string "svych TRENÉRU.\p"
    .string "Tví POKéMONi musí byt tvrdí!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "Vedela jsem to!$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "Mám se jeste hodne co ucit…\p"
    .string "Musím zvládnout PSYCHIC a naucit\n"
    .string "ji své POKéMONy…$"

SaffronCity_Gym_Text_TyronIntro::
    .string "Chápes to, ze?\p"
    .string "Ze síla sama nestací k vítezství\n"
    .string "ve svete POKéMONu?$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "Tomu neverím!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "SABRINA práve smetla KARATE\n"
    .string "MISTRA vedle.$"

SaffronCity_Gym_Text_TashaIntro::
    .string "Ty a já, nasi POKéMONi\n"
    .string "se utkají!$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "Prece jen jsem prohrála!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "Vedela jsem, ze se to\n"
    .string "stane.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "SABRINA je mladá, ale také\n"
    .string "nase velmi schopná VÚDKYNE.\p"
    .string "Snadno se k ní nedostanes!$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "Au!\n"
    .string "Vyrazen!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "Drív byly v SAFFRONU dva\n"
    .string "POKéMON GYMY.\p"
    .string "FIGHTING DOJO vedle ale prislo\n"
    .string "o status GYMU.\p"
    .string "Jednoduse jsme je rozdrtili,\n"
    .string "kdyz jsme se rozhodli mít jen jeden.$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "SAFFRON POKéMON GYM je slavná\n"
    .string "vychovou psychiku.\p"
    .string "Chces videt SABRINU, ze?\n"
    .string "Já to vím!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "Argh!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "Presne tak! Pouzil jsem telepatii,\n"
    .string "abych ti precetl mysl!$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "Cau!\n"
    .string "Budoucí sampione!\p"
    .string "POKéMONi SABRINY pouzívají\n"
    .string "psychickou moc místo síly.\p"
    .string "FIGHTING POKéMONi jsou hodne\n"
    .string "slabí proti PSYCHIC POKéMONum.\p"
    .string "Budou znicení, nez vubec\n"
    .string "stací zamírit úder!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "Psychická moc, jo?\p"
    .string "Kdybych ji mel, vydelal bych\n"
    .string "balík na automatech!$"

SaffronCity_Gym_Text_GymStatue::
    .string "SAFFRON POKéMON GYM\n"
    .string "VÚDCE: SABRINA\p"
    .string "VÍTEZNÍ TRENÉRI:\n"
    .string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "SAFFRON POKéMON GYM\n"
    .string "VÚDCE: SABRINA\p"
    .string "VÍTEZNÍ TRENÉRI:\n"
    .string "{RIVAL}, {PLAYER}$"

