FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
    .string "Nestanes se dobrym TRÉNÉREM\n"
    .string "s jedinym silnym POKéMONem.\p"
    .string "Ale vychovávat mnoho POKéMONu\n"
    .string "rovnomerne není snadné.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .string "Západne od VIRIDIAN CITY\n"
    .string "je úzká cesticka.\p"
    .string "Vede k HQ POKéMON LIGY.\n"
    .string "HQ rídí vsechny TRÉNÉRY.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .string "Pokud pracujes na POKéDEXu,\n"
    .string "navstiv SAFARI ZONE.\p"
    .string "Vsemozní vzácní POKéMONi\n"
    .string "se tam mnozí.$"

