TwoIsland_PokemonCenter_1F_Text_HaveYouVisitedGameCorner::
    .string "Byl jsi uz v GAME CORNERU?\p"
    .string "Není dobré jít sám.\n"
    .string "Musís si vzít kamaráda s sebou.$"

TwoIsland_PokemonCenter_1F_Text_OldLadyLivesOutOnCape::
    .string "Na TWO ISLAND nezije mnoho lidí.\p"
    .string "Je tam stará paní, která bydlí\n"
    .string "na mysu.\p"
    .string "Je tam uz nepamatuji od kdy.$"

