OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
    .string "Hm!\n"
    .string "Haaaaaaaaaaah!\p"
    .string "Aaaah! Tohle je nebe!\n"
    .string "Voda me hreje az do morku kostí!\p"
    .string "Mel by sis taky skocit dovnitr.\p"
    .string "Jdi doprostred, uvolni se\n"
    .string "a poradne se zahrej!$"

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
    .string "Má oblíbená cást koupele\n"
    .string "prichází hned po této.\p"
    .string "Vychutnám si misku polévky,\n"
    .string "aby me to zahrálo i zevnitr!$"

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed::
    .string "Voda je naprosto teplá.\n"
    .string "Je to vyborné…\p"
    .string "{PLAYER} a POKéMONi byli\n"
    .string "úplne osvezeni!$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
    .string "Koupání v termálním prameni je\n"
    .string "lécivé, ríká se.$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
    .string "Podívej se na muj oblicej.\n"
    .string "Vidís, jak hladkou mám plet?\p"
    .string "Voda z horkého pramene udrzuje\n"
    .string "mou plet mladsí, nez je muj vek.$"

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion::
    .string "Po poctivém dni tréninku není nic\n"
    .string "lepsího nez relaxacní koupel\l"
    .string "v termálním prameni.\p"
    .string "BRUNO, ktery je o stupen vyse,\n"
    .string "navstevuje SPA obcas.\p"
    .string "Prichází lécit svá zranení\n"
    .string "i zranení svych POKéMONu.$"

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa::
    .string "Horké prameny jdou ruku v ruce\n"
    .string "se sopkami.\p"
    .string "EMBER SPA jsem zde, no,\n"
    .string "vytvoril pred lety.\p"
    .string "Vytesal jsem bazén rovnou\n"
    .string "z obrovského balvanu rucne.\p"
    .string "V té dobe jsem to pouzíval.\n"
    .string "Asi se s tím rozloucím.$"

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06::
    .string "Tohle rozbíjí balvany, jako by\n"
    .string "byly z keksu.$"

