SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
    .string "Kjahaha!\n"
    .string "Smetnu te lehce!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
    .string "Cha!\n"
    .string "Príslis silny pro me!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
    .string "Co?\n"
    .string "Nechovám se tak, jak vypadám?\p"
    .string "He, to je soucást mé strategie!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
    .string "Cau!\n"
    .string "Jsi clenem mého fan klubu?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
    .string "Ach, tak ty nejsi fanousek…\p"
    .string "No, to muzu zmenit.\n"
    .string "Zazpívám ti!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
    .string "Lalala…\n"
    .string "Pustím své POKéMONy,\l"
    .string "vsechny dívky vrískají!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
    .string "Ostrov je príslis rozlehly…\n"
    .string "Není snadné ho hlídat.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
    .string "Uh-huh…$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
    .string "TRÉNÉRI jako ty z mest,\n"
    .string "jste fakt drsní.\p"
    .string "Mírís k TOWERu, ze ano?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
    .string "Trestám lidi, co zneuzívají\n"
    .string "POKéMONy!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
    .string "Nezdá se mi, ze bys byl\n"
    .string "problémovy TRÉNÉR.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
    .string "Kdyz se ke svym POKéMONum\n"
    .string "chovás laskave, pochopí to.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
    .string "EVA: Spojím se s JONem a\n"
    .string "budeme bojovat spolu.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
    .string "EVA: Já a JON jsme prohráli.\n"
    .string "Ehehe.$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
    .string "EVA: Budu trénovat víc\n"
    .string "s JONem.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
    .string "EVA: Chci se spojit s JONem,\n"
    .string "kdyz s tebou bojuji.\p"
    .string "Vrat se se dvema POKéMONy.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
    .string "JON: Kdyz jsem s EVOU, cítím,\n"
    .string "ze nemuzeme prohrát.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
    .string "JON: Kdyz jsem s EVOU,\n"
    .string "necítím, ze jsem prohrál!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
    .string "JON: Kdyz jsem s EVOU, cítím\n"
    .string "se závrate, vyhraju nebo\l"
    .string "prohraju.\p"
    .string "Je to magické!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
    .string "JON: Kdyz je to s EVOU, rád\n"
    .string "s tebou budu bojovat.\p"
    .string "Chtel bych zápas dva na dva.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
    .string "VCHOD DO SEVAULT CANYON\p"
    .string "TRÉNÉRI mají zákaz poskozovat\n"
    .string "rostliny v KANONU.$"

