Route3_Text_TunnelFromCeruleanTiring::
    .string "Uf… Musím si odpocinout…\n"
    .string "Sténám…\p"
    .string "Ten tunel z CERULEAN cloveka\n"
    .string "pekne vycerpá!$"

Route3_Text_ColtonIntro::
    .string "Hej!\n"
    .string "Videl jsem te ve VIRIDIAN FOREST!$"

Route3_Text_ColtonDefeat::
    .string "Zase jsi me porazil!$"

Route3_Text_ColtonPostBattle::
    .string "Krome lesních POKéMONu existují\n"
    .string "i jiné druhy.$"

Route3_Text_BenIntro::
    .string "Cau!\n"
    .string "Mám rád kratasy!\p"
    .string "Jsou skvele pohodlné a\n"
    .string "snadno se v nich pohybuje!$"

Route3_Text_BenDefeat::
    .string "Tomu neverím!$"

Route3_Text_BenPostBattle::
    .string "Pouzívás PC v POKéMON CENTRU\n"
    .string "k uskladnení svych POKéMONu?\p"
    .string "Kazdy BOX pojme az\n"
    .string "30 POKéMONu.$"

Route3_Text_JaniceIntro::
    .string "Promin!\n"
    .string "Dívals se na me, ze?$"

Route3_Text_JaniceDefeat::
    .string "Jsi sprosty!$"

Route3_Text_JanicePostBattle::
    .string "Nemel by ses koukat, kdyz nechces\n"
    .string "bojovat!$"

Route3_Text_GregIntro::
    .string "Jsi TRÉNÉR?\n"
    .string "Tak se do toho hned pustíme!$"

Route3_Text_GregDefeat::
    .string "Kdybych mel nové POKéMONy,\n"
    .string "vyhrál bych!$"

Route3_Text_GregPostBattle::
    .string "Kdyz se POKéMON BOX na PC zaplní,\n"
    .string "staci prepnout na jiny BOX.$"

Route3_Text_SallyIntro::
    .string "Ten pohled, co jsi mi venoval…\n"
    .string "Je tak zajímavy!$"

Route3_Text_SallyDefeat::
    .string "Bud hodny!$"

Route3_Text_SallyPostBattle::
    .string "Bojum se vyhnes, kdyz te\n"
    .string "TRÉNÉRI nezahlédnou.$"

Route3_Text_CalvinIntro::
    .string "Hej! Nemás kratasy!\n"
    .string "Co je s tebou?$"

Route3_Text_CalvinDefeat::
    .string "Prohra!\n"
    .string "Prohra! Prohra!$"

Route3_Text_CalvinPostBattle::
    .string "Nosím kratasy porád, i v zime.\n"
    .string "Taková je má zásada.$"

Route3_Text_JamesIntro::
    .string "Vyzvu te POKéMONem,\n"
    .string "kterého jsem práve chytil.$"

Route3_Text_JamesDefeat::
    .string "Hotovo!$"

Route3_Text_JamesPostBattle::
    .string "Trénovaní POKéMONi jsou silnejsí\n"
    .string "nez divocí.$"

Route3_Text_RobinIntro::
    .string "Jé!\n"
    .string "Dotkl ses me?$"

Route3_Text_RobinDefeat::
    .string "To je vsechno?$"

Route3_Text_RobinPostBattle::
    .string "CESTA 4 je u úpatí\n"
    .string "MT. MOON.$"

Route3_Text_RouteSign::
    .string "CESTA 3\n"
    .string "MT. MOON PRED VÁMI$"

