CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
    .string "Chycení POKéMONi se evidují\n"
    .string "s císlem ID a OT.\p"
    .string "OT znamená “Puvodní TRENÉR” -\n"
    .string "TRENÉR, ktery ho chytil první.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
    .string "Skvelé!\p"
    .string "Kámos mi vymení svého KANGASKHANa\n"
    .string "za mého HAUNTERa!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
    .string "No tak, HAUNTERe!\p"
    .string "Miluji HAUNTERa!\n"
    .string "Sbírám je!\p"
    .string "He?\p"
    .string "HAUNTER se behem vymeny zmenil\n"
    .string "v jiného POKéMONa!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
    .string "POKéMONy získané vymenou\n"
    .string "rozeznás podle ID císel.$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
    .string "Je to Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
    .string "RPG!\n"
    .string "Na to ted není cas!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
    .string "Sportovní hra!\n"
    .string "Tu si táta oblíbí!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
    .string "Logická hra!\n"
    .string "Vypadá návykove!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
    .string "Bojová hra!\n"
    .string "Vypadá drsne!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
    .string "3F: TV HERNÍ OBCHOD$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
    .string "Red a Green!\n"
    .string "Oba jsou POKéMON!$"

Text_CounterTeach::
    .string "Ach, ahoj!\n"
    .string "Konecne jsem dohrál POKéMONa.\p"
    .string "Ty jeste ne? Co kdybych te naucil\n"
    .string "jeden dobry útok?\p"
    .string "Mám na mysli útok\n"
    .string "COUNTER.\p"
    .string "Ne jako ten, o ktery se opírám,\n"
    .string "to si nemysli!$"

Text_CounterDeclined::
    .string "Nezajímá te? Prijd za mnou,\n"
    .string "az si to rozmyslís.$"

Text_CounterWhichMon::
    .string "Kterého POKéMONa mám naucit\n"
    .string "COUNTER?$"

Text_CounterTaught::
    .string "Pouzívás ten útok COUNTER, co\n"
    .string "jsem naucil tvého POKéMONa?$"
