CeladonCity_Gym_Text_ErikaIntro::
    .string "Dobry den…\n"
    .string "Krásné pocasí, ze?\l"
    .string "Je to tak príjemné…\p"
    .string "…Ach, propána…\n"
    .string "Zrejme jsem usnula. Vítej.\p"
    .string "Jmenuji se ERIKA.\n"
    .string "Jsem VUDCE CELADON GYMu.\p"
    .string "Studuji umení aranzování\n"
    .string "kvetin.\p"
    .string "Mí POKéMONi jsou vyhradne\n"
    .string "typu GRASS.\p"
    .string "…Ach, promin, netusila jsem,\n"
    .string "ze me chces vyzvat.\p"
    .string "Dobrá, ale neprohraji.{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "Ach!\n"
    .string "Vzdávám se.\l"
    .string "Jsi pozoruhodne silny.\p"
    .string "Musím ti predat\n"
    .string "RAINBOWBADGE.$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "Ty katalogizujes POKéMONy?\n"
    .string "To me opravdu zaujalo.\p"
    .string "Já bych nikdy nesbírala\n"
    .string "POKéMONy, co nejsou pekní.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "RAINBOWBADGE zarídí, ze te\n"
    .string "poslechnou POKéMONi do Lv. 50.\p"
    .string "Také dovolí POKéMONum pouzít\n"
    .string "STRENGTH v boji i mimo nej.\p"
    .string "Vezmi si prosím i toto.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "{PLAYER} dostal TM19\n"
    .string "od ERIKY.$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "TM19 obsahuje GIGA DRAIN.\p"
    .string "Polovina zpusobeného poskození\n"
    .string "uzdraví tvého POKéMONa.\p"
    .string "Není to úzasny útok?$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "Mel bys na to udelat místo.$"

CeladonCity_Gym_Text_KayIntro::
    .string "Reknu ti neco o tomhle GYMu.\p"
    .string "Sem smí jenom opravdové dámy!$"

CeladonCity_Gym_Text_KayDefeat::
    .string "Jsi prílis drsny!$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "Fuj!\n"
    .string "Doufám, ze te ERIKA znicí!$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "Vítej.\n"
    .string "Uz se mi zacalo nudit.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "Moje malovánky!$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "POKéMONi typu GRASS jsou tvrdí\n"
    .string "proti typu WATER.\p"
    .string "Také mají navrch nad typy\n"
    .string "ROCK a GROUND.$"

CeladonCity_Gym_Text_TinaIntro::
    .string "…Nenakukoval jsi sem\n"
    .string "pred chvílí?$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "Otevrels mi oci!$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "Aha, koukal jsi na ERIKU…\n"
    .string "Na me ses nedíval…$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "Koukni, koukni!\n"
    .string "Tohle je muj POKéMON!\p"
    .string "Mám ráda typ GRASS.\n"
    .string "Líbí se mi, ze je snadno chovat.$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "Ne!$"

CeladonCity_Gym_Text_TamiaPostBattle::
    .string "V nasem GYMu pouzíváme\n"
    .string "jen POKéMONy typu GRASS.\p"
    .string "Proc? Také je pouzíváme\n"
    .string "do kvetinovych aranzí!$"

CeladonCity_Gym_Text_LisaIntro::
    .string "Ahoj!\p"
    .string "Tady nemáme rády POKéMONy\n"
    .string "typu BUG a FIRE!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "Ach!\n"
    .string "Ty!$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "Nase VUDKYNE ERIKA byvá tichá,\n"
    .string "ale tady je slavná.$"

CeladonCity_Gym_Text_LoriIntro::
    .string "Tesí me.\n"
    .string "Mym koníckem je vycvik POKéMONu.$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "Ach!\n"
    .string "Skvelé!$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "Cekat me rande naslepo.\n"
    .string "Musím se naucit slusnosti,\l"
    .string "obzvlást kdyz dojde na boj.$"

CeladonCity_Gym_Text_MaryIntro::
    .string "Vítej v CELADON GYMu!\p"
    .string "Lépe nepodcenuj milé\n"
    .string "dámy tady.$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "Ach!\n"
    .string "Porazena!$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "Nevzala jsem si nejlepsí POKéMONy.\n"
    .string "Pockej do prístí!$"

CeladonCity_Gym_Text_GymStatue::
    .string "CELADON POKéMON GYM\n"
    .string "VUDKYNE: ERIKA\p"
    .string "VÍTEZNÍ TRENÉRI:\n"
    .string "{RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "CELADON POKéMON GYM\n"
    .string "VUDKYNE: ERIKA\p"
    .string "VÍTEZNÍ TRENÉRI:\n"
    .string "{RIVAL}, {PLAYER}$"
