RocketHideout_B3F_Text_Grunt1Intro::
    .string "Prestan se plést do záduzitostí\n"
    .string "TEAM ROCKET, nebo uvidís!$"

RocketHideout_B3F_Text_Grunt1Defeat::
    .string "Uf!\n"
    .string "Slozen!$"

RocketHideout_B3F_Text_Grunt1PostBattle::
    .string "SILPH SCOPE?\n"
    .string "Aha, ten stroj, co BOSS ukradl.\p"
    .string "Nekde tady je.$"

RocketHideout_B3F_Text_Grunt2Intro::
    .string "Dostali jsme z hora zprávu,\n"
    .string "ze prijdes!$"

RocketHideout_B3F_Text_Grunt2Defeat::
    .string "Coze?\n"
    .string "Prohrál jsem? Ne!$"

RocketHideout_B3F_Text_Grunt2PostBattle::
    .string "Klidne jdi dál!\p"
    .string "Ale vytah bez LIFT KEY\n"
    .string "nezprovoznís.$"
