ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Klidne pouzij to PC v rohu.\p"
    .string "Receptní mi to rekla.\n"
    .string "Je tak milá!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "POKéMON CENTRUM je v kazdém\n"
    .string "meste pred tebou.\p"
    .string "Nic to nestojí, takze se\n"
    .string "neostychej a vyléc POKéMONy.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "POKéMON CENTRA léci tvé\n"
    .string "unavené, zranené i omdlelé\l"
    .string "POKéMONy.\p"
    .string "Vsechny POKéMONy uzdraví\n"
    .string "úplne.$"
