SilphCo_8F_Text_WonderIfSilphIsFinished::
    .string "Coz SILPH skoncí…$"

SilphCo_8F_Text_ThanksForSavingUs::
    .string "Díky, ze jsi nás zachránil!$"

SilphCo_8F_Text_Grunt1Intro::
    .string "Dál uz se nedostanes!$"

SilphCo_8F_Text_Grunt1Defeat::
    .string "Málo síly!$"

SilphCo_8F_Text_Grunt1PostBattle::
    .string "Kdyz se neotocís…\n"
    .string "Zavolám posily!$"

SilphCo_8F_Text_ParkerIntro::
    .string "Delás nám problémy!$"

SilphCo_8F_Text_ParkerDefeat::
    .string "He?\n"
    .string "Prohrál jsem?$"

SilphCo_8F_Text_ParkerPostBattle::
    .string "Tak co ríkás bludisti\n"
    .string "v BUDOVE SILPH?$"

SilphCo_8F_Text_Grunt2Intro::
    .string "Já jsem jeden ze ctyr\n"
    .string "BRATRU ROCKETU!$"

SilphCo_8F_Text_Grunt2Defeat::
    .string "Páni!\n"
    .string "Ach, Bratri!$"

SilphCo_8F_Text_Grunt2PostBattle::
    .string "Nechávám te svym bratrum.$"

SilphCo_8F_Text_FloorSign::
    .string "SILPH CO. HLAVNÍ KANCELÁR\n"
    .string "8F$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
    .string "BOSS TEAM ROCKETu je strasne\n"
    .string "kruty!\p"
    .string "Pro nej jsou POKéMONi jen\n"
    .string "nástroje k pouzití.\p"
    .string "Co se stane, kdyz ten tyran\n"
    .string "prevezme nasi firmu…$"
