ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "Uf! Snazím se zapamatovat si\n"
    .string "vsechny své poznámky.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Dobre!\p"
    .string "Urcite si pozorne precti, co\n"
    .string "je na tabuli!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Mrkneme se do sesitu.\p"
    .string "První strana…\p"
    .string "POKé BALLS se pouzívají\n"
    .string "na chytání POKéMONu.\p"
    .string "V tymu muzes mít az sest\n"
    .string "POKéMONu.\p"
    .string "Lidem, kterí chovají a bojují\n"
    .string "s POKéMONy, ríkáme TRENéRI.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "Druhá strana…\p"
    .string "Zdravého POKéMONa muze byt\n"
    .string "tezké chytit, oslab ho.\p"
    .string "Otrav, popal nebo zpusob jiny\n"
    .string "stavovy problém k oslabení.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Tretí strana…\p"
    .string "POKéMON TRENéRI hledají\n"
    .string "ostatní do POKéMON souboju.\p"
    .string "Pro TRENéRY je chut vítezství\n"
    .string "vskutku sladká.\p"
    .string "Souboje neustále probíhají\n"
    .string "v POKéMON GYMECH vsude.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Ctvrtá strana…\p"
    .string "Konecny cíl vsech POKéMON\n"
    .string "TRENéRU je jednoduchy.\p"
    .string "Porazit osm nejlepsích\n"
    .string "VUDCU POKéMON GYM.\p"
    .string "Pak získás právo celit…\p"
    .string "ELITNí CTYRCE POKéMON\n"
    .string "LIGY!$"

ViridianCity_School_Text_TurnThePage::
    .string "Otocit stranu?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "DíVKA: Hej!\n"
    .string "Nedívej se mi do poznámek!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "Tabule uvádí stavové problémy\n"
    .string "POKéMONu behem souboje.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "O cem si chces prect?$"

ViridianCity_School_Text_ExplainSleep::
    .string "Spící POKéMON nemuze útocit.\p"
    .string "POKéMON zustanou spát i\n"
    .string "po souboji.\p"
    .string "Pouzij AWAKENING k probuzení\n"
    .string "ze spánku.$"

ViridianCity_School_Text_ExplainBurn::
    .string "Popálení snizuje sílu ÚTOKU.\n"
    .string "Zároven zpusobuje úbytek HP.\p"
    .string "Popálení zustává po souboji.\n"
    .string "Pouzij BURN HEAL k vyléceni.$"

ViridianCity_School_Text_ExplainPoison::
    .string "Otrávenému POKéMONovi\n"
    .string "neustále klesá zdraví.\p"
    .string "Jed zustává i po soubojích.\n"
    .string "Pouzij PROTIJED k vyléceni!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "Zmrazeny POKéMON je bezmocne\n"
    .string "nehybny.\p"
    .string "Zustane zmrazeny i po\n"
    .string "konci souboje.\p"
    .string "Pouzij ICE HEAL k rozmrazeni\n"
    .string "trpícího POKéMONa.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "Paralyza snizuje RYCHLOST a\n"
    .string "muze zabránit pohybu.\p"
    .string "Paralyza zustává po soubojích.\n"
    .string "Pouzij PARLYZ HEAL k léceni.$"
