PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "POKéMON TOWER byla postavena\n"
    .string "na památku zesnulych POKéMONu.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Prisels vzdát úctu?\p"
    .string "Pozehnej tvému POKéMON-milujícímu\n"
    .string "srdci, synu.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Prisla jsi vzdát úctu?\p"
    .string "Pozehnej tvému POKéMON-milujícímu\n"
    .string "srdci, dívko.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "Prisla jsem se modlit za mou\n"
    .string "drahou zesnulou CLEFAIRY.\p"
    .string "Snif!\n"
    .string "Topím se v slzách…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "Muj GROWLITHE…\n"
    .string "Proc jsi zemrel?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "Jsem CHANNELERka.\p"
    .string "Jsou tu duchové, co provádejí zlo.\n"
    .string "Cítím je vysoko ve VEZI.$"

