SevenIsland_SevaultCanyon_Text_CyndyIntro::
    .string "Má kondice je na vrcholu!$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
    .string "Co?\n"
    .string "Neco není v poradku…$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
    .string "V tomto stavu budu muset\n"
    .string "TRAINER TOWER odlozit…$"

SevenIsland_SevaultCanyon_Text_EvanIntro::
    .string "Nezálezí na tom, jestli mas\n"
    .string "nejsilnejsí POKéMONy…\p"
    .string "Nic to neznamená, kdyz je\n"
    .string "neumís správne pouzít!$"

SevenIsland_SevaultCanyon_Text_EvanDefeat::
    .string "Jsi v tom mistr.$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
    .string "Vidís je obcas, TRÉNÉRY se\n"
    .string "skvelymi POKéMONy, kterí\l"
    .string "netusí, co delat.\p"
    .string "Nez budou trénovat POKéMONy,\n"
    .string "TRÉNÉRI sami musí vyrust.$"

SevenIsland_SevaultCanyon_Text_JacksonIntro::
    .string "Pracuji na ochrane prírody.\n"
    .string "Príroda mi to vrací!$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
    .string "Páni! Jsi silny!\n"
    .string "Co takhle me chránit?$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
    .string "Z daleka mezi hvezdami je\n"
    .string "nase planeta jen kapka vody.\p"
    .string "Ale chceme tu kapku vody\n"
    .string "chránit pro vsechny.$"

SevenIsland_SevaultCanyon_Text_KatelynIntro::
    .string "Ty boty, které mas, jsou\n"
    .string "dost elegantní.$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
    .string "Jsi tvrdy orísek navzdory\n"
    .string "roztomilému vzhledu.$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
    .string "Tvá máma ti koupila ty parádní\n"
    .string "BEZECKÉ BOTY?\p"
    .string "Musí te zboznovat.$"

SevenIsland_SevaultCanyon_Text_LeroyIntro::
    .string "Vypadás silny.\n"
    .string "Nech me s tebou bojovat, prosím!$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
    .string "Vedel jsem to!\n"
    .string "Jsi tak silny, jak jsem si myslel!$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
    .string "Tvuj styl boje mi dal\n"
    .string "spoustu uzitecnych dat.\p"
    .string "Moc ti dekuji!$"

SevenIsland_SevaultCanyon_Text_MichelleIntro::
    .string "Dostala jsem to nejlepsí\n"
    .string "vzdelání, abych byla silná.\p"
    .string "Nechci nikomu prohrát!$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
    .string "Dekuji. Cítím se, jako bych\n"
    .string "byla osvobozena prohrou.$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
    .string "Z nejakého duvodu se rozzlobím\n"
    .string "nad sebemensí drobností.\p"
    .string "Uklidním se hlubokym\n"
    .string "dycháním.$"

SevenIsland_SevaultCanyon_Text_LexIntro::
    .string "LEX: Má drahá NYO, spolecne\n"
    .string "muzeme zvítezit!$"

SevenIsland_SevaultCanyon_Text_LexDefeat::
    .string "LEX: Zdá se, ze jsem byl\n"
    .string "prílis nedbaly…$"

SevenIsland_SevaultCanyon_Text_LexPostBattle::
    .string "LEX: Myslím, ze to byla\n"
    .string "dobrá zkusenost pro NYU.\p"
    .string "Más mou vdecnost.$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
    .string "LEX: Mohu te poprosit, abys\n"
    .string "bojoval s námi obema?$"

SevenIsland_SevaultCanyon_Text_NyaIntro::
    .string "NYA: Dám ze sebe vsechno,\n"
    .string "abych nezklamala mého mentora\l"
    .string "LEXe!$"

SevenIsland_SevaultCanyon_Text_NyaDefeat::
    .string "NYA: Ach, ne…\n"
    .string "Tak me to mrzí, já…$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
    .string "NYA: Myslím, ze potrebuji\n"
    .string "mnohem víc zkuseností pod\l"
    .string "vedením LEXe…\p"
    .string "…Tak, LEXe, prosím, mohu\n"
    .string "u tebe zustat?$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
    .string "NYA: Promin, ale muzeme bojovat\n"
    .string "ve stylu dva na dva?$"

SevenIsland_SevaultCanyon_Text_RouteSign::
    .string "SEVAULT CANYON\n"
    .string "TANOBY RUINS PRED VÁMI$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
    .string "Trénovat samostatne není\n"
    .string "spatné.\p"
    .string "Ale taky není spatné mírit\n"
    .string "na vrchol s partnerem.\p"
    .string "I BRUNO…\n"
    .string "Trénoval s chlapíkem jménem\l"
    .string "BRAWLY drív.$"
