LavenderTown_Text_DoYouBelieveInGhosts::
    .string "Verís na duchy?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "Vázne?\n"
    .string "Tak presto vericí existují…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Hahaha, asi ne.\p"
    .string "Ta bílá ruka na tvém rameni…\n"
    .string "Jen si to predstavuji.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "Toto mesto je známé jako\n"
    .string "pohrebiste POKéMONu.\p"
    .string "Smutecní obrady se konají\n"
    .string "v POKéMON TOWER.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "V POKéMON TOWER se objevili duchové.\p"
    .string "Myslím, ze jsou to duse\n"
    .string "POKéMONu, které zabili ROCKETI.$"

LavenderTown_Text_TownSign::
    .string "LAVENDER TOWN\n"
    .string "Vznesené purpurové mesto$"

LavenderTown_Text_SilphScopeNotice::
    .string "Novy SILPH SCOPE!\n"
    .string "Ucinte neviditelné viditelnym!\p"
    .string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "LAVENDER DOBROVOLNICKY\n"
    .string "DUM POKéMONu$"

LavenderTown_Text_PokemonTowerSign::
    .string "POKéMON TOWER\n"
    .string "Utiste duse POKéMONu$"

