SilphCo_10F_Text_GruntIntro::
    .string "Vítej v 10F!\n"
    .string "Tesí me, ze jsi prisel!$"

SilphCo_10F_Text_GruntDefeat::
    .string "Jsem v soku!$"

SilphCo_10F_Text_GruntPostBattle::
    .string "Pekny pokus, ale zasedacka\n"
    .string "je o patro vys.$"

SilphCo_10F_Text_TravisIntro::
    .string "Dost tech tvych hloupych her!$"

SilphCo_10F_Text_TravisDefeat::
    .string "Uz mi nezbyl zivot!$"

SilphCo_10F_Text_TravisPostBattle::
    .string "Spokojeny, ze jsi me porazil?\n"
    .string "Tak ted bez domu!$"

SilphCo_10F_Text_WaaaImScared::
    .string "Áááá!\n"
    .string "Mám strach!$"

SilphCo_10F_Text_KeepMeCryingASecret::
    .string "Ze breckám…\n"
    .string "Nech si to pro sebe, prosím.$"

SilphCo_10F_Text_FloorSign::
    .string "SILPH CO. HLAVNÍ KANCELÁR\n"
    .string "10F$"
