Route24_Text_JustEarnedFabulousPrize::
    .string "Gratuluji! Porazil jsi nasich\n"
    .string "pet souteznich TRENÉRU!\p"
    .string "Práve sis vyslouzil bájecnou cenu!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer::
    .string "{PLAYER} dostal NUGGET\n"
    .string "od záhadného TRENÉRA!$"

Route24_Text_YouDontHaveAnyRoom::
    .string "Nemás zádné místo!$"

Route24_Text_JoinTeamRocket::
    .string "Mimochodem, co bys rekl na to\n"
    .string "pridat se k TEAM ROCKET?\p"
    .string "Jsme skupina profesionálních\n"
    .string "zlocincu se zamerením na POKéMONy!\p"
    .string "Chces se pridat?\p"
    .string "Jsi si jisty?\p"
    .string "No tak, pridej se!\p"
    .string "Ríkám ti, at se pridás!\p"
    .string "…Dobre, potrebujes presvedcit!\p"
    .string "Dám ti nabídku, kterou\n"
    .string "nemuzes odmítnout!$"

Route24_Text_RocketDefeat::
    .string "Arghr!\n"
    .string "Ty jsi dobry!$"

Route24_Text_YoudBecomeTopRocketLeader::
    .string "S tvymi schopnostmi by ses stal\n"
    .string "spickovym vudcem v TEAM ROCKET.\p"
    .string "No tak, mysli na tu prílezitost!\n"
    .string "Nenech tu sanci propadnout.$"

Route24_Text_ShaneIntro::
    .string "Videl jsem tvuj vykon z trávy!$"

Route24_Text_ShaneDefeat::
    .string "To jsem si myslel!$"

Route24_Text_ShanePostBattle::
    .string "Schoval jsem se, protoze me ti\n"
    .string "lidé na moste vydesili.$"

Route24_Text_EthanIntro::
    .string "Dobre! Jsem c. 5!\n"
    .string "Zaslápnu te!$"

Route24_Text_EthanDefeat::
    .string "Whoa!\n"
    .string "Prílis silné!$"

Route24_Text_EthanPostBattle::
    .string "Dal jsem do toho vse. Nic nelituji!$"

Route24_Text_ReliIntro::
    .string "Jsem c. 4!\n"
    .string "Uz jsi unaveny?$"

Route24_Text_ReliDefeat::
    .string "Taky jsem prohrál!$"

Route24_Text_ReliPostBattle::
    .string "Dal jsem do toho vse, nic nelituji!$"

Route24_Text_TimmyIntro::
    .string "Tady je c. 3!\n"
    .string "Nebudu lehky!$"

Route24_Text_TimmyDefeat::
    .string "Au!\n"
    .string "Zaslápnut!$"

Route24_Text_TimmyPostBattle::
    .string "Dal jsem do toho vse. Nic nelituji!$"

Route24_Text_AliIntro::
    .string "Jsem druhy!\n"
    .string "Ted to bude vázné!$"

Route24_Text_AliDefeat::
    .string "Jak jsem mohl prohrát?$"

Route24_Text_AliPostBattle::
    .string "Dal jsem do toho vse. Nic nelituji!$"

Route24_Text_CaleIntro::
    .string "Lidé tomuhle ríkají NUGGET\n"
    .string "BRIDGE!\p"
    .string "Porazit nás pet TRENÉRU a\n"
    .string "vyhrát bájecnou cenu!\p"
    .string "Myslís, ze na to más?$"

Route24_Text_CaleDefeat::
    .string "Whoo!\n"
    .string "Dobrá práce!$"

Route24_Text_CalePostBattle::
    .string "Dal jsem do toho vse. Nic nelituji!$"
