CeladonCity_Hotel_Text_ThisHotelIsForPeople::
    .string "POKéMON?\n"
    .string "Ne, tohle je hotel pro lidi.\p"
    .string "Bohuzel jsme plne obsazení.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
    .string "Jsem na dovolené s bratrem\n"
    .string "a prítelem.\p"
    .string "CELADON je tak hezké mesto!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
    .string "Proc?\n"
    .string "Proc vzala svého bratra?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
    .string "Jupí! Jsem na dovolené!\n"
    .string "Vzala me sestra! Super!$"
