SilphCo_5F_Text_RocketsInUproarAboutIntruder::
    .string "TEAM ROCKET je vzhuru kvuli\n"
    .string "nejakému vetrelci.\p"
    .string "To jsi ty, ze?$"

SilphCo_5F_Text_YoureOurHeroThankYou::
    .string "TEAM ROCKET zmizel!\n"
    .string "Jsi nás hrdina! Díky!$"

SilphCo_5F_Text_Grunt1Intro::
    .string "Slysel jsem, ze se tu toulá\n"
    .string "decko.$"

SilphCo_5F_Text_Grunt1Defeat::
    .string "Bum!$"

SilphCo_5F_Text_Grunt1PostBattle::
    .string "Není moudré popírat se s\n"
    .string "TEAM ROCKET!$"

SilphCo_5F_Text_BeauIntro::
    .string "V tomto patre zkoumáme\n"
    .string "technologii POKé BALL.$"

SilphCo_5F_Text_BeauDefeat::
    .string "Sakra!\n"
    .string "K certu!$"

SilphCo_5F_Text_BeauPostBattle::
    .string "Pracovali jsme na ultimátním POKé\n"
    .string "BALL, ktery by chytil cokoli.$"

SilphCo_5F_Text_DaltonIntro::
    .string "Coze?\p"
    .string "Tady by nemely byt zádné\n"
    .string "deti!$"

SilphCo_5F_Text_DaltonDefeat::
    .string "Ach jo!$"

SilphCo_5F_Text_DaltonPostBattle::
    .string "Jsi teprve v 5F.\n"
    .string "K mému BOSSOVI je to dál!$"

SilphCo_5F_Text_Grunt2Intro::
    .string "Projev TEAM ROCKET trochu úcty!$"

SilphCo_5F_Text_Grunt2Defeat::
    .string "Khe…\n"
    .string "Khe…$"

SilphCo_5F_Text_Grunt2PostBattle::
    .string "Coz mi pripomíná.\p"
    .string "KOFFING se vyvine ve WEEZING!$"

SilphCo_5F_Text_PorygonFirstVRMon::
    .string "Je to ZPRÁVA o POKéMONech!\p"
    .string "POKéMON LAB vytvorila PORYGONa,\n"
    .string "prvního VR POKéMONa.$"

SilphCo_5F_Text_Over350TechniquesConfirmed::
    .string "Je to ZPRÁVA o POKéMONech!\p"
    .string "Potvrzeno bylo pres 350 technik\n"
    .string "POKéMONu.$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
    .string "Je to ZPRÁVA o POKéMONech!\p"
    .string "U nekterych POKéMONu bylo zjisteno,\n"
    .string "ze se vyvíjí pri vymene.$"

SilphCo_5F_Text_FloorSign::
    .string "SILPH CO. HLAVNÍ KANCELÁR\n"
    .string "5F$"

SilphCo_5F_Text_RocketBossLookingForStrongMons::
    .string "Ti grázlové, co nám zabrali\n"
    .string "budovu…\p"
    .string "Jejich BOSS ríkal, ze hledá\n"
    .string "silné POKéMONy.\p"
    .string "Doufám, ze nás REDITEL\n"
    .string "se vyhnul potízím…$"
