SSAnne_1F_Room2_Text_TylerIntro::
    .string "Miluji POKéMONy!\n"
    .string "A ty?$"

SSAnne_1F_Room2_Text_TylerDefeat::
    .string "Páni! \n"
    .string "Jsi skvely!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
    .string "Hele, hele!\n"
    .string "Bud muj kámos, jo?\p"
    .string "Pak si muzeme menit POKéMONy\n"
    .string "a delat veci.$"

SSAnne_1F_Room2_Text_AnnIntro::
    .string "Tyhle POKéMONy jsem nasbírala\n"
    .string "z celého sveta!$"

SSAnne_1F_Room2_Text_AnnDefeat::
    .string "Ach ne!\n"
    .string "Pro ne jsem objela svet!$"

SSAnne_1F_Room2_Text_AnnPostBattle::
    .string "Zranils mé ubohé POKéMONy!\p"
    .string "Pozaduji, abys je vylécil\n"
    .string "v POKéMON CENTRU!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
    .string "Plujeme kolem sveta,\n"
    .string "deti a já.$"
