VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "Cau!\n"
	.string "Mas {STR_VAR_1}?\p"
	.string "Chces ho vymenit za mého\n"
	.string "{STR_VAR_2}?$"

VermilionCity_House2_Text_ThatsTooBad::
	.string "To je skoda.$"

VermilionCity_House2_Text_ThisIsNoMon::
	.string "…Tohle není {STR_VAR_1}.\p"
	.string "Az nejakého ulovís, prosím\n"
	.string "vymen ho se mnou!$"

VermilionCity_House2_Text_ThankYou::
	.string "Díky!$"

VermilionCity_House2_Text_HowIsMyOldMon::
	.string "Jak se má muj stary {STR_VAR_2}?\p"
	.string "Muj {STR_VAR_1} se má skvele!$"
