SilphCo_7F_Text_HaveMonForSavingUs::
    .string "Ach! Ahoj! Ty nejsi ROCKET!\n"
    .string "Prisels nás zachránit?\l"
    .string "Páni, díky!\p"
    .string "Vezmi si toho POKéMONa za to,\n"
    .string "ze jsi nás zachránil.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .string "{PLAYER} získal LAPRASe od\n"
    .string "zamestnance SILPHu!$"

SilphCo_7F_Text_ExplainLapras::
    .string "Je to LAPRAS.\n"
    .string "Je to velmi chytry POKéMON.\p"
    .string "Drzeli jsme ho v laboratori,\n"
    .string "ale u tebe bude lépe.\p"
    .string "Myslím, ze budes dobry TRENÉR\n"
    .string "pro LAPRASe!\p"
    .string "Je to dobry plavec.\n"
    .string "Sveze te pres vodu!$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .string "BOSS TEAM ROCKET sel do\n"
    .string "zasedacky!\p"
    .string "Je nás REDITEL v porádku?\n"
    .string "Mám strach.$"

SilphCo_7F_Text_OhNo::
    .string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast::
    .string "たすかったよ　ありがと！$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .string "TEAM ROCKET sel po MASTER\n"
    .string "BALL, ktery chytí kazdého POKéMONa.$"

SilphCo_7F_Text_CanceledMasterBallProject::
    .string "Zrusili jsme projekt MASTER BALL\n"
    .string "kvuli TEAM ROCKET.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .string "Bylo by zlé, kdyby TEAM ROCKET\n"
    .string "ovládl SILPH ci nase POKéMONy.$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .string "Páni!\p"
    .string "Vyhnal jsi TEAM ROCKET úplne\n"
    .string "sám?$"

SilphCo_7F_Text_ReallyDangerousHere::
    .string "Ty!\n"
    .string "Tady je opravdu nebezpecno!\p"
    .string "Prisels me zachránit?\n"
    .string "To nemuzes!$"

SilphCo_7F_Text_ThankYouSoMuch::
    .string "Mnohokrát díky!$"

SilphCo_7F_Text_Grunt3Intro::
    .string "Ouha!\n"
    .string "Cítím malou mysku!$"

SilphCo_7F_Text_Grunt3Defeat::
    .string "Konec!$"

SilphCo_7F_Text_Grunt3PostBattle::
    .string "Mého BOSSE jen tak nenajdes!$"

SilphCo_7F_Text_JoshuaIntro::
    .string "Hehe!\p"
    .string "Spletl sis me za\n"
    .string "zamestnance SILPHu?$"

SilphCo_7F_Text_JoshuaDefeat::
    .string "Konec!$"

SilphCo_7F_Text_JoshuaPostBattle::
    .string "Pres svuj vek jsi sikovny\n"
    .string "TRENÉR!$"

SilphCo_7F_Text_Grunt1Intro::
    .string "Já jsem jeden ze ctyr\n"
    .string "BRATRU ROCKETU!$"

SilphCo_7F_Text_Grunt1Defeat::
    .string "Argh!\n"
    .string "Bratri, prohrál jsem!$"

SilphCo_7F_Text_Grunt1PostBattle::
    .string "Nevadí.\n"
    .string "Mí bratri to oplatí!$"

SilphCo_7F_Text_Grunt2Intro::
    .string "Detsky vetrelec?\n"
    .string "To budes ty!$"

SilphCo_7F_Text_Grunt2Defeat::
    .string "Dobre!\n"
    .string "Prohrál jsem!$"

SilphCo_7F_Text_Grunt2PostBattle::
    .string "Bez domu, nez se muj BOSS\n"
    .string "rozcílí!$"

SilphCo_7F_Text_RivalWhatKeptYou::
    .string "{RIVAL}: Co te zdrzelo, {PLAYER}?$"

SilphCo_7F_Text_RivalIntro::
    .string "{RIVAL}: Hahaha! Vedel jsem,\n"
    .string "ze prijdes, kdyz tu pockám!\p"
    .string "TEAM ROCKET te asi zpomalil!\n"
    .string "Ne ze by mi to vadilo!\p"
    .string "Videl jsem te v SAFFRONu, tak\n"
    .string "jsem zvedavy, jestli ses zlepsil!$"

SilphCo_7F_Text_RivalDefeat::
    .string "Ach jo!\n"
    .string "Tak jsi pripraven na BOSSE\l"
    .string "ROCKETU!$"

SilphCo_7F_Text_RivalVictory::
    .string "{RIVAL}“おまえなあ‥\p"
    .string "こんな　うでまえじゃ\n"
    .string "まだまだ‥\l"
    .string "いちにんまえ　とは　いえないぜ$"

SilphCo_7F_Text_RivalPostBattle::
    .string "Tak, {PLAYER}!\n"
    .string "Posouvám se vpred!\p"
    .string "Kdyz koukám do svého POKéDEXu,\n"
    .string "vidím, co je silné a jak se\l"
    .string "vyvíjí!\p"
    .string "Jsem génius, nebo co?\p"
    .string "Jdu do POKéMON LIGY a\n"
    .string "vyhodím ELITNÍ CTYRKU.\p"
    .string "Stanu se nejmocnejsím\n"
    .string "TRENÉREM sveta!\p"
    .string "{PLAYER}, hodne stestí!\n"
    .string "Nelam si hlavu!\l"
    .string "Cau!$"

SilphCo_7F_Text_FloorSign::
    .string "SILPH CO. HLAVNÍ KANCELÁR\n"
    .string "7F$"
