PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MAMA: …Jiste.\n"
    .string "Vsichni kluci jednou odejdou\l"
    .string "z domova. Ríkali to v TV.\p"
    .string "Aha, ano. PROF. OAK od vedle\n"
    .string "te hledal.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MAMA: …Jiste.\n"
    .string "Vsechny holky sní o cestování.\l"
    .string "Ríkali to v TV.\p"
    .string "Aha, ano. PROF. OAK od vedle\n"
    .string "te hledal.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MAMA: {PLAYER}!\n"
    .string "Mel by sis chvilku odpocinout.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MAMA: Ó, dobre! Ty i tví\n"
    .string "POKéMON vypadáte skvele.\l"
    .string "Opatruj se!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "V TV je film.\n"
    .string "Ctyri kluci jdou po\l"
    .string "kolejích.\p"
    .string "…Taky bych mel jít.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "V TV je film.\n"
    .string "Holka s culíky jde nahoru\l"
    .string "po cihlové ceste.\p"
    .string "…Taky bych mela jít.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Jejda, spatná strana…$"
