Route21_South_Text_JackIntro::
	.string "Své POKéMONy jsem chytil v mori.$"

Route21_South_Text_JackDefeat::
	.string "Potápec!!\n"
	.string "Dolu!!$"

Route21_South_Text_JackPostBattle::
	.string "Kde jsi chytil své POKéMONy?$"

Route21_South_Text_JeromeIntro::
	.string "Práve ted jsem na triatlonu.$"

Route21_South_Text_JeromeDefeat::
	.string "Funím…\n"
	.string "Funím… Funím…$"

Route21_South_Text_JeromePostBattle::
	.string "Jsem hotovy! Ale jeste me\n"
	.string "ceká cyklistika a maraton!$"

Route21_South_Text_RolandIntro::
	.string "Ách!\n"
	.string "Slunce a vítr, to je ono!$"

Route21_South_Text_RolandDefeat::
	.string "Au!\n"
	.string "Prohrál jsem!$"

Route21_South_Text_RolandPostBattle::
	.string "Jsem na skvarek spáleny\n"
	.string "od slunce!$"

Route21_South_Text_ClaudeIntro::
	.string "Hej, neplas mi ryby!$"

Route21_South_Text_ClaudeDefeat::
	.string "Promin! Jsem jen frustrovany\n"
	.string "z toho, ze nic nechytám.$"

Route21_South_Text_ClaudePostBattle::
	.string "Pche, nic jsem nechytil.\n"
	.string "Nemuze to tu byt náhodou\l"
	.string "obrí bazén nebo tak neco?$"

Route21_South_Text_NolanIntro::
	.string "Dej mi spolecnost, nez neco\n"
	.string "chytím.$"

Route21_South_Text_NolanDefeat::
	.string "To zabilo trochu casu.$"

Route21_South_Text_NolanPostBattle::
	.string "Ó pockej!\n"
	.string "Neco mi zabralo! Jo!$"

Route21_North_Text_LilIntro::
	.string "LIL: He? Souboj?\n"
	.string "IANe, nezvládnes to sám?$"

Route21_North_Text_LilDefeat::
	.string "LIL: Ó, vidís?\n"
	.string "Prohráli jsme. Spokojeny?$"

Route21_North_Text_LilPostBattle::
	.string "LIL: Jsem unavená.\n"
	.string "Nemuzeme uz jít domu?$"

Route21_North_Text_LilNotEnoughMons::
	.string "LIL: He? Souboj?\n"
	.string "Nechce se mi do toho samotné.\l"
	.string "Prines dva POKéMONy, ano?$"

Route21_North_Text_IanIntro::
	.string "IAN: Moje ségra se málo\n"
	.string "hybe, tak jsem ji prived.$"

Route21_North_Text_IanDefeat::
	.string "IAN: Och, séga!\n"
	.string "Seber se!$"

Route21_North_Text_IanPostBattle::
	.string "IAN: No tak, séga!\p"
	.string "Takhle nezhubnes!$"

Route21_North_Text_IanNotEnoughMons::
	.string "IAN: Chceme souboj dva na dva.\n"
	.string "Tak prineses dva POKéMONy?$"
