Route17_Text_RaulIntro::
    .string "Z bojování s deckama nezbohatnes.$"

Route17_Text_RaulDefeat::
    .string "Vyhorel jsem!$"

Route17_Text_RaulPostBattle::
    .string "Na CYKLISTICKÉ STEZCE\n"
    .string "se válí pekné veci.\p"
    .string "Da se na nich vydelat,\n"
    .string "kdyz je sebres a prodás.$"

Route17_Text_IsaiahIntro::
    .string "Hodne se chlubím postavou, malej.\n"
    .string "Pojd na to!$"

Route17_Text_IsaiahDefeat::
    .string "Hú!$"

Route17_Text_IsaiahPostBattle::
    .string "Mohl bych te odsud vystrelit\n"
    .string "brichem!$"

Route17_Text_VirgilIntro::
    .string "Mírís do FUCHSIE?$"

Route17_Text_VirgilDefeat::
    .string "Bourák a ohen!$"

Route17_Text_VirgilPostBattle::
    .string "Miluju závody z kopce!$"

Route17_Text_BillyIntro::
    .string "Jsme BIKERS!\n"
    .string "Vládneme silnicím, kámo!$"

Route17_Text_BillyDefeat::
    .string "Sezehnut!$"

Route17_Text_BillyPostBattle::
    .string "Hledas dobrodruzství?$"

Route17_Text_NikolasIntro::
    .string "At te VOLTORB nakopne!$"

Route17_Text_NikolasDefeat::
    .string "Uzemnen!$"

Route17_Text_NikolasPostBattle::
    .string "Svého VOLTORBa jsem chytil\n"
    .string "v opustené ELEKTRÁRNE.$"

Route17_Text_ZeekIntro::
    .string "Zvedl jsem POKéMONovi úroven,\n"
    .string "ale nevyvíjí se. Proc?$"

Route17_Text_ZeekDefeat::
    .string "Ty mi…!$"

Route17_Text_ZeekPostBattle::
    .string "Nekterí POKéMON snad potrebují\n"
    .string "KAMENY k vyvinutí.$"

Route17_Text_JamalIntro::
    .string "Potrebuju trochu pohybu!$"

Route17_Text_JamalDefeat::
    .string "Fuj!\n"
    .string "Dobrá rozcvicka!$"

Route17_Text_JamalPostBattle::
    .string "Urcite jsem shodil pár kilo!$"

Route17_Text_CoreyIntro::
    .string "Bud rebel!$"

Route17_Text_CoreyDefeat::
    .string "Aaaargh!$"

Route17_Text_CoreyPostBattle::
    .string "Bud pripraven bojovat za své ideály!$"

Route17_Text_JaxonIntro::
    .string "Pekné KOLO!\n"
    .string "Jak se rídí?$"

Route17_Text_JaxonDefeat::
    .string "Sakra!$"

Route17_Text_JaxonPostBattle::
    .string "Ten svah znesnaduje rízení.$"

Route17_Text_WilliamIntro::
    .string "Ztrat se, malej!\n"
    .string "Jsem zniceny!$"

Route17_Text_WilliamDefeat::
    .string "Spokojeny?$"

Route17_Text_WilliamPostBattle::
    .string "Potrebuju se trochu vyspat!$"

Route17_Text_WatchOutForDiscardedItems::
    .string "Upozornení.\p"
    .string "Pozor na odhozené predmety.$"

Route17_Text_SameSpeciesGrowDifferentRates::
    .string "TIPY PRO TRÉNÉRY\p"
    .string "Kazdy POKéMON je jedinecny.\p"
    .string "I POKéMON stejného druhu a\n"
    .string "úrovne rostou ruzne rychle.$"

Route17_Text_PressBToStayInPlace::
    .string "TIPY PRO TRÉNÉRY\p"
    .string "Stiskni B, abys zustal na míste,\n"
    .string "kdyz jsi na svahu.$"

Route17_Text_RouteSign::
    .string "CESTA 17\n"
    .string "CELADON CITY - FUCHSIA CITY$"

Route17_Text_DontThrowGameThrowBalls::
    .string "Upozornení!\p"
    .string "Neházej hrou, házej POKé\n"
    .string "BALLY!$"

Route17_Text_CyclingRoadSign::
    .string "CYKLISTICKÁ STEZKA\n"
    .string "Svah zde koncí!$"

