SixIsland_RuinValley_Text_CantFigureOutHowToGetInside::
    .string "Neumím prijít na to, jak se\n"
    .string "mám dostat dovnitr.$"

SixIsland_RuinValley_Text_IFoundThisPlace::
    .string "Hele, povím ti to, ja jsem\n"
    .string "tohle místo nasel.\p"
    .string "Nedívej se na me tak\n"
    .string "závistive, jo?$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly::
    .string "Dvere se vubec nehybou.\n"
    .string "Prozkoumat je dukladneji?$"

SixIsland_RuinValley_Text_LeftDoorAlone::
    .string "{PLAYER} nechal dvere byt.$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor::
    .string "Pri blizsím pohledu je na\n"
    .string "dverích nekolik tecek…$"

SixIsland_RuinValley_Text_DoorIsOpen::
    .string "Dvere jsou otevrené.$"

SixIsland_RuinValley_Text_StanlyIntro::
    .string "Zdá se, ze je v tomto svete\n"
    .string "stále mnoho nerozlustenych\l"
    .string "tajemství.$"

SixIsland_RuinValley_Text_StanlyDefeat::
    .string "Hmm…$"

SixIsland_RuinValley_Text_StanlyPostBattle::
    .string "Doporucuji ti, abys i ty\n"
    .string "premyslel jednou denne o\l"
    .string "tajemstvích nasého sveta.$"

SixIsland_RuinValley_Text_FosterIntro::
    .string "Zajímá me, co te primelo\n"
    .string "sem prijít?$"

SixIsland_RuinValley_Text_FosterDefeat::
    .string "Dlouho jsem nebojoval, mé\n"
    .string "instinkty jsou rozhozené.$"

SixIsland_RuinValley_Text_FosterPostBattle::
    .string "Na SEVII ISLANDS je nekolik\n"
    .string "ruin.\p"
    .string "Vetsina z nich je velmi\n"
    .string "stará.$"

SixIsland_RuinValley_Text_LarryIntro::
    .string "Ríká se, ze na tomto ostrove\n"
    .string "jsou tajemné kameny.\p"
    .string "Mám podezrení, ze to souvisí\n"
    .string "se zdejsími ruinami.$"

SixIsland_RuinValley_Text_LarryDefeat::
    .string "Ach, zajímavé.$"

SixIsland_RuinValley_Text_LarryPostBattle::
    .string "Ty ruiny támhle…\p"
    .string "Nemel jsem stestí najít\n"
    .string "zpusob, jak se dostat dovnitr.$"

SixIsland_RuinValley_Text_DarylIntro::
    .string "Souboj s tebou, tak vysoko!$"

SixIsland_RuinValley_Text_DarylDefeat::
    .string "Ach, ta lítost, ze prohrávám\n"
    .string "tak snadno s tebou!$"

SixIsland_RuinValley_Text_DarylPostBattle::
    .string "Zazij radost ze sportovního\n"
    .string "lezení!$"

SixIsland_RuinValley_Text_HectorIntro::
    .string "Tady kolem se docela\n"
    .string "vyznám.$"

SixIsland_RuinValley_Text_HectorDefeat::
    .string "Nemusís byt tak doterny.\n"
    .string "Rád ti to reknu.$"

SixIsland_RuinValley_Text_HectorPostBattle::
    .string "Dvere do ruin…\n"
    .string "Mají zvlástní vzory vyryté\l"
    .string "zvencí.\p"
    .string "Nevím vsak, co znamenají.$"
