RockTunnel_1F_Text_LennyIntro::
    .string "Tenhle tunel je pekne dlouhy, mlady!$"

RockTunnel_1F_Text_LennyDefeat::
    .string "Doh!\n"
    .string "Vyhrál jsi!$"

RockTunnel_1F_Text_LennyPostBattle::
    .string "Dej pozor na ONIX.\n"
    .string "Objevují se jen obcas.\p"
    .string "Ty na vysoké úrovni te muzou\n"
    .string "pekne zmácknout!$"

RockTunnel_1F_Text_OliverIntro::
    .string "Hmm.\n"
    .string "Mozná jsem se tu ztratil…$"

RockTunnel_1F_Text_OliverDefeat::
    .string "Klid!\n"
    .string "Co to delám?\l"
    .string "Kudy se jde ven?$"

RockTunnel_1F_Text_OliverPostBattle::
    .string "Ten spící POKéMON na CESTE 12\n"
    .string "me donutil jít okliku.$"

RockTunnel_1F_Text_LucasIntro::
    .string "Cizinci jako ty mi musí projevit\n"
    .string "trochu respektu!$"

RockTunnel_1F_Text_LucasDefeat::
    .string "Vzdávám!$"

RockTunnel_1F_Text_LucasPostBattle::
    .string "Más talent, aby ses vydal na túru!$"

RockTunnel_1F_Text_AshtonIntro::
    .string "POKéMON souboj!\n"
    .string "Pripraven, jdeme!$"

RockTunnel_1F_Text_AshtonDefeat::
    .string "Konec hry!$"

RockTunnel_1F_Text_AshtonPostBattle::
    .string "No nic, chytím si ZUBATa po ceste!$"

RockTunnel_1F_Text_LeahIntro::
    .string "Iiik!\p"
    .string "Nezkousej zádné triky\n"
    .string "ve tme!$"

RockTunnel_1F_Text_LeahDefeat::
    .string "Byla prílis tma…$"

RockTunnel_1F_Text_LeahPostBattle::
    .string "Videla jsem v tomhle tunelu MACHOPa.$"

RockTunnel_1F_Text_DanaIntro::
    .string "Dosla jsem az sem hledat\n"
    .string "divoké POKéMONy.$"

RockTunnel_1F_Text_DanaDefeat::
    .string "Doslo mi POKéMONu!$"

RockTunnel_1F_Text_DanaPostBattle::
    .string "Vypadal jsi roztomile a neskodne.\n"
    .string "To jsem se ale spletla!$"

RockTunnel_1F_Text_ArianaIntro::
    .string "Máte POKéMONy!\n"
    .string "Zacneme!$"

RockTunnel_1F_Text_ArianaDefeat::
    .string "Hrajes tvrde!$"

RockTunnel_1F_Text_ArianaPostBattle::
    .string "Uf!\n"
    .string "Jsem celá zpocená.$"

RockTunnel_1F_Text_RouteSign::
    .string "ROCK TUNNEL\n"
    .string "CERULEAN CITY - LAVENDER TOWN$"

