SevenIsland_TanobyRuins_Text_BrandonIntro::
    .string "Vís neco o této kamenné\n"
    .string "komnate?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
    .string "To bylo neprípustné.\n"
    .string "Nemusel jsi byt tak hruby.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
    .string "TANOBY RUINS jsou staré\n"
    .string "minimálne 1 500 let.\p"
    .string "Ale je to záhada, proc\n"
    .string "byly vubec postaveny.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
    .string "Ríká se, ze tu spí mysticky\n"
    .string "POKéMON.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
    .string "Nejsem v boji moc dobry.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
    .string "Slysel jsem, ze jsou jeste\n"
    .string "dalsí ruiny jako tahle.\p"
    .string "Mohou to byt odpocinková\n"
    .string "místa dalsích mystickych\l"
    .string "POKéMONu?$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
    .string "CLIFFORD me uci, jak malovat.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
    .string "Mohli bychom mít problémy,\n"
    .string "ze tady delame hluk.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
    .string "Rekla jsem, ze chci malovat\n"
    .string "starou budovu.\p"
    .string "Tak me sem CLIFFORD privedl.$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
    .string "Dnes jsme krome lekce prisli\n"
    .string "videt tu komnatu.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
    .string "Ach, jak mimorádné.$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
    .string "Aha, takze ty studujes\n"
    .string "POKéMONy sám…\p"
    .string "Ano, jsi opravdu pozoruhodná\n"
    .string "osoba.$"
