CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "Beru dárek pro svou\n"
    .string "prítelkyni.\p"
    .string "Asi to bude POKé PANENKA.\n"
    .string "Ted je to populární.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "Slysel jsem neco uzitecného.\p"
    .string "Kdyz se objeví divoky POKéMON,\n"
    .string "rozptylís ho POKé PANENKOU.\p"
    .string "Behem rozptylení muzes utéct\n"
    .string "od divokého POKéMONa.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "Vyjádri se dárky!\n"
    .string "4F: DÁRKY OD MUDRCE\p"
    .string "Evolucní akce!\n"
    .string "KAMENY ted ve sleve!$"
