CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
    .string "Líbí se mi tamten PORYGON!\n"
    .string "Ale tezko se ve slotech vyhrává!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
    .string "Hahaha! Dnes jsem to nahrnul!\n"
    .string "Kdyby tak kazdy den byl takovy…$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired::
    .string "Je potreba MINCOVNÍK…$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes::
    .string "MINCE vymeníme za ceny.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize::
    .string "Kterou cenu bys chtel?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo::
    .string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize::
    .string "Takze chces {STR_VAR_1}?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM::
    .string "Dobre, TM s {STR_VAR_2}\n"
    .string "je to, co chces?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins::
    .string "Promin, bude potreba víc\n"
    .string "MINCÍ nez tohle.$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom::
    .string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen::
    .string "あっ そう$"
