@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
    .string "Popel mého POKéMONa je ulozen\n"
    .string "v POKéMON TOWER.\p"
    .string "Tohle TM si muzes nechat.\n"
    .string "Uz ho nepotrebuju…$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
    .string "Popel mého POKéMONa je ulozen\n"
    .string "v POKéMON TOWER.\p"
    .string "Tohle TM si muzes nechat.\n"
    .string "Uz ho nepotrebuju…$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
    .string "{PLAYER} dostal TM27\n"
    .string "od malé holcicky.$"

Route12_NorthEntrance_2F_Text_ExplainTM27::
    .string "TM27 je útok zvany RETURN…\p"
    .string "Kdyz se k POKéMONovi chovás\n"
    .string "dobre, oplatí ti lásku tím, ze\l"
    .string "v boji vydá ze sebe vse.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
    .string "Na tohle nemás místo.$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
    .string "Mrkneme se, co ukázou\n"
    .string "dalekohledy…\p"
    .string "Tamhle nekdo rybarí!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .string "Mrkneme se, co ukázou\n"
    .string "dalekohledy…\p"
    .string "To je POKéMON TOWER!$"
