Route6_Text_RickyIntro::
    .string "Kdo je tam?\n"
    .string "Prestan nás odposlouchávat!$"

Route6_Text_RickyDefeat::
    .string "Proste nemuzu vyhrát!$"

Route6_Text_RickyPostBattle::
    .string "Septot…\n"
    .string "Septot…$"

Route6_Text_NancyIntro::
    .string "Promin!\n"
    .string "Tohle je soukromy rozhovor!$"

Route6_Text_NancyDefeat::
    .string "Fuj!\n"
    .string "Nesnásím prohry.$"

Route6_Text_NancyPostBattle::
    .string "Septot…\n"
    .string "Septot…$"

Route6_Text_KeigoIntro::
    .string "Tady moc broucku není.$"

Route6_Text_KeigoDefeat::
    .string "Ne!\n"
    .string "Delás si srandu!$"

Route6_Text_KeigoPostBattle::
    .string "Mám rád brouky, vracím se do\n"
    .string "VIRIDIAN FORESTU.$"

Route6_Text_JeffIntro::
    .string "He?\n"
    .string "Chces se mnou mluvit?$"

Route6_Text_JeffDefeat::
    .string "Tohle stojí za nic…\n"
    .string "Nezvládl jsem to…$"

Route6_Text_JeffPostBattle::
    .string "Mel bych si brát víc POKéMONu.\n"
    .string "Cítil bych se bezpecneji.$"

Route6_Text_IsabelleIntro::
    .string "Já?\n"
    .string "No dobre. Budu hrát!$"

Route6_Text_IsabelleDefeat::
    .string "Veci proste nevysly…$"

Route6_Text_IsabellePostBattle::
    .string "Chci byt silnejsí.\n"
    .string "Jaké je tvé tajemství?$"

Route6_Text_ElijahIntro::
    .string "Jeste jsem te tu nevidel.\n"
    .string "Jsi dobry?$"

Route6_Text_ElijahDefeat::
    .string "Jsi az moc dobry!$"

Route6_Text_ElijahPostBattle::
    .string "Jsou mí POKéMONi slabí?\n"
    .string "Nebo jsem jen spatny já?\l"
    .string "Co myslís?$"

Route6_Text_UndergroundPathSign::
    .string "PODZEMNÍ CESTA\n"
    .string "CERULEAN CITY - VERMILION CITY$"

