CeladonCity_Condominiums_1F_Text_Meowth::
    .string "MEOWTH: Mnau!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "Nemel bys utratit vsechny\n"
    .string "peníze za pití.\p"
    .string "Zkus radsi tohle.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "Nic neporazí zízen tak jako\n"
    .string "horky CAJ.\p"
    .string "Je opravdu nejlepsí.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "Mí drazí POKéMONi mi delají\n"
    .string "spolecnost.\n"
    .string "MEOWTH dokonce nosí peníze!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "Ach, ahoj, drahousku.\n"
    .string "Chutnal ti muj CAJ?\p"
    .string "Mimochodem, drahousku, nejsi\n"
    .string "náhodou z PALLET TOWNu?\p"
    .string "Holka z PALLET TOWNu, DAISY,\n"
    .string "si pochutnává na CAJI denne.\p"
    .string "Chodí do CELADON OBCHODÁKU\n"
    .string "si CAJ koupit.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "CLEFAIRY: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "NIDORAN♀: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "CELADON MANSION\n"
    .string "Apartmán správce$"
