SSAnne_Kitchen_Text_BusyOutOfTheWay::
    .string "Ty, mon petit!\n"
    .string "Tady máme práci!\l"
    .string "Z cesty!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash::
    .string "Videl jsem v kosi divnou BERRY.\n"
    .string "Co to asi bylo?$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
    .string "Mám tolik práce, ze se mi tocí\n"
    .string "hlava! Musís me pustit!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
    .string "Trá-lá-lá-lá…\p"
    .string "Loupu brambory kazdy den!\n"
    .string "Trá-lá…$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
    .string "Slysel jsi o SNORLAXovi?\n"
    .string "Je to zravec.\p"
    .string "Zádny jiny POKéMON nejí a\n"
    .string "nespí jako SNORLAX!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
    .string "Bre… Hek…\p"
    .string "Muzu loupat jen cibuli…\n"
    .string "Bre…$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
    .string "Khm!\n"
    .string "Já jsem le KUCHAR!\p"
    .string "Le hlavní chod je$"

SSAnne_Kitchen_Text_SalmonDuSalad::
    .string "Losos du Salát!\p"
    .string "Les hosté budou reptat, ze je\n"
    .string "zase ryba!$"

SSAnne_Kitchen_Text_EelsAuBarbecue::
    .string "Úhori au Barbecue!\p"
    .string "Les hosté se obávám vzbourí.$"

SSAnne_Kitchen_Text_PrimeBeefsteak::
    .string "Prvotrídní biftek!\p"
    .string "Ale mám dost filé du\n"
    .string "hovezí?$"
