CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
    .string "Mám zízen!\n"
    .string "Chci neco k pití!\p"
    .string "{FONT_NORMAL}Dát jí napít?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
    .string "Co jí dát k pití?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
    .string "Jupí!\p"
    .string "FRESH WATER!\p"
    .string "Díky!\n"
    .string "Tohle si ode me vezmi!$"

Text_ReceivedItemFromLittleGirl::
    .string "{PLAYER} dostal {STR_VAR_2}\n"
    .string "od holcicky.$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
    .string "TM16 obsahuje LIGHT SCREEN.\p"
    .string "Je to útok, ktery oslabuje sílu\n"
    .string "speciálních útoku soupere.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
    .string "Jupí!\p"
    .string "SODA POP!\p"
    .string "Díky!\n"
    .string "Tohle si ode me vezmi!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
    .string "TM20 obsahuje SAFEGUARD.\p"
    .string "Je to útok, ktery chrání tvé\n"
    .string "POKéMONy pred problémy stavu.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
    .string "Jupí!\p"
    .string "LEMONADE!\p"
    .string "Díky!\n"
    .string "Tohle si ode me vezmi!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
    .string "TM33 obsahuje REFLECT.\p"
    .string "Je to útok, ktery oslabuje sílu\n"
    .string "fyzickych útoku soupere.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
    .string "Na to nemás místo!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
    .string "Ne, díky!\n"
    .string "Vlastne uz zízen nemám!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
    .string "Moje sestra je TRENÉRKA, kdo\n"
    .string "by to byl rekl.\p"
    .string "Ale je tak detinská, ze me\n"
    .string "to privádí k sílenství!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
    .string "Mám zízen!\n"
    .string "Chci neco k pití!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
    .string "STRECHA:\n"
    .string "AUTOMATY$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
    .string "Automat!\n"
    .string "Co v nem je?$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
    .string "Jejda, málo penez!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
    .string "Vypadla plechovka {STR_VAR_1}!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
    .string "Uz není místo na dalsí veci!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
    .string "Nemám zízen!$"
