ViridianCity_Text_CanCarryMonsAnywhere::
    .string "Ty POKé BALLS u pasu!\n"
    .string "Mas POKéMONy, ze?\p"
    .string "Je skvelé, ze mas POKéMONy\n"
    .string "porád u sebe.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "Tahle POKéMON GYM je porád\n"
    .string "zavrená.\p"
    .string "Kdopak je asi VUDCEM?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "VUDCE VIRIDIAN GYM se vrátil!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "Chces vedet o dvou druzích\n"
    .string "housenkovitych POKéMONu?$"

ViridianCity_Text_OhOkayThen::
    .string "Aha, tak dobre!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CATERPIE není jedovaty,\n"
    .string "ale WEEDLE ano.\p"
    .string "Dej pozor, at tvého POKéMONa\n"
    .string "nebodne WEEDLOVO POISON STING.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Ach, dedo!\n"
    .string "Nebud tak protivny!\p"
    .string "Moc se omlouvám.\n"
    .string "Jeste nemel kávu.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "Obcas si zajdu nakoupit\n"
    .string "do PEWTER CITY.\p"
    .string "Vzdy musím prejít klikatou\n"
    .string "cestou ve VIRIDIAN FOREST.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "Naprosto ti zakazuji jít\n"
    .string "tudy!\p"
    .string "Tohle je soukromy pozemek!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Tak, dal jsem si kávu, a to je\n"
    .string "presne to, co potrebuju!\p"
    .string "Hm?\n"
    .string "Co je to za cervenou krabicku?\p"
    .string "Aha, ty pracujes na svém\n"
    .string "POKéDEXU.\p"
    .string "Pak ti dám jednu radu.\p"
    .string "Kdykoli chytís POKéMONa,\n"
    .string "POKéDEX automaticky aktualizuje\l"
    .string "svá data.\p"
    .string "…Ty nevís, jak se chytá\n"
    .string "POKéMON?\p"
    .string "Tak ti to radeji ukázu!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "A je to! Tak rekni, bylo to\n"
    .string "poucné, nemyslís?\p"
    .string "A vem si tohle taky.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "Kdyz necemu nerozumís,\n"
    .string "podívej se na tohle.\p"
    .string "Naucí te to základy\n"
    .string "POKéMON TRENéRA.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Tak, dal jsem si kávu, a to je\n"
    .string "presne to, co potrebuju!\p"
    .string "Ale udelal jsem ji moc silnou.\n"
    .string "Bolí me z toho hlava…\p"
    .string "Mimochodem, plnís si svuj\n"
    .string "POKéDEX?\p"
    .string "Zacni tím, ze POKéMONa nejdrív\n"
    .string "oslabís, nez ho zkusís chytit.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Tak, dal jsem si kávu, a to je\n"
    .string "presne to, co potrebuju!\p"
    .string "Ale udelal jsem ji moc silnou.\n"
    .string "Bolí me z toho hlava…\p"
    .string "Mimochodem, pomáhá ti moje\n"
    .string "stará TEACHY TV?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha!\n"
    .string "To je muj vnuk v tom porádu!\p"
    .string "Kdyz ucí on, musís se\n"
    .string "neco naucit.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… Mas tolik práce, ze nemás\n"
    .string "cas na TEACHY TV…\p"
    .string "Cas jsou peníze a ani jedno\n"
    .string "by se nemelo plytvat…$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN CITY \n"
    .string "Vecne zeleny ráj$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "TIPY PRO TRENéRY\p"
    .string "Chytej POKéMONy a rozsiruj\n"
    .string "svou sbírku.\p"
    .string "Cím víc jich mas, tím snáz\n"
    .string "se ti bojuje.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "TIPY PRO TRENéRY\p"
    .string "Bojové útoky POKéMONu jsou\n"
    .string "omezeny POWER POINTY, PP.\p"
    .string "Pro doplnení PP nech POKéMONa\n"
    .string "odpocinout v POKéMON CENTRU.$"

ViridianCity_Text_GymSign::
    .string "VIRIDIAN CITY POKéMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "Dvere VIRIDIAN GYM jsou\n"
    .string "zamceny…$"
