SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .string "{PLAYER}: Ahoj!\n"
    .string "Mas rád POKéMONy?\p"
    .string "{PLAYER}: Eh, ne, já se ptám tebe.\p"
    .string "{PLAYER}: Co?\n"
    .string "Jsi divná!\p"
    .string "COPYCAT: Hm? Mám prestat?\n"
    .string "Ale to je má oblíbená zábava!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .string "{PLAYER}: Ahoj.\n"
    .string "Asi mas ráda POKéMONy.\p"
    .string "{PLAYER}: Ne, já ne.\n"
    .string "Ptala jsem se tebe.\p"
    .string "{PLAYER}: Prosím?\n"
    .string "Jsi divná!\l"
    .string " \l"
    .string "COPYCAT: Hm? Mám prestat?\l"
    .string "Ale to je má oblíbená zábava!$"

Text_MimicTeach::
    .string "Ó páni!\n"
    .string "POKé PANENKA!\p"
    .string "Pro me?\n"
    .string "Díky!\p"
    .string "Víte co?\n"
    .string "Mohu naucit útok MIMIC.$"

Text_MimicDeclined::
    .string "Nelíbí se ti MIMIC?$"

Text_MimicWhichMon::
    .string "MIMIC opravdu miluji!\n"
    .string "Kdo se ho naucí?$"

Text_MimicTaughtMale::
    .string "{PLAYER}: Ahoj!\n"
    .string "Díky za posledne!\p"
    .string "{PLAYER}: Prosím?\p"
    .string "{PLAYER}: Je to tak zábavné\n"
    .string "napodobovat kazdy muj pohyb?\p"
    .string "COPYCAT: To si pis!\n"
    .string "Je to sranda!$"

Text_MimicTaughtFemale::
    .string "{PLAYER}: Ahoj!\n"
    .string "Díky za to, cos pro nás udelala.\p"
    .string "{PLAYER}: Prosím?\p"
    .string "{PLAYER}: Je to opravdu tak zábavné\n"
    .string "opakovat, co ríkám a delám?\p"
    .string "COPYCAT: To si pis!\n"
    .string "Je to sranda!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
    .string "にもつが　いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
    .string "{PLAYER}“やあ！　こんにちは！\n"
    .string "きみ　ポケモン　すきかい？\p"
    .string "{PLAYER}“ぼく　じゃなくって\n"
    .string "きみに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥‥　えー　なんだよ！\n"
    .string "ヘンな　やつ　だなあ！\p"
    .string "モノマネむすめ“‥‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし　\n"
    .string "ものまね　しゅみ　なんだ　もん！”$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
    .string "{PLAYER}“こんにちは！\n"
    .string "ポケモン　すきなのね？\p"
    .string "{PLAYER}“わたし　じゃなくって\n"
    .string "あなたに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥　えー　なんなの！\n"
    .string "おかしなこ　ねー！\p"
    .string "モノマネむすめ“‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし\n"
    .string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .string "DODUO: Giiih!\p"
    .string "ZRCÁTKO HEZKÉ, podívej se na me,\n"
    .string "kolik krásy mám!$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .string "Tohle je vzácny POKéMON!\n"
    .string "Co? Je to jen panenka!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .string "Hra, kde má MARIO na hlave\n"
    .string "kbelík!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .string "…\p"
    .string "Má tajemství!\p"
    .string "Dovednost: Napodobování!\n"
    .string "Konícek: Sbírání panenek!\l"
    .string "Oblíbeny POKéMON: CLEFAIRY!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
    .string "？　みえないぞ‥$"
