SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn::
    .string "POKéMONi mají své vlastní\n"
    .string "povahy, stejne jako lidé.\p"
    .string "Muj PIKACHU má UKVAPENOU\n"
    .string "povahu, takze vyrostl rychly.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins::
    .string "Tak, prípravy jsou hotové,\n"
    .string "muzu jít prozkoumat RUINY.$"

SevenIsland_Mart_Text_NeedToFishOnSevenIsland::
    .string "Potrebuji lovit na SEVEN ISLAND.\p"
    .string "Tím dokoncím své rybárské\n"
    .string "putování po SEVII ISLANDS.\p"
    .string "Mel bych si ale nejdrív\n"
    .string "doplnit POKé BALLy.$"

