Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
    .string "Cau! Pamatujes si me?\n"
    .string "Jsem asistent PROF. OAKA.\p"
    .string "Pokud má tvuj POKéDEX kompletní\n"
    .string "data o deseti druzích, mám ti\l"
    .string "dát odmenu.\p"
    .string "PROF. OAK mi pro tebe sveril\n"
    .string "HM05.\p"
    .string "Tak, {PLAYER}, zeptám se te.\p"
    .string "Sebrals data alespon o deseti\n"
    .string "druzích POKéMONu?$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "Vyborne! Chytil nebo vlastnil jsi\n"
    .string "{STR_VAR_3} druhu POKéMONu!\p"
    .string "Gratuluji!\n"
    .string "Tady mas!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .string "{PLAYER} dostal HM05\n"
    .string "od ASISTENTA.$"

Route2_EastBuilding_Text_ExplainHM05::
    .string "HM05 obsahuje skryty útok\n"
    .string "FLASH.\p"
    .string "FLASH osvetlí i ty nejtemnejsí\n"
    .string "jeskyne a dungeony.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .string "Kdyz se POKéMON naucí FLASH,\n"
    .string "projdes pres ROCK TUNNEL.$"
