FuchsiaCity_Gym_Text_KogaIntro::
    .string "KOGA: Fwahahaha!\p"
    .string "Díte jako ty se odvází\n"
    .string "vyzvat me?\p"
    .string "Z té predstavy se chvejí\n"
    .string "smíchem!\p"
    .string "Dobrá, ukázu ti pravou\n"
    .string "hruzu mistra ninja.\p"
    .string "Jed prinásí pomalou zkázu.\n"
    .string "Spánek ciní souperu bezmocnymi.\p"
    .string "Boj se plízivé hruzy\n"
    .string "JEDOVATYCH POKéMONu!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "Hmpf!\n"
    .string "Dokázals svou hodnotu!\p"
    .string "Tu mas!\n"
    .string "Vezmi si SOULBADGE!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "Pod úcinkem TOXIC POKéMON\n"
    .string "trpí cím dál víc.\p"
    .string "Skoda roste, jak souboj\n"
    .string "pokracuje!\p"
    .string "Jiste vydesí kazdého soupere!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "S odznakem SOULBADGE\n"
    .string "stoupne OBRANA tvych POKéMONu.\p"
    .string "Umozní ti i SURF mimo\n"
    .string "souboj.\p"
    .string "Ach!\n"
    .string "Vezmi si i tohle!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "{PLAYER} dostal TM06\n"
    .string "od KOGY.$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "V TM06 se skryvá\n"
    .string "TOXIC!\p"
    .string "Je to tajná technika stará\n"
    .string "ctyri sta let.$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "Udelej tomuto místo, díte!$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "Síla není klíc k POKéMONum.\n"
    .string "Chápes to?\p"
    .string "POKéMON je o strategii!\p"
    .string "Ukázu ti, jak strategie\n"
    .string "porazí hrubou sílu.$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "Co?\n"
    .string "Mimorádné!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "Mísís sílu s mozkem?\n"
    .string "Dobrá strategie!\p"
    .string "To je pozoruhodné na detsky\n"
    .string "TRÉNÉR.$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "Kdysi jsem byl kouzelník.\p"
    .string "Ale snil jsem o tom byt ninja,\n"
    .string "tak jsem se pridal do GYMU.$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "Je po mne!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "I kdyz jsem prohrál, budu\n"
    .string "dál trénovat podle nauky\l"
    .string "KOGY, svého mistra ninja.$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "Uvidíme, jak porazís mé\n"
    .string "speciální techniky!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "Osálils me!$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "Mám rád jed a spánek,\n"
    .string "trvají i po souboji!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "Zastav!\p"
    .string "Slavné neviditelné steny\n"
    .string "FUCHSIA GYMU te trápí?$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "Páni!\n"
    .string "Mas to!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "Ohromils me!\n"
    .string "Tu mas tip!\p"
    .string "Pozorne hledej mezery\n"
    .string "v neviditelnych stenách!$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "Také studuji cestu ninja\n"
    .string "s Mistrem KOGOU!\p"
    .string "Ninja mají dlouhou tradici\n"
    .string "ve vyuzívání zvírat!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "Au!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "Mám se jeste mnohému ucit.$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "Mistr KOGA pochází z dlouhé\n"
    .string "linie ninju.\p"
    .string "Z ceho pochází ty?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "Jsi sikovnejsí, nez jsem\n"
    .string "cekal!$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "Kde je svetlo, je i stín!\p"
    .string "Svetlo a stín!\n"
    .string "Co si vybírás?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "Hej!\n"
    .string "Budoucí sampión!\p"
    .string "FUCHSIA GYM je vychytralé\n"
    .string "místo. Plné neviditelnych sten!\p"
    .string "KOGA je sice blízko, ale\n"
    .string "blokován.\p"
    .string "Musís najít mezery ve stenách,\n"
    .string "abys k nemu dosel.$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "Je úzasné, jak ninja dokází\n"
    .string "i dnes desit!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "FUCHSIA POKéMON GYM\n"
    .string "VUDCE: KOGA\p"
    .string "VÍTEZNÍ TRÉNÉRI:\n"
    .string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "FUCHSIA POKéMON GYM\n"
    .string "VUDCE: KOGA\p"
    .string "VÍTEZNÍ TRÉNÉRI:\n"
    .string "{RIVAL}, {PLAYER}$"

