Route1_Text_WorkAtPokeMartTakeSample::
    .string "Cau!\n"
    .string "Pracuju v POKéMON MARTU.\p"
    .string "Je to soucást praktického\n"
    .string "retezce s vsemi druhy predmetu.\p"
    .string "Prijd k nám do VIRIDIAN CITY.\p"
    .string "Vím co, dám ti vzorek.\n"
    .string "Tady mas!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Stav se u nás, kdyz budes\n"
    .string "potrebovat POKé BALLS na chytání.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} ulozil LEKTVAR\n"
    .string "do kapsy PREDMETY v BATOHu.$"

Route1_Text_CanJumpFromLedges::
    .string "Vidís ty rímsy podél cesty?\p"
    .string "Je to trochu strasidelné, ale\n"
    .string "muzes z nich seskocit.\p"
    .string "Rychleji se tak vrátís\n"
    .string "do MESTA PALLET.$"

Route1_Text_RouteSign::
    .string "CESTA 1\n"
    .string "PALLET TOWN - VIRIDIAN CITY$"
