PokemonLeague_AgathasRoom_Text_Intro::
    .string "Já jsem AGATHA z ELITNÍ CTYRKY.\p"
    .string "Slysela jsem, ze se o tebe\n"
    .string "OAK zacal hodne zajímat, dítko.\p"
    .string "Ten dedek byval tvrdy a\n"
    .string "pohledny.\p"
    .string "Ale to bylo pred desítkami let.\n"
    .string "Ted je stínem svého já.\p"
    .string "Ted se chce jen babrat se\n"
    .string "svym POKéDEXem.\p"
    .string "Mylí se.\n"
    .string "POKéMONi jsou na boj!\p"
    .string "{PLAYER}! Ukázu ti, jak bojuje\n"
    .string "opravdovy TRÉNÉR!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_RematchIntro::
    .string "Já jsem AGATHA z ELITNÍ CTYRKY.\p"
    .string "Ty jsi to dítko, co si OAK\n"
    .string "vzal pod krídla, vid?\p"
    .string "Ten dedek byval tvrdy a\n"
    .string "pohledny.\p"
    .string "Ale to bylo pred desítkami let.\n"
    .string "Ted je stínem svého já.\p"
    .string "Ted se chce jen babrat se\n"
    .string "svym POKéDEXem.\p"
    .string "Mylí se.\n"
    .string "POKéMONi jsou na boj!\p"
    .string "{PLAYER}! Ukázu ti, jak bojuje\n"
    .string "opravdovy TRÉNÉR!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_Defeat::
    .string "Au!\n"
    .string "Jsi neco vyjimecného, dítko!$"

PokemonLeague_AgathasRoom_Text_PostBattle::
    .string "Vyhrál jsi!\p"
    .string "Ted vidím, co na tobe ten\n"
    .string "starik vidí.\p"
    .string "Nemám uz co dodat.\n"
    .string "Bez si, dítko!$"

